harness/developer-hub

tutorials/platform/onboard-terraform-provider.md

fixed minor issues in the terraform tutorial

---

docs/continuous-integration/migration-guides/_category_.json
docs/continuous-integration/migration-guides/migrating-from-circleci.md

Signed-off-by: Ompragash Viswanathan <ompragash@proton.me>
This PR contains a **Migrating from CircleCI** guide that helps the user to migrate their existing CircleCI pipelines to Harness CI.
- Created a new folder section `migration-guides` under `./docs/continuous-integration/migration-guides/`
- Added two files: `_category_.json` and `migrating-from-circleci.md`
1. File: `_category_.json`
> Need to check/add the values of the below parameters
- `position`
- `helpdocs_category_id`
2. File: `migrating-from-circleci.md`
> Need to check/add the values of the below parameters
- `sidebar_position`
- `helpdocs_topic_id`
- `helpdocs_category_id`
- @ronakforgit @codewdhruv for all their hard work and efforts in migrating other* CI pipelines to Harness CI, documenting all the errors/findings, …

CircleCi to Harness CI Migration Guide

---

docs/continuous-integration/migration-guides/migrating-from-circleci.md

Signed-off-by - krishika.singh@harness.io 
* The issue was with the closing of `<Tabs>` component in the markdown file. 
* In the headings **Define multi-stage build pipeline**, **Environment variables** and **Matrix**, whenever `CircleCI` tab is clicked the next heading description gets hidden. 
* `<Tabs>` and `<TabItem>` needed to be closed before the new heading.

Fixed Tabs Formatting in the CircleCI Migration Guide

---

release-notes/feature-flags.md

Added release notes for 10th Jan 2023 release for FF.
* *Issue(s)*

10Jan23-FF-ReleaseNotes

---

docs/feature-flags/4-ff-sdks/3-server-sdks/5-node-js-sdk-reference.md

The NodeJS SDK page said "Java" in place of "Node.js" and linked to the Python SDK starter instead of the NodeJS starter 👍

Fix incorrect languages on Node.js SDK Reference

---

docs/chaos-engineering/chaos-faults/kubernetes/experiments.ts

Changed heading from 'Kubelet Service Kill' to 'Kubelet service kill'
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

DOC-2532: Changed heading case

---

release-notes/chaos-engineering.md

Changed "There are no chaos infrastructure in your project." to "There are no chaos infrastructures in your project."
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

Fix grammar

---

docs/continuous-integration/ci-technical-reference/build-and-push-to-docker-hub-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-ecr-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-gcr-step-settings.md
docs/continuous-integration/ci-technical-reference/restore-cache-from-gcs-settings.md
docs/continuous-integration/ci-technical-reference/restore-cache-from-s-3-step-settings.md
docs/continuous-integration/ci-technical-reference/save-cache-to-gcs-step-settings.md
docs/continuous-integration/ci-technical-reference/save-cache-to-s-3-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-gcs-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-jfrog-artifactory-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-s-3-step-settings.md
docs/platform/7_Connectors/add-aws-connector.md
docs/platform/7_Connectors/connect-to-google-cloud-platform-gcp.md
docs/platform/7_Connectors/ref-cloud-providers/aws-connector-settings-reference.md
docs/platform/7_Connectors/ref-cloud-providers/gcs-connector-settings-reference.md

* CI-5758 : No specific change for this ticket, but applied general revisions to some GCP connector-related topics. I used the issue in this ticket for an example in the `GCP connector errors` part of `connect-to-google-cloud-platform-gcp.md`
* CI-6410 : Updated 9 step settings topics to include a note about which authentication methods are supported, not support, or untested (which I phrased as `may experience errors during pipeline runs`).
* I only made the minimum edits to these topics since the PR already includes so many changes. 
* Modified topics are the 'step setting' topics per the first column here: …

[CI-5758] [CI-6410] [DOC-2351] - Connector settings, Connector authentication, Connectors in CI steps

---

docs/continuous-integration/troubleshoot/troubleshooting-ci.md
docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md

* DOC-2599: Remove anti-hosted language.
* DOC-2499 (partial): Technical inaccuracy: DinD w/ Privileged mode is necessary for K8s infra only. Other infras don't need it because you can run Docker commands directly. Previously, the DinD topic said DinD wasn't **supported** for other infras - this is not true. It doesn't matter if it's supported, you don't need it.
* DOC-2499 (partial): Three changes to the "Define a Docker build infra" topic. 1) Renamed to "Use local runner build infrastructure"  because the previous name was misleading and unclear. 2) Clarified that local runner is best for small builds - use other infra for builds-at-scale. 3) …

[DOC-2599] Remove anti-hosted language, correct technical issues

---

docs/feature-flags/ff-using-flags/relay-proxy/deploy-relay-proxy.md
docs/feature-flags/ff-using-flags/relay-proxy/relay-proxy.md

These 2 pages were changed as requested in [DOC-2588](https://harness.atlassian.net/browse/DOC-2588):
1) On this page: /docs/feature-flags/ff-using-flags/relay-proxy/ 
In the proxy **configuration variables** table, made the **base** and **events** URLs match the defaults on page 2 below.
2) On this page: /docs/feature-flags/ff-using-flags/relay-proxy/deploy-relay-proxy
Also changed the example in "Configure SDKs to Work With the Relay Proxy" to remove references to our QA environment.
[DOC-2588]: https://harness.atlassian.net/browse/DOC-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-2588: Removes links to QA environment from ff proxy config

---

docs/continuous-integration/ci-quickstarts/ci-concepts.md
docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
docs/continuous-integration/ci-technical-reference/background-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-acr-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-docker-hub-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-ecr-step-settings.md
docs/continuous-integration/ci-technical-reference/build-and-push-to-gcr-step-settings.md
docs/continuous-integration/ci-technical-reference/ci-git-clone-step.md
docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
docs/continuous-integration/ci-technical-reference/configure-service-dependency-step-settings.md
docs/continuous-integration/ci-technical-reference/plugin-step-settings-reference.md
docs/continuous-integration/ci-technical-reference/restore-cache-from-gcs-settings.md
docs/continuous-integration/ci-technical-reference/restore-cache-from-s-3-step-settings.md
docs/continuous-integration/ci-technical-reference/run-step-settings.md
docs/continuous-integration/ci-technical-reference/save-cache-to-gcs-step-settings.md
docs/continuous-integration/ci-technical-reference/save-cache-to-s-3-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-gcs-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-jfrog-artifactory-step-settings.md
docs/continuous-integration/ci-technical-reference/upload-artifacts-to-s-3-step-settings.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md

* CI-5125: All topics with the Remote Cache Repo/Image field have the same language. Most have an example. Waiting for Hemanth to clarify if further examples are needed.
* DOC-2502: Added two topics: **Build and Push to ACR step settings** reference and **Build and push to ACR** task.
* DOC-1815: Originally, this ticket asked for more explanation of the Optimize setting. However, it was discovered that this setting only appears for K8s build infras. It is too much effort at this time to check every field for every step with every build infra; instead, I added a note at the top of most of the CI step settings reference topics to clarify that some …

[DOC-1815] [DOC-2502] [CI-5125] [CI-7162] - Standardized CI step settings references

---

docs/chaos-engineering/technical-reference/probes/cmd-probe.md
docs/chaos-engineering/technical-reference/probes/http-probe.md
docs/chaos-engineering/technical-reference/probes/k8s-probe.md
docs/chaos-engineering/technical-reference/probes/prom-probe.md

probePollingInterval field applies to all modes, not just continuous
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

[DOC-2720] Fixed error in the probePollingInterval field

---

docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/http-step.md

Mentioned explicitly that NG supports delegate proxy settings support by default
* *Issue(s)*

CDS-47304-default-delegate-proxy-support

---

docs/feature-flags/ff-sdks/client-sdks/flutter-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md

Version numbers in some SDK reference topics were out of date compared to the release notes. This catches them up.

Updates version nums in sdk refs

---

docs/platform/8_Pipelines/w_pipeline-steps-reference/additional-matrix-examples.md

[DOC-2733] Additional matrix examples

---

docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md

Adds:
- a note that if in a multi-instance setup, the default instance fails to boot, then the other instances will also fail
- explains how to not start the default instance if it isn't needed. 
- Updates code samples to use the default instance to make evaluations along with the additional instances

Ffm4195 erlang tech changes

---

release-notes/feature-flags.md

For 2 same-day releases of Node.js SDK

FFM-7293, FFM-7296: relnotes Node 1.2.13/4

---

release-notes/early-access.md
release-notes/harness-platform.md
release-notes/whats-new.md

PL Release Notes 788xx

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md

Preview site menu path: Documentation > Continuous Integration > Use CI > Set Up Build Infrastructure > Set up a local runner build infrastructure
* Added step for self-signed certs command
* Created three tabs containing the separate Delegate and Drone Runner instructions for Linux, macOS, and Windows.
Menu cascade for preview site: Documentation > Continuous Integration > Use CI > Set up Build Infrastructure > Set up a local runner build infrastructure
https://642324e7534eae00a330676b--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure

[CI-7494] Add mount cert command and break into tabs

---

docs/feature-flags/ff-using-flags/ff-target-management/add-target-groups.md
docs/feature-flags/ff-using-flags/ff-target-management/add-targets.md
docs/feature-flags/ff-using-flags/ff-target-management/targeting-users-with-flags.md

The only addition is the small section **How targets expire**, lines 117 - 127 in **add-targets.md**. 
[**Link to section in preview**](https://642432fb29d9280618c7dc31--harness-developer.netlify.app/docs/feature-flags/ff-using-flags/ff-target-management/add-targets#how-targets-expire).
The rest is just some opportunistic cleanup for style/clarity.

FFM-7317: adds target expiry section

---

release-notes/chaos-engineering.md

Path: "Documentation/Chaos engineering/release-notes/chaos-engineering" 
URL: https://hdh.pr.harness.io/pr-1113/release-notes/chaos-engineering
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

Release notes 0.9.x

---

docs/continuous-integration/ci-technical-reference/background-step-settings.md
docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
docs/continuous-integration/ci-technical-reference/run-step-settings.md
docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md

SPG-2501 - If there are multiple paths in Report Paths, make sure they are unique to avoid duplicate results/tests.

SPG-2501 clarify multiple paths for Report Paths

---

docs/feature-flags/ff-onboarding/getting-started-with-feature-flags.md
docs/feature-flags/ff-sdks/_category_.json
docs/feature-flags/ff-sdks/client-sdks/_category_.json
docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md
docs/feature-flags/ff-target-management/_category_.json

Find the new section on this path: /docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references#evaluate-a-flag > **(Optional) Provide a set of evaluations**

FFM-7502: adds set evals section in JS SDK, style tweaks

---

docs/continuous-integration/troubleshoot/troubleshooting-ci.md
docs/first-gen/firstgen-platform/account/manage-connectors/add-github-repo.md
docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-connector-settings-reference.md
docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md

CI-7786: With SSH auth, HTTP must be enabled over 443 or else the connection test will fail. I added this information to the Git connector settings reference and CI troubleshooting.
Refreshed the Git connector settings reference to follow similar changes I made for the [Bitbucket connector settings reference](https://developer.harness.io/docs/platform/connectors/code-repositories/ref-source-repo-provider/bitbucket-connector-settings-reference/). This makes the page cleaner and organizes context-dependent fields in tabs.
There was some language about GitHub RSA deprecation and PEM key format that appeared in multiple topics. I made some changes to standardize this language in most locations.
Preview links for significant revisions:
* Git connector settings reference: …

[CI-7786] - Git connector settings reference

---

docs/cloud-cost-management/2-getting-started-ccm/5-access-control/ccm-roles-and-permissions.md
docs/cloud-cost-management/2-getting-started-ccm/5-access-control/manage-access-control-for-ccm-dashboards.md
docs/cloud-cost-management/2-getting-started-ccm/5-access-control/manage-access-control-perspective-folders.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-auto-stopping-rules-for-azure.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-auto-stopping-rules-for-ecs.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-auto-stopping-rules-for-gcp.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-autostopping-rules-aws.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-autostopping-rules-for-kubernetes.md
docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/cost-optimization-governance.md
docs/cloud-cost-management/6-ccm-auditing.md
docs/cloud-cost-management/8-monitor-cloud-cost-with-integration/_category_.json
src/components/Docs/CloudCostManagement.tsx
src/components/Docs/data/cloudCostManagementData.ts

Added a note in Create AS rules topics to convey dependency on Dkron to run scheduled jobs.
Fixed some cosmetic issues.
Updated some of the topic titles.
Updated the module description on the landing page.

Minor-ccm-updates

---

src/components/Docs/CloudCostManagement.tsx
src/components/Docs/data/cloudCostManagementData.ts

- Changed the title from Cloud Cost Management to Cloud Cost Management Documentation
- Changed the heading "Documentation topics" to "Get started" - I know Sid told a few people that he didn't want us to use Get started in the module docs, but he has come around on that.
- Under "Get started" - added a tile for tutorials.

Updated the landing page

---

docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
tutorials/ci-pipelines/build/ci-java-http-server.md
tutorials/ci-pipelines/build/ci-node-docker-quickstart.md

Preview: https://6450069d914719149e51765c--harness-developer.netlify.app/tutorials/ci-pipelines/build/nodejs
* Reflect changes to starter pipeline
* Make the background step + connection test optional
* Add/promote information about caching
* Add more info to the standalone yaml if users skip the other content.
Preview:  https://6450069d914719149e51765c--harness-developer.netlify.app/tutorials/ci-pipelines/build/java
* Make them easier to read
* Fix some minor issues
* Replicate language-specific info on the GCS page (previously only on the S3 page)
S3 preview: https://6450069d914719149e51765c--harness-developer.netlify.app/docs/continuous-integration/use-ci/caching-ci-data/saving-cache
GCS preview: https://6450069d914719149e51765c--harness-developer.netlify.app/docs/continuous-integration …

[DOC-2956] CI tutorial - Node

---

docs/platform/20_References/runtime-inputs.md

Added execution time runtime input types
You can select the following runtime input types for a step or stage during an execution:  
* Allowed values (`allowedValues()`)
* Default value (optional) (`default()`)
* Request input value when step/stage is being executed (`executionInput()`)

DOC-2823-execution time inputs

---

docs/first-gen/firstgen-platform/techref-category/api/use-custom-secrets-manager-api.md

Removed feature flag corresponding to Custom secret manager from the FirstGen API doc.
* *Issue(s)*
- [x ] Tested Locally

[DOC-2299] Removed custom secret manager feature flag

---

docs/continuous-integration/ci-quickstarts/test-intelligence-concepts.md
docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings.md
docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md
tutorials/ci-pipelines/build/ci-java-http-server.md

- New topic about formatting test reports:
- https://646651542bf1342276580365--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref
- Related changes to link to the new page and some non-technical updates to "Enable Test Intelligence" and "Run Tests step settings"
- Use .ticonfig.yaml to ignore tests/files
- https://646651542bf1342276580365--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/#ignore-tests-or-files

[DOC-1808] [DOC-1604] [DOC-2543] CI Docs - Format Test Reports

---

release-notes/feature-flags.md

[**Link to preview**](https://646b6fcbe5b6bf11f43a3c22--harness-developer.netlify.app/release-notes/feature-flags)

FFM-7949: adds ruby sdk 1.1.1 relnotes

---

release-notes/service-reliability-management.md
release-notes/whats-new.md

SRM release notes for 793xx

---

docs/continuous-delivery/deploy-srv-diff-platforms/custom-deployments/custom-deployment-tutorial.md

Added the following syntax:
AWS KMS: <+infra.variables.AwsKms.spec.credential.type>
AWS secret manager: <+infra.variables.AwsSecretsManager.spec.region>
Azure KeyVault: <+infra.variables.AzureKeyVault.spec.vaultName>
GCP KMS: <+infra.variables.GcpKms.spec.keyName>
GCP Secret manager: <+infra.variables.GcpSecMan.spec.credentialsRef.identifier>
Custom secret manager: <+infra.variables.CustomSecMan.spec.isDefault>
Hashicorp Vault: <+infra.variables.HashiCorp.spec.vaultUrl>

CDS-56983-added secret manager connector variables syntax

---

docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/download-and-copy-artifacts-using-the-command-step.md

Document that 
"Only **Repeat** looping strategy is supported with Command steps"

[CDS-69726]: document repeat strategy limitation for command steps

---

release-notes/whats-new.md

I think we may need to update the required delegate version. According to https://harness.slack.com/archives/CH2L5PWPM/p1684844374106679 and the release notes confluence page, today's delegate version is 79307.
* *Issue(s)*

Update required delegate version

---

release-notes/continuous-delivery.md
release-notes/platform.md
release-notes/whats-new.md

Update required delegate version number in SaaS rls notes
Update the delegate version number required for the 79306 SaaS release. The confluence page and this slack thread has 79307 for the required/new delegate version:
https://harness.slack.com/archives/CH2L5PWPM/p1684844374106679 - Connect your Slack account
[CD](https://646e07cefa253f0b5bac514f--harness-developer.netlify.app/release-notes/continuous-delivery)
[Platform ](https://646e07cefa253f0b5bac514f--harness-developer.netlify.app/release-notes/platform)
[What's new](https://646e20715ffbfa0379e9a128--harness-developer.netlify.app/release-notes/whats-new)
* *Issue(s)*
Some items to keep track of. Screen shots of changes are optional but would help …

[DOC-3149] Update required delegate version number in SaaS rls notes

---

docs/platform/12_Variables-and-Expressions/harness-variables.md

PR for ticket: https://harness.atlassian.net/browse/CDS-68618
We want to document that the above said expression resolves only when the deployment is done to an environment group
* *Issue(s)*

Update harness-variables.md wrt <+env.envGroup..> expressions

---

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
docs/feature-flags/ff-sdks/client-sdks/flutter-sdk-reference.md
docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md
docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md
docs/feature-flags/ff-sdks/client-sdks/react-client.md
docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md
docs/feature-flags/ff-sdks/client-sdks/xamarin-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/apex-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/php-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/ruby-sdk-reference.md
docs/feature-flags/ff-sdks/shared/note-smp-compatible.md
docs/feature-flags/ff-sdks/shared/note-smp-not-compatible.md

[**Link to preview**](https://64805943cf8b0653c101b299--harness-developer.netlify.app/docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference)
This PR adds a note at top of each SDK topic to say whether or not SDK works with SMP.

FFM-8131: adds notes to sdk's on whether supported on SMP

---

docs/platform/2_Delegates/delegate-reference/common-delegate-profile-scripts.md
docs/platform/2_Delegates/install-delegates/install-a-kubernetes-delegate.md
release-notes/delegate.md
release-notes/shared/helm-2-deprecation-notice.md

Add helm 2 deprecation notice to delegate release notes, scrub helm 2 content
[Delegate release notes](https://6488844cc35cd21119e24c05--harness-developer.netlify.app/release-notes/delegate)
[Common delegate initialization scripts](https://6488844cc35cd21119e24c05--harness-developer.netlify.app/docs/platform/Delegates/delegate-reference/common-delegate-profile-scripts)
[Install a legacy Kubernetes delegate](https://6488844cc35cd21119e24c05--harness-developer.netlify.app/docs/platform/Delegates/install-delegates/install-a-kubernetes-delegate)
* *Issue(s)*

[DOC-3260] Add helm 2 deprecation notice to delegate release notes, scrub helm 2 content

---

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
release-notes/feature-flags.md

**Preview:** https://64906b8938df297c5615220d--harness-developer.netlify.app/release-notes/feature-flags

FFM-8260: adds java sdk v1.2.3 relnotes

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
release-notes/continuous-delivery.md
release-notes/early-access.md

Commented out Blue Green Scale Down step documentation as the feature is facing some issues. Will re-publish once QA approves and makes sure that there are no bugs in the feature.

take down BG scale down step docs until dev issues are fixed

---

docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
release-notes/feature-flags.md

Content was added to the June 19 FF release notes for the .net sdk: **lines 69 - 81**.
(The other changes are just reformatting)

FFM-8267: adds .net sdk 1.1.8 relnotes

---

docs/feature-flags/harness-policy-engine.md

This feature is enabled for most accounts, but is behind a feature flag for some accounts. So the feature flag note at the top of this topic has been modified to say that it **may be behind a feature flag for some accounts**.

Updates feature flag note at top of this topic

---

release-notes/platform.md

Update version number, remove PL-37981
For reviewers, [a preview](https://64945a755525f6394c050822--harness-developer.netlify.app/release-notes/platform#june-09-2023-version-79516) is available.
* *Issue(s)*

[DOC-3306] Update version number in release notes

---

docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md

Upgrader CronJob can't work on its own. It needs supporting K8S resources. This includes RBAC roles, Secret and ConfigMap
* *Issue(s)*

chore: [PL-39650]: Add full Upgrader sample yaml

---

docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md

Adds SDK codes which we are rolling on a per SDK bases - see https://harness.atlassian.net/wiki/spaces/FFM/pages/21356052573/SDK+Codes
1003 - language constraint
2001 to 2003 - the SDK does not retry on authentication - known issue.

FFM-8289 Add table of SDK Codes

---

docs/platform/2_Delegates/install-delegates/overview.md

Add Podman info to delegate install
For reviewers, [a preview](https://6499eae64756cc0aad98015a--harness-developer.netlify.app/docs/platform/Delegates/install-delegates/overview#install-docker-delegate-using-podman) is available.
* *Issue(s)*

[DOC-3322] Add Podman info to delegate install

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md

This PR updates the metadata names to lowercase in function-definition.json examples. Earlier it used to throw error due to upper-case initialisation of metadata names.
* *Issue(s)*

Updated the example for function definition on AWS Lambda deployment docs

---

release-notes/continuous-delivery.md

CDS-59624 listed twice in CD release notes 79411. Second reference should be CDS-59544.
https://harness.atlassian.net/wiki/spaces/PD/pages/21400387685/NG+Release+SAAS+May+26th+2023+for+794xx-+Build
https://harness.atlassian.net/browse/CDS-59544
* *Issue(s)*

fix jira ticket number in fixed issues for 79411 CD release notes

---

docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md

[**Link to preview**](https://64a2a4250103a879c04990b1--harness-developer.netlify.app/docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference#enable-verbose-evaluation-logs)
Updates Feature Flags Erlang SDK reference with new configuration option

FFM-8300 Erlang 2.0.0 release doc upates A

---

docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md
release-notes/feature-flags.md

[**Link to preview**](https://64a530516ace7a76a6964928--harness-developer.netlify.app/release-notes/feature-flags)

FFM-8599: adds python sdk 1.2.1 relnotes

---

docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings.md

Added note to Run Tests step settings page about Bazel container images.
Preview: https://64a58e8629e67500b5cdf09e--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings#build-tool

[DOC-3362] add bazel container image note

---

docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-error.md
docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-latency.md
docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md
tutorials/chaos-experiments/chaos-experiments-on-gitlab.md

Fixes dead links in 4 files:
- /docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-error.md
- /docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-latency.md
- /docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md
- /tutorials/chaos-experiments/chaos-experiments-on-gitlab.md

Hotfix: link fixes per deadLinkChecker

---

docs/first-gen/firstgen-release-notes/fg-delegate.md
docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
release-notes/delegate.md
release-notes/early-access.md
release-notes/self-managed-enterprise-edition.md
release-notes/whats-new.md

Add Harness trust center link to release notes, update early access
[What's new](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/release-notes/whats-new)
[Early access](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/release-notes/early-access)
[Delegate NG](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/release-notes/delegate)
[SMP NG](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
[SMP FG](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes)
[Delegate FG](https://64aeb5d8fa02d30077a6bbe9--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/fg-d …

[DOC-3395] Add Harness trust center link to release notes, update early access

---

docs/platform/2_Delegates/secure-delegates/secure-delegates-with-tokens.md
release-notes/delegate.md
release-notes/whats-new.md

Update revoke token info, add to ng release notes and what's new June 28
[NG delegate release notes](https://64b1c94d5e708e20486a39c2--harness-developer.netlify.app/release-notes/delegate)
[What's new](https://64b1c94d5e708e20486a39c2--harness-developer.netlify.app/release-notes/whats-new)
[Revoke tokens](https://64b1c94d5e708e20486a39c2--harness-developer.netlify.app/docs/platform/Delegates/secure-delegates/secure-delegates-with-tokens#option-revoke-tokens)
* *Issue(s)*

[DOC-3329] Update revoke token info, add to NG release notes and what's new June 28

---

docs/platform/Secrets/2-add-use-text-secrets.md

The example for referencing secrets uses secret id that are not possible, we do not allow `-` in IDs in harness.
I change the example secret name to match the secret shown in the screenshot above the examples to make the whole guide flow better, feel free to change the example ID if you want.
* *Issue(s)*

fix: invalid secret IDs

---

docs/platform/20_References/entity-identifier-reference.md

Update RBAC doc to add identifier restriction for Roles
-- Custom roles cannot start with underscore( _ ) 
Ref: https://harness.atlassian.net/browse/PL-40127
* *Issue(s)*

Pl 40127 role creation fails for names starting with underscore

---

docs/security-testing-orchestration/onboard-sto/shared/_supported-infrastructures.md
docs/security-testing-orchestration/whats-supported.md

Update to the following table, which is in a [reusable snippet](https://github.com/harness/developer-hub/pull/2705/files#diff-b143760d1c266988092e97ef66d950b250e464b241fae43cfa92a9156a0e90a5):
* [STO support by CI build infrastructure type](https://64c44bcbeececd14ee7cdc6b--harness-developer.netlify.app/docs/security-testing-orchestration/whats-supported#sto-support-by-ci-build-infrastructure-type)

Update sto infra support doc 3078

---

docs/first-gen/firstgen-release-notes/fg-delegate.md
release-notes/delegate.md

Delegate release notes - move deprecation notices above latest for FG and NG
[Delegate Release Notes (NextGen)](https://64d3a3c41310936fd21d67d9--harness-developer.netlify.app/release-notes/delegate)
[Delegate Release Notes (FirstGen)](https://64d3a3c41310936fd21d67d9--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/fg-delegate)
* *Issue(s)*

[DOC-3561] Delegate release notes - move deprecation notices above latest

---

client-redirects.js
docs/platform/7_Connectors/Code-Repositories/git-hub-app-support.md
docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
release-notes/continuous-integration.md
release-notes/self-managed-enterprise-edition.md

* The FF CDS_GITHUB_APP_AUTHENTICATION won't be deployed til 803xx. Hiding the doc related to that FF until it is deployed.
* Also removed 1 redirect that Docusaurus was ignoring (explanation below).
* Fix a couple links that were pointing to a nonexistent anchor.
When there are multiple categories.json with the same `label`, Docusaurus automatically assigns numbers to them to differentiate them. If one of those categories.json changes and has a different label, Docusaurus updates the numbering for the remaining same-label pages. Thus,  /docs/category/get-started-2 now points to the Platform doc's Get Started page; whereas it used to point to the Get Started with SRM page.
TL;DR: /docs/category/get-started-2 is a valid path so Docusaurus won't honor the redirect.

Revert CI-8370

---

docs/security-testing-orchestration/sto-techref-category/shared/legacy/_sto-ref-legacy-ingest.md
docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-ingestion-file.md
docs/security-testing-orchestration/sto-techref-category/xray-scanner-reference.md

- Commented out a section on Docker-in-Docker requirements in the [jFrog Xray scanner reference](https://64d51cc9c3e7a80eac188cd2--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/xray-scanner-reference).
- Updated a reusable snippet on supported ingestion formats for Security step references -- example section here: [Ingestion file](https://64d51cc9c3e7a80eac188cd2--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/xray-scanner-reference/#ingestion-file) 
- Updated a reusable snippet on supported ingestion formats for scanner-specific step references -- example section here: [Ingestion settings](https://64d51cc9c3e7a80eac188cd2--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/ …

update ingestionOnly format support, remove DinD ref re DOC-3490

---

release-notes/self-managed-enterprise-edition.md

Update air gap bundle download info in SMP release notes
[Self-Managed Enterprise Edition](https://64d544fa52290e0de7d70e6d--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
* *Issue(s)*

[SMP-1797] Update air gap bundle download info in SMP release notes

---

docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
tutorials/ci-pipelines/build/ci-dotnet.md

fix dotnet command
Test Intelligence [Build Arguments](https://64dbfbfbdcfccf009c4de79b--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/#build-arguments) - clarify that C# .NET expects .dll not csproj.
Test Intelligence [Pipeline YAML examples](https://64dbfbfbdcfccf009c4de79b--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/#pipeline-yaml-examples) for .NET - update `args` line as `dotnet test` is implied. Also updated this example in the .NET guide/tutorial.
Incidental changes: Duplicate the FF note for C#. Add tabs for Kotlin and Scala to the language setting.

dotnet with ti args

---

docs/platform/20_References/runtime-inputs.md

DOC-3574: Adding documentation for limitation related to nested json. Currently we don’t support the use of nested JSON body as it’s runtime input default value.
* *Issue(s)*

DOC-3574: Adding documentation for limitation related to nested json

---

docs/platform/20_References/runtime-inputs.md

DOC-3574: Updating documentation for limitation related to nested json - added double inverted comas around nested JSON string
* *Issue(s)*

DOC-3574: Updating documentation for limitation related to nested json

---

docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md

Add auto-population details to enable API access
[Enable API access](https://64dbdbe6fb88c128ccc52fd1--harness-developer.netlify.app/docs/platform/Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference#enable-api-access)
* *Issue(s)*

[DOC-2457] Add auto-population details to enable API access

---

docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
docs/continuous-integration/use-ci/caching-ci-data/run-if-no-cache.md

- DOC-3623: [Confirm cache before installing dependencies](https://64e8e93cd561de273606a032--harness-developer.netlify.app/docs/continuous-integration/use-ci/caching-ci-data/run-if-no-cache)
- DOC-3612: Add log line limit of 70KB to [Troubleshoot CI - Truncated execution logs](https://64e8e93cd561de273606a032--harness-developer.netlify.app/docs/continuous-integration/troubleshoot-ci/troubleshooting-ci#truncated-execution-logs).

DOC-3623 Check for cache before installing dependencies

---

docs/continuous-integration/ci-quickstarts/ci-concepts.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
tutorials/ci-pipelines/ci-kubernetes-build-farm.md

Some examples (added to the K8s cluster tutorial, all K8s build infra configuration topics, all VM build infra config topics, and the build stage settings topic):
[Build on a Kubernetes cluster](https://64e90bb7f3c7703d802dc89f--harness-developer.netlify.app/tutorials/ci-pipelines/kubernetes-build-farm)
[Set up a Kubernetes cluster build infrastructure](https://64e90bb7f3c7703d802dc89f--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure)
[Set up an AWS VM build infrastructure](https://64e90bb7f3c7703d802dc89f--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure)
Build stage …

DOC-3627 Add a note to some pages about plan tier requirement for build infra options

---

release-notes/continuous-delivery.md

- Preview draft: [Latest: Version 804xx](https://64ec9dec70ea1b0ffb4260c3--harness-developer.netlify.app/release-notes/continuous-delivery)
-  [NG Release SAAS August 23rd 2023 for 804xx- Build](https://harness.atlassian.net/wiki/spaces/PD/pages/21476737025/NG+Release+SAAS+August+23rd+2023+for+804xx-+Build)
* [CDS-77758 CD release notes :: 804xx](https://harness.atlassian.net/browse/CDS-77758)

CD 804xx relnotes CDS-7758

---

docs/platform/7_Connectors/Cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Add `kms:GenerateDataKey` requirement for S3 buckets - custom AWS KMS key
[AWS connector settings reference](https://64ff8019d0af9f61506bc5e8--harness-developer.netlify.app/docs/platform/Connectors/Cloud-providers/ref-cloud-providers/aws-connector-settings-reference)
* *Issue(s)*

[DOC-3264] Add kms:GenerateDataKey requirement for S3 buckets - custom aws kms key

---

docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md

- [Documentation for CDS-75250 - TAS Rolling Deploy should create the application when Application is not supported](https://harness.atlassian.net/browse/CDS-75488)
- Preview link (click the **Rolling** tab to view updated content): [TAS execution strategies](https://64f87884ae670f058181ddc0--harness-developer.netlify.app/docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart/#tas-execution-strategies)

update rolling deployment behavior per CDS-75488

---

docs/cloud-cost-management/shared/ccm-supported-platforms.md

Update proxy provisioning - autostopping in What's supported
[What's supported](https://650212e439a87142436c168b--harness-developer.netlify.app/docs/cloud-cost-management/whats-supported)
* *Issue(s)*

[DOC-3723] Update proxy provisioning - autostopping

---

docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md

[Cache Intelligence API](https://651315125ab14b02de4b68c1--harness-developer.netlify.app/docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence#cache-intelligence-api)
[Update the images used in your pipelines](https://651315125ab14b02de4b68c1--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci#update-the-images-used-in-your-pipelines)
* x-api-key is preferred auth method.
* x-api-key doesn't require accountIdentifier parameter.
* Delete cache endpoint is not a subpath of /info.

update cache intel endpoints

---

docs/platform/secrets/add-use-text-secrets.md

remove hidden characters that show up when using copy string functionality. When you copy these two secrets and paste them into an editor (e.g. harness pipeline YAML editor, you get a warning "The character U+200b is invisible")
* *Issue(s)*

Update add-use-text-secrets.md - remove invisible characters

---

docs/platform/variables-and-expressions/expression-v2.md

avoid using '>' unescaped* as it causes a variable resolution issue in a cd stage and can result in null. Updating the example to use '==' or '\>' will properly resolve the variable. Within the pipeline YAML, I also did remove all new lines in order to avoid needing to wrap the entire expression in quotes.
* *Issue(s)*

Update expression-v2.md example

---

docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md

To Support FFM-9030 this adds polling documentation for the JavaScript SDK
Also minor correction for install step to reference the correct distribution for non es module browsers

FFM-9030 Update JS SDK docs for polling, and correct install script

---

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md

Adds SDK codes to Golang and Android
We are rolling out SDK codes across the FF SDKs, one by one

FFM-9486 Add FF SDK Error Codes to Golang and Android SDKs

---

docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
docs/continuous-integration/use-ci/viewing-builds.md

Add [Export full logs](https://65246d524b0bda497f61fe29--harness-developer.netlify.app/docs/continuous-integration/troubleshoot-ci/troubleshooting-ci#export-full-logs) to Troubleshoot CI with existing truncated log info.
Add link to export full logs steps in Build details - [Pipeline tab (logs)](https://65246d524b0bda497f61fe29--harness-developer.netlify.app/docs/continuous-integration/use-ci/viewing-builds#pipeline-tab-logs)

CI-7017 add info about uploading logs larger than 5mb

---

docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism.md

Add details of `nodeName` construct for naming matrix stages
[Use looping strategies](https://651ed3d0157da404f3d76cc8--harness-developer.netlify.app/docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism)
* *Issue(s)*

Adding details of nodeName construct for naming matrix stages

---

release-notes/self-managed-enterprise-edition.md

Add CD service hooks to 0.9.1 patch rn
https://6525c7c27d422a44215c9d13--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#patches
* *Issue(s)*

[CDS-80906] Add CD service hooks to 0.9.1 patch rn

---

docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md

* [Set up a local runner build infrastructure](https://65259954ed03f717c915fc5d--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure):
* Change layout
* Group machine requirements under each OS's instructions
* Revise delegate install steps
* Mark self-signed certs as optional
* Add several troubleshooting items
* Add network driver error to codebase config troubleshooting: [Initial Git clone fails due to missing plugin](https://65259954ed03f717c915fc5d--harness-developer.netlify.app/docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase#initial-git-clone-fails-due-to-missing-plugin)

CI-9848, CI-9847 - local runner build infra and daemon troubleshooting

---

docs/continuous-integration/shared/docker-hub-rate-limiting-trbs.md
docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/download-images-from-private-registry.md

- Add account id parameter back into curl commands
- Create generic steps to pull Harness CI images from a private registry (separate from the STO topic).

Revert pr 3480

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md

techdebt: [[CDS-82108](https://harness.atlassian.net/browse/CDS-82108)]: secret type variables must be non-empty for step input and output variables
* *Issue(s)*
[CDS-82108]: https://harness.atlassian.net/browse/CDS-82108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

techdebt: [CDS-82108]: secret type variables must be non-empty

---

docs/platform/automation/cli/examples.md
tutorials/cd-pipelines/infra-provisioning/cloudformation.md
tutorials/cd-pipelines/kubernetes/helm-chart.md
tutorials/cd-pipelines/kubernetes/kustomize.md
tutorials/cd-pipelines/kubernetes/manifest.md
tutorials/cd-pipelines/kubernetes/ownapp.md
tutorials/cd-pipelines/serverless/aws-lambda.md
tutorials/cd-pipelines/serverless/gcp-cloud-func.md
tutorials/ci-pipelines/publish/ci-push-to-gar.md
tutorials/platform/secrets-management.md

This PR fixes some typos on HDH; many of them are incorrect autocorrection of **harnesscd-example-apps** to **harnessed-example-apps**. Someone probably did a bulk autocorrection at some point or folks copied the incorrect repo name over and over.

Fix typo s/harnessed/harnesscd

---

docs/self-managed-enterprise-edition/advanced-configurations/use-external-secrets-for-license-values.md

K8s external secrets - SMP
[Use external secrets for license values](https://654181405f367a0099210f51--harness-developer.netlify.app/docs/self-managed-enterprise-edition/advanced-configurations/use-external-secrets-for-license-values)
* *Issue(s)*

[SMP-1839] K8s external secrets - SMP

---

docs/chaos-engineering/technical-reference/chaos-faults/vmware/static/manifests/vmware-network-latency/ignore-source-and-destination-ports.yaml
docs/chaos-engineering/technical-reference/chaos-faults/vmware/static/manifests/vmware-network-latency/source-and-destination-ports.yaml
docs/chaos-engineering/technical-reference/chaos-faults/vmware/static/manifests/vmware-network-loss/ignore-source-and-destination-ports.yaml
docs/chaos-engineering/technical-reference/chaos-faults/vmware/static/manifests/vmware-network-loss/source-and-destination-ports.yaml
docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-latency.md
docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-loss.md

Adds port envs for vmware network faults
* *Issue(s)*

feat: [CHAOS-2892]: Adds port envs for vmware network faults

---

docs/security-testing-orchestration/sto-techref-category/shared/dind-bg-step.md

- Jira ticket: [DOC-3884 STO doc :: Integrations :: document any corner cases when running STO scans on OCI build infrastructures](https://harness.atlassian.net/browse/DOC-3884)
- To preview: go to [Docker-in-Docker requirements for STO](https://655396d527177a0099afd1c1--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#docker-in-docker-requirements-for-sto) and expand **Set up a Docker-in-Docker background step**
- Updates:
- Added a caveat that `dockerd` might not work on all platforms
- Added tabs to show both UI and YAML setups for DinD

update DinD setup snippet STO-3884

---

docs/platform/delegates/manage-delegates/delegate-metrics.md

I originally merged https://github.com/harness/developer-hub/pull/3981 before seeing Prateek's question below. Original topic content is now back in place on HDH. This PR is pending an answer from eng. After we hear back, I'll make the appropriate updates, if any are required.
@VikasMaddukuriHarness How do we handle the metric names for delegate versions earlier than 23.11.80403?
Do we need to call out naming differences based on delegate version in the doc?
Thanks.
cc @pratmit 
Updated with recommendation from @raghuAtWings. 
* *Issue(s)*

[PL-42355] Update delegate metric names for 23.11.81403

---

docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
release-notes/continuous-delivery.md
release-notes/delegate.md
release-notes/platform.md

Met with @bharatgoelharness, updating release note version numbers based on:
https://harness.atlassian.net/wiki/spaces/PD/pages/21545484350/QA+Build+Release+Sign+off+November+6th+-+build+814xx+-+2023
https://65577a52554dd3327c7cf7e5--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes#latest-november-15-2023-version-81405
[Continuous Delivery & GitOps](https://65577a52554dd3327c7cf7e5--harness-developer.netlify.app/release-notes/continuous-delivery)
[Delegate](https://65577a52554dd3327c7cf7e5--harness-developer.netlify.app/release-notes/delegate)
[Platform](https://65577a52554dd3327c7cf7e5--harness-developer.netlify.app/release-notes/platform)
* *Issue(s)*
Some …

[PL-42597] Update release note version numbers

---

docs/internal-developer-portal/plugins/available-plugins/harness-srm.md

- More meaningful UI defaults
- Avoid conditional usage by default. Let the plugin handle if no SLOs are set or services are configured.
- General updates to things copied over from CI/CD

Tweaks to the SRM plugin docs for IDP

---

docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-and-serverless-faults.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-agent-stop.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-cpu-hog.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-latency.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-modify-body.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-reset-peer.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-status-code.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-io-stress.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-memory-hog.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-network-latency.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-network-loss.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-volume-detach.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-fargate-cpu-hog.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-fargate-memory-hog.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-instance-stop.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-invalid-container-image.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-network-restrict.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-task-stop.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-container-resource-limit.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-container-timeout.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-task-role.md
docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-svc.yaml
docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-task-affected.yaml
docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-task.yaml

Added manifests for ecs-task-stop
Added a page to group serverless, ec2-backed and both serverless and ec2-backed faults
Added reference links to the above
[Preview](https://65609654a9a7b1172be3ac95--harness-developer.netlify.app/docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-and-serverless-faults)

CHAOS-3118 Group faults based on ec2, serverless and both

---

tutorials/cd-pipelines/kubernetes/manifest.md

This PR brings in two changes:
1. Ensures target namespace `guestbook` gets created via the sync option `Auto create namespace` flag.
2. Use appropriate name: s/Flux GitOps Agent/Flux GitOps Reconciler

Ensure target namespace gets created via `Auto create namespace` flag.

---

docusaurus.config.js

chore: use googleTagManager instead of gtag [HDH-198]

---

docs/platform/delegates/install-delegates/overview.md
docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile.md
docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md

Build a custom image with non-root access that includes custom certificates
https://6577814d56128f47afb6dfb9--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile#build-a-custom-image-with-non-root-access-that-includes-custom-certificates
* *Issue(s)*
[PL-43470]: https://harness.atlassian.net/browse/PL-43470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-43470] Build a custom image with non-root access that includes custom certificates

---

docs/shared/aws-connector-auth-options.md

replaced `default with `harness-delegate-ng` in the eksctl command. SAs are namespaced. We need it to be created in the same ns as the delegate. We should enhance this docs, as AWS's docs is confusing per see. At least explain the IAM OIDC provider step - item1: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
* *Issue(s)*

Fixing Delegate namespace for IRSA

---

docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/add-chaos-hub.md
docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution.md

"Introduction to chaos hub" was in the [flow of execution](https://developer.harness.io/docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution) page. Added the intro of chaos hub to  [add custom hub](https://developer.harness.io/docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/add-chaos-hub) page 
Preview
1. [Flow of execution](https://6581d9a06717f3421017a745--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution)
2. [Chaoshub](https://6581d9a06717f3421017a745--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/add-chaos-hub)

Fix structure

---

docs/continuous-error-tracking/get-started/cet-source-attach.md

CET's source attach mechanism has two ways to operate:
Using parameters to the agent - those will apply to all user classes that participate in an event and that we could find other source information for them from other sources.
Using parameters in the manifest of the jar that included the classes
The second option is the one that should be very usable for most users where there are many jars in the application and each is being built from different repos or paths inside the same repo.

feat [CET-2066] Add documentation for generating CET source attach manifest attributes using gradle and maven.

---

docs/platform/shared/cli/amd.md

This PR removes duplication of the `curl -LO` part for Linux/AMD-architecture installation of Harness CLI.

Remove duplication of the curl -LO part.

---

src/components/Certifications/data/ff-certification-developer-review-guide.md

Some of the bullet points on this page were showing Markdown formatting errors on the website.
This commit removes spaces which make markdown renderer properly render the text as **Bold**.
Here's what the website currently looks like:
https://developer.harness.io/certifications/feature-flags/?lvl=developer
Note that the **5.** point is bold, as expected. The others were not, and showing random stars.
* No issues in perticular. I just leave things in a better shape than I find them where I can 😸 

Fix FeatureFlags certifications page's bold markdown formating

---

docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md

To support Python SDK 1.3.0 release, this adds new SDK codes to public docs.

FFM-10063 Add new SDK codes to Python SDK

---

docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md

Adds deprecation notice to the React Native SDK, informing users to use the React SDK

FFM-10229 Deprecation notice

---

tutorials/cd-pipelines/kubernetes/cosign-opa.md

This PR updates https://developer.harness.io/tutorials/cd-pipelines/kubernetes/cosign-opa where some of the docker image tag were not formatted correctly.

Fix docker image tag for tutorial.

---

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md

At the time of this PR, the STO steps are not available on CI free plans. This PR adds a pill and note to https://developer.harness.io/tutorials/cd-pipelines/unified-cicd/e2e-pipeline so that readers are aware.

Add pill for STO step not available on free plans.

---

docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
tutorials/ci-pipelines/build/ci-ruby.md

No longer required to include bundle install in precommand.

remove bundle install in run tests step examples

---

docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md

We need to remove this section ``Delegate selectors do not override service infrastructure connectors. Delegate selectors only determine the delegate that executes the operations of your pipeline``
* *Issue(s)*

fix: [CDS-88861]: Remove delegate selector overrides info

---

docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss.md
docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop.md
docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-service-kill.md
docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/_category_.json
docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md

`default_health_check` env variable added
Doc review of security consideration
Variables-> Tunables
[Preview](https://65ae5fbf7f607731c6dc0880--harness-developer.netlify.app/docs/chaos-engineering/technical-reference/chaos-faults/gcp/)

GCP faults audit

---

docs/security-testing-orchestration/get-started/shared/_supported-versions-and-data-formats.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-categories.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
docs/security-testing-orchestration/sto-techref-category/shared/_supported-infrastructures.md

Updated sections:
- [Scanner categories supported by STO](https://65b05ec65d5cce1ae0db92d1--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#scanner-categories-supported-by-sto)
- [Scanners supported by STO](https://65b05ec65d5cce1ae0db92d1--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#scanners-supported-by-sto)

Add Secrets to Supported Categories and Supported Scanners STO-7048

---

tutorials/self-managed-enterprise-edition/use-an-external-mongodb-database.md
tutorials/self-managed-enterprise-edition/use-an-external-self-managed-mongodb.md
tutorials/self-managed-enterprise-edition/use-an-external-sm-timescaledb.md
tutorials/self-managed-enterprise-edition/use-self-managed-minio-object-storage.md

Update SMP external db tutorials for TLS support for 0.13.0
[External cloud-based MongoDB](https://65b12f7da64cb61cbb6e29f8--harness-developer.netlify.app/tutorials/self-managed-enterprise-edition/use-an-external-mongodb-database)
* *Issue(s)*

[PL-46234] Update SMP external cloud-based MongoDB tutorial for TLS support for 0.13.0

---

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md

Currently, the OWASP scan step is available on Harness CI free plan. This PR updates the tutorial to reflect this new change and adds some text to explain OWASP scan step.

Update OWASP step.

---

docs/chaos-engineering/technical-reference/probes/prom-probe.md

[Prometheus probe](https://65c8ff0c0d7890420fd598f9--harness-developer.netlify.app/docs/chaos-engineering/technical-reference/probes/prom-probe)

chore: [CHAOS-4175]: Doc Tasks for CHAOS-4167 - Add bearer token Auth support to prometheus probe

---

docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
release-notes/security-testing-orchestration.md

Essentially the same content in both places:
- Release Notes: [Version 1.83.1](https://65cbabfba7908600ad4908f7--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1831)
- [Show original CVSS scores overridden by Snyk security policies](https://65cbabfba7908600ad4908f7--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference#show-original-cvss-scores-overridden-by-snyk-security-policies)

Update ingest_tool_severity support info for Snyk STO-7109

---

docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-github-easyonboarding.md
docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-github.md

Removed admin:org_hook permission for github auth
* *Issue(s)*

Fix: [SEI-5421]: Removed admin:org_hook permission for github auth

---

docs/platform/delegates/install-delegates/install-delegate.md

Update based on GTM Slack feedback. 
Add minikube windows install link, clarify variable info for UI vs CLI delegate installs
[Install Harness Delegate on Kubernetes or Docker](https://65de52a4bb7acd465144b013--harness-developer.netlify.app/docs/platform/delegates/install-delegates/install-delegate)
* *Issue(s)*

[PL-47785] Add minikube windows install link, clarify variable info for UI vs CLI delegate installs

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
kb/continuous-integration/continuous-integration-faqs.md

https://65de2ab9e5606722554d9ada--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates
[Enable self-signed certificates - Default flow](https://65de2ab9e5606722554d9ada--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates#:~:text=default%20certificates%20beta%20feature.%20This%20feature%20automatically%20mounts%20certificates%20for%20out%2Dof%2Dthe%2Dbox%20step%20containers%2C%20and%20you%20no%20longer%20need%20to%20declare%20the%20certs%20path%20for%20the%20built%2Din%20steps%20in%20addition%20to)
[Enable self-signed certificates …

certs management ff

---

docs/platform/delegates/secure-delegates/delegate-mtls-support.md

Immutable delegates or image types don't exist any more, we are trying to rebrand them as just delegates (old thing called delegate now being called legacy delegate)
* *Issue(s)*

Remove references to immutable in delegate-mtls-support.md

---

docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
release-notes/security-testing-orchestration.md

Preview link: [Show original issue severities overridden by Snyk security policies](https://65e5f8dca08ae105758961b2--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference/#show-original-issue-severities-overridden-by-snyk-security-policies)

STO doc :: incorrect heading :: STO-7229

---

docs/software-engineering-insights/sei-metrics-and-reports/security-metrics.md
docs/software-engineering-insights/sei-metrics-and-reports/velocity-metrics-reports/planning-sprint-metrics.md

Fixed the errors on security report docs and added churn rate metric documentation as a sub-topic to the sprint reports topic. 
* *Issue(s)*

fix: [SEI-5988]: HDH DOC FIX (SECURITY REPORTS & CHURN RATE)

---

docs/platform/variables-and-expressions/runtime-inputs.md

Adding documentation for default value can not be overridden in the parent entity if value is provided by the child entity

---

docs/chaos-engineering/api-reference/hce-saas-api.md

Add steps to install CLI API on Linux and MacOS

CHAOS-4870 update hce cli api

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

Preview: SonarQube SonarScanner Technical Reference > [SonarQube proxy settings](https://65fda8c3ab32b224a28e165a--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference#sonarqube-proxy-settings)

how to add proxy settings to SonarQube step STO-7306

---

docs/platform/platform-whats-supported.md

A question came up in the community Slack. https://harnesscommunity.slack.com/archives/C02K03Q5L0J/p1711642188838719
The customer pointed out that the table here says that Audit Trail is available at the project scope.
https://developer.harness.io/docs/platform/platform-whats-supported/#resources-across-scopes
Here we have the info about viewing the Audit Trail and state that it's only org or account scope.
https://developer.harness.io/docs/platform/governance/audit-trail/#step-view-an-audit-trail
This PR updates the table with the correct info for the Audit Trial at the project scope
* *Issue(s)*

Update resources across scopes for audit trail

---

docs/security-testing-orchestration/sto-techref-category/shared/_supported-infrastructures.md
release-notes/security-testing-orchestration.md

Preview
- STO release notes > [Version 198.2](https://66074a1dd2b5ac6c58a8c6f4--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1982) > New features and enhancements, last bullet

harness-cloud-windows-amd64-ingestion-only-is-now-supported-sto-5428

---

release-notes/delegate.md

Last month, we announced two delegate changes that were scheduled to take place by March EOM.
https://developer.harness.io/release-notes/delegate/#important-upcoming-changes
This PR removes the date since the changes are still pending.
https://660c31d9e6829646ec91c9cc--harness-developer.netlify.app/release-notes/delegate#important-upcoming-changes
* *Issue(s)*

Delegate RN - remove March 31 date from upcoming changes

---

CONTRIBUTING.md
docs/platform/get-started/tutorials/gke-workload-identity.md
docs/platform/get-started/tutorials/secure-delegate-default-to-minimal.md
release-notes/chaos-engineering.md
release-notes/cloud-cost-management.md
release-notes/code-repository.md
release-notes/continuous-delivery.md
release-notes/continuous-error-tracking.md
release-notes/continuous-integration.md
release-notes/delegate.md
release-notes/feature-flags.md
release-notes/internal-developer-portal.md
release-notes/platform.md
release-notes/security-testing-orchestration.md
release-notes/self-managed-enterprise-edition.md
release-notes/service-reliability-management.md
release-notes/software-engineering-insights.md
release-notes/software-supply-chain-assurance.md

Tags have additional functionality tied to them, but we aren't currently using tags in a standardized, effective, or habitual way.
Only some release notes pages had tags in their metadata. Being on so few pages, these tags added no value, so I removed them. Impact is minimal to nonexistent.
I updated the guidance on using keywords and tags.
If we choose to use tags, we need to take on a site-wide project where we: 1) Agree on a set of standardized tags (such as "Tutorial", "Troubleshooting", "Kubernetes", etc.), 2) Agree when to use tags, and 3) Implement tags across the entire existing doc set at once so that the resulting "tag pages" are valuable. Then, the tag usage must be maintained …

Remove valueless `tags` metadata

---

docs/feature-flags/relay-proxy/relay_proxy_v2.md

- Adds redis cluster example to docs
- Updates HA mode example docs to specify it's HA mode with a single redis instance
- As a part of this I removed the docker-compose example file, the proxy version in it was pretty outdated and it's easier to keep one copy of this up to date in the repo than maintain a copy in the repo and here.
- Updates Required Configuration section to call out difference between configuring a single redis instance and a clustered redis instance
* Jira/GitHub Issue numbers (if any):FFM-10969
If your PR is open …

FFM-10969 Add redis cluster example to docs

---

docs/chaos-engineering/api-reference/hce-onboarding-api.md
docs/chaos-engineering/api-reference/hce-saas-api.md
docs/chaos-engineering/features/chaos-infrastructure/connect-chaos-infrastructures.md

CHAOS-4388 HCE onboard CLI

---

docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md

* Please describe your changes: instructions tell the user by example to set analytics to false, which dosnt send target information to harness, which is not needed in most cases and especially for new users (who would be the ones copy/pasting from the docs) really do not need this set to false. setting to true makes sure their target information lands in harness. …

Update net-sdk-reference.md to not set analytics to false

---

docs/chaos-engineering/chaos-faults/linux/linux-network-corruption.md
docs/chaos-engineering/chaos-faults/linux/linux-network-duplication.md
docs/chaos-engineering/chaos-faults/linux/linux-network-latency.md
docs/chaos-engineering/chaos-faults/linux/linux-network-loss.md
docs/chaos-engineering/chaos-faults/linux/linux-network-rate-limit.md
docs/chaos-engineering/chaos-faults/linux/static/manifests/linux-network-corruption/destination-ips.yaml
docs/chaos-engineering/chaos-faults/linux/static/manifests/linux-network-duplication/destination-ips.yaml
docs/chaos-engineering/chaos-faults/linux/static/manifests/linux-network-latency/destination-ips.yaml
docs/chaos-engineering/chaos-faults/linux/static/manifests/linux-network-loss/destination-ips.yaml
docs/chaos-engineering/chaos-faults/linux/static/manifests/linux-network-rate-limit/destination-ips.yaml

* Please describe your changes: Adds docs for supporting destination ports filtering for destination IPs
* Jira/GitHub Issue numbers (if any): CHAOS-5067

feat: [CHAOS-5067]: Adds docs for supporting destination ports filtering for destination IPs

---

docs/chaos-engineering/get-started/ce-on-smp/ce-smp-roadmap.md
docs/chaos-engineering/get-started/ce-on-smp/configure-proxy/_category_.json
docs/chaos-engineering/get-started/ce-on-smp/configure-proxy/connect-enterprise-chaoshub.md
docs/chaos-engineering/get-started/ce-on-smp/configure-proxy/connect-infrastructure.md

[Steps to connect chaos infra and enterprise ChaosHub via proxy](https://6620f7917b10263f90002430--harness-developer.netlify.app/docs/category/configure-proxy-on-self-managed-enterprise-edition)

CHAOS-5103 Connect to infra via proxy

---

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md

* Please describe your changes: Add option to Configure an optional registry mirror for delegate images
* Jira/GitHub Issue numbers (if any): PL-49148
* Preview links/images (Internal contributors only): https://6621719baf7a7614f8d642df--harness-developer.netlify.app/docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration#configure-an-optional-registry-mirror-for-delegate-images
PRs must meet these requirements to be …

[PL-49148] Add option to Configure an optional registry mirror for delegate images

---

docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md

Preview link: Gitleaks scanner reference > [Important notes](https://662197a33721d635a73dbc90--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference/#important-notes)

add Gitleak workflows based on WW input STO-7396

---

docs/internal-developer-portal/plugins/available-plugins/azure-devops.md
docs/internal-developer-portal/plugins/available-plugins/circleci.md
docs/internal-developer-portal/plugins/available-plugins/dynatrace.md
docs/internal-developer-portal/plugins/available-plugins/github-actions.md
docs/internal-developer-portal/plugins/available-plugins/jenkins.md
docs/internal-developer-portal/plugins/available-plugins/rafay-kubernetes.md
docs/internal-developer-portal/plugins/available-plugins/sonarqube.md
release-notes/internal-developer-portal.md

* Please describe your changes: Updated the broken URLs due to introduction of community plugins and introduction of additional yarn workspaces to maintain plugins separately out side of the Backstage codebase. 

fix: [IDP-2694]: Updated the broken URLs due to introduction of community plugins 

---

docs/platform/variables-and-expressions/harness-variables.md

Ticket: https://harness.atlassian.net/browse/PIPE-18334
It's an edge case for using ternary operator and semicolon as constant string in expression which is not supported. This PR contains the same changes for mentioning the limitation of same. …

[PIPE-18334] Adding edge case for ternary operator and colon as constant

---

docs/security-testing-orchestration/sto-techref-category/metasploit-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.md

- [Scanners supported by STO](https://6632597edfce338a457d6cc3--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#scanners-supported-by-sto) Reorganized into sections by target type rather than scan type. Added intros that list the types of scans supported by each target type.
- [Ingestion formats supported by STO](https://6632597edfce338a457d6cc3--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#ingestion-formats-supported-by-sto) For all scanners that support both JSON and SARIF, added paren to note that JSON is recommended.
- [Code repo scanners](https://6632597edfce338a457d6cc3--harness-developer.netlify.app/docs/security-testing-orchestration/s …

Update scanner support table sto 7461

---

docs/platform/triggers/triggers-reference.md

Recently, we have made a fix for `<+trigger.branch>` expression resolution within Issue Comment git webhook triggers. 
In this PR, we add a note about the requirement of this Feature Flag enabled  for the `<+trigger.branch>` expression to work as expected for this kind of trigger. …

Add note about CDS_USE_EXECUTION_TRIGGER_PAYLOAD_TO_EVALUATE_BRANCH_EXPRESSION Feature Flag

---

docs/platform/authentication/single-sign-on-sso-with-ldap.md

[PL-49092](https://harness.atlassian.net/browse/PL-49092)
More info: https://harness.atlassian.net/browse/PL-48951
Adding a note to the Cron Expression section
[PL-49092]: …

[PL-49092] Quartz Exp is valid, while Unix Exp is invalid for the Cron

---

docs/platform/delegates/manage-delegates/delegate-metrics.md

[PL-50714](https://harness.atlassian.net/browse/PL-50714)
Changes will be reflected on this doc: https://developer.harness.io/docs/platform/delegates/manage-delegates/delegate-metrics/
Adding a new metric entry to the table:
| `ldap_sync_group_flush_total` | Publishes the total count for a user group when the LDAP group sync returned 0 users for that group. The metric publishes the `accountIdentifier` , `GroupDN` and the `count`. |
If your PR is open longer than two weeks without any human activity, please …

[PL-50714] Publishes the total count for a user group

---

docs/platform/authentication/single-sign-on-saml.md

[PL-43422](https://harness.atlassian.net/browse/PL-43422)
Changes will be reflected on: https://developer.harness.io/docs/platform/authentication/single-sign-on-saml/#saml-sso-with-keycloak
Change: Adding a note - If the account uses vanity URL, then use the same in SAML setup. eg: https://<yourvanityurl>/gateway/api/users/saml-login?accountId=<YOUR ACCOUNT ID>
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.gith …

[PL-43422] note to use vanity URL instead of app.harness

---

docs/platform/authentication/single-sign-on-saml.md

[PL-39191]
If user.userprincipalname can't use email address as name identifier format, then use user.email for should be used as the Unique User Identifier.
This needs to be added so that the customer knows that user.email is expected to process the request on Harness's end. …

[PL-39191] Adding note about user.email

---

docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md

This [Supported scanners table (v2)](https://663bce0d6c9f9e248aa69f5e--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#scanners-supported-by-sto) has the following updates to the [Supported scanners table (v1)](https://developer.harness.io/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#scanners-supported-by-sto) currently on HDH
- [Data Theorem](https://663bce0d6c9f9e248aa69f5e--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/data-theorem-scanner-reference) -- moved from **Artifact scanners** to **Code repo scanners (commercial)**
- [Open Source Vulnerabilities (OSV)](https://663bce0d6c9f9e248aa69f5e--harness-developer.netlify.app/docs/s …

update scanners table STO-7544

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

- SonarScanner scanner reference > [Generate coverage reports and upload to SonarQube](https://66428adcc5b4d43528bb1629--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference#generate-coverage-reports-and-upload-to-sonarqube)

generate coverage reports for SonarQube STO-7557

---

docs/internal-developer-portal/get-started/enable-docs.md

* Please describe your changes:  Added information on techdocs not supported in harness code repo

fix: [IDP]: Added information on techdocs not supported in harness code repo

---

docs/platform/shared/cli/amd.md
docs/platform/shared/cli/arm.md
docs/platform/shared/cli/mac.md
docs/platform/shared/cli/windows.md

[PL-51420
](https://harness.atlassian.net/browse/PL-51420)
We released v0.0.25-Preview version. This needs to be updated in the below document. 
https://developer.harness.io/docs/platform/automation/cli/install#install-harness-cli 
CFD reference: https://harness.atlassian.net/browse/PL-51125
PRs must meet these requirements to be …

[PL-51420] Changing CLI ver from 0.24 to 0.25

---

docs/platform/role-based-access-control/add-manage-roles.md

[PL-46871] Account Admin: Custom resource group

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
kb/security-testing-orchestration/security-testing-orchestration-faqs.md
release-notes/security-testing-orchestration.md

- [SonarScanner scanner reference](https://6669ec77a49b3318aa1a76ee--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference)
- Removed [SonarQube pull-request scan configuration](https://developer.harness.io/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference/#sonarqube-pull-request-scan-configuration) (this link points to the public doc, not the draft)
- [Scan configuration](https://6669ec77a49b3318aa1a76ee--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference/#scan-configuration) Remove **Pull Request**, add description to **Branch Scan**  
- [SonarQube doesn't scan the main branch and pull request branches in the …

SonarScanner remove pull-request config STO-7705

---

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md

Add info in docs regarding the SYSTEM updates done on delegated displayed on audit logs.
"User information is not propagated when a Delegate agent is started from external sources. As a result, all subsequent operations by the Delegate agent will be recorded under the "SYSTEM" user. This includes the creation, deletion, and upsertion of delegates. This behavior is expected during the platform's upgrade process."
* Jira/GitHub Issue numbers (if any): [PL-46758](https://harness.atlassian.net/browse/PL-46758)
We aim to merge PRs within one week or less, …

[PL-46758] Add info in docs regarding the SYSTEM updates

---

docs/continuous-integration/ci-supported-platforms.md
release-notes/continuous-integration.md

- CI release notes > [Version 1.33](https://667cac06b5a0a52c22faf6e8--harness-developer.netlify.app/release-notes/continuous-integration#version-133)
- [Harness CI early access features](https://667cac06b5a0a52c22faf6e8--harness-developer.netlify.app/docs/continuous-integration/ci-supported-platforms#harness-ci-early-access-features) last row in table

CI 1.33 release notes v0 draft

---

.github/CODEOWNERS

This PR adds `@lkilpatrick-harness` to CI and CODE part of CODEOWNERS file alongside `dewan-ahmed`.

Add Dewan and Luke to CI and CODE codeowners

---

docs/feature-flags/use-ff/relay-proxy/relay_proxy_v2.md

- Documents limitations around target forwarding
- Adds `FORWARD_TARGETS` env var which was missing from our docs
* Jira/GitHub Issue numbers (if any): FFM-11803

FFM-11803 Add Target Forwarding Limitation to Relay Proxy Docs

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/define-kubernetes-manifests.md

Removed video referencing the v1 service with old FE experience thats no longer relevant to the new service experience.

CD docs - Removed an old video reference related to Kubernetes manifest

---

release-notes/continuous-integration.md

This PR adds CI 1.38 Release Notes.

CI 1.38 Release Notes

---

release-notes/continuous-integration.md

This PR adds CI 1.39 release notes and an update to 1.38 release notes.

CI 1.39 release notes.

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md

Wrapped environment variable for $API_KEY in quotes so it will interpolate the environment variable. This will make the script run as-is instead of requiring the customer to replace the $API_KEY string with their key.

Improve ci-images script to do API Key variable interpolation

---

docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md

A common error mode for users is giving the wrong key, and the error message is not always clear that the format is the problem. This should be front and center in all concerned docs as this has been an issue in FG and NextGen that customers hit and don't realize the problem. 
Please revise as necessary for clarity or consistency in format
Adding tip to section where one of my customers just hit this error mode and I had to spend 2 hours debugging with them. This is a common failure mode and I didn't realize what happened until I realized I was looking at the linked doc and he was looking at the doc with this proposed revision.

Update Github App documentation to prevent common error mode

---

docs/continuous-integration/ci-supported-platforms.md
release-notes/continuous-integration.md

This PR brings this changes over as it was in the backlog 
https://github.com/harness/developer-hub/pull/7176/

Adding CI 1.32 release notes from backlog

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
release-notes/self-managed-enterprise-edition.md

[CDS-97797] Added workload related warnings to Canary and Blue Green deployment methods
[CDS-97797]: https://harness.atlassian.net/browse/CDS-97797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

[CDS-97797] Added workload related warnings

---

docs/continuous-integration/use-ci/codebase-configuration/scm-status-checks.md
kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes:  addition to FAQ related to build status checks redirect url 
* Jira/GitHub Issue numbers (if any): \CI-13234

CI-13234 status checks points to another build with same commit

---

docs/infra-as-code-management/whats-supported.md
docusaurus.config.js
src/components/HarnessApiData/index.tsx

* Add dynamic content with HarnessAPIData component to render the latest supported framework versions of OpenTofu and Terraform.
* [JIRA](https://harness.atlassian.net/browse/IAC-2255)

docs: [IAC-2255]: Add dynamic IaCM supported framework versions

---

docs/continuous-integration/get-started/harness-ci-intelligence.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md

This PR resolves the broken link on CI docs caused by trailing slashes.
Both links have been updated with full path.

Resolve Docusaurus Trailing Slashes for CI docs.

---

kb/continuous-integration/continuous-integration-faqs.md

This PR adds redirect for the broken https://developer.harness.io/docs/frequently-asked-questions/harness-faqs/continuous-integration-ci-faqs/ page. The correct page for CI FAQ is: https://developer.harness.io/kb/continuous-integration/continuous-integration-faqs/

Add redirect for broken CI FAQ page.

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md

* Please describe your changes: Added docks for a new plugin, to publish build metadata to a docker image in JFrog Docker registry 
* Jira/GitHub Issue numbers (if any): CI-13652

CI-13652 JFrog - publish build metadata to a docker image

---

release-notes/continuous-integration.md

- Added new setting in the account default settings under CI named ‘Upload Logs Via Harness’, allowing customers to route CI step execution logs through Harness’ log service instead uploading them directly from the build environment. This was previously behind a feature flag, but is now available for all users. (CI-13647)
- Due to Docker rate limiting, CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR must be enabled whenever a base image connector is used (CI-13924, ZD-68737)
- For SMP customers the getting started purchase flow for CI has been removed from the side navigation as it is not relevant for SMP customers. (CI-13821)
- Fixed an issue where the plugin image url was incorrect when the registry …

Adding the 1.44 Release Notes

---

docs/platform/pipelines/failure-handling/abort-pipeline.md

Add more information about Abourt process to advise about why there is not an instant "stop" to an abort call.  
* Please describe your changes: \_____ Add more information about Abourt process to advise about why there is not an instant "stop" to an abort call.  
* Jira/GitHub Issue numbers (if any): \______ https://harness.atlassian.net/browse/PL-56864
PRs must meet …

(update) Abort Documentation

---

release-notes/continuous-integration.md

* Please describe your changes: This PR adds CI 1.46 Release Notes. It also adds CI 1.45 Release Notes, which were lost due to the recent `git hard --reset` action that was done on HDH.

Add CI 1.46 RN and 1.45 RN from backlog.

---

kb/cloud-cost-management/articles/onboarding/k8s.md

removing the 1:many delegate:cluster deployment model as it isnt something we should even show customers.

fix: remove single-delegate deployment model

---

docs/internal-developer-portal/layout-and-appearance/home-page-customization.md

We were referencing `<+greetings>` in the branding docs, when the correct usage is `<+greeting>`

correct <+greeting> reference in idp branding docs

---

docs/infra-as-code-management/whats-supported.md
src/components/Docs/data/iacmData.ts

* Update Whats supported doc to move supported framework details (re OpenTofu and Terraform) to the top and also added a new navigation tile to the IaCM landing page.
* [JIRA](https://harness.atlassian.net/browse/IAC-2490)

docs: [IAC-2490]: Update what's supported details

---

docs/platform/variables-and-expressions/harness-expressions-reference.md

- Documented about rollbackSteps expression and it can be used to detect stage rollback during normal pipeline execution.
- Added sample expressions for detecting stage rollback, pipeline rollback, and post-execution rollback.
* Jira/GitHub Issue numbers (if any): PIPE-21808

feat:[PIPE-21808]: Add section on handling rollback scenarios with rollbackSteps expression

---

docs/platform/automation/cli/install.md

Indicate that the CLI is primarily for CLG use case

---

src/components/Roadmap/data/fmeData.ts

We have released Traffic Insights and renamed the Alerts tab to Monitoring tab.  This hit 100% before last week, but I didn't want to push the change amidst issues others were having with source control and the rush to get many new modules live for Unscripted Virtual.
* Please describe your changes: \___Moving Traffic Insights to Released column_________
* Jira/GitHub Issue numbers (if any): \________n/a______________________
* Preview links/images (Internal contributors only): \_____n/a_____________ …

Update fmeData.ts move "Monitoring tab: feature traffic insights" to released column

---

.github/CODEOWNERS

Brandon is a new Principal Solutions Engineer for the CCM module and works to add and review documents to the CCM KB section. Adding him as codeowner so he has the ability to review documentation.

add brandon-harness as CODEOWNER to CCM KB

---

release-notes/chaos-engineering.md

CHAOS-6899 RN 1.47.0

---

docs/continuous-delivery/shared/cd-integrations-supported.md

feat:[CDS-101947]: Add harness code integration info with all swimelanes

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

STO: Add videos and document SonarQube token permissions

---

docs/continuous-delivery/gitops/troubleshooting.md

[CDS-102291] Update CrashLoopBackoff roubleshooting

---

docs/infra-as-code-management/workspaces/workspace-expressions.md

* Update workspace expression doc to warn users not to use reserved keyword: `workspace`
* [JIRA](https://harness.atlassian.net/browse/IAC-2672)

docs: [IAC-2672]: Update workspace expression doc

---

docs/continuous-delivery/cd-onboarding/new-user/rampup-templates.md

* Please describe your changes: This updates the templates best practices guide to add a recommendation for marking new template versions as stable.  This is needed so this new version is used by default in new pipelines.
* Jira/GitHub Issue numbers (if any): None

Add recommendationt to mark new template versions as "stable".

---

docs/platform/role-based-access-control/permissions-reference.md

* Please describe your changes:
**Added CDS and PIPE module related missing permissions with their reference in documentation:-**
- core_pipeline_view
- gitops_cert_view
- gitops_cert_edit
- gitops_cert_delete
- core_inputset_view
- core_inputset_delete
- core_inputset_edit
- core_environment_rollback
- core_accessPolicies_analyze
* Jira/GitHub Issue numbers (if any): **CDS-102272**
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) …

feat:[CDS-102272]:  Expose Actual Permission names with their reference

---

docs/continuous-delivery/gitops/use-gitops/manage-permissions.md

Currently, filtering applications by labels is behind FF CDS_GITOPS_LABELS_BASED_ACCESS_TO_APPS. Updated docs related to the FF

[CDS-103376] Updating Resource groups

---

docs/feature-flags/use-ff/webhook-for-ff.md

* Please describe your changes: Updates the webhook for FF docs to note that yaml validation for ff is not supported in the webhookn events tab

fix: [FFM-12188]: Support Webhook Format in FF Git Sync

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Documentation to prevent looker internal secrets being updated randomly on upgraded when customer uses ArgoCD since it cannot do server lookup
* Jira/GitHub Issue numbers (if any): PL-58621 [PL-58087](https://harness.atlassian.net/browse/PL-58087)
* Preview links/images (Internal contributors only): [Reference](https://github.com/wings-software/looker-docker/blob/main/chart/values.yaml#L321-L330)
PRs must meet …

[fix]: [PL-58621]: Update documents for looker secrets for ArgoCD users.

---

.github/CODEOWNERS

Adding some diversity to the FME roadmap owners so I can request approvals when needed.
* Please describe your changes: \________Added three FME colleagues
* Jira/GitHub Issue numbers (if any): \_________n/a_____________________
* Preview links/images (Internal contributors only): \________n/a__________

Update CODEOWNERS to add additional FME roadmap owners

---

docs/platform/authentication/single-sign-on-saml.md

* Please describe your changes: \____________
As per discussion between @usheerfotedar and eng, It should be this
Default Relay State            triggerType=login
What is relaystate -
Just a way to exchange additonal info between IdP SAML provider(OKTA) and Service Provider (Harness) This info can have custom usage.
For example, we use it to determine whether the call is coming for actual login or just to test login. More details here: https://support.okta.com/help/s/article/How-to-send-a-custom-relaystate-to-application-through-idp-initiated-authentication-urls?language=en_US
* Jira/GitHub Issue numbers (if any): \________. https://harnesssupport.zendesk.com/agent/tickets/71057
* Preview …

(Update) Add Leave blank to Relay State

---

release-notes/continuous-delivery.md

Release notes 1.69.x

---

docs/artifact-registry/platform-integrations/_category_.json
docs/artifact-registry/platform-integrations/cd-ar-integrations.md
docs/artifact-registry/platform-integrations/ci-ar-integrations.md

Integrations page for AR

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md

Adding -E in the run command ensures that variables declared without the sudo are present when the binary runs using the sudo command.

Added sudo -E in local runner doc

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/autostopping-guides/kubernetes-autostopping-traefik.md

For all the traefik examples we are using a legacy `kind`. When you follow the guide with newer versions you will get errors of kinds not found:
```
error: resource mapping not found for name: "whoami" namespace: "" from "middleware.yaml": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
```
When corrected to the new kind, things work as expected:
```
middleware.traefik.io/whoami created
``` …

Update kubernetes-autostopping-traefik.md kinds

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-network-corruption.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-network-duplication.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-network-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-network-loss.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-network-corruption/correlation.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-network-duplication/correlation.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-network-latency/correlation.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-network-loss/correlation.yaml

chore: [CHAOS-7264]: Support correlation percentage in tc-based network experiments

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-dns-error.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-dns-spoof.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-dns-error/transaction-percentage.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-dns-spoof/transaction-percentage.yaml

chore: [CHAOS-7252]: Add transaction percentage support in dns

---

docs/artifact-registry/platform-integrations/ci-ar-integrations.md

* Update CI Integration doc to include Run and Plugin steps
* [JIRA](https://harness.atlassian.net/browse/AH-872)

docs: [AH-872]: Update CI integration to include Run and Plugin steps.

---

docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-cpu-stress.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-memory-stress.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-method-exception.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-method-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-modify-return.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-jvm-trigger-gc.md

* Please describe your changes: Adds tip for using unique byteman port per java process

fix: [CHAOS-7334]: adds tip for using unique byteman port per java process

---

docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md

[fix]: [CDS-105909]: Add multi service runtime inputs not supported limitation

---

docs/continuous-delivery/cd-infrastructure/aws-cdk.md

Updating the doc to add suggestions for managing the dependencies before cdk deploy command.

chore:[CDS-105957]: Add Suggestions for managing dependencies before cdk deploy command

---

.github/CODEOWNERS

* Removing Uri from IaCM and Sushrut from AR codeowners:
* Uri's tag was throwing errors and Sushrut no longer works on AR.
* [JIRA](https://harness.atlassian.net/browse/IAC-3014)

chore: [IAC-3014]: Update codeowners for IACM and AR

---

docs/platform/triggers/trigger-pipelines-using-slack-events.md

Updated Configure Slack with the Webhook

---

docs/artifact-registry/platform-integrations/ci-ar-integrations.md
src/components/DocVideo/index.tsx

I've added the tango guides to the DocVideo plugin that way you can embed a tango guide like so:
`<DocVideo src="https://app.tango.us/app/embed/7892f010-0f5b-4acd-8ad3-9de5426ba386" title="Build and Push Docker Images with Harness Artifact Registry" />`
vs the iframe method. Its consistent with how we embed other videos, and its nice. Let me know what you think
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.gith …

Add tango to docvideo

---

.github/CODEOWNERS

There were duplicate entries for the RA section. Removing the one that had CXE members. Copy over @suranc as an owner.
Then add our Principal Engineers @brandon-harness and @venkat65-harness to codeowners.

Update CODEOWNERS: Add RA Owners

---

.github/CODEOWNERS

Khushi Sharma is our new DevRel engineer in the team and primarily owns IDP docs. Adding her to IDP Docs code owners.
cc @manishas @khushisharmaharness @Debanitrkl

Add Khushi as a Code Owner for IDP Docs

---

docs/platform/governance/policy-as-code/sample-policy-use-case.md

* Please describe your changes: \_____  Update with policy sample to deny secrets in pipelines, except for those at account level.
* Jira/GitHub Issue numbers (if any): \_____ https://harness.atlassian.net/browse/PIPE-24244

(Update) SamplePolicy

---

docs/continuous-delivery/gitops/connect-and-manage/gitops-agent-with-openshift-operator.md

[CDS-99978] Feature: Harness GitOps Agent Operator for OpenShift

---

release-notes/continuous-delivery.md

Release notes CD 1.79.x

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-csharp.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
docs/continuous-integration/use-ci/run-tests/tests-v2.md

CI TI limitation for location of codebase

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.68 RN

Add CI 1.68 RN.

---

release-notes/platform.md

* Please describe your changes: Platform system release 1.79.x
* Jira/GitHub Issue numbers (if any): PL-60698 

[PL-Doc] Release notes for 1.79.x

---

docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
docs/infra-as-code-management/iacm-features/module-registry/module-registry-tabs.md
docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md

* Add new module registry doc to specific mandatory requirements and submodule usage.
* [JIRA](https://harness.atlassian.net/browse/IAC-3227)

docs: [IAC-3227]: Add module registry structure and submodule usage docs

---

src/components/Roadmap/data/fmeData.ts

Per announcement in #ask-split-fme-product 3/4/25:  Gemini Code Assist development is blocked and will be removed from the roadmap. It requires Harness to conform a specific google auth requirement that the platform does not currently support – and is not on the roadmap. When/if this changes, the roadmap will be updated accordingly.
If your PR is open longer than two weeks without any human activity, please tag …

Update fmeData.ts removed Gemini Code Assist

---

kb/cloud-cost-management/cloud-cost-management-faqs.md

added new changes

---

src/components/Roadmap/data/sscaData.ts

[SSCA-3501] Update SSCA Roadmap for FY26 Q1

---

release-notes/continuous-delivery.md

Removed release notes 1.79  as the release 1.79 was burnt

Remove release notes 1.79

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md

@nofarblue three questions:
1. I used port 8284 as an example of a custom port. The pipeline example in the ticket used the same 8082 port as an example.
2. Do you want me to add a YAML example for build intelligence on/off based on an expression?
3. I see the text "By default, the Build Intelligence plugin is downloaded from Maven Central...." in the ticket but no change regarding Maven central is mentioned in the ticket. Is there any required change there?
* Please describe your changes: Docs update for CI-16538
* Jira/GitHub Issue numbers (if any): CI-16538
We aim to merge PRs within one week or less, but delays …

Docs update for CI-16538

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/container-step.md

Allowed values for environment variables are not currently supported in container step configuration.
Workaround: To enforce allowed values, define a stage variable with constraints and reference that variable in the container step's environment variable field.
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/ …

[CDS-108450] Note regarding Allowed values for environment variables

---

docs/continuous-integration/use-ci/prep-ci-pipeline-components.md

Previous admonition was misplaced. This feature is available when running a pipeline; not when creating a pipeline.
* Please describe your changes: Previous admonition was misplaced. This feature is available when running a pipeline; not when creating a pipeline.
* Jira/GitHub Issue numbers (if any): CI-11419

Update note re: dynamic branch selection.

---

src/components/Roadmap/index.tsx
src/constants.ts

Goal is to change Mgmt to Management in *heading* that shows up on our roadmap page.  I'm not trying to change what shows up in the drop-down for selecting modules.
* Please describe your changes: \______Want to spell out Management where we can_______________
* Jira/GitHub Issue numbers (if any): \_________n/a_____________________
PRs must meet these requirements to be …

Update roadmap files to spell out "Management" in FME

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
docs/platform/references/allowlist-harness-domains-and-ips.md
docs/platform/security/add-manage-ip-allowlist.md

Duplicate information exists on https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure/#allowlisting-for-access-to-on-prem-services-linux-platform. Shall we keep this? Per [this thread](https://harness.slack.com/archives/C08E50LNUEA/p1743781913097729), there should be a single place to get the list of all IPs and CIDRs.
* Please describe your changes: This PR adds IPs and CIDR per [this thread](https://harness.slack.com/archives/C08E50LNUEA/p1743781913097729)
* Jira/GitHub Issue numbers (if any): CI-17041
If your PR is open longer than two weeks without any human …

Add IPs and CIDR to allowlist.

---

docs/platform/automation/api/api-permissions-reference.md

Fixed the Input set RBAC permissions. The permissions was wrongly mentioned as core_inputsets_* where it should be core_inputset_*

Fixed the Input set RBAC permissions

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md

Now, you can link to the architecture diagram like so: `[<text>](/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure/#architecture-diagram)`
PRs must …

Move architecture diagram outside of a details block.

---

docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md

If paths are specified without a corresponding key, Cache Intelligence will be disabled for that step.
No caching or restoration will occur in such cases.​
This change ensures that caching behavior is intentional
* Please describe your changes: Documenting changes to default cache key generation behavior when a path is provided without a key …

Updating default cache key behavior

---

src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.css
src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.tsx

* Updated the Dynamic Markdown select component to include inline TOC and apply selected tile URL hash for deep linking.
* Some scroll control was also added to ensure that the appropriate header is still visible when a TOC item is clicked.
https://github.com/user-attachments/assets/f246ea9b-f81e-46df-8ce2-4f889867040e

feature: Add InLine TOC and URL hash for deep linking

---

docs/database-devops/concepts-and-features/understanding-changelog-directories/changelog-directories-structure.md

We are always pointing to changelog file location with folder structure added in search-path command argument.
So we already expect path relative to changelog file by default. Hence removing this `relativeToChangelogFile` property input. …

[feat]: [DBOPS-1173]: Update includeAll path reference expectation

---

docs/platform/variables-and-expressions/runtime-input-usage.md

Added Note in Upload file as runtime input doc, to explicitely state that this will not be supported for SMP

Add note in the doc to explicitly state that the upload file at runtime feature will not be supported for SMP

---

docs/platform/governance/policy-as-code/add-a-governance-policy-step-to-a-connector.md
docs/platform/governance/policy-as-code/add-a-governance-policy-step-to-a-pipeline.md
docs/platform/governance/policy-as-code/add-a-governance-policy-step-to-a-service-account.md
docs/platform/governance/policy-as-code/add-a-policy-engine-step-to-a-secret.md
docs/platform/governance/policy-as-code/aida-for-policies.md
docs/platform/governance/policy-as-code/configure-gitexperience-for-opa.md
docs/platform/governance/policy-as-code/disable-a-policy-set.md
docs/platform/governance/policy-as-code/harness-governance-overview.md
docs/platform/governance/policy-as-code/harness-governance-quickstart.md
docs/platform/governance/policy-as-code/policy-as-code-faqs.md
docs/platform/governance/policy-as-code/sample-policy-use-case.md
docs/platform/governance/policy-as-code/using-harness-policy-engine-for-feature-flags.md
docs/platform/governance/policy-as-code/using-policy-enforcement-on-pipeline-steps.md

I changed the titles and sidebar ordering of policy as code section to hopefully make it easier to look through.

Reorganzied and simplified OPA section

---

docs/database-devops/concepts-and-features/subs-properties-in-changelogs.md

[DBOPS-936]: minimum version required info for substitution property
[DBOPS-936]: https://harness.atlassian.net/browse/DBOPS-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DBOPS-936]: minimum version required info for substitution property

---

docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md

* Please describe your changes: \_____. Users need to enable flag for Base Image Connector
* Jira/GitHub Issue numbers (if any): \_______ Customer ran into same issue (https://harnesssupport.zendesk.com/agent/tickets/83477) in https://harness.atlassian.net/browse/CI-13924

(Update) Docker Layer Caching REQ

---

release-notes/feature-management-experimentation.md

* Please describe your changes: Adds a release note from April that documents the ability to centralize control for flag update behavior in the React SDK.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-151

FMEPRD-151 Add April 16 Release Note

---

docs/platform/variables-and-expressions/variables-and-expressions-faqs.md

The expression <+manifestConfig.primaryManifestId> is not supported in CI Execution (CIE) stages.

[CDS-108832] Added FAQ

---

docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md

* Please describe your changes: This update clarifies the behavior when connecting to private Amazon ECR repositories using a Docker connector in Harness. Specifically, it notes that authentication tokens for private ECR repositories expire every 12 hours (per AWS documentation), requiring periodic updates to the connector credentials. The update also specifies that the built-in harnessImage connector is an account-level Docker connector, and distinguishes between authentication requirements for private and public ECR repositories. 
The reviewer to check if the doc update was made to the right section in addition to regular review.
* Jira/GitHub Issue numbers (if any): CI-17171
* Preview …

Clarify ECR authentication for private repositories in Docker connector setup

---

docs/feature-management-experimentation/10-getting-started/docs/key-concepts.md

Project level permissions (aka "view restrictions") move to RBAC in Phase Two, Part One.  This is "day one" of being migrated to Harness.
Environment-level permissions move to RBAC in Phase Two, Part Two.  This part, often referred to as "granular permissions management" was originally scheduled for early Summer 2025 but will move into fall somewhere most likely.  Phase Two, Part Two also includes object-level permissions moving to RBAC in that same time frame.  Example: who can edit this flag in particular.
* Preview links/images (Internal contributors …

Update key-concepts.md to clarify when projects and env level perms move

---

docs/platform/delegates/delegate-reference/delegate-required-sdks.md

fix: [PL-63372]: fix latest version in harness delegate

---

docs/feature-management-experimentation/20-sdks-and-infrastructure/sdk-overview/versioning-policy-for-sdks-and-customer-deployed-components.md

* Please describe your changes: Adds a redirect (`/docs/feature-management-experimentation/sdks-and-infrastructure/sdk-overview/sdk-versioning-policy` should redirect to `/docs/feature-management-experimentation/sdks-and-infrastructure/sdk-overview/versioning-policy-for-sdks-and-customer-deployed-components`), syncs changes made in https://github.com/splitio/documentation/pull/1093, published in https://help.split.io/hc/en-us/articles/360038143771-Versioning-policy-for-SDKs-and-customer-deployed-components.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-166 …

FMEPRD-166 Update Versioning Policy for SDKs Documentation

---

docs/platform/git-experience/move-inline-entities-to-git.md

and input sets instructions.

---

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/aws/aws-recommendations.md

updated AWS recommendation names

---

docs/infra-as-code-management/get-started/get-started.md
docs/infra-as-code-management/pipelines/operations/approval-step.md

* Add 'warning' admonition to let users know that approval steps use resources until the step is resolved
* [JIRA](https://harness.atlassian.net/browse/IAC-3942)

docs: [IAC-3942]: Add approval resources uage admonition

---

docs/feature-management-experimentation/20-sdks-and-infrastructure/faqs-client-side-sdks/ios-android-browser-sdk-does-the-sdk-cache-expire.md

* Please describe your changes: Discussion with Gaston on Slack about an update to this FAQ. Flagged by Dave K on a Zoom call.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-186
* Preview links/images (Internal contributors only): https://684a0e9afef70d175fb2296a--harness-developer.netlify.app/docs/feature-management-experimentation/sdks-and-infrastructure/faqs-client-side-sdks/ios-android-browser-sdk-does-the-sdk-cache-expire
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWN …

FMEPRD-186 Update Mobile and Web SDK: Does the SDK Cache Expire? FAQ

---

release-notes/delegate.md

* Please describe your changes: Added support for an alternative method to fetch Jenkins job details when the queueItem API returns null
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CDS-109699

RN - Added support for an alternative method to fetch Jenkins job details when the queueItem API returns null

---

docs/platform/harness-aida/harness-mcp-server.md

* Please describe your changes: Fix the MCP repo URL to https://github.com/harness/mcp-server
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/ML-1134

fix: [ML-1134]: Fix harness MCP server url

---

kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: On https://developer.harness.io/kb/continuous-integration/continuous-integration-faqs/#can-i-get-logs-for-a-service-running-on-harness-cloud-when-a-specific-run-step-is-executing, there's a broken link https://developer.harness.io/kb/continuous-integration/continuous-integration-faqs/articles/parallel-step-for-logging which should actually point to https://developer.harness.io/kb/continuous-integration/articles/parallel-step-for-logging
If your PR …

Fix broken FAQ link.

---

docs/continuous-integration/shared/ssh-during-docker-build.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ghcr.md

* Please describe your changes: This PR introduces a reusable documentation block for using SSH keys during Docker builds, and includes it across multiple "Build and Push to [X] Registry" pages.
* Jira/GitHub Issue numbers (if any): CI-17612

Add reusable guide for SSH key usage during Docker builds

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md

[CDS-112250] Lambda function definition limitation

---

docs/database-devops/troubleshooting/troubleshooting.md
docs/database-devops/use-database-devops/get-started/gitops/_category_.json
docs/database-devops/use-database-devops/get-started/gitops/gitops-in-dbops.md
docs/database-devops/use-database-devops/get-started/runtime-secrets.md
docs/database-devops/use-database-devops/set-up-connectors.md

This pull request introduces several updates to the documentation for database DevOps, focusing on improving clarity, adding new information, and ensuring consistency across files. Key changes include adding a detailed explanation about rollback behavior for destructive database operations, updating GitOps branching strategy links, and introducing prerequisites for runtime secrets. Additionally, minor adjustments were made to connector documentation.
- Added a detailed explanation about the limitations of rollback operations for `dropTable` and `dropColumn`, emphasizing that data cannot be recovered without a prior backup. A warning was also added to …

fix: runtime docs and removed jdbc connector

---

docs/internal-developer-portal/catalog/catalog-yaml.md
docs/internal-developer-portal/catalog/manage-catalog.md
docs/internal-developer-portal/flows/harness-pipeline.md
docs/internal-developer-portal/flows/manage-workflow-2o.md
docs/internal-developer-portal/get-started/catalog-2o.md
docs/internal-developer-portal/idp-2o-overview/2-0-overview-and-upgrade-path.md

added the link to guidelines for identifier creation at suitable places

[IDP] - identifier rules

---

docs/artifact-registry/ar-best-practices.md

* Update AR best practice to clarify that proxy names do not require team inclusion and should include proxy in the name, e.g. `acct-docker-proxy-dev`
* [JIRA](https://harness.atlassian.net/browse/AH-1526)

docs: [AH-1526]: Clarify upstream proxy naming convention

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md

Removing mention of Feature Flags  related to enabling Delegate 2.0.
None of these feature flags are required, and we are working on removing them from code.
This is how the page will look like now:
PRs must meet these requirements to …

Remove mention to unnecessary Feature Flags in Delegate 2.0 Docs

---

docs/database-devops/use-database-devops/get-started/get-started-with-changelogs.md

This pull request introduces a new documentation page, "Get Started with Changelogs," to guide users on how to define and manage changelogs for SQL and MongoDB in Harness Database DevOps. The page includes detailed examples of changelogs for both database types, showcasing schema changes, indexing, and sample data management.
* **SQL Changelog Examples**: The page provides YAML examples for SQL changelogs, demonstrating how to create tables, add indexes, insert sample data, and define rollback operations.
* **MongoDB Changelog Examples**: Similarly, the page includes YAML examples for MongoDB changelogs, showcasing operations like creating collections, adding …

feat: add mongoDB changset example

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-gcs-step-settings.md

document glob pattern support in GCSUpload and plugin/gcs steps
- Updated the Upload Artifacts to GCS step to reflect support for glob patterns in `sourcePath` and `ignore` fields.
- Added example using `dist/*.zip` and `ignore: "*.tmp"` to demonstrate use case.
- Modified pipeline YAML examples (Harness Cloud and Kubernetes) to show glob support in `sourcePath`.
- Clarified glob support in plugin step documentation under the "Use a plugin step" section.
Related to Drone GCS plugin update supporting globbing.
[JIRA](https://harness.atlassian.net/browse/CI-18069)

document glob pattern support in GCSUpload and plugin/gcs steps

---

docs/continuous-integration/secure-ci/github-app-token-in-harness.md
kb/continuous-integration/articles/github-app-pat-dispenser.md

- Added a new doc at secure-ci/github-app-token-in-harness.md that explains how to securely generate and use GitHub App tokens in Harness CI pipelines using the github-app-token community plugin.
- Updated the legacy PAT dispenser article to include a note linking to the new recommended approach.
This provides a modern, cloud-compatible alternative for ephemeral GitHub authentication in CI workflows.
[JIRA](https://harness.atlassian.net/browse/CI-17916)

Add GitHub App Token Plugin Doc and Cross-Link from Existing PAT Article

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/event-listener-step.md

This feature has been GAed and is now being cleaned up. GA-ed for QA, Prod1, Prod2, Prod3. 
Additional details: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/harness-core/pulls/105357/

Feature Flag cleanup: CDS_EVENT_LISTENER_STEP

---

docs/database-devops/troubleshooting/troubleshooting.md

* Please describe your changes:  This pull request adds new troubleshooting documentation for errors encountered during rollback operations in PostgreSQL with replication enabled. The update explains the cause of the error, provides a workaround, and outlines a planned long-term fix.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1417 …

feat: add new error faq and solution

---

src/components/Roadmap/index.module.scss
src/components/Roadmap/index.tsx

Enhances the roadmap by adding a feature count next to each column title (Now, Next, Later). The count is styled as a badge to improve visibility and provide a better user experience.
Changes include:
- Displaying the number of features in each roadmap category.
- Styling the count as a distinct badge for better UI.
- Ensuring the feature count is visible on both desktop and mobile views.
Before:
After:

Roadmap: Display feature count on roadmap columns

---

docs/feature-management-experimentation/split-to-harness/administering-migrated-account.md

1. [link to [commit](https://github.com/harness/developer-hub/commit/8fb55dcccff278252b0b973ad004a53936f00b7a)] Add the following info for paid accounts:
Harness account with **Enterprise plan** vs Harness account with **free plan**
* **Naming:**
* **Enterprise plan**
* Harness account name = [Split account name]
* **Harness organization name = [Split account name] + FME**
* Free plan
* Harness account name = [Split account name]
* Harness organization name = default
* **Resource group used at the project level**
* **Enterprise plan - FME All Resources**
* Free plan - All Project Level Resources
2. [link to [commit](https://github.com/harness/developer-hub/commit/3ce73b253253611371a6e791fd4f036728569d3a)] Correct, complete, or clarify info related to **shared** vs **FME only** scenarios …

Update FME Admin RBAC guide: Paid (Enterprise plan) account

---

docs/feature-management-experimentation/10-getting-started/split-and-harness.md
docs/feature-management-experimentation/80-integrations/index.md
src/components/Docs/data/fmeIntegrations.js

* Please describe your changes: Updating the `Harness platform integrations` section in the Split + Harness doc page and adds a tile for Harness IDP as a `Harness Module Integration` on the Integrations landing page. Flagged by Josh Klein and Trevor on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-266 …

FMEPRD-266 Add Harness IDP Integration and Doc Page Link

---

src/components/Docs/FeatureManagementExperimentation.tsx
src/components/Docs/data/featureManagementExperimentationData.ts
src/components/Docs/data/platformData.ts

* Please describe your changes: The current [Harness FME landing page](https://developer.harness.io/docs/feature-management-experimentation) references "Split FME" and also does not reflect the new doc sets that have been added. Also adding FME as an entry next to Feature Flags in the Platform `Get Started with Harness Modules` section of the landing page. Conversation with Dave K on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-252
* Preview links/images (Internal contributors only): https://68a51084d44d4eccb96cb0aa--harness-developer.netlify.app//docs/feature-management-experimentation
We aim to merge PRs within one week or less, but delays happen …

FMEPRD-252 Update Harness FME Landing Page and Add Harness FME to Platform Landing Page

---

docs/continuous-delivery/monitor-deployments/using-cd-custom-dashboards.md

Automatic Filtering docs

---

docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/metrics-impact-cards.md

* Please describe your changes: Add a section for Troubleshooting Experiment Data Mismatch in the Understanding Experiment Results doc page. Conversation with Charles on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-257

FMEPRD-257 Understanding Experiment Results Update

---

release-notes/ai-test-automation.md

* Please describe your changes: Added only to the release notes \__________________________________

AI Test Automation Release notes August 22nd

---

docs/platform/harness-aida/ai-devops.md
docs/platform/harness-aida/aida-ccm.md
docs/platform/harness-aida/aida-ci.md
docs/platform/harness-aida/aida-code-pr.md
docs/platform/harness-aida/aida-code.md
docs/platform/harness-aida/aida-overview.md
docs/platform/harness-aida/aida-sto.md
docs/platform/harness-aida/code-agent.md
docs/platform/harness-aida/harness-mcp-server.md
docs/platform/harness-aida/release-agent.md

* Please describe your changes: Adding a doc page for the Release Agent as a part of the Harness AI Platform doc set. This reflects the `AI Across Your SDLC` section on the [marketing website](https://www.harness.io/products/harness-ai#:~:text=with%20intelligent%20automation.-,AI%20Across%20Your%20SDLC,-Harness%20AI%20is) where Release Agent and the AI SRE Agent are folded into the **Release & Manage Incidents** section.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-271
If your PR is open longer than two weeks …

FMEPRD-271 Add Release Agent to Harness AI Platform Documentation

---

release-notes/database-devops.md

This pull request updates the `release-notes/database-devops.md` file with new release notes for August 2025, covering versions 1.51.x through 1.54.x. The changes focus on usability improvements, feature enhancements, and bug fixes across the schema overview experience, database schema management workflows, authoring and validation capabilities, and rollback flexibility.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1514
If your PR is open longer than two weeks without any human …

feat: add release notes for 1.5x.x for dbdevops

---

docs/security-testing-orchestration/set-up-scans/shared/sast-scanners.md
docs/security-testing-orchestration/set-up-scans/shared/sca-scanners.md
docs/security-testing-orchestration/set-up-scans/shared/secret-scanners.md
docs/security-testing-orchestration/sto-techref-category/github-advanced-security.md
docs/security-testing-orchestration/sto-techref-category/shared/sto-supported-ingestion-formats.md
docs/security-testing-orchestration/sto-techref-category/shared/sto-supported-scanners.md

STO: Document GHAS Native Step

---

docs/platform/get-started/subscriptions-licenses/subscriptions.md

* Please describe your changes: Removes mentions of FF Classic and replaces instances with licensing and consumption information about FME. Discussion with Trevor S on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-284

FMEPRD-284 Update View and Manage Subscriptions Documentation

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md

* Please describe your changes: Update note that TI supports venv for Python
* Jira/GitHub Issue numbers (if any): CI-18964

Update note that TI supports venv for Python

---

docs/chaos-engineering/faults/chaos-faults/aws/aws.md
docs/chaos-engineering/faults/chaos-faults/aws/experiments.ts
docs/chaos-engineering/faults/chaos-faults/aws/lambda-block-tcp-connection.md
docs/chaos-engineering/faults/chaos-faults/aws/static/manifests/lambda-block-tcp-connection/function-name.yaml
docs/chaos-engineering/faults/chaos-faults/aws/static/manifests/lambda-block-tcp-connection/target-hostnames.yaml
docs/chaos-engineering/faults/chaos-faults/aws/static/manifests/windows-ec2-process-kill/force.yaml
docs/chaos-engineering/faults/chaos-faults/aws/static/manifests/windows-ec2-process-kill/process-ids.yaml
docs/chaos-engineering/faults/chaos-faults/aws/static/manifests/windows-ec2-process-kill/process-names.yaml
docs/chaos-engineering/faults/chaos-faults/aws/windows-ec2-process-kill.md
docs/chaos-engineering/faults/chaos-faults/kubernetes/experiments.ts
docs/chaos-engineering/faults/chaos-faults/kubernetes/kubernetes.md
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/pod-application-function-error.md
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/pod-application-function-latency.md
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-connection-error/function.yaml
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-connection-error/message.yaml
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-connection-error/name.yaml
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-function-latency/function.yaml
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-function-latency/latency.yaml
docs/chaos-engineering/faults/chaos-faults/kubernetes/pod/static/manifests/pod-application-function-latency/name.yaml

add missing fault docs

---

docs/security-testing-orchestration/sto-techref-category/nexus-scanner-reference.md

STO: Document Nexus IQ Native Step

---

docs/feature-management-experimentation/split-to-harness/sso-for-admins.md

Update the guide for the SCIM case: Legacy Split user groups are copied over, even if not set up for SCIM.
The result is that if SCIM was not set up to create and sync these users, they are temporarily not SCIM-managed. It's smart enough to deal with a mix of SCIM-managed and non-SCIM-managed users and groups.
Additional minor improvements:
* Add internal section links
* Minor formatting of dates and `app.harness.io`
Jira ticket numbers: FMEPRD-298

[FMEPRD-298] FME SSO guide: Update - Split users groups created even if not yet set up for SCIM
