docs/harness-cloud-operations/computing-uptime.md
=> Updated for the rest of the modules

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
* https://harness.atlassian.net/browse/CDS-80782
=> [CDS-80782]: Remove Rancher FF from docs

docs/harness-cloud-operations/computing-uptime.md, src/components/HomepageCertifications/data/certificationsData.ts
=> Updated Cert and Uptime

tutorials/internal-developer-portal/service-onboarding-pipeline.md
Updated the cookiecutter template and replaced it with another react app
* *Issue(s)*
=> fix [IDP-1358] : Updated the cookiecutter template

src/components/Docs/data/internalDeveloperPortal.ts, src/components/LandingPage/data/internalDeveloperPortalData.tsx
Updated the HDH landing page for IDP docs and tutorials 
* *Issue(s)*
=> fix [IDP-1467] : Updated the HDH landing page for IDP docs and tutorials

release-notes/chaos-engineering.md
=> fix: [CHAOS-2730]: Added release notes docs for 1.22.x release for Chaos Module

docs/continuous-delivery/cd-integrations.md
=> CD feature flags table

docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
https://harness.atlassian.net/browse/DOC-3844
- [x ] Issue
* https://harness.atlassian.net/browse/DOC-3844
=> DOC-3844 skip helm chart tests

docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
Remove CD_TERRAFORM_CLOUD_CLI_NG FF
* *Issue(s)*
=> Remove CD_TERRAFORM_CLOUD_CLI_NG FF

docs/harness-cloud-operations/computing-uptime.md
=> Added examples

docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-jira-issues-in-cd-stages.md
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-74797
=> CDS-74797 add CDS_JIRA_UPDATE_SELECT_FIELDS_ENABLED flag

release-notes/chaos-engineering.md
=> fix: [CHAOS-2883]: Added release notes for 1.23.x Chaos Module

release-notes/internal-developer-portal.md
I think it makes sense to see the date of the latest release, to understand how "latest" is this.
* *Issue(s)*
=> IDP: Add date to the latest release notes

.github/CODEOWNERS, .github/pull_request_template.md
Committing CODEOWNERS v1.
* *Issue(s)*
=> Initial Commit of CODEOWNERS

docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-jira-issues-in-cd-stages.md
=> fix:[CDS-74797]: fixed FF description of jira update docs

docs/platform/variables-and-expressions/harness-variables.md
=> fix: [CDS-80944]: fix documentation for method invocation in expressions

docs/service-reliability-management/get-started/create-first-slo.md
=> SRM: Quarter start month in SLO

kb/continuous-delivery/continuous-delivery-faqs.md, kb/continuous-integration/continuous-integration-faqs.md
=> Addition-Faqs[ October 27 ]

kb/continuous-delivery/continuous-delivery-faqs.md
=> 33 CD FAQS ZANINI

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> 4 CCM FAQS ZANINI

kb/continuous-integration/continuous-integration-faqs.md
=> 5 CI FAQS ZANINI

kb/platform/harness-platform-faqs.md
=> 11 PLATFORM FAQS ZANINI

kb/security-testing-orchestration/security-testing-orchestration-faqs.md
=> 2 STO FAQS ZANINI

docs/platform/variables-and-expressions/runtime-inputs.md
=> Add Fixed Value Tutorial reference in HDH Docs

docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
=> Update deploy-helm-charts.md to include Helm feature flags

docs/continuous-delivery/gitops/use-gitops/sops.md
* *[CDS-80356](https://harness.atlassian.net/browse/CDS-80356)*
[CDS-80356]: https://harness.atlassian.net/browse/CDS-80356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CDS-80356: [Documentation] K8s secrets with SOPS - first draft.

docs/service-reliability-management/srm-roles-and-permissions.md
=> SRM RBAC support

docs/platform/approvals/adding-harness-approval-stages.md
=> feat:[CDS-82193]: added notes for usergroup as expression in HA

release-notes/internal-developer-portal.md
Added the blog post to the release notes and corrected an URL
* *Issue(s)*
=> fix [IDP] Added the blog post to the release notes and corrected an URL

docs/continuous-delivery/cd-infrastructure/terraform-infra/rollback-provisioned-infra-with-the-terraform-rollback-step.md, docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md, docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
[CDS-76320]: Update run-a-terraform-plan-with-the-terraform-plan-step.md
* *Issue(s)*
[CDS-76320]: https://harness.atlassian.net/browse/CDS-76320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-76320]: Update run-a-terraform-plan-with-the-terraform-plan-step.md

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
https://harness.atlassian.net/browse/CDS-77574
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-77574
=> CDS-77574 scoping export output vars

docs/service-reliability-management/monitored-service/monitored-service-metric-threshold.md
=> SRM: Metric threshold update

docs/continuous-delivery/x-platform-cd-features/executions/step-and-stage-conditional-execution-settings.md
https://harness.atlassian.net/browse/CDS-79110
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-79110
=> CDS-79110 label changes to Cond Exec

docs/platform/variables-and-expressions/harness-variables.md
https://harness.atlassian.net/browse/CDS-78004
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-78004
=> CDS-78004-trigger-exp

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md, docs/continuous-delivery/deploy-srv-diff-platforms/serverless-lambda-cd-quickstart.md, docs/platform/connectors/cloud-providers/add-aws-connector.md, docs/shared/aws-connector-auth-options.md
https://harness.atlassian.net/browse/CDS-81877
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-81877
=> CDS-81877 IRSA delegate steps added to SAM and Serverless

docs/platform/variables-and-expressions/runtime-inputs.md
Update runtime input strings
[Fixed values, runtime inputs, and expressions](https://652f03e4e46c9506a9f05166--harness-developer.netlify.app/docs/platform/variables-and-expressions/runtime-inputs)
* *Issue(s)*
=> [DOC-3226] Update runtime input strings

docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
=> [fix]: [CCM-14914]: AWS CCM SMP Infra Doc Update

docs/internal-developer-portal/features/software-catalog.md
Updated the time to reflect changes from catalog
* *Issue(s)*
=> fix [IDP] : Updated the time to reflect changes from catalog

docs/platform/triggers/triggers-reference.md
=> [feat]: [CDS-83138]: Update Webhook triggers reference

certifications/faqs.md, certifications/instructions.md
=> Updated retake for paid exam information

certifications/chaos.md, certifications/faqs.md, certifications/instructions.md, certifications/sto.md, docusaurus.config.js, sidebars-certifications.js, src/components/Certifications/CertificationsSTO.tsx
=> Updated Cert Order to Match Docs and added STO Base

kb/cloud-cost-management/articles/slack-email-alert.md, kb/continuous-delivery/articles/Pipeline-success-on-failure.md, kb/continuous-delivery/articles/ability-to-view:filter-pipeline-execution-by-inputs.md, kb/continuous-delivery/articles/create-terraform-resource-group-with-specified-scope-resorces.md, kb/continuous-delivery/articles/harness-order-to-apply-manifest-resorces.md, kb/continuous-delivery/articles/helm-connector.md, kb/continuous-delivery/articles/input-set-gitsync.md, kb/continuous-delivery/articles/output-variable-for-powershell-script.md, kb/continuous-delivery/articles/ternary-operator.md, kb/continuous-integration/articles/using-images-from-multiple-ACRs.md, kb/platform/articles/Unable-to-Install-Custom-Tools-on-Delegate-via-Init-Script.md, kb/platform/articles/api-to-clone-pipeline.md, kb/platform/articles/api-to-run-a-pipeline-with-runtime-inputs.md, kb/platform/articles/delegate-details-api.md, kb/platform/articles/delegate-installation-gke-error.md, kb/platform/articles/mount-custom-cert-with-delegate.md, src/components/KnowledgeBase/LandingPage.tsx, src/components/KnowledgeBase/data/knowledgeBaseData.ts
* Harmonize Names with Title
* Removed blank KB MDs
* Updated Selected Articles
* *Issue(s)*
=> Tidy around the KB

src/components/Certifications/CertificationsSTO.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
=> Updated pages for STO

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
* remove-ff-NG_CDS_NATIVE_EKS_SUPPORT
=> remove-ff-NG_CDS_NATIVE_EKS_SUPPORT

docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md, release-notes/delegate.md, release-notes/self-managed-enterprise-edition.md
SMP 0.10.0 release notes
[Harness Self-Managed Enterprise Edition Release Notes (NextGen)](https://6542d27fb5e696436fdafce7--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
[Harness Self-Managed Enterprise Edition Release Notes (FirstGen)](https://65416136170517008a3164c8--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes)
* *Issue(s)*
=> [SMP-2216] SMP 0.10.0 809xx release notes

docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift.md
Install in an OpenShift environment
[Install in an OpenShift environment](https://65412dfefb6721289814d80d--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift)
* *Issue(s)*
=> [SMP-2229] Install in an OpenShift environment

docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Add ccm to smp helm install
[Install using Helm](https://653ffdc43b03cd3811a22d97--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga)
* *Issue(s)*
=> [SMP-2246] Add ccm to smp helm install

docs/self-managed-enterprise-edition/monitor-harness-on-prem.md
Update SMP monitoring for 0.10.0
[Monitoring options](https://654107faefdcf313c4a813d5--harness-developer.netlify.app/docs/self-managed-enterprise-edition/monitor-harness-on-prem)
* *Issue(s)*
=> [SMP-2228] Update SMP monitoring for 0.10.0

kb/continuous-delivery/continuous-delivery-faqs.md, kb/platform/harness-platform-faqs.md
=> Amit FAQ contribution

docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
=> [fix]: [CCM-14942]: [CBP] AWS SMP Airgapped - Default to HTTPS

docs/internal-developer-portal/whats-supported.md
Added the information on what's supported with integrators
* *Issue(s)*
=> fix [IDP-1528] : Added the information on what's supported with integrators

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-auth-access-id.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-image-access-id.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-image-access-token.md
Previews of updated topics:
- [Anchore Enterprise scanner reference](https://65439b8c0af945072c5978cf--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference)
- [Harness STO Scanner Support](https://65439b8c0af945072c5978cf--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#harness-sto-scanner-support) Added link to Container scanners, licensed
=> Anchore Enterprise integration v2 draft DOC-6382

release-notes/security-testing-orchestration.md
=> Add STO-6441 to release notes

src/components/LandingPage/Platform.tsx, src/components/LandingPage/SMP.tsx
Update smp and pl tutorial landing pages
[Administer Harness Platform](https://654425e47b6f0c006fa81961--harness-developer.netlify.app/tutorials/platform)
[Administer Harness Self-Managed EE](https://654425e47b6f0c006fa81961--harness-developer.netlify.app/tutorials/self-managed-enterprise-edition)
* *Issue(s)*
=> [DOC-3717] Update smp and pl tutorial landing pages

docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
=> fix: [CDS-83115]: fix setup docs for agent with proxy configured

docs/chaos-engineering/technical-reference/probes/cmd-probe.md, docs/chaos-engineering/technical-reference/probes/http-probe.md, docs/chaos-engineering/technical-reference/probes/k8s-probe.md, docs/chaos-engineering/technical-reference/probes/prom-probe.md, docs/chaos-engineering/technical-reference/probes/slo-probe.md
=> chore: [CHAOS-2938]: Add the probe usage examples in the docs and sync the probe with latest probe schema changes

docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-io-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-service-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-blackhole-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-disk-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-corruption.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-duplication.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-service-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-time-chaos.md
=> chore: [CHAOS-2918]: Enhance VMware Experiment Documentation in Developer Hub

docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
=> fix: [CDS-83115]: Fix casing in example

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> Add connector/data pipeline related FAQs

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> Update cloud-cost-management-faqs.md for Connectors and Data-Pipeline

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> Added FAQs for AutoStopping from related JIRA Questions

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-cost-optimization-governance.md, kb/cloud-cost-management/cloud-cost-management-faqs.md
=> docs: [CCM-14971]: Governance FAQs

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> feat: updated FAQs for dashboards

release-notes/platform.md
Platform 81308 release notes
[Platform](https://6543ab00d3454f17028acfca--harness-developer.netlify.app/release-notes/platform)
* *Issue(s)*
=> [PL-42318] Platform 81308 release notes

release-notes/whats-new.md
=> add pl 81308

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md, tutorials/cd-pipelines/notifications.md
=> [CDS-82636]: Removing FF from docs

kb/cloud-cost-management/cloud-cost-management-faqs.md
=> Updated KB with recommendations FAQs

src/components/LandingPage/data/continuousDeliveryData.tsx
This PR adds a missing tutorial card for cosign OPA tutorial.
* *Issue(s)*
=> Add missing tutorial card for cosign OPA tutorial.

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-canary-phased-traffic-shift.md
https://harness.atlassian.net/browse/CDS-78932
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-78932
=> Update ecs-basic feature flag added

tutorials/cd-pipelines/kubernetes/cosign-opa.md
=> Adding update to paid

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-79647
=> CDS-79647 S3 artifact image incorrect

docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-self-managed-add-ingress-controller-service-annotations.md
=> Update SMP KOTS notes

docs/faqs/self-managed-ee-faq.md
Create SMP FAQ
[FAQs](https://6545582c13b2102059cb1170--harness-developer.netlify.app/docs/faqs)
[Harness Self-Managed Enterprise Edition FAQs](https://6545582c13b2102059cb1170--harness-developer.netlify.app/docs/faqs/self-managed-ee-faq)
* *Issue(s)*
=> [PL-42367] Create SMP FAQ

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
https://harness.atlassian.net/browse/CDS-80791
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-80791
=> CDS-80791 new migration notice

release-notes/service-reliability-management.md, release-notes/whats-new.md
=> SRM RN 1.6

docs/service-reliability-management/monitored-service/health-source/datadog.md
=> Update datadog.md so metrics collector header appears

docs/internal-developer-portal/get-started/onboarding-guide.md, docs/internal-developer-portal/get-started/register-a-new-software-component.md
Added the section headers for IDP onboarding guide
* *Issue(s)*
=> fix: Added the section headers for IDP onboarding guide

docs/continuous-error-tracking/get-started/cet-arc.md
=> CET: Tiny links in Agent log

docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-rate-limit.md
Docs review for [CHAOS-2815](https://github.com/harness/developer-hub/pull/3867)
[CHAOS-2815]: https://harness.atlassian.net/browse/CHAOS-2815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs 2815 smriti

kb/platform/harness-platform-faqs.md
=> FAQ of the week

kb/continuous-delivery/continuous-delivery-faqs.md
=> Faqs addition to CD-Knowledge Base

docs/continuous-error-tracking/get-started/cet-event-dashboard.md
=> CET:Event list filters

docs/platform/templates/templates-best-practices.md
See https://harness.atlassian.net/browse/CDS-78456
* [*Issue(s)*](https://harness.atlassian.net/browse/CDS-78456)
=> Documentating diff edge conditions during reconcile

docs/security-testing-orchestration/use-sto/view-and-troubleshoot-vulnerabilities/jira-integrations.md
=> Jira integration updates per DOC-3866

docs/platform/pipelines/w_pipeline-steps-reference/pipeline-settings.md
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-68344
=> CDS-68344 limit reached executions are not failed

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
https://harness.atlassian.net/browse/CDS-81707
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-81707
=> CDS-81707 attach CloudWatch alarms

docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-loss.md
Documentation review for [CHAOS-2892](https://github.com/harness/developer-hub/pull/3919)
[CHAOS-2892]: https://harness.atlassian.net/browse/CHAOS-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs review for CHAOS-2892

release-notes/continuous-delivery.md
Per request from Ivan Mijailovic at https://harness.atlassian.net/browse/CDS-81032?focusedCommentId=598957. 
* *Issue(s)*
=> Changed the delegate version in the release note for CDS-81032.

docs/chaos-engineering/technical-reference/chaos-faults/linux/experiments.ts, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-rate-limit.md
Doc review for [CHAOS-2495](https://github.com/harness/developer-hub/pull/4042)
[CHAOS-2495]: https://harness.atlassian.net/browse/CHAOS-2495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Doc review

docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-corruption.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-duplication.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-loss.md
Docs review for [CHAOS-2873](https://github.com/harness/developer-hub/pull/3917)
[CHAOS-2873]: https://harness.atlassian.net/browse/CHAOS-2873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs review 2873

src/components/Docs/data/internalDeveloperPortal.ts
fixed broken link on IDP docs landing page
* *Issue(s)*
=> fix: fixed broken link on IDP docs landing page

docs/platform/authentication/single-sign-on-saml.md, docs/platform/authentication/single-sign-on-sso-with-ldap.md, docs/platform/authentication/single-sign-on-sso-with-oauth.md, docs/platform/shared/local-login-note.md
Local login note
[Single Sign-On (SSO) with SAML](https://65497cf23bdcc31579acd1dc--harness-developer.netlify.app/docs/platform/authentication/single-sign-on-saml)
[Single Sign-On (SSO) with LDAP](https://65497cf23bdcc31579acd1dc--harness-developer.netlify.app/docs/platform/authentication/single-sign-on-sso-with-ldap)
[Single Sign-On (SSO) with OAuth](https://65497cf23bdcc31579acd1dc--harness-developer.netlify.app/docs/platform/authentication/single-sign-on-sso-with-oauth)
* *Issue(s)*
=> [PL-31914] Local login note

docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md, docs/continuous-delivery/gitops/use-gitops/sops.md
=> Fix SOPS BYO script

docs/platform/settings/default-settings.md
Update default settings topic
[Default settings](https://654a6da2da3bf906c1842371--harness-developer.netlify.app/docs/platform/settings/default-settings)
* *Issue(s)*
=> [DOC-3428] Update default settings topic

docs/continuous-delivery/get-started/services-and-environments-overview.md
added redirect for:
https://developer.harness.io/docs/continuous-delivery/onboard-cd/cd-concepts/cd-pipeline-basics
- [ x] Issue
* https://harness.atlassian.net/browse/DOC-3885
=> DOC-3885 added redirect

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
https://harness.atlassian.net/browse/CDS-57169
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-57169
=> CDS-57169 HTTP step cert support

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md, docs/continuous-delivery/gitops/applicationsets/harness-git-ops-application-set-tutorial.md, docs/continuous-delivery/gitops/pr-pipelines/pr-pipelines.md, docs/continuous-delivery/gitops/use-gitops/create-cluster-with-iam.md, docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md, docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/harness-governance-overview.md, docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md, docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md, docs/platform/triggers/selective-stage-execution-using-triggers.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/manage-feature-flags.md, kb/platform/harness-platform-faqs.md, release-notes/continuous-delivery.md, release-notes/shared/cd-79700-early-access.md
https://harness.atlassian.net/browse/CDS-83708
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-83708
=> CDS-83708 removing some FEATURE FLAGS

docs/platform/git-experience/import-input-sets.md
=> fix broken links in import-input-sets.md

docs/internal-developer-portal/public-api.md
Added the list of supported APIs in Harness IDP
* *Issue(s)*
=> feat: [IDP-1574] Added the list of supported APIs

release-notes/internal-developer-portal.md
Added the IDP v0.14.0 release notes
* *Issue(s)*
=> feat: [IDP-1573] : Added the IDP v0.14.0 release notes

docs/platform/variables-and-expressions/expression-v2.md
* *[CDS-80824](https://harness.atlassian.net/browse/CDS-80824)*
[CDS-80824]: https://harness.atlassian.net/browse/CDS-80824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CDS-80824 (Issue with JEXL Scripting).

release-notes/security-testing-orchestration.md
Preview: [Latest: Version 1.73.1](https://654c2f020e49ad0e5eab3ad4--harness-developer.netlify.app/release-notes/security-testing-orchestration#latest-version-1731)
=> STO 1.73.1 release notes STO-6718

docs/first-gen/firstgen-release-notes/fg-delegate.md, docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
Add FirstGen JRE notice to release notes
[Harness SaaS Release Notes (FirstGen)](https://654ce7bd9c446f4e1adb970c--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes)
[Delegate Release Notes (FirstGen)](https://654ce7bd9c446f4e1adb970c--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/fg-delegate)
* *Issue(s)*
=> [PL-42483] FirstGen JRE notice

docs/faqs/harness-security-faqs.md, docs/first-gen/firstgen-fa-qs/harness-security-faq.md, docs/first-gen/firstgen-platform/account/manage-connectors/add-microsoft-azure-cloud-provider.md, docs/first-gen/firstgen-platform/security/access-management-howtos/provision-azure-ad-users-and-groups-scim.md, docs/first-gen/firstgen-platform/security/access-management-howtos/single-sign-on-sso-with-saml.md, docs/first-gen/firstgen-platform/security/secrets-management/azure-key-vault.md, docs/first-gen/firstgen-platform/techref-category/configuration-as-code-yaml/harness-yaml-code-reference.md, docs/first-gen/starthere-firstgen/supported-platforms.md, docs/get-started/shared/auth-supported.md, docs/platform/authentication/multiple-identity-providers.md, docs/platform/authentication/single-sign-on-saml.md, docs/platform/authentication/single-sign-on-sso-with-oauth.md, docs/platform/connectors/cloud-providers/add-a-microsoft-azure-connector.md, docs/platform/get-started/key-concepts.md, docs/platform/get-started/onboarding-guide.md, docs/platform/platform-whats-supported.md, docs/platform/role-based-access-control/add-users.md, docs/platform/role-based-access-control/provision-users-and-groups-using-azure-ad-scim.md, docs/platform/role-based-access-control/rbac-in-harness.md, docs/platform/secrets/secrets-management/azure-key-vault.md, src/components/Docs/data/platformData.ts, tutorials/cd-pipelines/vm/azure.md
PL docs replace Azure AD with Microsoft Entra ID
* *Issue(s)*
=> [DOC-3802] PL docs replace Azure AD with Microsoft Entra ID

docs/platform/authentication/single-sign-on-saml.md, docs/platform/automation/terraform/harness-terraform-provider.md, docs/platform/role-based-access-control/provision-use-jit.md, docs/platform/role-based-access-control/provision-users-and-groups-using-azure-ad-scim.md
=> more azure ad - ms entra

kb/continuous-delivery/continuous-delivery-faqs.md
=> 11 FAQs added , few duplicates removed

release-notes/self-managed-enterprise-edition.md
SMP 0.10.1 release notes
https://654e7fdb154d800be9c5e171--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#0101
* *Issue(s)*
=> [SMP-2283] SMP 0.10.1 release notes

src/components/Certifications/FeatureFlags.tsx
Updated mis-aligned DIVs
* *Issue(s)*
=> Updated mis-aligned DIVs

src/components/Certifications/FeatureFlags.tsx, src/components/Certifications/data/certificationsData.ts, src/components/HomepageCertifications/data/certificationsData.ts
=> Move FF Admin to Beta

docs/continuous-delivery/cd-integrations.md
- [x ] Maintenance/Chore
* *Issue(s)*
=> remove PIPELINE_QUEUE_STEP

docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-scan-mode.md
=> Doc 2505 v2

docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md, docs/platform/delegates/secure-delegates/trust-store-override-for-delegates.md
Fo reviewers, a preview is available.
[Install delegates with custom certificates](https://6553d7aabed9d60c3c570bc6--harness-developer.netlify.app/docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs)
* *Issue(s)*
=> feat: [DOC-3609] [DOC-3762] [SMP-1696] : fix cert docs and add new solution doc

docs/internal-developer-portal/features/checks-datasources.md
Added the info on mono-repo not supported
* *Issue(s)*
=> [IDP] : Added the info on mono-repo not supported

release-notes/service-reliability-management.md
=> SRM Release Notes 1.7

docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md, release-notes/continuous-delivery.md
=> Cds 814xx relnotes

docs/platform/delegates/manage-delegates/delegate-metrics.md
With the changes as per this jira - https://harness.atlassian.net/browse/PL-42354, we need to update some metrics names in documentation. This pr is to update those names
* *Issue(s)*
=> fix: [PL-42355]: Modified the count metrics names in delegate metrics

docs/platform/delegates/manage-delegates/delegate-metrics.md
=> revert 814xx changes

docs/platform/delegates/delegate-concepts/delegate-image-types.md
=> [PL42564] Remove Helm 2

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
https://harness.atlassian.net/browse/CDS-79647
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-79647
=> CDS-79647 S3 File Filter

release-notes/security-testing-orchestration.md
Preview: [Latest: Version 1.74.1](https://6555456837f8e50d2845bd4b--harness-developer.netlify.app/release-notes/security-testing-orchestration#latest-version-1741)
=> STO relnotes 2023-11-15 STO-6737

docs/platform/pipelines/add-a-stage.md
https://harness.atlassian.net/browse/CDS-74861
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-74861
=> CDS-74861 env and infra def in Custom stage

tutorials/internal-developer-portal/register-component-in-catalog.md, tutorials/internal-developer-portal/service-onboarding-pipeline.md
Added the video tutorials. 
* *Issue(s)*
=> [IDP] : Added the video tutorials

docs/continuous-delivery/gitops/get-started/harness-cd-git-ops-quickstart.md, docs/continuous-delivery/gitops/get-started/harness-git-ops-basics.md
=> Minor URL and indentation fix

docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
=> feat: [CDS-84475]: improve the encrypt terraform json outputs

docs/harness-cloud-operations/computing-uptime.md
=> feat: [FFM-9882]: Update feature flag sli definitions

docs/continuous-delivery/gitops/pr-pipelines/pr-pipelines.md
=> [CDS-84452]: Update pr-pipelines.md

docs/continuous-delivery/cd-integrations.md
=> techdebt: [CDS-84452]: Update cd-integrations.md

docs/first-gen/continuous-delivery/kubernetes-deployments/define-kubernetes-manifests.md
https://65568f70ad7e400ea4afa51f--harness-developer.netlify.app/docs/first-gen/continuous-delivery/kubernetes-deployments/define-kubernetes-manifests#option-bind-tasks-to-the-delegate
* *Issue(s)*
=> [DOC-1979] Add FG BIND_FETCH_FILES_TASK_TO_DELEGATE ff

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md, release-notes/continuous-delivery.md, release-notes/early-access.md
=> Remove CD_NG_DOCKER_ARTIFACT_DIGEST FF from Docs

release-notes/continuous-delivery.md
=> Updated the format for older releases, except those in 2022.

docs/cloud-cost-management/shared/ccm-aida-create-rule-partial.md, docs/cloud-cost-management/shared/ccm-aida-overview-partial.md
Preview of changes:
1. https://654c783bddff423f276ed3d3--harness-developer.netlify.app/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/cag-aida/gen-ai-overview
2. https://654c783bddff423f276ed3d3--harness-developer.netlify.app/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/cag-aida/gen-ai-use
* *Issue(s)*
=> [feat]: [CCM-14739]: Doc Update for AIDA Improvements & Azure Support

tutorials/internal-developer-portal/service-onboarding-pipeline.md
Added the cookiecutter script for gitlab
* *Issue(s)*
=> feat: [IDP-1675] Added the cookiecutter script for gitlab

release-notes/chaos-engineering.md
=> Release notes 1.24.x [WIP]

kb/platform/harness-platform-faqs.md
=> FAQ of the week 10th to 17th Nov

kb/continuous-delivery/continuous-delivery-faqs.md
=> Added FAQs for Nov17

release-notes/delegate.md
=> update hotfix format

docs/platform/triggers/triggers-reference.md, docs/platform/variables-and-expressions/runtime-inputs.md, kb/continuous-delivery/articles/ternary-operator.md
* *Issue(s)*
* https://harness.atlassian.net/browse/CDS-84396
=> Add documentation for using default values with triggers

docs/first-gen/firstgen-release-notes/fg-delegate.md
Update CG important notice - remove stale dates
https://6557b73cddefa80d9b9d8d0f--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/fg-delegate#important-notice---action-required
* *Issue(s)*
=> update important notice

docs/continuous-error-tracking/get-started/overops-cet-migration.md
=> Remove POC instance

docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-route-unmap.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cloud-foundry.md
Docs review for [CHAOS-2912](https://github.com/harness/developer-hub/pull/4066)
[CHAOS-2912]: https://harness.atlassian.net/browse/CHAOS-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CHAOS-2912 docs review

src/components/Certifications/CertificationsSTO.tsx
=> Wire course into HDH

docs/continuous-delivery/gitops/pr-pipelines/pr-pipelines.md
Revert: https://github.com/harness/developer-hub/pull/4140/files
* *Issue(s)*
=> techdebt: [CDS-84452]: revert - https://github.com/harness/developer-hub/pull/4140/files

docs/platform/Harness-AIDA/aida-overview.md, docs/security-testing-orchestration/use-sto/shared/sto-aida-overview-partial.md, release-notes/early-access.md, release-notes/security-testing-orchestration.md
Updates:
-[Early access features](https://655be44b87e8df0098897b97--harness-developer.netlify.app/release-notes/early-access)
- [Harness AI Development Assistant (AIDA™️)](https://655be44b87e8df0098897b97--harness-developer.netlify.app/release-notes/early-access#harness-ai-development-assistant-aida%EF%B8%8F)
- [STO features promoted to GA](https://655be44b87e8df0098897b97--harness-developer.netlify.app/release-notes/early-access/#sto-features-promoted-to-ga)
- [Use AI to fix security issues](https://655be44b87e8df0098897b97--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/view-and-troubleshoot-vulnerabilities/ai-based-remediations) (removed note about FF)
=> AIDA for STO is now GA STO-6750

docs/continuous-delivery/verify/verify-deployments-with-the-verify-step.md
* *CDS-84418: Documentation for CDS-80057: Allow for Per Metric Fail on No Analysis*
=> [CDS-84418] Corrected language issues.

release-notes/chaos-engineering.md
Release notes in new format
[Preview link](https://655c51c087e8df469d897b8b--harness-developer.netlify.app/release-notes/chaos-engineering)
=> Update release notes to match the new format

docs/platform/triggers/triggering-pipelines.md
=> [feat]: [CDS-83958]: Add limitation on webhook registration for gitlab trigger

release-notes/continuous-delivery.md
* *[CDS-81969](https://harness.atlassian.net/browse/CDS-81969)*
[CDS-81969]: https://harness.atlassian.net/browse/CDS-81969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-81969] Add ServiceNow app release in whats new section of the docs.

docs/internal-developer-portal/features/api-reference.md, docs/internal-developer-portal/get-started/add-api-docs.md
Split the API docs and References
* *Issue(s)*
=> fix [IDP-1704] : Split the API docs and References

certifications/feature-flags.md, src/components/Certifications/CertificationsFeatureFlags.tsx, src/components/Certifications/CertificationsSTO.tsx, src/components/Certifications/LandingPage.tsx
=> Updated STO Admin Pre-Alpha and FF URLs

src/components/LandingPage/data/allTutorialsData.tsx, src/components/LandingPage/data/continuousIntegrationData.tsx, src/components/Tutorials/ContinuousIntegrationBuildData.ts, tutorials/ci-pipelines/build/ci-c.md, tutorials/ci-pipelines/build/ci-java-http-server.md
Preview: https://6556946d0140ac12175029d1--harness-developer.netlify.app/tutorials/ci-pipelines/build/c
=> c cpp tutorial

docs/continuous-delivery/verify/configure-cv/verify-deployments-with-cloudwatch.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-datadog.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-prometheus.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-signalfx.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-sumologic.md, docs/service-reliability-management/manage-slo/slo-downtime/configure-slo-downtime.md, docs/service-reliability-management/manage-slo/slo-downtime/manage-slo-downtime.md, docs/service-reliability-management/manage-slo/slo-downtime/slo-downttime-overview.md, docs/service-reliability-management/monitored-service/health-source/cloudwatch.md, docs/service-reliability-management/monitored-service/health-source/datadog.md, docs/service-reliability-management/monitored-service/health-source/prometheus.md, docs/service-reliability-management/monitored-service/health-source/static/verify-deployment-with-prometheus.md, docs/service-reliability-management/monitored-service/health-source/static/verify-deployments-with-cloudwatch.md, docs/service-reliability-management/monitored-service/health-source/static/verify-deployments-with-sumologic.md, docs/service-reliability-management/monitored-service/health-source/sumologic.md, docs/service-reliability-management/monitored-service/monitored-service-metric-threshold.md, docs/service-reliability-management/slo/request-based-slo.md, release-notes/service-reliability-management.md
* *Issue(s)*
[OPS-13475](https://harness.atlassian.net/browse/OPS-13475)
[OPS-13475]: https://harness.atlassian.net/browse/OPS-13475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SRM: Removed feature flags

docs/internal-developer-portal/plugins/available-plugins/harness-srm.md
Added docs for Harness SRM Plugin
* *Issue(s)*
=> feat [IDP-1715] : Added docs for Harness SRM Plugin

plugins/feedback-plugin/index.js, src/components/Feedback/index.tsx
=>   HDH-192-ability-to-include-calling-page-on-refiner

docs/continuous-delivery/x-platform-cd-features/cd-steps/flow-control/synchronize-deployments-using-barriers.md
=> Add note about which stage types have support for barriers

release-notes/delegate.md
=> Delegate hotfix 81408

docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
=> techdebt: [CDS-85240]: Updates Argo CD versions supported with GitOps Agent

docs/platform/governance/audit-trail/audit-streaming.md, docs/platform/governance/audit-trail/audit-trail.md
=> [PL-43116]: Doc updates for audit trail and audit stream done as part of doc review

docs/platform/notifications/add-smtp-configuration.md, docs/platform/role-based-access-control/add-user-groups.md
=> Adds link for sending notification using Microsoft Teams

src/components/NavbarItems/CoveoSearch.js, src/components/NavbarItems/CoveoSearch.scss
=> feat: add Coveo support for SSCA, IaCM, Code Repository [HDH-196]

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Removed Settings for Enabling Overrides V2
* *Issue(s)*
=> Removed Settings for Enabling Overrides V2

docs/internal-developer-portal/plugins/available-plugins/harness-srm.md
=> fix [IDP] Updated the plugin name. 

docs/platform/pipelines/w_pipeline-steps-reference/pipeline-settings.md
=> Adding Pipeline/Stage Timeouts

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md, release-notes/continuous-delivery.md, release-notes/early-access.md
=> Remove CDS_WEBAPP_ENABLE_CLEAN_OPTION from code

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
=> Remove CDS_AWS_BACKOFF_STRATEGY FF from docs

docs/self-managed-enterprise-edition/performance-reports.md
=> Remove PIE_STATIC_YAML_SCHEMA from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_TERRAFORM_CLOUD from docs

kb/platform/harness-platform-faqs.md
=> FAQ for 17th to 24th Nov

CONTRIBUTING.md, README.md
=> Updated Readmes

docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
Add multi-service/environment reconciliation not supported limitation to documentation
* *Issue(s)*
=> [fix]: [CDS-84038] Add multi-service/environment reconciliation not supported limitation to documentation

docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md, release-notes/security-testing-orchestration.md
Previews:
- [Aqua Security scanner reference](https://655bfeae8043f814760fa3c4--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference)
- STO release notes > [Latest: Version 1.75](https://655bfeae8043f814760fa3c4--harness-developer.netlify.app/release-notes/security-testing-orchestration#latest-version-175)
=> Aquasec v0 draft for review STO-6355

tutorials/cd-pipelines/kubernetes/cosign-opa.md
Adding YouTube video link for this tutorial: `tutorials/cd-pipelines/kubernetes/cosign-opa`
=> Add youtube video link.

kb/platform/articles/Unable-to-Install-Custom-Tools-on-Delegate-via-Init-Script.md
=> fix path syntax

docs/internal-developer-portal/features/service-onboarding-pipelines.md, docs/internal-developer-portal/whats-supported.md, tutorials/internal-developer-portal/service-onboarding-pipeline.md
Added the information on template actions
* *Issue(s)*
=> fix: [IDP] : Added the information on template actions

docs/faqs/harness-delegate-faqs.md, docs/platform/delegates/delegate-concepts/delegate-overview.md
Delegate log file path symlink
https://65652be1ed8ccb1507d1b0bc--harness-developer.netlify.app/docs/faqs/harness-delegate-faqs#can-i-change-the-delegate-log-file-path
* *Issue(s)*
=> [PL-43168] Delegate log file path symlink

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
=> Remove CDS_ASG_V2 from docs

docs/continuous-delivery/cd-infrastructure/aws-cdk.md, docs/continuous-delivery/cd-integrations.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove CDS_AWS_CDK from docs

docs/continuous-delivery/cd-integrations.md, docs/faqs/continuous-delivery-faqs.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove PIE_EXPRESSION_CONCATENATION from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove CDS_K8S_SERVICE_HOOKS_NG from docs

docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/1-auto-stopping-rules.md, docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/autostopping-dashboard.md, docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-autostopping-rules-aws.md, docs/continuous-integration/get-started/overview.md, docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md, docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md, docs/feature-flags/ff-creating-flag/manage-stale-flags.md, docs/first-gen/continuous-delivery/continuous-verification/continuous-verification-overview/concepts-cv/24-7-service-guard-overview.md, docs/first-gen/continuous-delivery/continuous-verification/continuous-verification-overview/concepts-cv/what-is-cv.md, docs/first-gen/continuous-delivery/model-cd-pipeline/pipelines/pipeline-configuration.md, docs/first-gen/firstgen-platform/security/access-management-howtos/sso-ldap.md, docs/platform/dashboards/create-dashboards.md, docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md, docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism.md, docs/platform/pipelines/w_pipeline-steps-reference/step-skip-condition-settings.md, src/components/DocVideo/index.tsx
=> wistia to youtube migrate phase 2

tutorials/cd-pipelines/kubernetes/manifest.md
Updated CD Kubernetes Manifest tutorial with GitOps CLI steps.
=> Updated manifest tutorial with GitOps CLI steps

tutorials/internal-developer-portal/service-onboarding-pipeline.md
Added the information on pipeline variables
* *Issue(s)*
=> fix: [IDP]: Added the information on pipeline variables

release-notes/continuous-delivery.md
=> [CDS-85246] CDS 816xx release notes.

docs/continuous-delivery/verify/configure-cv/abort-verification.md, docs/platform/pipelines/abort-pipeline.md
* *[CDS-85211](https://harness.atlassian.net/browse/CDS-85211)*
[CDS-85211]: https://harness.atlassian.net/browse/CDS-85211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-85211] Documentation: Skip Verification for CV

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
=> Edits to merged PR #4306

docs/platform/secrets/secrets-management/add-a-google-cloud-secret-manager.md, docs/platform/secrets/secrets-management/add-hashicorp-vault.md, docs/platform/secrets/secrets-management/add-secrets-manager.md, docs/platform/secrets/secrets-management/harness-secret-manager-overview.md
=> [PL-43119]: Secret Management Updates and Fixes

static/robots.txt
@wei-harness we will need to update Coveo for IaCM. 
- x ] Maintenance/Chore
* *Issue(s)*
=> Modifying Robots

src/css/custom.css
* *Issue(s)*
https://harness.atlassian.net/browse/HDH-203?atlOrigin=eyJpIjoiYzgxNzdiMGE1ZDBmNGU4ZTlhOWUzNjJkNGZjM2IwN2EiLCJwIjoiaiJ9
=> Update custom.css - HDH-203

release-notes/delegate.md
=> Delegate hotfix 23.11.81602

docs/continuous-delivery/cd-integrations.md
=> Remove CD_AI_ENHANCED_REMEDIATIONS from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md, docs/continuous-delivery/shared/multiple-helm-charts.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG from docs

release-notes/security-testing-orchestration.md
=> STO relnotes 2023-11-29 STO-6766

docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
=> [PL-42532] Delegate upgrader self-signed certs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/gitops/pr-pipelines/pr-pipelines.md
=> techdebt: [CDS-84452]: remove FF GITOPS_UPDATE_APP_STEP

src/components/Certifications/CertificationsFeatureFlags.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
=> FF Admin to GA 

docs/platform/delegates/delegate-reference/common-delegate-profile-scripts.md
Now we can get the latest tf version dynamically. The current doc is still at 0.12.25.
* *Issue(s)*
=> adding a smart tf installer

docs/platform/delegates/manage-delegates/auto-scale-using-replicas.md
Delegate scale down
https://65495929b9d1b35aaa35fd6e--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/auto-scale-using-replicas#scale-down-delegate-pods
* *Issue(s)*
=> [DOC-3857] Delegate scale down

kb/platform/harness-platform-faqs.md
=> FAQ for 24th Nov to 1st Dec

release-notes/self-managed-enterprise-edition.md
=> add delegate version in the release notes

release-notes/self-managed-enterprise-edition.md
add delegate vernos, update rss date
[Self-Managed Enterprise Edition](https://656a4e1378668a3ec07fd33e--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
* *Issue(s)*
=> add delegate vernos, update rss date

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/k8s-dry-run.md
https://harness.atlassian.net/browse/CDS-85869
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-85869
=> CDS-85869 Update k8s-dry-run.md

docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-provisioning-with-harness.md, docs/continuous-delivery/cd-integrations.md
=> Remove CDS_TF_TG_SKIP_ERROR_LOGS_COLORING from docs

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
=> Remove CDS_BASIC_ASG from docs

docs/continuous-delivery/cd-integrations.md, docs/platform/connectors/code-repositories/git-hub-app-support.md, docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md, release-notes/continuous-integration.md, release-notes/delegate.md, release-notes/early-access.md
=> Remove CDS_GITHUB_APP_AUTHENTICATION from Docs

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-canary-phased-traffic-shift.md
=> Remove CDS_ECS_BASIC_DEPLOYMENT_STRATEGY from docs

docs/platform/automation/api/api-permissions-reference.md, docs/platform/role-based-access-control/permissions-reference.md
This commit documents the newly activated IACM RBAC permissions.
* *Issue(s)*
=> [IAC-1305]: IACM permissions

docs/platform/automation/terraform/automate-harness-onboarding.md, docs/platform/delegates/manage-delegates/auto-scale-using-replicas.md, tutorials/platform/secure-delegate-default-to-minimal.md
[PL-43263] [PL-37616] Remove delegate-service from YAML examples
* *Issue(s)*
[PL-43263]: https://harness.atlassian.net/browse/PL-43263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PL-37616]: https://harness.atlassian.net/browse/PL-37616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PL-43263] [PL-37616] Remove delegate-service from yaml examples

docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md, release-notes/platform.md
Platform NG 81709 FG 81708 release notes
[Platform Release Notes (NextGen)](https://656de2228dc25f65d43b6d67--harness-developer.netlify.app/release-notes/platform)
[Harness SaaS Release Notes (FirstGen)](https://656de2228dc25f65d43b6d67--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes)
* *Issue(s)*
=> [PL-43234] Platform NG 81709 FG 81708 release notes

docs/first-gen/firstgen-platform/techref-category/account-ref/delegate-ref/whitelist-harness-domains-and-ips.md, docs/platform/pipelines/download-logs.md, docs/platform/references/allowlist-harness-domains-and-ips.md
=> fix: [DOC-3920]: Add docs for ip whitelist

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
=> add redirect for http step

docs/faqs/continuous-delivery-faqs.md, docs/faqs/continuous-integration-ci-faqs.md, kb/platform/harness-platform-faqs.md
=> Added FAQs for CD, CI and Platform

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
* *[CDS-85760](https://harness.atlassian.net/browse/CDS-85760)*
[CDS-85760]: https://harness.atlassian.net/browse/CDS-85760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-85760] Document permissions for Overrides V2

src/components/Docs/data/internalDeveloperPortal.ts
Updated the broken links
* *Issue(s)*
=> fix[IDP] : Updated the broken links

docs/platform/rate-limits.md
=> [PL-32478] Update API rate limit documentation

docs/platform/git-experience/gitexp-bidir-sync-setup.md
- [x ] Maintenance/Chore
* *Issue(s)*
=> Update intro to gitexp-bidir-sync-setup

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md, release-notes/continuous-error-tracking.md, release-notes/continuous-integration.md, release-notes/early-access.md, release-notes/service-reliability-management.md
- dbothwell added December 2023 updates to [Continuous Error Tracking](https://656f5ead3e0544168c1136fa--harness-developer.netlify.app/release-notes/continuous-error-tracking) release notes
- CET and SRM release notes: Update to new format.
- Early access page: Move a GA feature to the GA section.
- CI Azure VM build infra: Add information about the VM app and Entra ID registration. https://656e2947b0e9200ba3fdab2c--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure
=> misc 4 dec 23

docs/platform/delegates/manage-delegates/delegate-metrics.md
=> [PL-42260] Clarify delegate metrics

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
=> Remove CDS_MULTI_SERVICE_PROPAGATION from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
=> Remove CDP_AWS_SAM from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_POST_PROD_ROLLBACK from doxs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md, docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-services.md, docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
=> Remove CDS_OCI_HELM_ECR_CONFIG_SUPPORT_NG from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md
=> Remove CDS_AZURE_WEBAPP_NG_LISTING_APP_NAMES_AND_SLOTS from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_USE_OLD_SERVICE_V1 from docs

docs/continuous-delivery/cd-onboarding/new-user/manage-cd-in-git.md
https://harness.atlassian.net/browse/CDS-78797
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-78797
=> CDS-78797 Managing Harness CD resources in Git

docs/platform/automation/cli/install.md, docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md, tutorials/cd-pipelines/kubernetes/helm-chart.md
=> Moved CLI Download Info to Template

docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-and-serverless-faults.md
Add ecs-task-scale link to docs
=> Add ecs-task-scale link to docs

docs/platform/automation/cli/install.md, tutorials/cd-pipelines/kubernetes/helm-chart.md, tutorials/cd-pipelines/kubernetes/kustomize.md, tutorials/cd-pipelines/kubernetes/manifest.md, tutorials/cd-pipelines/kubernetes/ownapp.md, tutorials/cd-pipelines/serverless/aws-lambda.md, tutorials/cd-pipelines/serverless/gcp-cloud-func.md
=> Finished clean up of templating CLI install commands

docs/continuous-delivery/cd-integrations.md
=> techdebt: [CDS-81326]: remove FF GITOPS_GITHUB_RESTRAINT_FOR_STEPS

docs/continuous-delivery/gitops/applicationsets/harness-git-ops-application-set-tutorial.md
=> remove FF ng_svc_env_redesign

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/background-step.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/git-clone-step.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/plugin-step.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/run-step.md
=> Remove CDS_CONTAINER_STEP_GROUP from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
=> Remove CDS_SUPPORT_SKIPPING_BG_DEPLOYMENT_NG from docs

docs/internal-developer-portal/plugins/available-plugins/dynatrace.md
Added the docs for Dynatrace Plugin
* *Issue(s)*
=> feat [IDP-1797] : Added the docs for Dynatrace Plugin

release-notes/chaos-engineering.md
Add item to release notes 1.24.5
=> Add item to release notes

docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md, release-notes/early-access.md, release-notes/security-testing-orchestration.md
Previews: 
- [Latest: Version 1.76](https://6571002401f8a006d426924e--harness-developer.netlify.app/release-notes/security-testing-orchestration#latest-version-176)
- Early Access update: [Aqua Security integration](https://6571002401f8a006d426924e--harness-developer.netlify.app/release-notes/early-access/#aqua-security-integration)
=> STO relnotes 2023-12-06 STO-6805

release-notes/security-testing-orchestration.md
Preview: [STO release notes](https://65723cf862d11500756a7e8b--harness-developer.netlify.app/release-notes/security-testing-orchestration)
=> refactor STO relnotes STO-6810

docs/continuous-delivery/cd-onboarding/new-user/migrate-github-action-to-harness.md
https://harness.atlassian.net/browse/CDS-80470
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-80470
=> CDS-80470 Migrate from Github Actions to Harness

release-notes/self-managed-enterprise-edition.md
SMP 0.11.2 patch release notes
https://65722a876d83220a909fd0f5--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#december-7-2023-0112
* *Issue(s)*
=> [SMP-2348] SMP 0.11.2 patch release notes

docs/chaos-engineering/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
Review of [CHAOS-3048](https://github.com/harness/developer-hub/pull/4499)
[CHAOS-3048]: https://harness.atlassian.net/browse/CHAOS-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chaos 3048 docs review smriti

docs/chaos-engineering/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-stop/cfDeploymentPlatform.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-stop/faultInjectorPort.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-stop/skipSSLValidation.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-cpu-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-fill.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-io-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-error.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-spoof.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-memory-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-corruption.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-duplication.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-service-restart.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-time-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/data-block-size.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-path.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-storage.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-process-kill/force-kill.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-process-kill/process-command.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-process-kill/process-ids.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-process-kill/process-names.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-service-restart/interval.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-service-restart/self-healing-services.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-service-restart/sequence.yaml, docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-service-restart/services.yaml
Adds docs for breaking LCI changes
* *Issue(s)*
=> chore: [CHAOS-3048]: Adds docs for breaking lci changes

docs/continuous-delivery/cd-onboarding/new-user/onboarding-path.md
=> docs: add k8s & fargate service examples in cd onboarding guide

release-notes/early-access.md, release-notes/platform.md
=>  Remove USE_GET_FILE_V2_GIT_CALL from docs

docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
=> Remove CDS_IMPROVED_HELM_DEPLOYMENT_TRACKING from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
=> Remove CDS_HELM_SEND_TASK_PROGRESS_NG from docs

docusaurus.config.js, plugins/scarf-plugin/index.js
* *Issue(s)*
- [ 
] *Optional* Screen Shoot.
=> HDH-198 investigate-scarf-insights

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove CDS_HELM_FETCH_CHART_METADATA_NG from docs

docs/internal-developer-portal/get-started/enabling-module.md, docs/internal-developer-portal/get-started/overview.md, release-notes/internal-developer-portal.md, sidebars.js, src/components/Docs/InternalDeveloperPortal.tsx, tutorials/internal-developer-portal/using-secret-as-an-input.md
Removed the beta labels for IDP Module
* *Issue(s)*
=> fix [IDP] : Removed the beta labels for IDP Module

release-notes/internal-developer-portal.md
Added the docs and tutorials for release notes
* *Issue(s)*
=> fix [IDP] : Added the docs and tutorials for release notes

tutorials/internal-developer-portal/how-to-track-migrations.md
Updated a small nit with tutorial block
* *Issue(s)*
=> fix [IDP] : Updated a small nit with tutorial block

docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-route-unmap.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cloud-foundry.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/experiments.ts, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/shared/cf-secrets.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/shared/vsphere-secrets.md, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-route-unmap/cfDeploymentPlatform.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-route-unmap/faultInjectorPort.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-route-unmap/host.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-route-unmap/path.yaml, docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/static/manifests/cf-app-route-unmap/skipSSLValidation.yaml
Adds cf-app-route-unmap fault docs
* *Issue(s)*
=> feat: [CHAOS-2912]: Adds cf-app-route-unmap fault docs

docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-blackhole-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-disk-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-network-corruption.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-network-duplication.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-service-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-time-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-blackhole-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-memory-hog.md
Add href links to environment variables
Fix href links
Fix minor typos
=> Adds href links to Windows faults env variables

docs/chaos-engineering/technical-reference/probes/cmd-probe.md, docs/chaos-engineering/technical-reference/probes/datadog-probe.md, docs/chaos-engineering/technical-reference/probes/http-probe.md, docs/chaos-engineering/technical-reference/probes/prom-probe.md, docs/chaos-engineering/technical-reference/probes/slo-probe.md
[CHAOS 2950](https://github.com/harness/developer-hub/pull/4200) docs review
=> CHAOS-2950  docs review 

docs/chaos-engineering/technical-reference/probes/http-probe.md, docs/chaos-engineering/technical-reference/probes/prom-probe.md
=> chore: [CHAOS-3222]: Add the docs example for the http headers

kb/continuous-delivery/articles/last-published-tag.md, kb/continuous-delivery/articles/understanding-artifact-sources-in-nextgen.md
=> [KB][CDS-85420]: Future-Proof Your Workflow: Harness NextGen Artifact Sources

docs/chaos-engineering/technical-reference/probes/cmd-probe.md, docs/chaos-engineering/technical-reference/probes/datadog-probe.md, docs/chaos-engineering/technical-reference/probes/http-probe.md, docs/chaos-engineering/technical-reference/probes/prom-probe.md, docs/chaos-engineering/technical-reference/probes/slo-probe.md
Adds Datadog probe docs
* *Issue(s)*
=> feat: [CHAOS-2950]: Adds Datadog probe docs

docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md, release-notes/feature-flags.md
=> release notes for 1.4.0 java sdk added

docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md
SMP increase PV size for StatefulSets
[Increase PV size for StatefulSets](https://657268f95345c11d63843b2f--harness-developer.netlify.app/docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets)
* *Issue(s)*
=> [SMP-2350] SMP increase PV size for StatefulSets

release-notes/platform.md
PL NG release notes - important feature change notice
* *Issue(s)*
=> [PL-43488] PL NG release notes - important feature change notice

docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md, release-notes/continuous-delivery.md, release-notes/early-access.md
=> [CDS-86041] CDS 818xx release notes

release-notes/continuous-delivery.md
* *[CDS-86041](https://harness.atlassian.net/browse/CDS-86041)*
[CDS-86041]: https://harness.atlassian.net/browse/CDS-86041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-86041] Corrected the version numbers in the CDS 818xx release notes

docs/platform/delegates/manage-delegates/delegate-metrics.md
=> [PL-43519] Restart note

release-notes/feature-flags.md
=> React Native release notes updated

docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
=> [SMP-2340] Update smp supported k8s versions

docs/internal-developer-portal/get-started/enable-docs.md
Updated the tutorial on enabling techdocs
* *Issue(s)*
=> feat [IDP-1818] : Updated the tutorial on docs

src/components/HomepageCertifications/data/certificationsData.ts
=> Updated STO Cert

docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
Helm delegate custom certs
[Install delegates with custom certificates](https://6579e13c58648436826e06df--harness-developer.netlify.app/docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs)
* *Issue(s)*
=> [DOC-3933] Helm delegate custom certs

docs/continuous-delivery/cd-integrations.md, docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md, docs/continuous-integration/use-ci/viewing-builds.md, docs/platform/pipelines/download-logs.md, kb/continuous-integration/articles/CI-step-logs-dont-load-in-real-time.md
Build logs troubleshooting and downloading logs
=> CI-10724, CI-10725

docs/platform/templates/reconcile-pipeline-templates.md
* *[CDS-86161](https://harness.atlassian.net/browse/CDS-86161)*
[CDS-86161]: https://harness.atlassian.net/browse/CDS-86161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-86161] Documentation Improvement for template Reconciliation

docs/chaos-engineering/chaos-infrastructure/connect-chaos-infrastructures.md, docs/chaos-engineering/chaos-infrastructure/disconnect-chaos-infrastructure.md, docs/chaos-engineering/configure-chaos-experiments/probes/validate-hypothesis-using-probes.md, docs/chaos-engineering/get-started/key-concepts.md, docs/chaos-engineering/technical-reference/architecture/kubernetes.md, docs/chaos-engineering/technical-reference/security/namespace-considerations.md, docs/chaos-engineering/technical-reference/security/security-templates/openshift-scc.md, docs/chaos-engineering/technical-reference/security/security-templates/psp.md
=> DOC 3935 Structure the right panel

kb/continuous-delivery/continuous-delivery-faqs.md
=> Faqs[CDS-86349]Addition for 1st Dec

docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md, docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md
=> Updating Doc with required permissions for SSH and WinRM for SSH

release-notes/security-testing-orchestration.md
=> sto relnotes update 2023-12-14

docs/first-gen/firstgen-release-notes/fg-delegate.md, docs/platform/delegates/delegate-concepts/delegate-image-types.md, docs/platform/delegates/delegate-concepts/graceful-delegate-shutdown-process.md, docs/platform/delegates/install-delegates/build-custom-delegate-images-with-third-party-tools.md, docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md, docs/platform/delegates/install-delegates/overview.md, docs/platform/delegates/manage-delegates/delete-a-delegate.md, docs/platform/shared/delegate-image-types-intro-table.md, docs/platform/shared/delegate-legacy-eos.md, release-notes/delegate.md
=> [PL-43600] Legacy EOS shared

docs/platform/variables-and-expressions/harness-variables.md
Description: Adding best practices for expression usage with method invocation
* *Issue(s)*
=> feat: [CDS-86606]: add best practices for expressions usage with method invocation

docs/continuous-delivery/cd-integrations.md, docs/platform/triggers/troubleshoot-registered-triggers.md
=> Remove CDS_TRIGGER_ACTIVITY_PAGE from docs

certifications/cloud-cost-management.md, src/components/Certifications/CertificationsCloudCostManagement.tsx, src/components/Certifications/CertificationsSTO.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts, src/components/HomepageCertifications/data/certificationsData.ts
=> Prep for STO Admin Beta and CCM Admin Alpha

docs/platform/delegates/install-delegates/automate-delegate-installation.md, docs/platform/delegates/install-delegates/build-custom-delegate-images-with-third-party-tools.md, docs/platform/delegates/install-delegates/docker-delegate-to-ecs-fargate.md, docs/platform/delegates/install-delegates/enable-root-user-privileges-to-add-custom-binaries.md, docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md, docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md, docs/platform/delegates/install-delegates/overview.md, docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md, docs/platform/shared/delegate-additional-permissions.md, tutorials/platform/install-delegate.md
=> [PL-39963] Add delegate install additional permissions note

release-notes/chaos-engineering.md
=> release notes for 1.26.0

docs/platform/variables-and-expressions/harness-variables.md
=> feat: [CDS-86606]: add best practices for expressions usage

docs/platform/delegates/delegate-concepts/delegate-overview.md, release-notes/delegate.md, release-notes/platform.md
Delegate logging level env variable
https://6580720992f97864e27c8293--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-overview#delegate-logs
* *Issue(s)*
=> [PL-43632] [PL-41644] Delegate logging level env variable

docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
=> Update argoCD 2.9.0 support

docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md
https://harness.atlassian.net/browse/CDS-85396 has additional context.
A preview is available.
https://65805e54b77199586a4c7f39--harness-developer.netlify.app/docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events/
* *Issue(s)*
=> Add restrictions around Runtime Input options for Notification config

docs/platform/delegates/delegate-concepts/delegate-overview.md
Update disable delegate logging info
https://6580be6e8b2c28202e44d63d--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-overview#delegate-logs
* *Issue(s)*
=> [PL-43645] Update disable delegate logging info

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
=> fix formatting

release-notes/continuous-delivery.md
=> CD release notes Dec 2023 81904

release-notes/delegate.md
Adding 23.12.81806 to Delegate hotfix release notes
* *Issue(s)*
=> Update delegate HF RN - add 23.12.81806

docs/feature-flags/add-prerequisites-to-feature-flag.md
=> nested prerequisites note updated

docs/security-testing-orchestration/sto-techref-category/shared/dind-bg-step.md
Preview: [Docker-in-Docker requirements for STO](https://6581dd56112e264804e4b199--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#docker-in-docker-requirements-for-sto)
=> tweak DinD requirements STO-6848

docs/cloud-cost-management/get-started/key-concepts.md
=> Update key-concepts.md for Node cost clarification

release-notes/feature-flags.md
=> android sdk 1.2.2 notes update

src/components/Certifications/CertificationsChaos.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
=> Tidy for Alpha [Public]

docs/platform/approvals/custom-approvals.md
=> fix headings

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> Updated CLI Version to 0.18

docs/security-testing-orchestration/sto-techref-category/semgrep-scanner-reference.md
=> add Semgrep tutorial links to Semgrep scanner reference STO-6728

docs/continuous-delivery/cd-integrations.md, docs/platform/pipelines/w_pipeline-steps-reference/pipeline-settings.md
=> Remove PIE_PIPELINE_SETTINGS_ENFORCEMENT_LIMIT from docs

docs/continuous-delivery/cd-integrations.md
=> Remove NG_EXPRESSIONS_NEW_INPUT_ELEMENT from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/flow-control/synchronize-deployments-using-barriers.md
=> Remove CDS_NG_BARRIER_STEPS_WITHIN_LOOPING_STRATEGIES from docs

docs/continuous-delivery/cd-integrations.md, docs/platform/triggers/trigger-on-a-new-artifact.md
=>  Remove CDS_NG_TRIGGER_MULTI_ARTIFACTS from docs

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-apply-step.md
=> Update kubernetes-apply-step.md with correct FF

docs/internal-developer-portal/get-started/onboarding-guide.md
Removed beta label
* *Issue(s)*
=> fix [IDP-1879] : Removed beta label

docs/platform/governance/policy-as-code/harness-governance-overview.md
This adds the information that JSON that is sent to OPA will still contain unresolved JEXL expressions. This was causing customers some confusion.
* *Issue(s)*
=> Update OPA docs

docs/software-engineering-insights/sei-ingestion-satellite/run-the-satellite-container.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-bitbucket-enterprise.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-gitlab.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-harnessng.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-jira.md, docs/software-engineering-insights/sei-integrations/automated-integrations/set-integration-gitlab-enterprise.md
Fixed gaps on the following docs:
1. Running the satellite container
2. Jira integration
3. Gitlab cloud integration
4. Gitlab enterprise integration
5. HarnessNG integration
* *Issue(s)*
=> fix [SEI-4632]: Fixed gaps on satellite docs

release-notes/delegate.md
=> feat: [CDS-87234]: add release notes for terragrunt cli options

release-notes/feature-flags.md
=> .net sdk 1.4.1 r4elease notes updated

docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
=> Windows Local runner minor fix

release-notes/delegate.md, release-notes/shared/cd-79700-fixed-issues.md
=> Remove PIE_PROCESS_ON_JSON_NODE from docs

docs/continuous-delivery/cd-integrations.md
=> Remove PIPELINE_ROLLBACK from docs

docs/platform/automation/cli/reference.md, docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> feat: [PLG-3106] Update the reference with org and project flags usage

docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift.md
Add paid pill to SMP installation topics
[Install using Helm](https://6583448e0888fb54f406ab90--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga)
[Install in an air-gapped environment](https://6583448e0888fb54f406ab90--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment)
[Install in an OpenShift environment](https://6583448e0888fb54f406ab90--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift)
[Install using KOTS](https://6583448e0888fb54f406ab90--harness-developer.netlify.app/docs/self-manag …
=> [PL-43707] Add paid pill to SMP installation topics

docs/continuous-error-tracking/get-started/onboarding-guide.md, docs/continuous-error-tracking/get-started/overops-cet-migration.md, docs/continuous-error-tracking/shared/agent-compatibility.md, release-notes/continuous-error-tracking.md
* *https://harness.atlassian.net/browse/CET-59*
* *https://harness.atlassian.net/browse/CET-698*
* Release notes for CET: https://harness.atlassian.net/wiki/spaces/OV/pages/21574779033/QA+ET+Build+December+2023+-+5.32.2
=> CET Release Notes 5.32.2

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Jira with the change : https://harness.atlassian.net/browse/CDS-87009
* *Issue(s)*
=> [feat]: [CDS-87240]: Update Overrides v2 permissions in documentation

release-notes/delegate.md, release-notes/shared/cd-79700-early-access.md
=> Remove CDS_BG_STAGE_SCALE_DOWN_STEP_NG from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_SERVICENOW_TICKET_TYPE_V2 from docs

release-notes/security-testing-orchestration.md
Preview: [Version 1.77.1](https://658366058c16a86c74df4b1b--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1771)
=> STO 1.77.1 relnotes STO-6853

docs/feature-flags/ff-security-compliance/manage-access-control.md
=> updated redirect link to replace the inactive link from helpdocs

docs/software-engineering-insights/sei-ingestion-satellite/run-the-satellite-container.md, docs/software-engineering-insights/sei-ingestion-satellite/satellite-overview.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-bitbucket-enterprise.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-circleci.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-droneci.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-github-enterprise.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-github.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-gitlab.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-harnessng.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-jira.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-sonarqube.md, docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-testrail.md, docs/software-engineering-insights/sei-integrations/automated-integrations/set-integration-gitlab-enterprise.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-github-actions.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-checkmarx.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-coverity.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-gerrit.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-helix.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-pagerduty.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-postgresql.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-snyk.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-splunk.md, docs/software-engineering-insights/sei-integrations/other-integrations/sei-integration-zendesk.md, docs/software-engineering-insights/sei-technical-reference/push-artifacts-to-sei.md
YAML files updated with the latest changes.
* *Issue(s)*
=> Fix [SEI-4643]: YAML files updated with the latest changes

release-notes/early-access.md, release-notes/platform.md
Update PL 813xx, 815xx, 816xx, 817xx RN
Sync published RNs with lists: https://harness.atlassian.net/wiki/spaces/PD/pages/21265449030/Release+Notes+2023
Add missing items, fix typos, update early access
[Platform Release Notes](https://65844e304f641503f0031917--harness-developer.netlify.app/release-notes/platform)
[Early access features](https://6583d6204f6415b0ed031787--harness-developer.netlify.app/release-notes/early-access)
* *Issue(s)*
=> [PL-43722] Update PL 813xx, 815xx, 816xx, 817xx RN

release-notes/platform.md
=> 42912, 42917

docs/internal-developer-portal/plugins/available-plugins/kubernetes.md, docs/internal-developer-portal/scorecards/opa-implementation.md, tutorials/internal-developer-portal/opa-scorecards.md
Added the information on plugins and Feature Flag
* *Issue(s)*
=> fix: [IDP] : Added the information on plugins and Feature Flag

kb/continuous-delivery/continuous-delivery-faqs.md
=> Addition_Faqs[CDS-87433]: FAQs for 22nd Dec

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
https://harness.atlassian.net/browse/CDS-76124
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-76124
=> CDS-76124-ASG-BG-Incremental-Traffic-Shift

tutorials/cd-pipelines/e2e-pipeline.md
=> Clarify Docker connector creation steps in e2e pipeline tutorial

docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
* https://harness.atlassian.net/browse/CDS-86736
=> [CDS-86736]: Document helm command improvements

docs/continuous-delivery/x-platform-cd-features/cd-steps/approvals/using-harness-approval-steps-in-cd-stages.md
https://harness.atlassian.net/browse/CDS-80984
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-80984
=> CDS-80984 Auto Approval using expression

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md, docusaurus.config.js
=> Remove Scarf.sh trial

docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-memory-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-memory-hog.md
[CHAOS-3571](https://github.com/harness/developer-hub/pull/4702) review
[CHAOS-3571]: https://harness.atlassian.net/browse/CHAOS-3571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs 3571 -Doc review of Chaos-3571

docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-memory-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-memory-hog.md
Adds details for linux and vmware memory stress fault
* *Issue(s)*
=> chore: [CHAOS-3571]: Adds details for linux and vmware memory stress fault

release-notes/delegate.md
Delegate HF 81808 release notes
* *Issue(s)*
=> [PL-43780] [CDS-87415] Delegate HF 81808 release notes

docs/platform/role-based-access-control/resource-type-reference.md
Resource type reference
[Resource type reference](https://6573935d458d3767ad441720--harness-developer.netlify.app/docs/platform/role-based-access-control/resource-type-reference)
* *Issue(s)*
=> [PL-43427] Resource type reference

release-notes/chaos-engineering.md
=> Release notes 1.27.x [WIP]

docs/platform/triggers/trigger-on-a-new-artifact.md
Improving explanation of Artifactory trigger config as requested by customer here: https://harness.atlassian.net/browse/CDS-87443.
* *Issue(s)*
* https://harness.atlassian.net/browse/CDS-87443
=> fix: [CDS-87443]: Improve documentation of Artifactory trigger config

src/components/NavbarItems/CoveoSearch.js
=> fix: overlay error in dev mode [HDH-210]

src/components/NavbarItems/CoveoSearch.js
=> minor fix to HDH-210

package.json, yarn.lock
* Increased Heap Space to 6GB
* Removed Unused Linting [Vale]
* *Issue(s)*
=> Increased Heap Space

package.json
* Edited Lint CI
* Adding an additional GB of Heap [7GB] for Harness CI Cloud Build.
* *Issue(s)*
=> Updated Package.JSON Lints

kb/chaos-engineering/chaos-engineering-faq.md, kb/continuous-integration/continuous-integration-faqs.md, kb/continuous-integration/drone-faqs.md, kb/feature-flags/harness-feature-flag-faqs.md, kb/security-testing-orchestration/security-testing-orchestration-faqs.md
Restructuring/cleaning up some FAQ pages in the KB for grammar/style/organization/readability and fix broken/missing links.
=> Some KB cleanup

docs/platform/automation/cli/reference.md, docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> PLG-3110 Added docs to support gitops-cluster and environment linking

plugins/feedback-plugin/index.js
=> HDH 212 fixing feedback plugin

tutorials/cd-pipelines/unified-cicd/gar-gke-pipeline.md
This PR updates the sample app repo from personal GitHub repo to harness-community repo.
=> Update GitHub repo org

release-notes/delegate.md
=> Update delegate release notes for Hotfix 81809

kb/continuous-delivery/continuous-delivery-faqs.md
=> Addition_FAQs[CDS-87433]: Addition of FAQs for 29th Dec

client-modules/FocusOnAnchor.js, docusaurus.config.js, plugins/focusOnAnchor-plugin/index.js
=> FIX : [ HDH-209 ]  post-3-x-upgrade-focus-on-anchor-plug-in-broken 

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
Have verified existing limits for all artifact sources by pushing images. Updating the chart with the existing behaviour.
* *Issue(s)*
=> fix: [CDS-81853]: Update artifact source limits

release-notes/platform.md
=> fixed heading

src/components/Certifications/CertificationsCloudCostManagement.tsx
=> Updated CCM Alpha

src/components/LandingPage/data/continuousDeliveryData.tsx, src/components/Tutorials/UnifiedCICDData.ts, tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md
Docker Hub Kubernetes CI/CD Pipeline
* *Issue(s)*
=> Updated Name to Docker Hub Kubernetes CI/CD Pipeline

release-notes/continuous-delivery.md
=> CD release notes for Version 1.17.8

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docusaurus.config.js
Re-added Scarf Plugin
* *Issue(s)*
=> Re-added Scarf Plugin

release-notes/chaos-engineering.md
Update chaos engineering release notes
=> Update chaos engineering release notes

docs/internal-developer-portal/whats-supported.md
Updated the what's supported for git providers in IDP
* *Issue(s)*
=> fix [IDP] : Updated the what's supported for git providers in IDP

kb/continuous-delivery/continuous-delivery-faqs.md
=> Updated FAQ Q4

docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md
Fixed the deadlink on custom ci/cd integration topic for propels-template-repository.
* *Issue(s)*
=> [SEI-4777]: Fix deadline for propel-templates repository

docs/security-testing-orchestration/get-started/onboarding-guide.md, docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md, docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/ingesting-issues-from-other-scanners.md
=> STO broken link fixes 2024-01-02

kb/continuous-delivery/articles/harness-approval-api.md
=> DOC-3946 change <step_group_id> to STEP_GROUP_ID

docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md, docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
* Add powershell variable syntax for Windows set network driver env var troubleshooting.
* Add troubleshooting to check if runner is running.
=> Ci local runner edits 2 jan 24

docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md, docs/first-gen/continuous-delivery/concepts-cd/deployment-types/terragrunt-provisioning-with-harness.md, docs/first-gen/continuous-delivery/helm-deployment/helm-deployments-overview.md, docs/first-gen/first-gen-quickstarts/traditional-ssh-quickstart.md, kb/continuous-delivery/continuous-delivery-faqs.md, kb/continuous-integration/continuous-integration-faqs.md, release-notes/self-managed-enterprise-edition.md, src/components/Certifications/data/cd-certification-architect-review-guide.md
=> fixed broken links

docs/platform/Harness-AIDA/aida-overview.md, docs/security-testing-orchestration/use-sto/shared/sto-aida-notes-partial.md
Update AIDA setup descriptions to include the **Allow Overrides** option.
=> Sto aida doc updates sto 3870

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md
This PR fixes a typo and updates a few outdated commands for https://developer.harness.io/tutorials/cd-pipelines/unified-cicd/e2e-pipeline
=> Update e2e CICD tutorial.

docs/continuous-delivery/gitops/gitops-ref/troubleshooting.md
Troubleshooting option for repo connectivity to installed agent
=> techdebt: [CDS-86988]: Troubleshoot Doc Updation 

docs/platform/automation/cli/examples.md, docs/platform/automation/cli/reference.md
=> feat: PLG [3129]: update cli docs with expanded secrets command

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> Update latest cli version in docs to 0.0.21

docs/internal-developer-portal/get-started/layout-deepdive.md
Updated some changes to the Layout Docs
* *Issue(s)*
=> fix [IDP] : Updated some changes to the Layout Docs

docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/lines-of-code-metric.md
Removed the calculation example on ADO for SCM reports
* *Issue(s)*
=> Fix: [SEI-4794]: Lines of Code for ADO

tutorials/security-tests/build-scan-push-sto-ci.md, tutorials/security-tests/build-scan-push-sto-only.md, tutorials/security-tests/container-scan-aqua-trivy.md, tutorials/security-tests/dast-scan-zap.md, tutorials/security-tests/sast-scan-semgrep.md, tutorials/security-tests/your-first-sto-pipeline.md
=> Sto tutorial yaml pipeline tweaks sto 3948

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
Preview link: [Additional configuration for pipelines with STO scan steps](https://6595b3a83aedf307d91eb01f--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates#additional-configuration-for-pipelines-with-sto-scan-steps)
=> update per STO-6748

tutorials/security-tests/your-first-sto-pipeline.md
=> Word tweaks to your-first-sto-pipeline.md

docs/continuous-delivery/x-platform-cd-features/executions/step-and-stage-conditional-execution-settings.md
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-87507
=> CDS-87507 step-and-stage-conditional-execution-settings.md

docs/platform/Harness-AIDA/_category_.json, docs/platform/Security/_category_.json, docs/platform/authentication/_category_.json, docs/platform/delegates/_category_.json, docs/platform/organizations-and-projects/_category_.json, src/components/Docs/data/platformData.ts
Move Harness AIDA up in left nav, add to PL doc landing page
[Platform](https://65972aa81448ae419d84914a--harness-developer.netlify.app/docs/platform)
https://65972aa81448ae419d84914a--harness-developer.netlify.app/docs/category/harness-aida
* *Issue(s)*
=> [PL-43891] Move Harness AIDA up in left nav, add to PL doc landing page

docs/platform/triggers/custom-trigger-passing-data.md, docs/platform/triggers/schedule-pipelines-using-cron-triggers.md, docs/platform/triggers/selective-stage-execution-using-triggers.md, docs/platform/triggers/trigger-deployments-using-custom-triggers.md, docs/platform/triggers/trigger-on-a-new-artifact.md, docs/platform/triggers/trigger-pipelines-from-a-third-party-ci-system.md, docs/platform/triggers/trigger-pipelines-on-new-helm-chart.md, docs/platform/triggers/triggering-pipelines.md, docs/platform/triggers/triggers-overview.md, docs/platform/triggers/triggers-reference.md, docs/platform/triggers/troubleshoot-registered-triggers.md
Triggers overview
[Triggers overview](https://6597213ef4cd523e667eb1f2--harness-developer.netlify.app/docs/platform/triggers/triggers-overview)
* *Issue(s)*
=> [DOC-1528] Triggers overview

docs/platform/automation/api/api-permissions-reference.md, docs/platform/role-based-access-control/permissions-reference.md
Doc update for new IDP permissions being changed to active mode
* *Issue(s)*
=> feat: [IDP-1743]: Doc update for new IDP permissions being changed to active mode

docs/faqs/continuous-delivery-faqs.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Addition: [CDS-87894]: FAQs for Jan 5th

docs/internal-developer-portal/scorecards/checks-datasources.md, tutorials/internal-developer-portal/how-to-track-migrations.md
Updated the filepath information for github datasources
* *Issue(s)*
=> fix [IDP] : Updated the filepath information for github datasources

kb/platform/harness-platform-faqs.md
=> Zanini FAQs PL

kb/continuous-delivery/continuous-delivery-faqs.md
=> Zanini FAQs CDS

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md
This PR removes the need to replace placeholder GITHUB_USERNAME field from YAML. This will come from user input.
=> GitHub user will come from user input.

release-notes/delegate.md
Delegate 23.12.81811 hotfix release notes
https://65986d588ca97b52d391f144--harness-developer.netlify.app/release-notes/delegate#version-231281811
* *Issue(s)*
=> Delegate 23.12.81811 hotfix release notes

docs/platform/connectors/cloud-providers/add-tas-connector.md
Update for delegate HF 23.12.81811
https://65986e251b14f052f2b8dc26--harness-developer.netlify.app/docs/platform/connectors/cloud-providers/add-tas-connector#refresh-token-support
* *Issue(s)*
=> Update for docs delegate HF 23.12.81811

docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md, docs/first-gen/cloud-cost-management/setup-cost-visibility/set-up-cost-visibility-for-azure.md, docs/first-gen/continuous-delivery/azure-deployments/aks-howtos/1-harness-account-setup.md, docs/first-gen/firstgen-platform/account/manage-connectors/add-microsoft-azure-cloud-provider.md, docs/first-gen/firstgen-platform/security/access-management-howtos/single-sign-on-sso-with-saml.md, docs/first-gen/firstgen-platform/security/secrets-management/azure-key-vault.md, docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md, docs/platform/role-based-access-control/provision-users-and-groups-using-azure-ad-scim.md
https://harness.atlassian.net/browse/CDS-83989
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-83989
=> updated Azure AD to Microsoft Entra ID

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
=> fix: [CDS-88126]: update sorting of artifact for google artifact registry

docusaurus.config.js, package.json, release-notes/continuous-integration.md, src/components/Docs/ServiceReliabilityManagement.tsx, yarn.lock
Upgrade Test, do not merge.
* *Issue(s)*
@wei-harness @rohanmaharjan100 do not merge. Locally, my build does not "seal". Seeing if remote is better.
=> 3.1.0 Upgrade

docusaurus.config.js, roadmap/roadmap.md, src/components/Roadmap/Card/Card.tsx, src/components/Roadmap/Card/styles.module.scss, src/components/Roadmap/data/carddata.ts, src/components/Roadmap/data/cdData.ts, src/components/Roadmap/data/ciData.ts, src/components/Roadmap/data/ffData.ts, src/components/Roadmap/index.module.scss, src/components/Roadmap/index.tsx
=>  HDH-207-create-roadmap-functionality-on-hdh

docs/platform/git-experience/manage-environments-infra-definitions.md, docs/platform/git-experience/manage-services-using-git-experience.md
=> fix: [CDS-76667]: Add defaulting scenerio for managing services and environment using gitEx

docs/platform/git-experience/manage-environments-infra-definitions.md, docs/platform/git-experience/manage-services-using-git-experience.md
=> feat:[CDS-87714]: Add video tutorial

docusaurus.config.js
=> FIX : [HDH 216] broken-link-to-code-repository

release-notes/platform.md
Platform 1.19.6 release notes
[Platform](https://659c1386b2a3340f296ffe02--harness-developer.netlify.app/release-notes/platform)
* *Issue(s)*
=> [PL-43856] Platform 1.19.6 release notes

docs/chaos-engineering/ce-onboarding-guide/run-experiments-in-sandbox.md
Minor additions to CHAOS-3624
[Preview](https://659be8a56dc36011898b2866--harness-developer.netlify.app/docs/chaos-engineering/ce-onboarding-guide/run-experiments-in-sandbox)
=> Minor additions to CHAOS-3624

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md, release-notes/feature-flags.md
Android SDK release notes updated.
=> android sdk notes updated

release-notes/security-testing-orchestration.md
=> update date in frontmatter  security-testing-orchestration.md

docusaurus.config.js, package.json, yarn.lock
* Build time issue with anchor check.
* RSS Feed Broken
* *Issue(s)*
=> Downgarde to DS 3.0.1 from 3.1

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_REMOVE_COMMENTS_FROM_VALUES_YAML from docs

docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/lines-of-code-metric.md, docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/scm-rework.md
Added topic on Rework metric calculations.
* *Issue(s)*
=> [SEI-4789]: Technical Reference - Metric calculations - Rework for SCM

release-notes/delegate.md
=> feat: [CDS-87547]: Release notes for 82002

docs/platform/automation/cli/reference.md, docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> feat: [PLG-3112-3121-docs] Docs update for latest CLI version release

tutorials/cd-pipelines/kubernetes/cosign-opa.md
The menu for adding a policy set might have recently changed. This PR updates https://developer.harness.io/tutorials/cd-pipelines/kubernetes/cosign-opa/ to match those changes.
=> Update instructions for revised policyset menu.

docs/continuous-delivery/cd-integrations.md, release-notes/delegate.md
=> Remove CDS_ECS_BG_GREEN_SERVICE_ROLLBACK from docs

docs/platform/triggers/trigger-on-a-new-artifact.md
If tied to an Issue, list the Issue(s) here: https://harness.atlassian.net/browse/DOC-3917
* *Issue(s)*
=> Added a note that clarifies trigger recommendation for Docker repositories

kb/continuous-delivery/articles/pulling-image-artifactory.md
=> feat:[CDS-87417]: Knowledge base on pulling image from artifactory

docs/chaos-engineering/technical-reference/architecture/architecture.md
=> updated architecture

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md
=> Added PDF for Lab

release-notes/security-testing-orchestration.md
Preview: [Version 1.78](https://659ee9b6b1061c1554d6baa3--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-178)
=> STO relnotes 2024-01-09 STO-6938

docs/platform/triggers/trigger-deployments-using-custom-triggers.md
https://harness.atlassian.net/browse/CDS-88452
- [x ] Issue
* https://harness.atlassian.net/browse/CDS-88452
=> CDS-88452-broken-link

release-notes/security-testing-orchestration.md
Preview: [January 11 runner update](https://65a05e4054fcee3e281a5340--harness-developer.netlify.app/release-notes/security-testing-orchestration#january-11-runner-update)
=> uncomment STO 1.78 release notes STO-6938

docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
https://harness.atlassian.net/browse/CDS-88352
- [ x] Issue
* https://harness.atlassian.net/browse/CDS-88352
=> CDS-88352 OCI ECR update

release-notes/delegate.md
=> move 2023 release to previous releases

docs/code-repository/code-supported.md, docs/code-repository/config-repos/rules.md, docs/code-repository/pipelines/code-triggers.md, docs/code-repository/work-in-repos/keyword-search.md, docs/platform/triggers/triggering-pipelines.md, docs/platform/triggers/triggers-reference.md
-smtp config required for notifications with SMP
-codeowners syntax and details
=> CODE - codeowners and notifications

docs/faqs/chaos-engineering-faq.md, docs/troubleshooting/chaos-engineering/troubleshooting.md
=> Update troubleshooting guide

docs/chaos-engineering/technical-reference/probes/cmd-probe.md
Add environment and secret usage
=> update command probe

kb/continuous-delivery/continuous-delivery-faqs.md
=> Add-Faqs[CDS-87894]: Faqs for Jan 12

docs/platform/secrets/secrets-management/custom-secret-manager.md
=> clean up topic formatting

src/components/Roadmap/index.module.scss
=> HDH-207-create-roadmap-functionality-on-hdh

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-apply-step.md
=> Remove CDS_K8S_APPLY_MANIFEST_WITHOUT_SERVICE_NG from docs

docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md, kb/continuous-delivery/continuous-delivery-faqs.md
=> Remove CDS_ENABLE_TAS_ARTIFACT_AS_MANIFEST_SOURCE_NG from docs

docs/continuous-delivery/cd-integrations.md
https://harness.atlassian.net/browse/CDS-76452
- [ x] Issue
* CDS_SCOPE_INFRA_TO_SERVICES
=> CDS-76452 CDS_SCOPE_INFRA_TO_SERVICES

docs/platform/secrets/secrets-management/azure-key-vault.md
https://harness.atlassian.net/browse/PL-31624
- [ x] Issue
* https://harness.atlassian.net/browse/PL-31624
=> PL-31624 details on text and file secrets

docs/continuous-delivery/cd-integrations.md, docs/get-started/release-status.md, docs/platform/dashboards/use-dashboard-intelligence-by-aida.md, docs/self-managed-enterprise-edition/advanced-configurations/use-external-secrets-for-license-values.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift.md
=> change file name to release-status from beta-preview-ga

release-notes/chaos-engineering.md
=> Release notes 1.28.1

src/components/Roadmap/HorizonCard/styles.module.scss, src/components/Roadmap/index.module.scss, src/components/Roadmap/index.tsx
* *Issue(s)*
- [
] *Optional* Screen Shoot.
=> HDH-207 create roadmap mobile view

kb/continuous-delivery/continuous-delivery-faqs.md
Recloned and added FAQs again.
=> added FAQs again

release-notes/delegate.md
=> Patch for delegate 82005 - Update delegate.md

docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
=> Remove extraneous note from burp-scanner-reference.md

docs/chaos-engineering/technical-reference/probes/slo-probe.md
Added content for sloSourceMetadata and scope parameters
=> Added content

release-notes/continuous-delivery.md
=> Release notes for 1.20.9 release

docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md
Updates Python SDK docs with new API
=> FFM-10393 FF Python SDK - add new API docs

docs/troubleshooting/troubleshooting-nextgen.md
* https://harness.atlassian.net/browse/CDS-88516
=> [CDS-88516]: docs improvement for delegate OOM error 

docs/security-testing-orchestration/get-started/shared/_supported-infrastructures.md
=> remove ARM64 support on k8s/VMs STO-6969

docs/platform/connectors/cloud-providers/add-aws-connector.md
=> update Harness Delegate for consistency

docs/harness-cloud-operations/computing-uptime.md
=> fix: [IDP]: Update module name in module SLAs page

docs/code-repository/pipelines/code-triggers.md
Permissions required for Trigger creation
* *Issue(s)*
=> Permissions required for Trigger creation

docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-latency.md
=> Spelling corrections on pod-network-latency.md

docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md, release-notes/feature-flags.md
=> release notes for java 1.5.0

src/components/Certifications/CertificationsChaos.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
=> GA'd Chaos Dev Cert

release-notes/feature-flags.md
=> missing smp release notes added

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md, docs/feature-flags/ff-sdks/client-sdks/flutter-sdk-reference.md, docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md, docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md, docs/feature-flags/ff-sdks/client-sdks/react-client.md, docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md, docs/feature-flags/ff-sdks/client-sdks/xamarin-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/apex-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md, docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md, docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/php-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md, docs/feature-flags/ff-sdks/server-sdks/ruby-sdk-reference.md
**What**
Add links directly to the GH repo of each SDK instead of manually inserting the number on each release
**Why**
SDK releases are frequent and doing this will reduce the maintenance needed.
* *Issue(s)*
=> [FFM-10422] - Update SDK pages to point to latest releases on GH

release-notes/security-testing-orchestration.md
Preview: [Version 1.80.1](https://65a861b06173ad07faac6d4c--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1801)
MA has reviewed/approved STO-6824
CH has reviewed/approved STO-6919
Added STO-6958 after initial review
=> STO 1.80.1 release notes STO-7009

docs/continuous-delivery/gitops/get-started/harness-git-ops-basics.md
Mentioned demo video wasn't showing up.
* *Issue(s)*
=> Update docs to make video show up

docs/security-testing-orchestration/sto-techref-category/aa_step-palette-scanner-reference.TEMPLATE.v2.txt, docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/security-step-ui-settings-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-methods.md, docs/security-testing-orchestration/sto-techref-category/shared/legacy/_sto-ref-legacy-orchestrated.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-scan-mode-00-orchestrated.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/_sto-ref-ui-scan-mode-00-orchestration.md, docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/zap-scanner-reference.md, docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/ingest-scan-results-into-an-sto-pipeline.md, docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-an-orchestrated-scan-in-sto.md, docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/sto-workflows-overview.md
=> update Orchestrated refs to Orchestration STO-7011

kb/platform/harness-platform-faqs.md
=> Adding 10 questions on Platf FAQ list

docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
**What**
Customer is reporting some of the config items are wrong. This PR fixes issues
* *Issue(s)*
=> FFM-10422 - Fix errors in NodeJS SDK docs

release-notes/early-access.md
Add PL 1.20.9 early access feature: https://developer.harness.io/release-notes/platform#early-access-features
For reviewers, a preview is available: 
[Early access features](https://65a96053f6b16704b6606681--harness-developer.netlify.app/release-notes/early-access)
* *Issue(s)*
=> Add PL-43499

docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md
Update delegate tag info
[Use delegate selectors](https://65a9896476696a02f961d11c--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/select-delegates-with-selectors)
* *Issue(s)*
=> [PL-44153] Update delegate tag info

docs/platform/pipelines/add-a-stage.md
=> Remove CDS_CUSTOM_STAGE_WITH_ENV_INFRA from docs

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/x-platform-cd-features/environments/scope-infra-to-services.md
=> Remove CDS_SCOPE_INFRA_TO_SERVICES from docs

docs/continuous-delivery/cd-integrations.md
=> Remove PIE_RETRY_STEP_GROUP from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_MERGED_RUN_AND_RETRY_PIPELINE_COMPONENT from docs

docs/security-testing-orchestration/get-started/key-concepts/output-variables.md, docs/security-testing-orchestration/sto-techref-category/shared/dind-bg-step.md
tabbing issue fixed (STO-7026): [Docker-in-Docker requirements for STO](https://65aa8788cb616310fb52b004--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#docker-in-docker-requirements-for-sto)
stale note removed (STO-7027): [Scan output variables](https://65aa8788cb616310fb52b004--harness-developer.netlify.app/docs/security-testing-orchestration/get-started/key-concepts/output-variables)
=> fix tabbed issue in DinD snippet STO-7026

release-notes/feature-flags.md
=> node js release notes updated

release-notes/internal-developer-portal.md
Removed the unreleased feature tutorial from release notes
* *Issue(s)*
=> fix [IDP] Removed the unreleased feature tutorial from release notes

release-notes/platform.md
=> Update placeholder verno

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docs/platform/shared/cli/windows.md
=> updated the latest release number of Harness-CLI

src/components/Certifications/styles.module.scss, src/components/HomepageCertifications/Carousel.module.scss, src/components/HomepageCertifications/styles.module.scss
* *Issue(s)*
- [
] *Optional* Screen Shoot.
=> HDH-215-responsive-mobile-cert-section

tutorials/cd-pipelines/unified-cicd/e2e-pipeline.md
=> Update CD E2E tutorial with added CLI automations

docs/get-started/harness-platform-architecture.md
Added IDP module to the list of all Harness Platform Modules
* *Issue(s)*
=> fix [IDP] Added IDP module to the list of all Harness Platform Modules

docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/scm-commits.md
Added documentation on the ingestion logic of commits data in SEI.
* *Issue(s)*
=> [SEI-5018]: SCM Commits behaviour in SEI

release-notes/software-engineering-insights.md
Added the release notes for version 202401.1
* *Issue(s)*
=> [SEI-5020]: SEI Release Notes 202401.1

release-notes/chaos-engineering.md
=> Add 1.29.0 release notes

docs/internal-developer-portal/roadmap/_category_.json, docs/internal-developer-portal/roadmap/harness-vs-backstage.md, docs/internal-developer-portal/roadmap/roadmap.md
Added the Roadmap tab in IDP
* *Issue(s)*
=> feat [IDP-2024] : Added the Roadmap tab in IDP

release-notes/platform.md
[PL-44116](https://harness.atlassian.net/browse/PL-44116) PL 1.21.5
https://harness.atlassian.net/wiki/spaces/PD/pages/21609677152/NG+Release+SAAS+January+15th+2024+for+1.21.x-+Build
https://65aad3538e420615d47bc820--harness-developer.netlify.app/release-notes/platform#version-121x-
* *Issue(s)*
[PL-44116]: https://harness.atlassian.net/browse/PL-44116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PL-44116] PL 1.21.5 release notes

docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-self-managed-add-ingress-controller-service-annotations.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md, docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift.md, docs/self-managed-enterprise-edition/smp-supported-platforms.md
=> update smp install topics and paid feature tags

release-notes/platform.md
=> update important feature change notice in PL RN

.github/CODEOWNERS, docs/code-repository/pull-requests/review-pr.md, release-notes/code-repository.md
* support for videos in PR comments
* Update CODEOWNERS for Code Repository docs. Remove trailing whitespace.
=> videos in pr comments

docs/chaos-engineering/technical-reference/chaos-faults/kube-resilience/kube-resilience.md, docs/chaos-engineering/technical-reference/chaos-faults/kube-resilience/kubelet-density.md
=> Minor updates

docs/internal-developer-portal/flows/idp-stage.md, docs/internal-developer-portal/governance/audit-trails.md, docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md, docs/internal-developer-portal/scorecards/opa-implementation.md, release-notes/internal-developer-portal.md, tutorials/internal-developer-portal/service-onboarding-pipeline.md
Rectified all the typo errors
* *Issue(s)*
=> fix [IDP-2036] : Rectified all the typo errors

docs/internal-developer-portal/flows/custom-actions.md, docs/internal-developer-portal/flows/idp-stage.md, docs/internal-developer-portal/flows/service-onboarding-pipelines.md
Added the support matrix for custom actions
* *Issue(s)*
=> fix [IDP] : Added the support matrix for custom actions

tutorials/internal-developer-portal/service-onboarding-pipeline.md
Updated the template for gitlab
* *Issue(s)*
=> feat: [IDP-2021] :  Updated the template for gitlab

src/components/Certifications/CertificationsCloudCostManagement.tsx, src/components/Certifications/data/certificationsData.ts
=> CCM Admin to Beta

release-notes/delegate.md
=> add Harness version 1.20.9, Harness Delegate version 24.01.82108

release-notes/delegate.md
=> add missing ff info

release-notes/delegate.md
=> comment out release heading pending filter info

docs/security-testing-orchestration/get-started/shared/_supported-infrastructures.md
=> update format of Supported Infrastructures table STO-7014

kb/continuous-integration/continuous-integration-faqs.md
=> Zanini CI FAQs - Jan 22nd

kb/feature-flags/harness-feature-flag-faqs.md
=> Zanini FF FAQs - Jan 22nd

kb/platform/harness-platform-faqs.md
=> Zanini PL FAQs - Jan 22nd

release-notes/feature-flags.md
=> release notes for js 1.22.0 updated

docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
=> [fix]: [CDS-87972]: Update multi-service documentation

docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/scm-commits.md
Fixed the errors in the SCM Commits metrics ingestion logic doc errors.
* *Issue(s)*
=> [SEI-5111]: Fix commits metric document error

release-notes/security-testing-orchestration.md
=> hide STO-6958 STO-7043

release-notes/feature-flags.md
=> release notes for react 1.7.0 added

src/components/Roadmap/data/cdData.ts, src/components/Roadmap/data/platformData.ts, src/components/Roadmap/data/roadmapData.ts, src/components/Roadmap/index.tsx
=> Add future roadmap for CD

docs/continuous-delivery/cd-integrations.md, docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-jira-issues-in-cd-stages.md
=> Remove CDS_JIRA_UPDATE_SELECT_FIELDS_ENABLED from docs

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
- Added step-palette options, misc tweaks [Anchore Enterprise](https://65afda3b140c9b268fc87ac3--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference)
- Added Anchore Enterprise to list of supported container scans: [Scanners supported by STO](https://65afda3b140c9b268fc87ac3--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference/#scanners-supported-by-sto)
=> Anchore scanner reference updates STO-7013

docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile.md
Update build custom delegate images
https://65b05fdddb2ec617b7b950e2--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile#build-a-custom-image-with-non-root-access-that-includes-custom-certificates
* *Issue(s)*
=> [DOC-3961] [PL-46559] Update build custom delegate images

docs/internal-developer-portal/flows/custom-actions.md
Added the output name explicitly for custom actions
* *Issue(s)*
=> fix [IDP] : Added the output name explicitly for custom actions

docs/security-testing-orchestration/get-started/onboarding-guide.md
=> fix bad RBAC link in onboarding-guide.md

docs/software-engineering-insights/sei-metrics-and-reports/dora-metrics.md
Removed sub topic on DORA MTBF
* *Issue(s)*
=> Fix: [SEI-5113]: Removed sub topic on DORA MTBF

docs/continuous-delivery/verify/configure-cv/verify-deployments-with-app-dynamics.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-cloudwatch.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-custom-health-metrics.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-datadog.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-dynatrace.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-elastic-search.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-google-cloud-operations.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-loki.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-new-relic.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-prometheus.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-signalfx.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-splunk.md, docs/continuous-delivery/verify/configure-cv/verify-deployments-with-sumologic.md
Moonitored service should be created at project level warning.
- [X ] Maintenance/Chore
* *Issue(s)*
=> Added warning

src/components/Roadmap/index.tsx
=> fix set platform to index 1 in roadmap

release-notes/feature-flags.md
=> flutter sdk 2.1.2 release notes updated

kb/cloud-cost-management/cloud-cost-management-faqs.md, kb/continuous-delivery/continuous-delivery-faqs.md, kb/continuous-integration/continuous-integration-faqs.md
New FAQ added and some fixes in CI FAQ
=> FAQ updates

release-notes/platform.md
During SMP RN work, there were items included in the filter that were missing from previous RN due to label issues. This PR adds the items to applicable RN vernos.
* *Issue(s)*
=> Update PL RN with issues discovered during SMP RN process

release-notes/delegate.md
=> add delegate 24.01.82108 RN

docusaurus.config.js, yarn.lock
* Add Roadmap
* Chore, update yarn.lock
* *Issue(s)*
=> Add Roadmap to HDH

src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
Tidy for STO Admin Post GA
* *Issue(s)*
=> Tidy for STO Admin Post GA

docs/platform/delegates/delegate-concepts/graceful-delegate-shutdown-process.md
Add upgrader shutdown process
[Graceful delegate shutdown](https://65b4087461304e0eb572f3c0--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/graceful-delegate-shutdown-process)
* *Issue(s)*
=> [PL-46612] Add upgrader shutdown process

kb/continuous-delivery/continuous-delivery-faqs.md
=> Addition_of_FAQs[CDS-88933]: FAQs for 26th JAN

docs/chaos-engineering/technical-reference/chaos-faults/aws/security-configurations/_category_.json, docs/chaos-engineering/technical-reference/chaos-faults/aws/security-configurations/aws-switch-profile.md, docs/chaos-engineering/technical-reference/chaos-faults/aws/security-configurations/policy-for-all-aws-faults.md
Add introduction for AWS superset policy
Add correct case for "Security configurations"
=> CHAOS-2114 Add introduction for AWS superset policy

docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
Added the video tutorial link for custom plugins in the docs
* *Issue(s)*
=> feat [IDP] : Added the video tutorial link for custom plugins in the docs

docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-disk-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-io-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-web-app-access-restrict.md, docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-web-app-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/node/node-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/load/locust-loadgen.md
Audit for load fault and azure faults
=> Audit for load fault and azure faults

docs/chaos-engineering/technical-reference/security/introduction.md, docs/chaos-engineering/technical-reference/security/security-templates/introduction.md, docs/chaos-engineering/technical-reference/security/security-templates/openshift-scc.md, docs/chaos-engineering/technical-reference/security/security-templates/psp.md
Add intro for security templates
=> CHAOS-2112 Add intro for security templates

docs/software-engineering-insights/sei-technical-reference/scm-metrics-calculation/scm-coding-days.md
Added SCM Coding Days metric calculation topic under Tech Reference.
* *Issue(s)*
=> feat: [SEI-5132]: Added SCM Coding Days metric calculation topic

kb/continuous-delivery/continuous-delivery-faqs.md
=> Fix[PL-46669]: Delegate token hardcoded in devloper-hub

release-notes/delegate.md
Delegate 24.01.822xx release notes
https://65b319487f893a6658a4ea7b--harness-developer.netlify.app/release-notes/delegate#harness-version-122x-harness-delegate-version-2401822xx
* *Issue(s)*
=> [PL-46605] Delegate 24.01.82202 release notes

docs/chaos-engineering/technical-reference/architecture/architecture.md
Add execution plane resource utilization matrix
=> CHAOS-2920 Update architecture.md

docs/platform/shared/cli/amd.md, docs/platform/shared/cli/arm.md, docs/platform/shared/cli/mac.md, docusaurus.config.js, src/components/Certifications/data/cd-certification-developer-review-guide.md
* Removed Scarf
* Patched CV Doc Link on CD Dev Cert
* *Issue(s)*
=> Removed Scarf

release-notes/continuous-integration.md
=> Updating mac docs

docs/platform/delegates/manage-delegates/customize-delegate-logging.md
=> fix note format

docs/faqs/harness-delegate-faqs.md, docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile.md, docs/platform/delegates/manage-delegates/hide-logs-using-regex.md, release-notes/delegate.md
Hide log info using regex
[Hide log information based on regex patterns](https://65b7db0bdd6169228b1d5b81--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/hide-logs-using-regex)
https://65b7db0bdd6169228b1d5b81--harness-developer.netlify.app/docs/faqs/harness-delegate-faqs#can-i-remove-sensitive-information-from-logs
HF release note: https://65b7db0bdd6169228b1d5b81--harness-developer.netlify.app/release-notes/delegate#version-240182110
* *Issue(s)*
=> [PL-46673] Hide log info using regex - feature and delegate HF doc

release-notes/continuous-delivery.md
=> Release notes for 1.22.0

docs/security-testing-orchestration/sto-techref-category/aa_step-palette-scanner-reference.TEMPLATE.v2.txt, docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aws-security-hub-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/custom-ingest-reference.md, docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nessus-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/semgrep-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/_zz-step-palette-scanner-reference.TEMPLATE.txt, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/_auto-detect.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/_name.md, docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/zap-scanner-reference.md
Updated topics for integrations that support orchestration | extraction for repos | containers | apps.
Added the following section: [Target and variant detection](https://65b4364441423d201b50794b--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference#target-and-variant-detection)
=> Auto detect targets variants v2 STO-6974

docs/platform/delegates/delegate-concepts/delegate-registration.md
add early access 1.19.6 feature (PL-42471)
https://659c4bf2249fad145435b783--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-registration#allowlist-verification
* *Issue(s)*
=> add early access 1.19.6 feature (PL-42471)

release-notes/platform.md
=> Uncomment PL-42471

release-notes/delegate.md
=> add PL-42471

release-notes/early-access.md
=> add PL-42471 allowlist verification for delegate registration

release-notes/delegate.md
=> add ZD-56849 to PL-46531

release-notes/platform.md
[PL-46590](https://harness.atlassian.net/browse/PL-46590) PL 1.22.x SaaS release notes
https://harness.atlassian.net/wiki/spaces/PD/pages/21618098251/NG+Release+SAAS+January+22nd+2024+for+1.22.x-+Build
* *Issue(s)*
[PL-46590]: https://harness.atlassian.net/browse/PL-46590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PL-46590] PL 1.22.3 release notes

src/components/HomepageCertifications/data/certificationsData.ts
=> Updated Cert Data to include CE

docs/platform/Harness-AIDA/aida-overview.md, docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Update AIDA dashboard intelligence
[Overview of Harness AI Development Assistant (AIDA)](https://65b8ff811e675bf1027f8b7a--harness-developer.netlify.app/docs/platform/Harness-AIDA/aida-overview)
[Use Dashboard Intelligence by AIDA](https://65b7fdb07b34bc3e619bc1f5--harness-developer.netlify.app/docs/platform/dashboards/use-dashboard-intelligence-by-aida)
* *Issue(s)*
=> [PL-46627] Update AIDA dashboard intelligence

release-notes/continuous-integration.md
=> Update CI-110789 with delegate dependency

release-notes/delegate.md
=> add CI-10789

docs/internal-developer-portal/plugins/available-plugins/kubernetes.md, docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md, docs/internal-developer-portal/roadmap/_category_.json
Example annotations for kubernetes plugin
* *Issue(s)*
=> feat: [IDP-2093] : Example annotations for kubernetes plugin

src/components/Certifications/CertificationsCloudCostManagement.tsx, src/components/Certifications/LandingPage.tsx, src/components/Certifications/data/certificationsData.ts
=> CCM Admin GA

src/components/Docs/data/selfManagedEnterpriseEditionData.ts
=> [PL-46769] Update SMP landing page

kb/continuous-delivery/continuous-delivery-faqs.md, kb/feature-flags/harness-feature-flag-faqs.md, kb/platform/harness-platform-faqs.md
amit full quarter faq contribution
Amit quarter faq contribution
=> amit full quarter faq contribution

docs/internal-developer-portal/get-started/register-a-new-software-component.md
Added the instructions to register multiple software-components together
* *Issue(s)*
=> feat: [IDP-2096] : Added the instructions to register multiple software-components together

docs/internal-developer-portal/get-started/register-a-new-software-component.md
Updated the small nits
* *Issue(s)*
=> fix [IDP] :  Updated the small nits

docs/cloud-cost-management/shared/ccm-supported-platforms.md
- [  ] Issue
- [x ] Maintenance/Chore
* *Issue(s)*
=> [FEAT]: CCM 15811

docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md, docs/first-gen/fg-sme/vm/embedded-kubernetes-on-prem-infrastructure-requirements.md, docs/first-gen/firstgen-platform/account/manage-delegates/delegate-requirements-and-limitations.md, docs/platform/delegates/delegate-concepts/delegate-requirements.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md, docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md
SMP is not using GRPC, all communication goes via REST now. 
* *Issue(s)*
=> [DOC-2349] [PL-44156] Update gRPC requirement

docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
=> FFM - add Android SDK ProGuard note

docs/chaos-engineering/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md, docs/troubleshooting/chaos-engineering/known-issues.md
Add info about linux resilience probes
=> CHAOS-3927 Add info about linux resilience probes

tutorials/internal-developer-portal/service-onboarding-with-idp-stage.md
Added the conditional execution docs
* *Issue(s)*
=> feat: [IDP-870] : Added the conditional execution docs

release-notes/self-managed-enterprise-edition.md
SMP patch release 0.13.1 release notes
**Note:** Air gap bundle and Helm chart links are placeholders and won't be active until the patch is deployed.
https://65bcf005929de08b002d4218--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#february-2-2024-patch-version-0131
* *Issue(s)*
=> [PL-46738] SMP patch 0.13.1 release notes

release-notes/delegate.md
=> feat: [CDS-91176]: add doc for delegate hotfix 82203

docs/platform/variables-and-expressions/harness-variables.md
Block expressions with getClass(). This expression evaluation can lead to the execution of a bash script in our infra. 
* *Issue(s)*
=> fix: [CDS-88993]: Block expressions with getClass() doc

docusaurus.config.js, src/css/custom.css
=> Chore [HDH-222] add Sign In button to main nav

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/coverity-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/semgrep-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_app-instance.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_code-repo.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_container-image.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_intro.md, docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_note.md, docs/security-testing-orchestration/sto-techref-category/zap-scanner-reference.md
=> Auto detect targets variants v2 sto 6974

docs/internal-developer-portal/flows/custom-actions.md
Added the information on custom actions
* *Issue(s)*
=> fix [IDP] : Added the information on custom actions

tutorials/internal-developer-portal/service-onboarding-pipeline.md, tutorials/internal-developer-portal/service-onboarding-with-idp-stage.md
Added the information on how to add files in templates and conditional inputs
* *Issue(s)*
=> feat: [IDP-2079]:  Added the information on how to add files in templates and conditional inputs

src/components/Roadmap/HorizonCard/index.tsx, src/components/Roadmap/HorizonCard/styles.module.scss, src/components/Roadmap/data/cdData.ts, src/components/Roadmap/data/ciData.ts, src/components/Roadmap/data/ffData.ts, src/components/Roadmap/data/platformData.ts, src/components/Roadmap/data/roadmapData.ts, src/components/Roadmap/index.module.scss, src/components/Roadmap/index.tsx
=> HDH 219 Roadmap Enhancements

docs/continuous-delivery/cd-infrastructure/terraform-infra/optional-tf-var-files.md
=> Remove CDS_TERRAFORM_SUPPORT_OPTIONAL_VAR_FILE_PATHS_NG from docs

docs/continuous-delivery/cd-integrations.md
=> Remove CDS_JIRA_APPROVAL_OPTIMIZATION from docs

release-notes/continuous-delivery.md
=> CDS-89314 - updating hotfix doc

docs/platform/delegates/delegate-concepts/delegate-overview.md, release-notes/delegate.md, release-notes/early-access.md
Add task capacity details
https://65c12e88f25be40729a68b6b--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-overview#delegate-task-capacity
* *Issue(s)*
=> [PL-46834] Add task capacity details

docs/chaos-engineering/technical-reference/hce-saas-api/_category_.json, docs/chaos-engineering/technical-reference/hce-saas-api/hce-saas-api.md
=> CHAOS-3251 HCE SAAS API doc

docs/internal-developer-portal/flows/service-onboarding-pipelines.md, docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md, docs/internal-developer-portal/plugins/custom-plugins/overview.md
Updated the most important steps to be more prominent
* *Issue(s)*
=> fix [IDP] : Updated the most important steps to be more prominent

docs/internal-developer-portal/flows/service-onboarding-pipelines.md
Added the extensive docs on how to write template
* *Issue(s)*
=> feat: [IDP-2079] : Added the extensive docs on how to write template

kb/continuous-delivery/continuous-delivery-faqs.md
=> Addition_of_FAQs[CDS-91011]: weekly added Faqs for 2nd Feb 24

release-notes/chaos-engineering.md
Chaos engineering release notes 1.30
=> CHAOS-4046 Release notes 1.30

src/components/Roadmap/index.tsx
- [ X] Maintenance/Chore
* *Issue(s)*
- [ X] Tested Locally
=> Removed coming soon from header

docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
- [ x ] Maintenance/Chore
* *Issue(s)*
=> Added example of multiple self-signed certificates

docs/continuous-delivery/shared/jira-approval-steps.md, docs/continuous-delivery/shared/servicenow-approval-steps.md, docs/platform/approvals/adding-harness-approval-stages.md, docs/platform/approvals/custom-approvals.md
=> fix:[CDS-88785]: adding log limitation ref in approval logs

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
Correct version compatibility, clarify text
* *Issue(s)*
=> [PL-46853] Correct version compatibility, clarify text

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
=> minor recast of expiration text

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
=> Venkat-edits

docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-disk-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-dns-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-host-reboot.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-modify-response.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-reset-peer.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-io-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-rate-limit.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-service-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-vm-poweroff.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-blackhole-chaos.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-cpu-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-disk-stress.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-memory-hog.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-corruption.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-duplication.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-latency.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-loss.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-process-kill.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-service-stop.md, docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-time-chaos.md
=> CHAOS-4060 VMware faults audit

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
=> fix:[CDS-91108]: http step tls credentials to use only secret refs

docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/create-a-new-dashboard.md, docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/shared/field-descriptions.md, docs/chaos-engineering/configure-chaos-experiments/chaosguard/configuring-chaosguard.md, docs/chaos-engineering/configure-chaos-experiments/chaosguard/shared/field-descriptions.md
=> CHAOS-3706 Chaos dashboard descriptions

src/components/HomepageCertifications/Carousel.module.scss, src/components/HomepageCertifications/Carousel.tsx, src/components/HomepageCertifications/CertCard.module.scss, src/components/HomepageCertifications/data/certificationsData.ts, src/components/HomepageCertifications/index.tsx, src/components/HomepageCertifications/styles.module.scss
=> FIX homepage certs carousel

release-notes/feature-flags.md
=> release notes for js 1.23.0

release-notes/feature-flags.md
=> release notes for android 1.2.4

release-notes/feature-flags.md
=> release notes for andriod 1.2.5 added

release-notes/feature-flags.md
=> release notes for flutter 2.1.3 added

src/components/LearnAboutPlatform/styles.module.scss, src/components/Roadmap/data/ccmData.ts, src/components/Roadmap/data/ceData.ts, src/components/Roadmap/data/idpData.ts, src/components/Roadmap/data/roadmapData.ts, src/components/Roadmap/data/seiData.ts, src/components/Roadmap/data/srmData.ts, src/components/Roadmap/data/stoData.ts, src/components/Roadmap/index.tsx
* Added All GA Modules to Roadmap Scaffolding
* CSS for Code on Homepage Hoover was Missing.
* *Issue(s)*
=> Added All GA Modules to Roadmap Scaffolding

docusaurus.config.js, src/css/custom.css
=> UPDATE  HDH-224-adjust-sizing-on-hdh-top-banner

kb/security-testing-orchestration/security-testing-orchestration-faqs.md
=> Change heading level in security-testing-orchestration-faqs.md

kb/platform/new-navigation-faqs.md
=> add missing info, minor formatting updates

docs/platform/variables-and-expressions/status-type-reference.md
Expression status type reference
[Expression status type reference](https://65820ee6e552d06d80f9c905--harness-developer.netlify.app/docs/platform/variables-and-expressions/status-type-reference)
* *Issue(s)*
=> [DOC-3229] [PL-44169] Expression status type reference

src/components/Roadmap/HorizonCard/styles.module.scss, src/components/Roadmap/data/roadmapData.ts, src/components/Roadmap/index.tsx
* Wired in to Roadmap
* Added Hover CSS
* *Issue(s)*
=> Updated for IaCM Roadmap

docs/chaos-engineering/technical-reference/probes/http-probe.md
Update HTTP probe since https://github.com/harness/developer-hub/pull/4607 PR is not reflecting the changes
=> Update http probe

docs/internal-developer-portal/plugins/available-plugins/azure-devops.md
Added the docs for azure-devops plugin
* *Issue(s)*
=> feat: [IDP-2131]: Added the docs for azure-devops plugin

docs/internal-developer-portal/plugins/custom-plugins/overview.md
=> Custom plugins status change

docs/internal-developer-portal/flows/idp-stage.md
Added the new set permissions required for slack step token
* *Issue(s)*
=> feat: [IDP-2128]: Added the new set permissions required for slack step token

docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/create-a-new-dashboard.md, docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/shared/field-descriptions.md
=> Update chaos dashboard

docs/internal-developer-portal/flows/custom-actions.md, docs/internal-developer-portal/flows/service-onboarding-pipelines.md, release-notes/internal-developer-portal.md
Added the information on custom field extensions
* *Issue(s)*
=> feat: [IDP-2146]: Added the information on custom field extensions

release-notes/feature-flags.md
=> release notes for react sdk added

src/components/Roadmap/data/stoData.ts
=> Updated the STO roadmap for FY 25

client_module/searchBar.js, docusaurus.config.js, src/css/custom.css
=> FEAT adding search in nav for mobile

kb/platform/harness-platform-faqs.md
Update PL KB FAQs
* *Issue(s)*
=> [PL-46881] Update PL KB FAQs

src/components/HomepageFeatures/index.tsx, src/components/HomepageFeatures/styles.module.scss
* *Issue(s)*
- [
] *Optional* Screen Shoot.
=> FIX : [HDH 225] Button in Homepage not responsive

.github/pull_request_template.md
Chore: s/Screen Shoot/Screenshot for PR template
* *Issue(s)*
=> Chore: s/Screen Shoot/Screenshot for PR template

src/components/Roadmap/data/platformData.ts, src/components/Roadmap/index.module.scss
=> FIX : adding scrollbar at top of roadmap

kb/platform/harness-platform-faqs.md
=> fix headings, continue cleanup in kb pl faqs

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
- [X ] Feature
- [ X] Maintenance/Chore
* *Issue(s)*
- [X ] Tested Locally
=> AWS SAM configuration clarification for authentication with IRSA

src/components/Roadmap/data/IacmData.ts, src/components/Roadmap/data/ccmData.ts, src/components/Roadmap/data/cdData.ts, src/components/Roadmap/data/ceData.ts, src/components/Roadmap/data/ciData.ts, src/components/Roadmap/data/ffData.ts, src/components/Roadmap/data/idpData.ts, src/components/Roadmap/data/platformData.ts, src/components/Roadmap/data/seiData.ts, src/components/Roadmap/data/srmData.ts, src/components/Roadmap/data/stoData.ts
=> Added "Released" Column in Roadmaps

release-notes/self-managed-enterprise-edition.md
SMP 0.12.1, 0.13.3 patch release notes
[Self-Managed Enterprise Edition Release Notes](https://65c54f6847885c1dad5c4e78--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
* *Issue(s)*
=> [PL-46956] SMP 0.12.1, 0.13.3 patch release notes

docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md, docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scans.md
=> Snyk workflow updates v2 sto 7110

docs/platform/git-experience/gitexp-bidir-sync-setup.md
- [X ] Feature
- [ X] Maintenance/Chore
* *Issue(s)*
- [ X] Tested Locally
=> GitX bidirectional Repo

src/components/Roadmap/data/idpData.ts
Added the roadmap for IDP
* *Issue(s)*
=> feat: [IDP-2066]:  Added the roadmap for IDP

docs/internal-developer-portal/flows/custom-actions.md
Updated an info on the harnessautoorgpicker
* *Issue(s)*
=> fix: [IDP-2156]: Updated an info on the harnessautoorgpicker

docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/_category_.json, docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/add-chaos-hub.md, docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/introduction.md, docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/manage-hub.md, docs/chaos-engineering/configure-chaos-experiments/chaosguard/_category_.json, docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md, docs/chaos-engineering/configure-chaos-experiments/experiments/create-complex-chaos-experiments.md, docs/chaos-engineering/configure-chaos-experiments/experiments/resilience-score.md, docs/chaos-engineering/get-started/key-concepts.md
Introduction to ChaosHub page
Change chaosguard to ChaosGuard
Change chaos hub to ChaosHub
Change headings
=> CHAOS-4162 ChaosHub changes

docs/harness-cloud-operations/computing-uptime.md
=> CHAOS-4150 Add SRM SLI

docs/internal-developer-portal/get-started/enable-docs.md
Added the warning on directory limitation for docs
* *Issue(s)*
=> fix: [IDP]: Added the warning on directory limitation for docs

release-notes/self-managed-enterprise-edition.md
=> Fix typo in self-managed-enterprise-edition.md

docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
Added the information on folder structure for custom plugins
* *Issue(s)*
=> fix: [IDP]: Added the information on folder structure for custom plugins

docs/platform/triggers/trigger-deployments-using-custom-triggers.md
=> fix setting location - update from general to pipeline

release-notes/security-testing-orchestration.md
=> Update 1.83.1 relnotes

src/components/Roadmap/data/ccmData.ts
=> added roadmap for CCM

src/components/Roadmap/data/stoData.ts
=> Updated the STO roadmap for FY 25 descriptions

release-notes/feature-flags.md
=> .net release notes updated

kb/platform/harness-platform-faqs.md
=> [PL-46881] Update kb pl faqs

release-notes/delegate.md
Harness version 1.24.7, Harness Delegate version 24.02.82302 release notes
https://harness.atlassian.net/wiki/spaces/PD/pages/21637005335/NG+Release+SAAS+February+5th+2024+for+1.24.x-+Build
[Delegate](https://65c4f224a42ede292fd63ea2--harness-developer.netlify.app/release-notes/delegate)
* *Issue(s)*
=> [PL-46876] Harness Delegate version 24.02.82302 release notes

release-notes/platform.md
[PL-46862](https://harness.atlassian.net/browse/PL-46862)
https://harness.atlassian.net/wiki/spaces/PD/pages/21637005335/NG+Release+SAAS+February+5th+2024+for+1.24.x-+Build
https://65c4bc926564570a74526be5--harness-developer.netlify.app/release-notes/platform
* *Issue(s)*
[PL-46862]: https://harness.atlassian.net/browse/PL-46862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PL-46862] PL 1.24.7 Release Notes

docs/internal-developer-portal/get-started/onboarding-guide.md
Added the limitation info for bitbucket cloud connector 
* *Issue(s)*
=> fix: [IDP-2205]: Added the limitation info for bitbucket cloud connector 

docs/internal-developer-portal/flows/idp-stage.md
Small nit removed the typo
* *Issue(s)*
=> fix: [IDP]: Small nit removed the typo
