harness/developer-hub

- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-api-block.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-api-latency.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-api-modify-body.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-api-modify-header.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-api-status-code.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-api-block/https-enabled.yaml
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-api-latency/https-enabled.yaml
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-body/https-enabled.yaml
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-headers/https-enabled.yaml
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-api-status-code/https-enabled.yaml
> chore: [CHAOS-4194]: Doc Tasks - Add the https support and custom certificate in api-chaos faults

- kb/continuous-delivery/articles/chained-pipeline-output-variables.md
> Fix value field while providing output variable in chained pipeline yaml

- release-notes/delegate.md
This is Work in Progress
* *Issue(s)*
> Delegate 82304 hotfix for CDS-91499, ZD-57892

- src/components/Docs/data/platformData.ts
> fix access control link on pl landing page

- docs/software-supply-chain-assurance/slsa/generate-slsa.md
- tutorials/secure-supply-chain/generate-slsa.md
> Update: Document SLSA Supported Infra & Steps

- docs/platform/automation/cli/reference.md
- docs/platform/shared/cli/amd.md
- docs/platform/shared/cli/arm.md
- docs/platform/shared/cli/mac.md
- docs/platform/shared/cli/windows.md
TO BE MERGED AFTER [https://github.com/harness/harness-cli/pull/69](https://github.com/harness/harness-cli/pull/69)
* *Issue(s)*
> feat: [GTM-3249]: Add pipeline run subcommand to CLI docs and increment CLI release

- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/create-custom-scan-images.md
> add redirect

- release-notes/self-managed-enterprise-edition.md
SMP 0.13.4 patch release notes
[Self-Managed Enterprise Edition](https://65cba118e060690e4bcc90e0--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
* *Issue(s)*
> [PL-47052] SMP 0.13.4 patch release notes

- docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
> Fix typo snyk-scanner-reference.md

- docs/platform/automation/cli/reference.md
> Added Pipeline Run

- docs/continuous-delivery/x-platform-cd-features/services/cd-services-config-files.md
> Remove CDS_NG_CONFIG_FILE_EXPRESSION from docs

- release-notes/feature-flags.md
> .NET 1.4.2 release notes added

- docs/software-engineering-insights/sei-integrations/sei-integrations-overview.md
Added data sync statement.
* *Issue(s)*
> [SEI-5520]: Added data sync statement

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
- [x ] Issue
* *Issue(s)*
Please refer to the zendesk ticket for more details: https://harnesssupport.zendesk.com/agent/tickets/52871
> [CDS-83440]: Update download-and-copy-artifacts-using-the-command-step.md

- docs/internal-developer-portal/scorecards/scorecard.md
Updated the info on use of tags for scorecards
* *Issue(s)*
> fix: [IDP]: Updated the info on use of tags for scorecards

- docs/platform/variables-and-expressions/add-a-variable.md
Detail information: https://harness.atlassian.net/browse/CDS-91198
* *Issue(s)*
> Add documentation for use of dateTimestamp variable in yamls

- docs/chaos-engineering/configure-chaos-experiments/image-registry.md
Update image registry to mention about default command that is provided with workflow controller
> CHAOS-3320 Update image-registry

- docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-volume-detach.md
- docs/chaos-engineering/technical-reference/chaos-faults/aws/resource-access-restrict.md
- docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-cpu-hog.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-cpu-hog.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-dns-error.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-dns-spoof.md
- docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-dns-chaos.md
- docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-memory-hog.md
> CHAOS-4278 fix dead links

- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md
> feat: [CDS-80530]: Document rollback behaviour for traditional deployments

- docs/software-engineering-insights/sei-integrations/sei-integrations-overview.md
Fixed broken links on integration landing page
* *Issue(s)*
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker.
> Fix: [SEI-5542]: Fixed broken links on integrations landing page

- docs/internal-developer-portal/plugins/available-plugins/pagerduty.md
Updated the links for pageduty plugin
* *Issue(s)*
> fix: [IDP-2260]: Updated the links for pageduty plugin

- docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
What
Update docs to reflect new SDK APIs and remove old/outdated information
* *Issue(s)*
> FFM-10521 - Update docs for Android V2 SDK

- release-notes/early-access.md
- release-notes/software-engineering-insights.md
Added Release Notes for 202402.1
* *Issue(s)*
> [SEI-5554]: Added Release Notes for 202402.1

- kb/continuous-delivery/continuous-delivery-faqs.md
> Addtion_Of_Faqs[CDS-91011]: FAQs for 9th Feb

- release-notes/security-testing-orchestration.md
> hide-STO-6840-in-relnotes

- docs/platform/pipelines/input-sets.md
Add details of RBAC for Input Sets
https://65cb905d3fd94d008f3d41e3--harness-developer.netlify.app/docs/platform/pipelines/input-sets#manage-access-to-input-sets
* *Issue(s)*
> Details of RBAC for Input Sets [CDS-80218]

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-annotations-and-labels.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-releases-and-versioning.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollback.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-steps-timeouts-and-deadline-parameters.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/using-open-shift-with-harness-kubernetes.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
- [X ] Feature
* *Issue(s)*
- [X ] Tested Locally
> Traffic Routing Step Reference

- docs/platform/security/add-manage-ip-allowlist.md
https://harness.atlassian.net/browse/PL-47596
* *Issue(s)*
> PL-47596 Cleanup FF PL_IP_ALLOWLIST_NG

- release-notes/platform.md
[PL-47074](https://harness.atlassian.net/browse/PL-47074)
Adding two RN Summary as requested by engineers:
adding PL-46486 as requested by Sahiba
adding PL-46492 as requested by Nataraja
https://harness.atlassian.net/browse/PL-46485
https://harness.atlassian.net/browse/PL-46492
* *Issue(s)*
[PL-47074]: https://harness.atlassian.net/browse/PL-47074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-47074] Patch for PL 1.24.7 Release Notes

- release-notes/feature-flags.md
> added android 2.0.0 sdk notes

- src/components/Roadmap/data/ciData.ts
> Ci feb roadmap update

- release-notes/delegate.md
> feat: [CDS-91176]: add doc for delegate hotfix 82306

- kb/platform/harness-platform-faqs.md
https://harness.atlassian.net/browse/PL-47596
* *Issue(s)*
> [PL-47596] Cleanup FF PL_IP_ALLOWLIST_NG

- docs/continuous-error-tracking/shared/agent-compatibility.md
- kb/continuous-error-tracking/continuous-error-tracking-faqs.md
- release-notes/continuous-error-tracking.md
> CET Release Notes 5.34.0

- tutorials/self-managed-enterprise-edition/use-an-external-mongodb-database.md
- tutorials/self-managed-enterprise-edition/use-an-external-postgres-database.md
- tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
- tutorials/self-managed-enterprise-edition/use-an-external-self-managed-mongodb.md
- tutorials/self-managed-enterprise-edition/use-an-external-sm-timescaledb.md
- tutorials/self-managed-enterprise-edition/use-aws-elasticache.md
> Update SMP tutorials

- docs/chaos-engineering/technical-reference/probes/cmd-probe.md
- docs/chaos-engineering/technical-reference/probes/http-probe.md
- docs/chaos-engineering/technical-reference/probes/k8s-probe.md
- docs/chaos-engineering/technical-reference/probes/prom-probe.md
[Update http probe](https://65cdb83f22d9657470976465--harness-developer.netlify.app/docs/chaos-engineering/technical-reference/probes/http-probe)
> CHAOS-4287 Update probes

- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-kubernetes.md
> [CCM-16368]: CCM K8S Cost Visibility

- docs/software-engineering-insights/sei-metrics-and-reports/precalculated-reports.md
Added the topic on precalculated reports.
* *Issue(s)*
> [SEI-5665]: ADDED PRECALCULATED REPORTS TOPIC

- docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-sonarqube.md
Added section on usage of usePrivilegedAPIs for SonarQube integrations
* *Issue(s)*
> [SEI-5154]: Document usage of usePrivilegedAPIs for SonarQube integration

- docs/feature-flags/ff-security-compliance/manage-access-control.md
> repairing broken links in access control docs

- src/components/Docs/data/platformData.ts
- tutorials/platform/install-delegate.md
Update install a delegate tutorial
[Install Harness Delegate on Kubernetes or Docker](https://65d12b6328293de324cb9078--harness-developer.netlify.app/tutorials/platform/install-delegate)
* *Issue(s)*
> [PL-47609] Update install a delegate tutorial

- docs/platform/delegates/manage-delegates/auto-scale-using-replicas.md
Update autoscale YAML details
Doc for https://harness.atlassian.net/browse/PL-43686
[Auto scale using replicas](https://65cab6bda9fc21302d9d96df--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/auto-scale-using-replicas)
* *Issue(s)*
> [PL-47027] Update autoscale YAML details

- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md
> fix: [CDS-85765]: add missing info about basic deployment using winrm

- docs/internal-developer-portal/whats-supported.md
Added the info on usage of third party secret managers
* *Issue(s)*
> fix: [IDP-2292]: Added the info on usage of third party secret managers

- docs/software-engineering-insights/sei-metrics-and-reports/velocity-metrics-reports/planning-sprint-metrics.md
Added documentation regarding mid-sprint calculations for the sprint metrics report
* *Issue(s)*
> [SEI-5677]: Added documentation regarding mid-sprint calculations for the sprint metrics report

- release-notes/platform.md
[PL-47012](https://harness.atlassian.net/browse/PL-47012)
https://harness.atlassian.net/wiki/spaces/PD/pages/21650997249/NG+Release+SAAS+February+12th+2024+for+1.25.x-+Build
xBUILD LINK HEREx
https://65d2ee1fb12513d783bdb862--harness-developer.netlify.app/
* *Issue(s)*
[PL-47012]: https://harness.atlassian.net/browse/PL-47012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-47012] PL 1.25.5 Release Notes

- src/components/Docs/data/cloudCostManagementData.ts
> added new tiles

- release-notes/platform.md
add links to delegate rn
* *Issue(s)*
> add links to delegate rn

- docs/platform/pipelines/looping-strategies/additional-matrix-examples.md
> feat:[CDS-92173]: Add matrix example

- kb/continuous-delivery/continuous-delivery-faqs.md
> Addition_of_FAQs[CDS-91917]: Addition of Faqs 17th Feb

- docs/feature-flags/ff-creating-flag/tag_management.md
> tag management doc corections

- release-notes/continuous-delivery.md
CD Release Notes 1.25.x
* *Issue(s)*
> DOC-3976-CD-Release-Notes-1.25.x

- docs/internal-developer-portal/plugins/build-a-frontend-plugin.md
- docs/internal-developer-portal/plugins/on-hold-plugins.md
Added the tutorial to create frontend backstage plugins
* *Issue(s)*
> feat: [IDP-2064]: Added the tutorial to create frontend backstage plugins

- docs/internal-developer-portal/catalog/system-model.md
SEO optimized the system model docs
* *Issue(s)*
> fix: [IDP-2293]: SEO optimized the system model docs

- docs/internal-developer-portal/scorecards/checks-datasources.md
Added the info on supported annotations for k8s datasources
* *Issue(s)*
> fix: [IDP-2304]: Added the info on supported annotations for k8s datasources

- src/components/HomepageFeatures/index.tsx
> fix: make type in tutorial cards optional

- release-notes/chaos-engineering.md
> CHAOS-4369 Release notes 1.31.2

- kb/cloud-cost-management/cloud-cost-management-faqs.md
> chore: [CCM-16239]: Update Governance FAQs

- release-notes/feature-flags.md
> javascript rns updated

- client_module/searchBar.js
- src/css/custom.css
> HDH-226 mobile-search-bar-missing-from-sidebars-with-hierarchy

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> Traffic shifting nit fixes

- docs/chaos-engineering/configure-chaos-experiments/probes/configure-and-add-probe.md
> Fix broken link

- docs/faqs/chaos-engineering-faq.md
- docs/troubleshooting/chaos-engineering/troubleshooting.md
Add troubleshooting guide content related to probe execution
> CHAOS-4165 Add troubleshooting guide content

- release-notes/delegate.md
Delegate hotfix RN 24.02.82308
https://65d6724a55b6e51306ecae22--harness-developer.netlify.app/release-notes/delegate#version-240282308-
* *Issue(s)*
> [cds-91937]: Updated doc for ASG hotfix around healthy pecentage count

- docs/internal-developer-portal/flows/custom-actions.md
Added the docs for dependency projectpickerref
* *Issue(s)*
> feat: [IDP-2329]: Added the docs for dependency projectpickerref

- release-notes/internal-developer-portal.md
Added the IDP release notes for v0.22.0
* *Issue(s)*
> feat: [IDP-2327]:  Added the IDP release notes for v0.22.0

- docs/cloud-cost-management/4-use-ccm-cost-optimization/1-ccm-recommendations/node-pool-recommendations.md
> [CCM-16194] : Added public pricing message for node pool

- docs/cloud-cost-management/4-use-ccm-cost-optimization/1-ccm-recommendations/workload-recommendations.md
> [CCM-16142] 

- docs/feature-flags/manage-featureflags-in-git-repos.md
The original images were set using image tags whicvh had set values on how they should appear which made them appear skewed. 
I used Markdown instead which has repaired the issue.
> images appeared skewed. removed them from img tags

- release-notes/feature-flags.md
> java sdk rns added

- docs/software-supply-chain-assurance/shared/ssca-supported.md
> added TUF & Cosign to SSCA whats supported

- docs/software-supply-chain-assurance/shared/ssca-supported.md
> updating ssca attestation to in-toto

- docs/chaos-engineering/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
> CHAOS-1980 add unsupported items

- docs/internal-developer-portal/catalog/system-model.md
Added the information on entity relations
* *Issue(s)*
> feat: [IDP- 2296]: Added the information on entity relations

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
> [feat]: [CDS-88825]: AWS ASG Docs improvement

- kb/continuous-delivery/continuous-delivery-faqs.md
> Adding_FAQs[CDS-91917]: FAQs for 23rd Feb24

- docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
> feat: [CDS-0]: Argo Upgrade updated

- docs/faqs/chaos-engineering-faq.md
Specify how to avoid overriding images in the manifest
> CHAOS-4157 Update chaos-engineering-faq.md

- release-notes/continuous-delivery.md
> DOC-3985-CD RN 1.26.x

- docs/chaos-engineering/technical-reference/architecture/architecture.md
> CHAOS-4440 Upgrade image versions

- docs/troubleshooting/chaos-engineering/troubleshooting.md
> CHAOS-4154 Update troubleshooting guide

- docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
What
The link to the FF Overview page is broken, this change fixes it
* *Issue(s)*
> [FFM-9537] - Fix FF Java SDK docs broken link

- src/components/Roadmap/data/roadmapData.ts
- src/components/Roadmap/data/sscaData.ts
- src/components/Roadmap/index.tsx
> Add SSCA to Roadmap

- docs/continuous-delivery/deploy-srv-diff-platforms/custom-deployment-tutorial.md
- docs/continuous-delivery/deploy-srv-diff-platforms/integrations/_category_.json
- docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
- [ X] Feature
* *Issue(s)*
- [ X] Tested Locally
> Integration tab gartner

- docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/aws-security-hub-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/zap-scanner-reference.md
> remove legacy configs for scanners with step palettes STO-7187

- docs/platform/role-based-access-control/permissions-reference.md
> fixed topic levels

- src/components/Roadmap/data/idpData.ts
Added the info on SMP to public roadmap
* *Issue(s)*
> feat: [IDP-2349]: Added the info on SMP to public roadmap

- docs/software-supply-chain-assurance/slsa/generate-slsa.md
> Update SLSA docs overview

- docs/feature-flags/add-prerequisites-to-feature-flag.md
There's been a reshuffle on the left nav bar in docs which has caused some stretched images and broken links.
> stretched images and links on doc corrected

- release-notes/platform.md
Update version from 1.26.11 to deployed version, 1.26.14
Update date in frontmatter for RSS feed
* *Issue(s)*
> Update version and date PL RN

- release-notes/delegate.md
Update version from 1.26.11 to deployed version, 1.26.14
Update date in frontmatter for RSS feed
https://monitoring.harness.io/d/ZJD3rKZIz/microservice-version-dashboard?orgId=1&refresh=5m&from=now-5m&to=now
* *Issue(s)*
> Update version and date DEL RN

- docs/continuous-delivery/x-platform-cd-features/cd-steps/run-a-script-on-multiple-target-instances.md
> Clarification on use case of expression

- certifications/instructor-led-training/continuous-delivery.md
> Removed Beta

- docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
> Integrations tab, more details

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
- [X ] Maintenance/Chore
* *Issue(s)*
- [ X] Tested Locally
> Added an important note about rollback in AWS SAM

- src/components/Roadmap/data/ffData.ts
Adding brief roadmap for FF v1.
* *Issue(s)*
> Update ffData.ts Roadmap view for Feature Flags

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> changed language for rollback

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/skip-harness-label-selector-tracking-on-kubernetes-deployments.md
> Added more info related to matchLabels

- docs/software-supply-chain-assurance/get-started/key-concepts.md
- docs/software-supply-chain-assurance/get-started/overview.md
- docs/software-supply-chain-assurance/shared/ssca-supported.md
> Update: SLSA L2 -> L3

- docs/chaos-engineering/configure-chaos-experiments/chaosguard/introduction-to-chaosguard.md
> CHAOS-4466 Update feature flag

- docs/software-engineering-insights/sei-profiles/workflow-profile.md
ADDED JIRA RELEASE STAGE SUB-TOPIC SECTION
* *Issue(s)*
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker.
> [SEI-5808]: ADDED JIRA RELEASE STAGE SUB-TOPIC SECTION

- docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-github-easyonboarding.md
REMOVED WEBHOOK REFERENCE FROM GITHUB 2.0 TOPIC
* *Issue(s)*
> [SEI-5861]: REMOVED WEBHOOK REFERENCE FROM GITHUB 2.0 TOPIC

- docs/chaos-engineering/get-started/powered-by-litmus.md
[updated powered-by-litmus](https://65df0ba35a8a760653f5d541--harness-developer.netlify.app/docs/chaos-engineering/get-started/powered-by-litmus)
> CHAOS-4479 updated powered-by-litmus

- docs/chaos-engineering/ce-on-smp/ce-smp-roadmap.md
- docs/chaos-engineering/ce-onboarding-guide/ce-onboarding-guide.md
- docs/chaos-engineering/ce-onboarding-guide/run-experiments-in-sandbox.md
- docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/create-a-new-dashboard.md
- docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/manage-hub.md
- docs/chaos-engineering/configure-chaos-experiments/chaosguard/chaosguard-concepts.md
- docs/chaos-engineering/configure-chaos-experiments/chaosguard/introduction-to-chaosguard.md
- docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md
- docs/chaos-engineering/get-started/overview.md
- docs/chaos-engineering/get-started/powered-by-litmus.md
- docs/chaos-engineering/integrations/chaos-cd.md
- docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-io-stress.md
- docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
- docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss.md
- docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
- docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop.md
- docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-service-kill.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-cpu-hog-exec.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-dns-error.md
- docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/time-chaos.md
- docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-rate-limit.md
- docs/chaos-engineering/technical-reference/chaos-faults/windows/vmware-windows-blackhole-chaos.md
- docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-blackhole-chaos.md
- docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-cpu-hog.md
- docs/chaos-engineering/technical-reference/chaos-faults/windows/windows-ec2-memory-hog.md
- docs/chaos-engineering/technical-reference/security/introduction.md
- docs/chaos-engineering/technical-reference/security/security-templates/psp.md
> CHAOS-3959 Update dead links

- kb/continuous-delivery/continuous-delivery-faqs.md
- [X ] Maintenance/Chore
* *Issue(s)*
N/A
> FAQ for Blue Green Scale Down Step

- kb/continuous-delivery/articles/pipeline-retry-api.md
Publishing KB for pipeline retry API
> Publishing KB for pipeline retry API

- release-notes/software-engineering-insights.md
ADDED HOTFIX ITEMS FOR 202402.1.1
* *Issue(s)*
> [SEI-5871]: ADDED HOTFIX ITEMS FOR 202402.1.1

- docs/continuous-delivery/gitops/get-started/harness-cd-git-ops-quickstart.md
> added help link to metadata

- docs/code-repository/get-started/key-concepts.md
- docs/code-repository/work-in-repos/keyword-search.md
- docs/code-repository/work-in-repos/semantic-search.md
- docs/platform/harness-aida/aida-code.md
- docs/platform/harness-aida/aida-overview.md
* Semantic search  (under [CODE module](https://65d941ac14504086dc90d689--harness-developer.netlify.app/docs/code-repository/work-in-repos/semantic-search), under [Platform](https://65d941ac14504086dc90d689--harness-developer.netlify.app/docs/platform/harness-aida/aida-code), on [Overview page](https://65d941ac14504086dc90d689--harness-developer.netlify.app/docs/platform/harness-aida/aida-overview))
* IDE plugin (added to[ Overview page](https://65d941ac14504086dc90d689--harness-developer.netlify.app/docs/platform/harness-aida/aida-overview) only for now)
> code and ide with aida

- docs/continuous-delivery/manage-deployments/deployment-logs-and-limitations.md
> Document log limit

- src/components/Docs/ChaosEngineering.tsx
- src/components/Docs/CloudCostManagement.tsx
- src/components/Docs/ContinuousDelivery.tsx
- src/components/Docs/ContinuousErrorTracking.tsx
- src/components/Docs/ContinuousIntegration.tsx
- src/components/Docs/FeatureFlags.tsx
- src/components/Docs/InternalDeveloperPortal.tsx
- src/components/Docs/Platform.tsx
- src/components/Docs/SecurityTestingOrchestration.tsx
- src/components/Docs/SelfManagedEnterpriseEdition.tsx
- src/components/Docs/ServiceReliabilityManagement.tsx
- src/components/Docs/SoftwareEngineeringInsights.tsx
- src/components/Docs/styles.module.scss
>   HDH-231-dark-mode-for-documentaion-page-illustrations

- docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
> Added example for SCCM

- src/components/Roadmap/data/IacmData.ts
- src/components/Roadmap/data/platformData.ts
> Add tags to IaCM roadmap

- docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
This work was to show CD support for GCP OIDC. (Thats a loot of acronyms yeesh)
Most of this task has been done by April for CI! So thanks! 
A Question:
Where do you think I should put a warning that OIDC for GCP doesn't work with Google Cloud Functions?
- [ X] Feature
* *Issue(s)*
- [X ] Tested Locally
> Added CD required roles to GCP connector reference

- src/components/Roadmap/index.tsx
> Adjusted order of Roadmap to match Docs

- src/components/Roadmap/data/ffData.ts
Updating Roadmap with more flag features
* *Issue(s)*
> Updating Roadmap with more flag features

- roadmap/roadmap.md
- src/components/Roadmap/data/IacmData.ts
- src/components/Roadmap/data/aidaData.ts
- src/components/Roadmap/data/ccmData.ts
- src/components/Roadmap/data/cdData.ts
- src/components/Roadmap/data/ceData.ts
- src/components/Roadmap/data/ciData.ts
- src/components/Roadmap/data/codeData.ts
- src/components/Roadmap/data/ffData.ts
- src/components/Roadmap/data/idpData.ts
- src/components/Roadmap/data/platformData.ts
- src/components/Roadmap/data/roadmapData.ts
- src/components/Roadmap/data/seiData.ts
- src/components/Roadmap/data/srmData.ts
- src/components/Roadmap/data/sscaData.ts
- src/components/Roadmap/data/stoData.ts
- src/components/Roadmap/index.tsx
- src/constants.ts
> minor updates to roadmap section

- roadmap/roadmap.md
> fixed missing title on roadmap page

- src/components/Roadmap/data/ceData.ts
> CHAOS-4496 Update ceData.ts

- src/components/Roadmap/data/srmData.ts
[Update release, now, next and later roadmaps](https://65e0622c125a31fc67823288--harness-developer.netlify.app/roadmap/#srm)
> CHAOS-4514 update SRM

- src/components/Roadmap/data/codeData.ts
> added roadmap items for code repository in codeData

- src/components/Roadmap/data/aidaData.ts
> Update AIDA roadmap

- docs/cloud-cost-management/get-started/key-concepts.md
> [CCM-16588]

- src/components/Roadmap/data/aidaData.ts
Fix typos in AIDA Roadmap
* *Issue(s)*
> fix typos - AIDA roadmap

- docs/continuous-error-tracking/shared/agent-compatibility.md
> Add Java 21 support and update dates of release and EOL

- src/components/Roadmap/data/ciData.ts
> ci roadmap delivery estimate change

- src/components/Roadmap/data/aidaData.ts
> fixed dates on aida tiles

- release-notes/delegate.md
(CDS-91534, ZD-54319) Delegate hotfix 24.02.82404
---Preview building now---
* *Issue(s)*
> (CDS-91534, ZD-54319) Delegate hotfix 24.02.82404

- release-notes/delegate.md
> Update for RSS

- docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> Update the correct nexus for docker limit

- docs/harness-cloud-operations/computing-uptime.md
* *Issue(s)*
This is to remove artifact source API response errors from Major/Partial Outage.
**What are these APIs?**
Example: DockerArtifactResource --> Get Builds
These APIs will be used to fetch the images/tags of artifacts to provide IntelliSense in harness UI. If these are down, users can still provide the tags directly in UI / Yaml. 
During deployment phase, respective swimlanes will directly use the 3rd party APIs so deployments will not be blocked.
I propose to remove this from **Major Outage**
> Artifact Source - Update computing-uptime.md

- docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-command-step.md
> feat: [CDS-92895]: improve docs for tanzu command with manifests

- release-notes/delegate.md
(CDS-92300) Delegate hotfix 24.02.82406
* *Issue(s)*
> (CDS-92300) Delegate hotfix 24.02.82406

- docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md
UPDATED ENVIRONMENT SPECIFIC ENDPOINTS FOR CUSTOM INTEGRATIONS
* *Issue(s)*
> [SEI-5882]: UPDATE ENV ENDPOINTS FOR CUSTOM INTEGRATIONS

- docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-rally.md
- release-notes/software-engineering-insights.md
ADDED RELEASE NOTES FOR VERSION 202402.2
* *Issue(s)*
> [SEI-5925]: ADDED RELEASE NOTES FOR VERSION 202402.2

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQ_Addition:[CDS-92653]:FAQs for 2nd MARCH 24

- docs/faqs/chaos-engineering-faq.md
Add FAQ to execute command probe in source mode by passing usr name and pwd as env variables
> CHAOS-3708 Add FAQ

- src/components/University/LandingPage.tsx
> Updated University Landing Page

- docs/software-engineering-insights/get-started/sei-onboarding-guide.md
Modifed the onboarding guide for the SEI module
* *Issue(s)*
> feat: [SEI-5946]: SEI MODULE ONBOARDING GUIDE

- docusaurus.config.js
- src/components/Community/Aspects.tsx
> Patched Slack Join Links

- release-notes/platform.md
- release-notes/self-managed-enterprise-edition.md
[PL-47565](https://harness.atlassian.net/browse/PL-47565)
0.14.1 - https://harness.atlassian.net/wiki/spaces/PD/pages/21654175763/Release+Notes+tickets+for+0.14.0+release
* *Issue(s)*
[PL-47565]: https://harness.atlassian.net/browse/PL-47565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-47565] PL SMP 0.14.1 Release Notes

- release-notes/platform.md
[PL-47879](https://harness.atlassian.net/browse/PL-47879)
https://harness.atlassian.net/wiki/spaces/PD/pages/21673181249/NG+Release+SAAS+February+26th+2024+for+1.27.x-+Build
* *Issue(s)*
[PL-47879]: https://harness.atlassian.net/browse/PL-47879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-47879] PL 1.27.10 Release Note

- release-notes/platform.md
comment out 1.27.10
RN PR was merged before deployment.
* *Issue(s)*
> comment out 1.27.10

- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/sto-images.md
> images more than 3 months old are not supported STO-7231

- release-notes/early-access.md
> Re-add STO / OSV integration to early-access.md

- university/instructor-led-training/continuous-delivery.md
> Updated Day Two

- docs/continuous-integration/development-guides/mlops-with-ci.md
Move video to the bottom of the page for https://developer.harness.io/docs/continuous-integration/development-guides/mlops-with-ci/
> Move video to the bottom of the page.

- docs/software-engineering-insights/sei-technical-reference/trellis-metrics-calculation.md
ADDED SUB-TOPIC FOR TICKET PORTION TRELLIS METRIC
* *Issue(s)*
> [SEI-5755]: ADDED SUB-TOPIC FOR TICKET PORTION TRELLIS METRIC

- release-notes/continuous-delivery.md
Documented CD Release Notes 1.27.x
> CD RN 1.27.x

- release-notes/platform.md
Uncomment 1.27.10 PL RN
[Platform](https://65e64c58d9452412ec84d4a8--harness-developer.netlify.app/release-notes/platform)
* *Issue(s)*
> [PL-47879] Uncomment 1.27.10 PL RN

- release-notes/feature-flags.md
> .net sdk release notes updated

- docs/platform/triggers/triggering-pipelines.md
Add entry to git webhook troubleshooting section, regarding self-hosted git providers. They need to have connectivity to https://app.harness.io in order to successfully deliver webhook events to Harness.
* *Issue(s)*
> Update git webhook triggers troubleshooting section

- docs/platform/get-started/tutorials/_category_.json
> pl tutorials patch

- src/components/University/LandingPage.tsx
- src/components/University/styles.module.scss
* Updated Available Cert Text
* Adjusted min-height to be closer.
* *Issue(s)*
> Updated Available Cert Text

- docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
- docs/internal-developer-portal/plugins/custom-plugins/overview.md
Updated the beta banner for custom plugins
* *Issue(s)*
> fix [IDP] : Updated the beta banner for custom plugins

- release-notes/self-managed-enterprise-edition.md
> comment out SMP 0.14.1 RN

- docs/internal-developer-portal/catalog/yaml-file.md
Added all the example YAMLs for catalog entities
* *Issue(s)*
> feat: [IDP-2406] : Added all the example YAMLs for catalog entities

- docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
> Update cloudinfo region to us-east-1 for SMP

- docs/internal-developer-portal/flows/idp-stage.md
Added info on git connector regarding catalog entity registration
* *Issue(s)*
> fix: [IDP]: Added info on git connector regarding catalog entity registration

- src/components/DocVideo/index.tsx
>  HDH-234-investigate-fix-reject-cookies-one-trust-video-plugin

- release-notes/feature-flags.md
> ios sdk release notes updated

- release-notes/feature-flags.md
> javascript release notes updated

- docs/get-started/shared/gitx-whats-supported.md
- docs/platform/git-experience/gitexp-bidir-sync-setup.md
- docs/platform/git-experience/manage-environments-infra-definitions.md
- docs/platform/git-experience/manage-services-using-git-experience.md
- kb/continuous-delivery/continuous-delivery-faqs.md
> Remove CDS_INFRA_GITX, CDS_SERVICE_GITX, CDS_ENV_GITX from docs

- docs/continuous-delivery/shared/cd-integrations-supported.md
Update SMP exceptions 
https://harness.slack.com/archives/CSL96M7UG/p1709749222297799
* *Issue(s)*
> Update SMP exceptions

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot-deployment.md
- docs/platform/connectors/cloud-providers/add-aws-connector.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
This feature is behind this flag: `CDS_AWS_OIDC_AUTHENTICATION`
* *Issue(s)*
> Added docs on AWS with OIDC.

- release-notes/continuous-delivery.md
> updated version number

- release-notes/feature-flags.md
> javascript sdk notes added

- release-notes/feature-flags.md
> android sdk release notes added.

- release-notes/feature-flags.md
> react sdk 1.9.0 updated

- release-notes/cloud-cost-management.md
> [NEW FORMAT RELEASE NOTES]: CCM

- docs/continuous-delivery/gitops/use-gitops/gitops-pipeline-steps.md
> chore: [CDS-93284]: Updates Documentation on OAuth support

- docs/hdh/hdh-docusaurus-sandbox.md
- release-notes/chaos-engineering.md
- release-notes/cloud-cost-management.md
- release-notes/code-repository.md
- release-notes/continuous-delivery.md
- release-notes/continuous-error-tracking.md
- release-notes/continuous-integration.md
- release-notes/delegate.md
- release-notes/early-access.md
- release-notes/feature-flags.md
- release-notes/internal-developer-portal.md
- release-notes/platform.md
- release-notes/security-testing-orchestration.md
- release-notes/self-managed-enterprise-edition.md
- release-notes/service-reliability-management.md
- release-notes/software-engineering-insights.md
- release-notes/software-supply-chain-assurance.md
- src/components/DocsButton/index.tsx
- university/instructor-led-training/continuous-delivery.md
> Updating Public Cal

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Update SMP install with Helm client version compatibility info
https://65e9f0d52faa5c34fd82b754--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga#helm-client-version-compatibility
* *Issue(s)*
> [PL-48063] Update SMP install with Helm client version compat info

- docs/continuous-delivery/gitops/connect-and-manage/external-secrets-integration.md
> Add Doc on how to use External Secrets. 

- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- university/instructor-led-training/continuous-delivery.md
Updated University Address
* *Issue(s)*
> Updated University Address

- docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md
Remove wistia video
* *Issue(s)*
> [PL-48065] Remove wistia video

- docs/platform/triggers/trigger-pipelines-on-new-helm-chart.md
update for standards, fix typos
* *Issue(s)*
> update for standards, fix typos

- release-notes/internal-developer-portal.md
Added the blogs to the release notes
* *Issue(s)*
> fix: [IDP]: Added the blogs to the release notes

- docs/cloud-cost-management/architechture-diagrams/AutoStopping_for_AWS_EC2.md
- docs/cloud-cost-management/architechture-diagrams/AutoStopping_for_AWS_ECS_and_Auto_Scaling_Groups.md
- docs/cloud-cost-management/architechture-diagrams/AutoStopping_for_Azure_VMs.md
- docs/cloud-cost-management/architechture-diagrams/AutoStopping_for_GCP_VMs_and_Instance_Groups.md
- docs/cloud-cost-management/architechture-diagrams/CCM_SaaS_Architecture.md
- docs/cloud-cost-management/architechture-diagrams/Cloud_Asset_Governance_Architecture.md
- docs/cloud-cost-management/architechture-diagrams/Kubernetes_AutoStopping_Workflow.md
> made images expandable:

- release-notes/cloud-cost-management.md
> updated version from 1.9.1 to 1.9,3

- docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
- docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
Preview links:
- [HQL AppScan scanner reference](https://65e73ecb3b5ee8299d048e80--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference)
- [Scanners supported by STO](https://65e73ecb3b5ee8299d048e80--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#scanners-supported-by-sto)
- [Scanners supported by STO](https://65e73ecb3b5ee8299d048e80--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#scanners-supported-by-sto)
> App scan integration sto 7052

- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- release-notes/security-testing-orchestration.md
Preview links:
- Release notes > [Version 1.83.1](https://65ee584a4ab570d036156d2c--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1831)
- SonarQube scanner reference >  [SonarQube pull-request scan configuration](https://65ee584a4ab570d036156d2c--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference/#sonarqube-pull-request-scan-configuration)
> SonarQube branch/PR scans STO-7251

- docs/self-managed-enterprise-edition/troubleshooting/network-issues.md
Add Redis init error with Istio
https://harness.atlassian.net/browse/PL-47983?focusedCommentId=687338
* *Issue(s)*
> Add Redis initi error with Istio

- docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
> fix broken links in sysdig-scanner-reference.md

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQs:[CDS-92653]: Addition to faqs for 9 March 24

- docs/platform/notifications/add-smtp-configuration.md
https://developer.harness.io/docs/platform/notifications/add-smtp-configuration/#option-send-notifications-for-a-user-group-using-email
JIRA issue to track: https://harness.atlassian.net/browse/PL-48048
Based on [PL-46480](https://harness.atlassian.net/browse/PL-46480)
* *Issue(s)*
[PL-46480]: https://harness.atlassian.net/browse/PL-46480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-48048] adding reference to add multiple emails based on the ticket PL-46480

- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
> add form template explanation snow

- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-kubernetes.md
> [CCM-16626]: updated info

- docs/platform/secrets/add-winrm-keys.md
Add missing WinRM credential steps
[Add WinRM keys](https://65f0671493f1081940916871--harness-developer.netlify.app/docs/platform/secrets/add-winrm-keys)
* *Issue(s)*
> [PL-48153] Add missing WinRM credential steps

- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-aws.md
> [CCM-16676] : updated permissions for auto stopping

- docs/continuous-delivery/shared/cd-integrations-supported.md
> CDS-91990-supported manifest overrides

- docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md
Update topic content, replace Wistia video with text
[Use delegate selectors](https://65f05b0ccb20810b9df39428--harness-developer.netlify.app/docs/platform/delegates/manage-delegates/select-delegates-with-selectors)
* *Issue(s)*
> [PL-48065] Update topic content, replace Wistia video with text

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-v2-summary.md
- docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-quickstart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
- docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
- docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
- docs/first-gen/continuous-delivery/custom-deployments/create-a-custom-deployment.md
- docs/first-gen/continuous-delivery/kubernetes-deployments/override-variables-per-infrastructure-definition.md
- docs/first-gen/continuous-delivery/kubernetes-deployments/use-go-templating-in-kubernetes-manifests.md
- docs/first-gen/continuous-delivery/model-cd-pipeline/expressions/how-to-pass-variables-between-workflows.md
- docs/first-gen/continuous-delivery/model-cd-pipeline/infrastructure-provisioner/provision-infrastructure-without-deploying-to-it.md
- docs/first-gen/continuous-delivery/terraform-category/terraform-dry-run.md
- docs/internal-developer-portal/Troubleshooting/troubleshoot.md
- docs/platform/variables-and-expressions/harness-variables.md
- docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md
- docs/software-engineering-insights/sei-troubleshooting-faqs.md
- docs/troubleshooting/troubleshooting-nextgen.md
- kb/continuous-delivery/continuous-delivery-faqs.md
- Remove dead community links
- Fix curl commands for go template
- Improve presentation of some content on Variables and Expressions page.
- Other minor changes
> Small fixes

- docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md
- docs/platform/get-started/tutorials/install-delegate.md
- docs/platform/shared/delegate-install-k8s-supported-vernos.md
Add supported K8s versions to delegate install
https://65f0b8ed14bf7e3d8607dc44--harness-developer.netlify.app/docs/platform/delegates/install-delegates/overview#prerequisite
https://65f0b8ed14bf7e3d8607dc44--harness-developer.netlify.app/docs/platform/get-started/tutorials/install-delegate#prerequisite
* *Issue(s)*
> [PL-44166] Add supported k8s versions to delegate install

- docs/platform/connectors/cloud-providers/add-tas-connector.md
- release-notes/delegate.md
> Remove CDS_CF_TOKEN_AUTH from docs

- docs/chaos-engineering/chaos-faults/cloud-foundry/cf-app-container-kill.md
- docs/chaos-engineering/chaos-faults/cloud-foundry/cloud-foundry.md
- docs/chaos-engineering/chaos-faults/cloud-foundry/experiments.ts
> Chaos 3803 docs review

- docs/chaos-engineering/chaos-faults/cloud-foundry/cf-app-container-kill.md
- docs/chaos-engineering/chaos-faults/cloud-foundry/cloud-foundry.md
- docs/chaos-engineering/chaos-faults/cloud-foundry/experiments.ts
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/boshDeployment.yaml
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/cfDeploymentPlatform.yaml
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/faultInjectorPort.yaml
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/instanceAffectedPercentage.yaml
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/signal.yaml
- docs/chaos-engineering/chaos-faults/cloud-foundry/static/manifests/cf-app-container-kill/skipSSLValidation.yaml
Adds docs for cf-app-container-kill fault
* *Issue(s)*
> feat: [CHAOS-3803]: Adds docs for cf-app-container-kill fault

- release-notes/internal-developer-portal.md
> fix typo error

- release-notes/chaos-engineering.md
> CHAOS-4557 release notes 1.32.1

- docs/platform/pipelines/harness-yaml-quickstart.md
> feat: [CDS-93402]: Add schema information for services, environment and infrastructure definitions

- release-notes/early-access.md
- release-notes/software-engineering-insights.md
ADDED RELEASE NOTES  FOR SEI RELEASE VERSION 202403.1
* *Issue(s)*
> [SEI-6125]: RELEASE NOTES SEI VERSION 202403.1

- release-notes/software-engineering-insights.md
Fix release notes item for SEI
* *Issue(s)*
> Fix release notes item for SEI

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
- release-notes/delegate.md
> Remove CDS_ECS_BG_VALIDATION from docs

- release-notes/internal-developer-portal.md
fixed the broken links
* *Issue(s)*
> fix [IDP]: fixed the broken links

- release-notes/platform.md
[PL-48012](https://harness.atlassian.net/browse/PL-48012)
https://harness.atlassian.net/wiki/spaces/PD/pages/21684125729/NG+Release+SAAS+March+4th+2024+for+1.28.x-+Build
This is a list of tickets that will be added after discussion with Nataraja - [Click here for the list](https://harness.atlassian.net/issues/?filter=15297&jql=(%22Release_BE_SAAS%5BShort%20text%5D%22%20~%201.28.0%20OR%20%22Release_NG_UI_SAAS%5BShort%20text%5D%22%20~%201.11.0%20OR%20%22RELEASE_UI_SAAS%5BShort%20text%5D%22%20~%201.11.0%20)%20AND%20project%20in%20(Platform)%20AND%20%22Release%20Notes%20Candidate%5BCheckboxes%5D%22%20%3D%20Yes)
https://65f1cb74f269a23ce3288e1a--harness-developer.netlify.app/release-notes/platform#version-12811 …
> [PL-48012] PL 1.28.11 Release Notes

- docs/platform/get-started/subscriptions.md
Remove 'last 30 day' comment from IACM, since it doesn't apply.
* *Issue(s)*
> Update subscriptions.md - changes to IACM description

- docs/platform/get-started/subscriptions.md
Add link to CD Services HDH Page
* *Issue(s)*
> Update subscriptions.md - Add link to CD Services HDH Page

- docs/continuous-delivery/x-platform-cd-features/services/add-inline-manifests-using-file-store.md
> [CDS-88535]: Add notes for creating file store api with different identifier.

- docs/harness-cloud-operations/computing-uptime.md
Reverts harness/developer-hub#5877
> Revert "Update computing-uptime.md"

- docs/platform/pipelines/failure-handling/abort-pipeline.md
* CDS-86459 (Abort Pipeline should be a separate permission)
> Abort Permissions details

- docs/platform/get-started/subscriptions.md
> minor copy edits

- docs/platform/pipelines/failure-handling/resume-pipeline-deployments.md
> feat: [CDS-92860]: update documentation for retry failed pipeline

- release-notes/security-testing-orchestration.md
> Update timestamp, headings

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
> [feat]: [CDS-88012]: Add maximum healthy percentage docs for ASG Instance refresh operation

- docs/platform/pipelines/failure-handling/abort-pipeline.md
- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- kb/cloud-cost-management/cloud-cost-management-faqs.md
- kb/continuous-integration/continuous-integration-faqs.md
- kb/feature-flags/harness-feature-flag-faqs.md
- kb/platform/harness-platform-faqs.md
- kb/platform/pipeline-faq.md
- kb/security-testing-orchestration/security-testing-orchestration-faqs.md
- release-notes/software-engineering-insights.md
Various style/grammar fixes and some small issues to address.
> Grab bag 14 mar 24

- src/components/University/IltCard.tsx
- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/data/iltData.ts
> Minor verbiage tweaks

- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/data/iltData.ts
> Harmonize Coming Soon UX

- docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/stop-pipelines-using-opa.md
> update pipeline example STO-6980

- src/components/University/CertCard.module.scss
- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/styles.module.scss
* *Issue(s)*
- [
] *Optional* Screenshot.
> HDH-233-create-landing-page-for-harness-university

- docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
- docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md
Remove and update apt-get
[Install a delegate with third-party tool custom binaries](https://65f45c01aca90e04897480f1--harness-developer.netlify.app/docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries)
[Install a legacy Kubernetes delegate](https://65f45c01aca90e04897480f1--harness-developer.netlify.app/docs/platform/delegates/install-delegates/install-a-kubernetes-delegate)
* *Issue(s)*
> [PL-48327] Remove and update apt-get

- src/components/Roadmap/data/seiData.ts
> Add BYOK support

- release-notes/feature-flags.md
> android 2.0.2 rns updated

- docs/platform/variables-and-expressions/add-a-variable.md
- docs/platform/variables-and-expressions/expression-v2.md
- docs/platform/variables-and-expressions/harness-variables.md
- docs/platform/variables-and-expressions/runtime-input-usage.md
- docs/platform/variables-and-expressions/runtime-inputs.md
* create separate page for runtime input usage
* Small cleanup of expressions intro - was missing basic usage details
* Sidebar reorg for this section
* small cleanup & missing info for custom variables
> expressions and runtime input clean up

- docs/continuous-delivery/cd-integrations.md
- docs/platform/connectors/monitoring-and-logging-systems/connect-to-monitoring-and-logging-systems.md
> Added Docs for NerdGraph API in New Relic connector

- .github/CODEOWNERS
Updated to the best of my knowledge. Not sure about the ownership of the following: FirstGen Troubleshooting: /docs/category/firstgen-troubleshooting Harness Security FAQs: /docs/faqs/harness-security-faqs Internal Developer Portal FAQs: /docs/faqs/internal-developer-portal
* *Issue(s)*
> Added separate section for FAQs and FirstGen docs

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
> Added Missing feature flag.

- docs/platform/triggers/trigger-deployments-using-custom-triggers.md
> feat: [CDS-92915]: Add executionUrl information in the curl command response

- kb/continuous-delivery/continuous-delivery-faqs.md
> Addition_FAQs[CDS-93887]: Added FAQs for 16th March 24

- release-notes/continuous-delivery.md
> CDS-93925-CD-RN-1.29.x

- release-notes/delegate.md
> Release notes for Delegate HF releae 82505

- docs/platform/governance/audit-trail/audit-streaming.md
WIP Splunk audit streaming
* *Issue(s)*
> [PL-48336] WIP Splunk audit streaming

- docs/faqs/cloud-cost-management-faqs.md
> changed faq

- release-notes/continuous-delivery.md
> added zendisk ticket number to CDS-91335

- release-notes/platform.md
https://harness.atlassian.net/browse/PL-48345
https://harness.atlassian.net/wiki/spaces/PD/pages/21698052126/NG+Release+SAAS+March+12th+2024+for+1.29.x-+Build
* *Issue(s)*
> [PL48345] PL 1.29.6 Release Notes

- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md
> feat: [CDS-93783]: improve pdc dynamic provisioning doc

- docs/software-engineering-insights/get-started/sei-onboarding-guide.md
- docs/software-engineering-insights/sei-supported-platforms.md
* *Issue(s)*
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker.
> [SEI-6156]: UPDATED SELF ONBOARDING GUIDE 

- release-notes/delegate.md
https://harness.atlassian.net/browse/PL-48410
* *Issue(s)*
> [PL-48410] Update delegate RN for CDS specific item

- kb/platform/harness-platform-faqs.md
A broken link was committed and merged, breaking subsequent links. 
* *Issue(s)*
> Hotfix Broken Link

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
SMP Add load balancer details - Ingress ALB, NLB, and ELB
https://65f3994fd1cbb31327c97501--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga#add-a-load-balancer
* *Issue(s)*
> [PL-46482] SMP Add load balancer details - Ingress ALB, NLB, and ELB

- docs/platform/authentication/single-sign-on-saml.md
https://65f91df4735a946a60a90ea5--harness-developer.netlify.app/docs/platform/authentication/single-sign-on-saml#saml-sso-with-keycloak
- [ x ] Maintenance/Chore
* *Issue(s)*
- [ x ] Tested Locally
> Rewrite of Keycloak SSO Integration

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
> [feat:CDS-94239]: remove FF snow update multi from docs

- docs/chaos-engineering/chaos-faults/aws/ec2-network-latency.md
- docs/chaos-engineering/chaos-faults/aws/ec2-network-loss.md
- docs/chaos-engineering/chaos-faults/kubernetes/node/node-network-latency.md
- docs/chaos-engineering/chaos-faults/kubernetes/node/node-network-loss.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-corruption.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-duplication.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-latency.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-loss.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-partition.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-rate-limit.md
- docs/chaos-engineering/chaos-faults/vmware/vmware-network-latency.md
- docs/chaos-engineering/chaos-faults/vmware/vmware-network-loss.md
- docs/chaos-engineering/chaos-faults/vmware/vmware-network-rate-limit.md
- docs/chaos-engineering/chaos-faults/windows/windows-network-blackhole-chaos.md
> CHAOS-4788 Add a note for network faults

- release-notes/feature-flags.md
> flutter sdk release notes updated

- release-notes/feature-flags.md
> python server sdk rns updated

- release-notes/feature-flags.md
> .net sdk 1.6.1 rns added

- kb/continuous-delivery/continuous-delivery-faqs.md
> Remove CDS_CUSTOM_STAGE_WITH_ENV_INFRA FF reference from Docs

- docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/harness-governance-overview.md
https://harness.slack.com/archives/CSL96M7UG/p1710951275659189
* *Issue(s)*
> Remove OPA_PIPELINE_GOVERNANCE FF

- docs/continuous-delivery/get-started/cd-tutorials/helm-chart.md
- kb/continuous-delivery/continuous-delivery-faqs.md
- kb/continuous-integration/continuous-integration-faqs.md
- kb/platform/harness-platform-faqs.md
- kb/platform/pipeline-faq.md
used a google sheet and duplicate-finding formula to find exact matches.
> PL and CD FAQs literal duplicates

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
- docs/first-gen/continuous-delivery/kubernetes-deployments/use-go-templating-in-kubernetes-manifests.md
> CDS-93975-updated Go templating cURL commands

- release-notes/self-managed-enterprise-edition.md
SMP 0.14.4 patch release notes
[Self-Managed Enterprise Edition](https://65fb464e7788091e2aa131ea--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)
* *Issue(s)*
> [PL-48456] SMP 0.14.4 patch release notes

- docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md
UPDATED PAYLOAD FIELD ON CUSTOM CICD INTEGRATION
* *Issue(s)*
> [SEI-6231]: UPDATED PAYLOAD FIELD ON CUSTOM CICD INTEGRATION

- release-notes/software-engineering-insights.md
SEI HOTFIX RELEASE VERSION 202403.1.1
* *Issue(s)*
> [SEI-6235]: SEI HOTFIX RELEASE VERSION 202403.1.1

- release-notes/software-engineering-insights.md
> TYPO FIXED

- docs/internal-developer-portal/get-started/onboarding-guide.md
- docs/internal-developer-portal/whats-supported.md
Added the docs on new git integration
* *Issue(s)*
> feat: [IDP-2219]: Added the docs on new git integration

- docs/cloud-cost-management/3-use-ccm-cost-reporting/2-ccm-cost-categories/1-ccm-cost-categories.md
> [CCM-16585]: updated cost categories

- docs/cloud-cost-management/3-use-ccm-cost-reporting/1-ccm-perspectives/1-create-cost-perspectives.md
- docs/cloud-cost-management/3-use-ccm-cost-reporting/6-use-ccm-dashboards/access-ccm-dashboards.md
> Datascan limit

- release-notes/feature-flags.md
> .net sdk 1.6.0 notes added

- release-notes/feature-flags.md
> node.js rns 1.6.1 added

- release-notes/feature-flags.md
> android sdk 2.1.0 rns added

- release-notes/feature-flags.md
> python 1.6.0 rns added

- release-notes/self-managed-enterprise-edition.md
https://harness.atlassian.net/browse/PL-48459
Added two tickets for the patch of SMP 0.14.5
https://harness.atlassian.net/browse/PL-48373
https://harness.atlassian.net/browse/CDS-94037
* *Issue(s)*
> [PL48459] SMP 0.14.5 Patch Release Notes

- docs/code-repository/config-repos/create-repo.md
- docs/code-repository/config-repos/import-repo.md
- docs/code-repository/config-repos/rules.md
- docs/code-repository/get-started/overview.md
- Illegal strings in repo names
- Link in RBAC information
- Add link to API reference
> CODE - Reserved words, RBAC, API reference

- docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/optimize-sto-pipelines.md
- kb/security-testing-orchestration/security-testing-orchestration-faqs.md
> Add troubleshooting info to BDH/Sonar scanner refs STO-7274

- docs/cloud-cost-management/3-use-ccm-cost-reporting/1-ccm-perspectives/1-create-cost-perspectives.md
- docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> Perspective limits

- docs/chaos-engineering/architecture-and-security/architecture/windows-chaos-infrastructure.md
Update windows chaos infra details
> CHAOS-4803 update windows infra

- release-notes/chaos-engineering.md
> CHAOs-4765 update release notes 1.33.1

- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> [feat: CDS-94393]: removed FF CDS_GET_SERVICENOW_STANDARD_TEMPLATE

- docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
**What**
Update and add table of SDK codes for dotnet
* *Issue(s)*
> FFM-11002 - Adding SDK codes to FF .NET SDK

- release-notes/internal-developer-portal.md
Added the release notes for v0.24.0
* *Issue(s)*
> feat: [IDP-2512]: Added the release notes for v0.24.0

- release-notes/feature-flags.md
> .net sdk 1.6.2 rns added

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> [feat]: [CDS-74808]: updating traffic routing docs with more information

- docs/security-testing-orchestration/sto-techref-category/aws-security-hub-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/fossa-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/metasploit-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nessus-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nexus-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/openvas-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/qualys-web-app-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/qwiet-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/reapsaw-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/scoutsuite-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/tenable-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
> remove DinD snippet from topics that don't need it STO-7308

- docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements-no-dind.md
- docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements.md
- docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_access-id.md
- docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_access-token.md
- docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_domain.md
- docs/security-testing-orchestration/sto-techref-category/xray-scanner-reference.md
- docs/security-testing-orchestration/use-sto/secure-sto-pipelines/add-certs-to-delegate.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/create-custom-scan-images.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/download-images-from-private-registry.md
…add Yarn and PNPM to an OWASP image STO-7230
* *Issue(s)*
> Aubrey tweaks STO-7230

- kb/platform/harness-platform-faqs.md
Added platform and delegate FAQs
> Added platform and delegate FAQs

- docs/platform/get-started/subscriptions.md
updated IACM to say 120 Executions per Year
* *Issue(s)*
> Update subscriptions.md - updated IACM to say 120 Executions per Year

- docs/platform/get-started/subscriptions.md
some visual improvements
* *Issue(s)*
> Update subscriptions.md - some visual improvements

- docs/chaos-engineering/architecture-and-security/security/namespace-considerations.md
Update namespace considerations with 'hce' namespace and service account
> CHAOS-3959 update namespace-considerations

- docs/chaos-engineering/features/probes/cmd-probe-usage.md
- docs/chaos-engineering/features/probes/dynatrace-probe.md
- docs/chaos-engineering/features/probes/http-probe.md
- docs/chaos-engineering/features/resilience-probes/introduction.md
[Dynatrace probes docs](https://65f9264a8e91116de0d8f808--harness-developer.netlify.app/docs/chaos-engineering/features/probes/dynatrace-probe)
> CHAOS-2951 Dynatrace probe docs

- docs/chaos-engineering/troubleshooting/troubleshooting.md
> CHAOS-4328 update troubleshooting

- docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
- docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md
- docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
- docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
- docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
- docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
Add log level to FF Golang SDK codes
* *Issue(s)*
> Go SDK Codes: add level

- docs/chaos-engineering/features/experiments/experiment-using-api.md
> fix: [CHAOS-4695]: Update Chaos API doc link in API tutorial

- release-notes/feature-flags.md
> .net sdk 1.6.3 notes added

- docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> Artifactory: Fixed incorrect details for artifact path filter

- README.md
- docusaurus.config.js
> minor changes

- docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_app-instance.md
- docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_note.md
- release-notes/early-access.md
- release-notes/security-testing-orchestration.md
> remove FF for OSV and Target Auto-Detect STO-7324

- kb/platform/harness-platform-faqs.md
> PL FAQ cleanup

- docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
> move OSV support from SAST to SCA STO-7326

- docs/continuous-delivery/shared/cd-integrations-supported.md
> Unsupported helm v2 bug fix

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQs:[CDS-93887]: FAQs for 22nd March 24

- docs/chaos-engineering/chaos-faults/windows/static/manifests/windows-network-blackhole-chaos/server-host.yaml
- docs/chaos-engineering/chaos-faults/windows/windows-network-blackhole-chaos.md
> chore: [CHAOS-4866]: Add global blackhole chaos tunable docs

- docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-create-auto-stopping-rules/create-autostopping-rules-for-kubernetes.md
> [CCM-16959]: add in line dependencies

- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-kubernetes.md
> [CCM-14124]: fixed docs

- release-notes/feature-flags.md
> added go 0.1.18 rns.

- docs/cloud-cost-management/4-use-ccm-cost-optimization/autostopping-guides/kubernetes-autostopping-quick-start-guide.md
> [CCM-16949]: fixed example for kubernetes autostopping nginx 

- src/components/University/IltCard.tsx
- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/data/iltData.ts
- src/components/University/styles.module.scss
> HDH-239-hdh-ilt-small-improvements

- release-notes/platform.md
https://harness.atlassian.net/browse/PL-48413
https://6602d1908617a72ee26d000b--harness-developer.netlify.app/release-notes/platform#version-1307
* *Issue(s)*
> [PL-48413] PL 1.30.7 Release Notes

- release-notes/delegate.md
https://harness.atlassian.net/browse/PL-48414
https://harness.atlassian.net/wiki/spaces/PD/pages/21705981968/NG+Release+SAAS+March+18th+2024+for+1.30.x-+Build
https://6602d120aa3817364976f8fb--harness-developer.netlify.app/release-notes/delegate#harness-version-1307-harness-delegate-version-240382600-
* *Issue(s)*
> [PL-48414] DEL 82600 Release Notes

- kb/continuous-delivery/articles/configuration-inheritance-stepgroup-step.md
> Added missing feature flag

- release-notes/continuous-delivery.md
> Moved logic changes to early access.

- docs/platform/connectors/artifact-repositories/nexus-connector-settings-reference.md
> fix pl 404

- release-notes/delegate.md
fix 1.30.7 headings, remove whitespace
* *Issue(s)*
> fix 1.30.7 headings, remove whitespace

- docs/continuous-integration/development-guides/ci-python.md
- docs/continuous-integration/development-guides/ci-ruby.md
- docs/continuous-integration/get-started/overview.md
- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
- docs/continuous-integration/use-ci/run-step-settings.md
- docs/continuous-integration/use-ci/run-tests/run-tests-in-ci.md
- docs/continuous-integration/use-ci/run-tests/speed-up-ci-test-pipelines-using-parallelism.md
- docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-python.md
- docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
- docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-test-splitting.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
- docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
- docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
- docs/infra-as-code-management/workspaces/create-workspace.md
- docs/platform/pipelines/pipeline-chaining.md
- docs/security-testing-orchestration/get-started/shared/_why-define-baselines.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/set-up-baselines.md
- kb/continuous-delivery/continuous-delivery-faqs.md
- kb/continuous-integration/continuous-integration-faqs.md
Misc small updates
- CI-11838
- CI-11817
- CI-8389
- CI-10906
- Weekly 404s
> Ci grab bag 26 mar 24

- docs/continuous-delivery/shared/jira-approval-steps.md
- docs/continuous-delivery/shared/servicenow-approval-steps.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/approvals/using-harness-approval-steps-in-cd-stages.md
- docs/platform/variables-and-expressions/harness-variables.md
* [CDS-89280](https://harness.atlassian.net/browse/CDS-89280)
[CDS-89280]: https://harness.atlassian.net/browse/CDS-89280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed <+approval> functor from non-Harness approval topics

- docs/infra-as-code-management/workspaces/provision-workspace.md
> Fix typo in provision-workspace.md

- docusaurus.config.js
- src/components/HomepageUniversity/Carousel.module.scss
> adding_Do_not_sell_or_share_my_personal_information

- docs/feature-flags/ff-creating-flag/tag_management.md
> adding additional line in tagging docs

- release-notes/self-managed-enterprise-edition.md
SMP add 0.14.6 upgrade info
https://66042223faa41f0cda02f035--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#march-26-2024-patch-version-0146
* *Issue(s)*
> [PL-48563] SMP add 0.14.6 upgrade info

- release-notes/feature-flags.md
> added .net 1.6.4 rns

- release-notes/delegate.md
add CDS-93298 to 24.03.82600 RN
https://harness.atlassian.net/browse/CDS-93298?focusedCommentId=699451
* *Issue(s)*
> add CDS-93298 to 24.03.82600 RN

- docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/stop-pipelines-using-opa.md
- release-notes/early-access.md
- release-notes/security-testing-orchestration.md
> new OPA functionality is now GA STO-7344

- src/components/HomepageUniversity/Carousel.module.scss
> Carousel_dot_css_fix

- release-notes/software-engineering-insights.md
ADDED SEI-6245 TO HOTFIX VERSION 3.1.1
* *Issue(s)*
> [SEI-6333] : ADDED SEI-6245 TO HOTFIX VERSION 3.1.1

- docs/internal-developer-portal/scorecards/track-migrations.md
- docs/internal-developer-portal/tutorials/how-to-track-migrations.md
- docusaurus.config.js
- src/components/Community/Aspects.tsx
> Updated Slack Link

- docs/harness-cloud-operations/harness_data_architecture.md
- docs/harness-cloud-operations/harness_ff_architecture.md
- docs/harness-cloud-operations/harness_saas_architecture.md
- docs/harness-cloud-operations/harness_services_architecture.md
- docs/harness-cloud-operations/tenancy.md
> added tenancy page with account migration steps in cloud ops section

- docs/platform/organizations-and-projects/projects-and-organizations.md
> Correct audit trail project scope info

- release-notes/delegate.md
- release-notes/platform.md
Add PL-46976 to PL and DEL RN
https://harness.atlassian.net/browse/PL-48687
https://harness.atlassian.net/browse/PL-46976?focusedCommentId=700607
https://6606c788773f5201575ea287--harness-developer.netlify.app/release-notes/platform#fixed-issues
https://6606c788773f5201575ea287--harness-developer.netlify.app/release-notes/delegate#fixed-issues
* *Issue(s)*
> [PL-48687] Add PL-46976 to PL and DEL RN

- docusaurus.config.js
> Added Roadmap to Top Nav

- docs/cloud-cost-management/ccm-auditing.md
Remove AUDIT_TRAIL_WEB_INTERFACE FF - feature in prod
* *Issue(s)*
> Remove AUDIT_TRAIL_WEB_INTERFACE FF - feature in prod

- package.json
- yarn.lock
Upgrade to DS 3.2.0, will monitor perf. 
* *Issue(s)*
> Upgrade to DS 3.2.0 

- docs/internal-developer-portal/get-started/custom-dashboards.md
Updated the custom dashboard docs with new set of explores and OOTB dashboards
* *Issue(s)*
> feat: [IDP-2560]: Updated the custom dashboard docs with new set of explores and OOTB dashboards

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQs:[CDS-94779]: FAQs for 29th March 24

- docs/service-reliability-management/monitored-service/health-source/loki.md
> fix: [CDS-93365]: Added note for CustomHealth connector in docs

- docs/harness-cloud-operations/harness_ff_architecture.md
- docs/harness-cloud-operations/harness_saas_architecture.md
- docs/harness-cloud-operations/harness_services_architecture.md
> Update SaaS/FF Architecture Image Sizes

- docs/continuous-delivery/cd-infrastructure/aws-cdk.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/git-clone-step.md
- [] Maintenance/Chore
* *Issue(s)*
> Added documentation for user id possible mismatch for git commands

- docs/platform/get-started/key-concepts.md
> update FG EOL/EOS note

- kb/platform/harness-platform-faqs.md
[PL-48716](https://harness.atlassian.net/browse/PL-48716)
* *Issue(s)*
[PL-48716]: https://harness.atlassian.net/browse/PL-48716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PL-48716 - FAQ addition

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
> Remove CDS_ASG_SHIFT_TRAFFIC_STEP_NG from docs

- docs/continuous-delivery/get-started/upgrading/cdng-upgrade-faq.md
> Added Oldgen data retention to FAQ

- docs/continuous-delivery/x-platform-cd-features/cd-steps/step-groups.md
> feat: [CDS-84377]: Add examples of using output variables within step group

- docs/service-reliability-management/srm-whats-supported.md
- release-notes/early-access.md
Early access features are now documented within modules.
> update srm early access for new style

- docs/continuous-delivery/verify/verify-deployments-with-the-verify-step.md
> Remove CV_UI_DISPLAY_FAIL_IF_ANY_CUSTOM_METRIC_IN_NO_ANALYSIS from docs

- docs/internal-developer-portal/dashboard/_category_.json
Fixed the sidebar label for IDP
* *Issue(s)*
> fix: [IDP]: Fixed the sidebar label for IDP

- docs/chaos-engineering/features/probes/datadog-probe.md
> Chaos-3995-review Review

- release-notes/cloud-cost-management.md
added release notes
* *Issue(s)*
> [CCM-17129]: Update cloud-cost-management.md

- docs/internal-developer-portal/catalog/register-software-component.md
- docs/internal-developer-portal/flows/create-a-new-service-using-idp-stage.md
- docs/internal-developer-portal/flows/create-a-service.md
- docs/internal-developer-portal/flows/self-service-onboarding-pipeline-tutorial.md
- docs/internal-developer-portal/flows/service-onboarding-pipelines.md
- docs/internal-developer-portal/get-started/add-api-docs.md
- docs/internal-developer-portal/get-started/add-links-docs.md
- docs/internal-developer-portal/get-started/enable-a-new-plugin.md
- docs/internal-developer-portal/get-started/enable-docs.md
- docs/internal-developer-portal/get-started/register-a-new-software-component.md
- docs/internal-developer-portal/get-started/setup-git-integration.md
- docs/internal-developer-portal/plugins/build-a-frontend-plugin.md
- docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
- docs/internal-developer-portal/roadmap/roadmap.md
- docs/internal-developer-portal/scorecards/scorecard-quickstart.md
- docs/internal-developer-portal/scorecards/track-migrations.md
- docs/internal-developer-portal/tutorials/add-links-in-components.md
- docs/internal-developer-portal/tutorials/how-to-track-migrations.md
- docs/internal-developer-portal/tutorials/opa-scorecards.md
- docs/internal-developer-portal/tutorials/register-component-in-catalog.md
- docs/internal-developer-portal/tutorials/service-onboarding-pipeline.md
- docs/internal-developer-portal/tutorials/service-onboarding-with-idp-stage.md
- docs/internal-developer-portal/tutorials/using-secret-as-an-input.md
Added the tutorial phills
* *Issue(s)*
> fix: [IDP-2577]: Added the tutorial phills

- kb/platform/pipeline-faq.md
> minor copy edit, add link

- .github/issue_template.md
- .github/pull_request_template.md
Thanks for contributing to the Harness Developer Hub! Our code owners will review your PR.
Update the PR template to reflect our current practices.
Also updated the issue template.
Took some inspiration from Datadog's bare bones PR template: https://github.com/DataDog/documentation/blob/master/.github/PULL_REQUEST_TEMPLATE.md 
> New PR and Issue templates

- docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
[PL-48351] Add doc to install the Azure CLI
https://66073448b87aa360004345ea--harness-developer.netlify.app/docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries#install-azure-cli
* *Issue(s)*
[PL-48351]: https://harness.atlassian.net/browse/PL-48351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PL-48351] Add doc to install the Azure CLI

- release-notes/security-testing-orchestration.md
> STO 2024-04-03 releas notes STO-7391

- kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> feat: [CDS-91915]: Add Knowledge base how bidirectional sync prevent github api limit

- release-notes/feature-flags.md
Updating the release notes for .NET SDK 1.6.7. 
> added rns for .net sdk 1.6.7

- release-notes/feature-flags.md
Adding Golang SDK 0.1.19 release notes.
> adding golang sdk 0.1.9 rns

- release-notes/cloud-cost-management.md
> Release 1.11.3 updated notes

- release-notes/delegate.md
Delegate 24.04.82603 Hotfix RN
Preview: https://660eb5a696df2703408f6ad4--harness-developer.netlify.app/release-notes/delegate#version-240482603-
> Delegate 24.04.82603 Hotfix RN

- release-notes/delegate.md
> update date in metadata

- docs/platform/approvals/adding-harness-approval-stages.md
- docs/platform/authentication/authentication-overview.md
- docs/platform/authentication/multiple-identity-providers.md
- docs/platform/certificates/add-custom-certificate.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
- docs/platform/connectors/monitoring-and-logging-systems/connect-to-monitoring-and-logging-systems.md
- docs/platform/delegates/delegate-concepts/delegate-overview.md
- docs/platform/delegates/delegate-concepts/delegate-registration.md
- docs/platform/delegates/delegate-reference/delegate-environment-variables.md
- docs/platform/git-experience/git-settings.md
- docs/platform/governance/audit-trail/audit-streaming.md
- docs/platform/governance/policy-as-code/aida-for-policies.md
- docs/platform/governance/policy-as-code/sample-policy-use-case.md
- docs/platform/governance/policy-as-code/using-policy-enforcement-on-pipeline-steps.md
- docs/platform/monitored-service.md
- docs/platform/pipelines/executions-and-logs/download-logs.md
- docs/platform/pipelines/failure-handling/define-a-failure-strategy-on-stages-and-steps.md
- docs/platform/pipelines/input-sets.md
- docs/platform/role-based-access-control/add-manage-roles.md
- docs/platform/role-based-access-control/manage-dashboards.md
- docs/platform/role-based-access-control/provision-use-jit.md
- docs/platform/templates/create-a-remote-step-template.md
- docs/platform/triggers/trigger-on-a-new-artifact.md
- docs/platform/triggers/trigger-pipelines-on-new-helm-chart.md
- docs/platform/triggers/triggers-overview.md
- docs/platform/triggers/triggers-reference.md
Standardizes the  feature flag note format in PL docs
https://harness.atlassian.net/wiki/spaces/DOCS/pages/21544468526/Harness+documentation+style+guide#Admonitions-(Notes)
> Standardize ff note in PL docs

- src/components/Roadmap/data/platformData.ts
> chore: [CCM-0]: Update platform Roadmap For CCM SMP

- docs/chaos-engineering/features/probes/dynatrace-probe.md
Specify connectivity requirement for Dynatrace probe.
> CHAOS-4975 Update dynatrace-probe.md

- docs/platform/git-experience/gitexp-bidir-sync-setup.md
> fix: [CDS-94325]: Fix Bidirectional sync documentation to avoid confusion

- docs/internal-developer-portal/catalog/custom-catalog-properties.md
Updated the title and sidebar labels for CCP
> fix: [IDP]: Updated the title and sidebar labels for CCP

- docs/chaos-engineering/features/probes/datadog-probe.md
Adds Datadog probe metrics docs
* *Issue(s)*
> chore: [CHAOS-3995]: Adds Datadog probe metrics docs

- release-notes/feature-flags.md
Updating Release Notes for Android SDK 2.1.1. 
> update android sdk 2.1.1 release notes

- docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md
We only support custom headers not payload.
> Remove "payload" from documention

- package.json
- yarn.lock
> Update to DS 3.2.1

- release-notes/cloud-cost-management.md
- release-notes/continuous-error-tracking.md
- release-notes/internal-developer-portal.md
- release-notes/software-engineering-insights.md
> [!IMPORTANT]
> **The date in the metadata triggers the RSS feeds. Our customers subscribe to these to get notified of new releases.**
> **You must update this date every time you publish new release notes.**
> release notes metadata

- docs/platform/variables-and-expressions/harness-variables.md
To add a missing expression to the expression reference. 
CDS-95148
> Add missing expression to reference. (CDS-95148)

- release-notes/security-testing-orchestration.md
> hotfix for 1.90 release STO-7402

- docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
Update delegate YAML samples - add comments
[Example Kubernetes manifest and Helm chart for Harness Delegate](https://660eb91f9a35f5034f75fb05--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate)
> [PL-38188] Update delegate YAML samples - add comments

- docs/chaos-engineering/chaos-faults/aws/aws-iam-integration.md
- docs/chaos-engineering/chaos-faults/gcp/gcp-iam-integration.md
GCP IAM integration
https://660d420f128a30d7d92c63be--harness-developer.netlify.app/docs/chaos-engineering/chaos-faults/gcp/gcp-iam-integration
> CHAOS-4583 GCP IAM integration

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQs:[CDS-94779]:FAQs for 5th April CD

- docs/internal-developer-portal/plugins/available-plugins/github-actions.md
- docs/internal-developer-portal/plugins/available-plugins/github-codespaces.md
Added the docs on github codespaces plugin
> feat: [IDP-2613]: Added the docs on github codespaces plugin

- docs/feature-flags/ff-sdks/server-sdks/php-sdk-reference.md
**What**
PHP doc has some errors around config this fixes those + update links to point to client repo url
> [FFM-11123] - Update Feature Flags PHP SDK document

- .github/pull_request_template.md
> adjusting template

- docs/internal-developer-portal/scorecards/checks-datasources.md
* Please describe your changes: Updated the info for catalog metadata related checks
> fix: [IDP]: Updated the info for catalog metadata related checks

- release-notes/feature-flags.md
Updating  FF Release Notes with PHP SDK Beta 0.2.0 
* Jira/GitHub Issue numbers (if any): \FFM-11165
> adding php beta sdk release notes

- docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> SecureConnect coverage

- release-notes/feature-flags.md
* Please describe your changes: \ adding release notes for golang 0.1.20
* Jira/GitHub Issue numbers (if any): \FFM-11183
> adding release notes for golang 0.1.20

- docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
Correct incorrect yaml in google functions file.
> Fixed yaml to be accurate (hopefully)

- docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.md
> Fix snippet reference in Additional CLI Flags

- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-redis-database.md
* Please describe your changes: fix 404 in Redis external db doc - SMP
* Jira/GitHub Issue numbers (if any): https://harness.slack.com/archives/C012UCJARRN/p1712689256565869
> fix 404 in Redis external db doc - SMP

- kb/platform/harness-platform-faqs.md
> Adding 8 FAQs to our docs

- release-notes/security-testing-orchestration.md
Preview link: [Version 1.90.1](https://66158ffcba6b4f2285c2d09c--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1901)
> BDH step was upgraded to 9.5.0, not 9.0.0

- kb/platform/harness-platform-faqs.md
* Please describe your changes: PL KB FAQ cleanup -  copy edits, remove duplicates, move to applicable categories through line 1311
* Preview links/images (Internal contributors only): [Harness Platform FAQs](https://6615d911ba6b4f5f9ec2d08f--harness-developer.netlify.app/kb/platform/harness-platform-faqs)
> PL KB FAQ cleanup -  copy edits, remove duplicates, move to applicable categories

- release-notes/internal-developer-portal.md
* Please describe your changes: Added the release notes for IDP v0.25.0
> feat: [IDP-2617]: Added the release notes for IDP v0.25.0

- docs/chaos-engineering/get-started/powered-by-litmus.md
[Update fault list and add hyperlinks to chaos fault docs](https://66166548106657110a7f2bdb--harness-developer.netlify.app/docs/chaos-engineering/get-started/powered-by-litmus)
CHAOS-5023
> CHAOS-5023 update powered-by-litmus

- docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
- docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
- docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md
Adds metrics size exceeded SDK codes to .NET, Node and Python
> FFM-11022 Update FF SDK codes

- docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
> update hr link, update yaml file ref for standards

- docs/platform/settings/clock-sychronization.md
- docs/platform/settings/default-settings.md
* Please describe your changes: Add Clock synchronization topic. This topic was previously on the [community.harness.io site](https://web.archive.org/web/20230118133155/https://community.harness.io/t/clock-synchronization-ntp-delegate-or-on-prem-as-per-iso-soc2/899) but was not added to HDH
* Jira/GitHub Issue numbers (if any): PL-48906
* Preview links/images (Internal contributors only):  [Clock synchronization](https://6616d426040b5c1e7cecad51--harness-developer.netlify.app/docs/platform/settings/clock-sychronization) …
> [PL-48906] Clock synchronization

- docs/internal-developer-portal/plugins/available-plugins/github-catalog-discovery.md
* Please describe your changes: Updated the config to remove the unsupported fields for github catalog discovery plugin
> fix: [IDP-2635]: Updated the config to remove the unsupported fields

- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
Preview link: [Additional CLI flags](https://6615d51950609f5a40c235af--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference#additional-cli-flags)
> add -Dsonar.projectName and -Dsonar.projectKey STO-7377

- release-notes/security-testing-orchestration.md
Preview link: [Version 1.92.1](https://661704832e1b4a5c586eb60f--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1921)
> STO 1.92.1 release notes STO-7427

- kb/platform/harness-platform-faqs.md
- kb/platform/pipeline-faq.md
* Please describe your changes: PL KB FAQ cleanup - copy edits, remove duplicates, move to applicable categories from line 1311 to the end of the file
* Preview links/images (Internal contributors only): [Harness Platform FAQs](https://66172b32f1ca3405af56b26c--harness-developer.netlify.app/kb/platform/harness-platform-faqs)
> PL KB FAQ cleanup - copy edits, remove duplicates, move to applicable categories

- docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
Product name is incorrect, should be HCL AppScan not HQL AppScan
> Update HQL to HCL

- docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
Change installation requirements of FF Golang SDK
> FFM-11164 Update Go SDK docs

- kb/platform/harness-platform-faqs.md
* Please describe your changes: fix link format
> fix link format

- docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md
* Please describe your changes: \ Updating the React Native Docs 
* Jira/GitHub Issue numbers (if any): \ FFM-11208
> updating react native sdk docs

- docs/internal-developer-portal/catalog/ccp-for-workflows.md
- docs/internal-developer-portal/catalog/custom-catalog-properties.md
* Please describe your changes: Added the videos to the docs
> feat: [IDP-2642]: Added the videos to the docs

- docs/code-repository/config-repos/delete-repo.md
- docs/code-repository/config-repos/security.md
- docs/code-repository/config-repos/webhooks.md
- docs/platform/governance/policy-as-code/harness-governance-overview.md
- docs/platform/governance/policy-as-code/harness-governance-quickstart.md
- docs/platform/governance/policy-as-code/using-harness-policy-engine-for-feature-flags.md
- docs/platform/governance/policy-as-code/using-policy-enforcement-on-pipeline-steps.md
- release-notes/code-repository.md
* Please describe your changes: added Enable Security to code repository documentation
> adding security documentations for code repository

- docs/continuous-integration/migration-guides/migration-utility.md
* Please describe your changes: Add a small topic about the migration utility
* Jira/GitHub Issue numbers (if any): n/a
> add migration utility topic

- release-notes/feature-flags.md
* Please describe your changes: \ Updating Javascript SDK notes.
* Jira/GitHub Issue numbers (if any): \ FFM-11200
> added javascript sdk rns

- docs/continuous-integration/shared/docker-hub-rate-limiting-trbs.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
- docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
* Please describe your changes: Add ECR container registry option for Harness images. Fix GCR option information. Remove misleading and unnecessary screenshot. Add tip about anonymous access with GCR/ECR options.
* Jira/GitHub Issue numbers (if any): CI-12007
* Preview links/images (Internal contributors only): [Harness CI images](https://66182fc39359cb0f6e606278--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci) / [Connect to the Harness container image registry](https://66182fc39359cb0f6e606278--harness-developer.netlify.app/docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector …
> ci-12007 - Harness Container Image Registry

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: SMP - update release vernos in RN
> SMP - update release vernos in RN

- release-notes/feature-flags.md
* Please describe your changes: \ Adding Node.js Release Notes. 
* Jira/GitHub Issue numbers (if any): \ FFM-11214
> added node.js 1.7.0 rns

- client_module/iframeEmbed.js
- client_module/searchBar.js
- docusaurus.config.js
- src/pages/index.tsx
* Please describe your changes: \_Adding New Client Module for Iframe embedding_________________________________
* Jira/GitHub Issue numbers (if any): \_________HDH 243_____________________
* Preview links/images (Internal contributors only): \__________
________
>  HDH-243-investigate-an-emebed-mode-e-g-pass-a-request-parameter-to-hdh

- release-notes/feature-flags.md
* Please describe your changes: \ Release Notes for ff-android-client-sdk 2.2.0
* Jira/GitHub Issue numbers (if any): \ FFM-11225
> added android sdk 2.2.0 rns

- docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md
* Please describe your changes: \ typo impacting rendering
* Jira/GitHub Issue numbers (if any): \ FFM-11208
> correcting typo

- docs/hdh/hdh-docusaurus-sandbox.md
> Update Sandbox to have Embed

- release-notes/delegate.md
* Please describe your changes: 24.04.82705
* Jira/GitHub Issue numbers (if any): CDS-95510
* Preview links/images (Internal contributors only): https://6617f2088b99841ea0016b76--harness-developer.netlify.app/release-notes/delegate#version-240482705-
> [fix]: [CDS-95510]: Delegate Hotfix 82705

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQS:[CDS-95478]: Adding FAQS for CD Kb 12th April24

- docs/continuous-delivery/x-platform-cd-features/cd-steps/step-groups.md
* Please describe your changes: \ A community member pointed out a docs inconsistency; do we support nested step groups? 
- [ X] Code owner review.
> Fix technical docs error about step group nesting

- docs/chaos-engineering/chaos-faults/linux/linux-network-corruption.md
- docs/chaos-engineering/chaos-faults/linux/linux-network-duplication.md
- docs/chaos-engineering/chaos-faults/linux/linux-network-latency.md
- docs/chaos-engineering/chaos-faults/linux/linux-network-loss.md
- docs/chaos-engineering/chaos-faults/linux/linux-network-rate-limit.md
> Docs review

- docs/software-supply-chain-assurance/artifact-view.md
> Document Tab view in Artifact view

- docs/internal-developer-portal/flows/service-onboarding-pipelines.md
* Please describe your changes:  Added the input examples for templates
> feat: [IDP-2661]: Added the input examples for templates

- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-mongodb-database.md
- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-postgres-database.md
- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-redis-database.md
- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-self-managed-mongodb.md
- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-an-external-sm-timescaledb.md
- docs/self-managed-enterprise-edition/advanced-configurations/external-db/use-self-managed-minio-object-storage.md
- docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md
- docs/self-managed-enterprise-edition/advanced-configurations/use-external-secrets-for-license-values.md
- docs/self-managed-enterprise-edition/back-up-and-restore-helm.md
- docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md
- docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md
- docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-self-managed-add-ingress-controller-service-annotations.md
- docs/self-managed-enterprise-edition/get-started/onboarding-guide.md
- docs/self-managed-enterprise-edition/monitor-harness-on-prem.md
- docs/self-managed-enterprise-edition/performance-reports.md
- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-openshift.md
- docs/self-managed-enterprise-edition/self-managed-helm-based-install/uninstall-helm-chart.md
- docs/self-managed-enterprise-edition/self-managed-helm-based-install/upgrade-helm-chart.md
- docs/self-managed-enterprise-edition/support-bundle-utility.md
- docs/self-managed-enterprise-edition/troubleshooting/check-mongodb-health.md
- docs/self-managed-enterprise-edition/troubleshooting/helm-upgrade-failure.md
- docs/self-managed-enterprise-edition/troubleshooting/license-issues.md
- docs/self-managed-enterprise-edition/troubleshooting/network-issues.md
- docs/self-managed-enterprise-edition/troubleshooting/quick-reference-to-commands.md
* Please describe your changes: SMP docs - remove ws and grem
> SMP docs - remove ws and grem

- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/data/iltData.ts
- src/components/University/data/sptData.ts
> Added SPT to HDH

- release-notes/platform.md
[PL-48750](https://harness.atlassian.net/browse/PL-48750)
https://harness.atlassian.net/wiki/spaces/PD/pages/21724594239/NG+Release+SAAS+April+1st+2024+for+1.32.x-+Build
https://harness.atlassian.net/wiki/spaces/PD/pages/21734916118/NG+Release+SAAS+April+5th+2024+for+1.33.x-+Build
https://661e990773bf9134b0b434c6--harness-developer.netlify.app/release-notes/platform#version-1335
[PL-48750]: https://harness.atlassian.net/browse/PL-48750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
> [PL-48750] PL 1.33.x Release Notes

- docs/chaos-engineering/get-started/hce-onboarding.md
- docs/chaos-engineering/get-started/overview.md
- docs/chaos-engineering/get-started/tutorials/first-chaos-engineering.md
> Grammar check

- docs/feature-flags/ff-creating-flag/manage-variations.md
* Jira/GitHub Issue numbers (if any):  FFM-11258
> [FFM-11258] Fixing feature flag doc

- release-notes/feature-flags.md
* Please describe your changes: Updated Release Notes for JavaScript 1.26.1
* Jira/GitHub Issue numbers (if any): FFM-11248
> release notes for javascript sdk 1.26.1

- docs/platform/git-experience/oauth-integration.md
> fix: [PIPE-18425]: Add in GitEx documentation that we don't support Oauth for Azure repos

- client_module/iframeEmbed.js
> HDH-243 Hide Cookie Notice in Embed mode

- docs/platform/references/tags-reference.md
> fix: [CDS-87692]: Add in docs that we support expressions in tags

- docs/platform/variables-and-expressions/harness-variables.md
* Please describe your changes: \Added missing expression
> added missing org identifier expression

- release-notes/security-testing-orchestration.md
Adding some tickets that got missed b/c they were updated after the publish date. Also includes some corrections and grammer tweaks. 
Preview link: [Security Testing Orchestration release notes](https://66203e48ac0328a4ac1fb3d0--harness-developer.netlify.app/release-notes/security-testing-orchestration)
> STO release notes - misc updates/fixes STO-7313

- src/css/custom.css
>  HDH-245-tab-color-in-dark-mode-detals-sections

- docs/chaos-engineering/certifications/run-experiments-in-sandbox.md
> fix rendering

- src/components/HomepageUniversity/data/universityData.ts
> Added ILT for CI

- docs/feature-flags/ff-creating-flag/manage-variations.md
* Please describe your changes: \ fixing skewed images on doc.
* Jira/GitHub Issue numbers (if any): \ FFM-11258
* Preview links/images (Internal contributors only): \ 
> edit img tags

- docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
* Please describe your changes: Update to Ruby for TI pipeline to update testGlobs pattern
> Update testGlobs pattern.

- docs/platform/delegates/delegate-concepts/delegate-image-types.md
* Please describe your changes: Delegate image doc - add arch info
* Jira/GitHub Issue numbers (if any): PL-49150
* Preview links/images (Internal contributors only): [Delegate image types](https://662167643721d609e73dc432--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-image-types)
> [PL-49150] Delegate image doc - add arch info

- docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
* Please describe your changes: Update SMP K8s supported versions
* Jira/GitHub Issue numbers (if any): PL-49112
* Preview links/images (Internal contributors only): [Supported Kubernetes versions](https://66214e5eddf022125f430e6f--harness-developer.netlify.app/docs/self-managed-enterprise-edition/smp-supported-platforms#supported-kubernetes-versions)
> [PL-49112] Update SMP K8s supported versions

- docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> Commitment orch beta label and AWS EC2 mention

- docs/cloud-cost-management/shared/ccm-supported-platforms.md
> Updated CCM what's supported section to mention commitment orch beta instead of coming soon

- docs/platform/get-started/subscriptions-licenses/subscriptions.md
> Update subscriptions.md - Updated Developer definition

- docs/chaos-engineering/features/chaosguard/chaosguard-concepts.md
- docs/chaos-engineering/features/chaosguard/configuring-chaosguard.md
Implement peer review on CHAOS-5172
> peer review of CHAOS-5172

- docs/continuous-delivery/gitops/get-started/harness-cd-git-ops-quickstart.md
* Please describe your changes: Adding instructions how to set mTLS for GitOps Agent
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CDS-93470
> feat: [CDS-93909]: Add docs for GitOps Agent mTLS

- docs/continuous-delivery/x-platform-cd-features/cd-steps/step-groups.md
> added redirect

- docs/software-supply-chain-assurance/get-started/overview.md
- docs/software-supply-chain-assurance/ssca-supported.md
- src/components/Docs/SoftwareSupplyChainAssurance.tsx
> Add Limited GA pill to Harness SSCA

- docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
- [Checkmarx scanner reference](https://6621d2033721d660453dbbb5--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference) - updated the intro
- [Supported Checkmarx workflows](https://6621d2033721d660453dbbb5--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference#supported-checkmarx-workflows)
> add detailed support info for Checkmarx STO-7419

- docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
> Fixed docs errors, gaps relating terraform

- docs/continuous-delivery/manage-deployments/rollback-deployments.md
- kb/continuous-delivery/continuous-delivery-faqs.md
- release-notes/continuous-delivery.md
- release-notes/self-managed-enterprise-edition.md
> remove post prod rollback FF mentions

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
* Please describe your changes: SMP Add vanity URL script
* Jira/GitHub Issue numbers (if any): PL-49173
* Preview links/images (Internal contributors only): [Configure a vanity URL based on your load balancer](https://6626863f47045708c19113c1--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga#optional-configure-a-vanity-url-based-on-your-load-balancer)
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOW …
> [PL-49173] SMP Add vanity URL script

- docs/continuous-integration/secure-ci/secure-connect.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
* Please describe your changes: Hide an unreleased FF. Add permissions for secure connect API key.
* Jira/GitHub Issue numbers (if any): CI-12133
* Preview links/images (Internal contributors only): *building*
> Ci grab bag 23 apr 24

- release-notes/platform.md
[PL-49108](https://harness.atlassian.net/browse/PL-49108)
https://harness.atlassian.net/wiki/spaces/PD/pages/21749825690/NG+Release+SAAS+April+15th+2024+for+1.34.x-+Build
[PL-49108]: https://harness.atlassian.net/browse/PL-49108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> [PL-49108] PL 1.34.x Release Notes

- release-notes/delegate.md
* Please describe your changes: remove upcoming important changes from del RN https://harness.slack.com/archives/C06FDKGFV1U/p1713830510916069?thread_ts=1713782480.523249&cid=C06FDKGFV1U
* Preview links/images (Internal contributors only): [Delegate RN](https://6626feab65330c5f8efed51b--harness-developer.netlify.app/release-notes/delegate)
PRs must meet these requirements …
> remove upcoming important changes from del RN

- release-notes/platform.md
> fix delegate version numbers for 1.33.5 release

- release-notes/chaos-engineering.md
[Preview](https://6618ba9f81bac580d29e4937--harness-developer.netlify.app/release-notes/chaos-engineering)
- Release notes 1.35.0
- Fixed previous release notes typos
- Removed unnecessary whitespaces
> CHAOS-5040 Release notes 1.35.0

- docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> new changes

- release-notes/infrastucture-as-code-management.md
- src/components/ReleaseNotes/data/releaseNotesData.ts
IACM's first release notes entry. Previous entries will be backfilled about 6-8 weeks after the first entry approval.
JIRA: [IAC-1786](https://harness.atlassian.net/browse/IAC-1786)
[IAC-1786]: https://harness.atlassian.net/browse/IAC-1786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [IAC-1786] IAC 0.181.0 Release Notes

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: Update MinIO backup instructions in SMP RN
> Update minio backup instructions in self-managed-enterprise-edition.md

- release-notes/delegate.md
- release-notes/platform.md
[PL-49109](https://harness.atlassian.net/browse/PL-49109)
https://harness.atlassian.net/wiki/spaces/PD/pages/21749825690/NG+Release+SAAS+April+15th+2024+for+1.34.x-+Build#NG-Delegate-dependent-changes--
* Please describe your changes: Delegate version 24.04.82804
* Jira/GitHub Issue numbers (if any): PL-49109
* Preview links/images (Internal contributors only): [Delegate RN](https://66290aaae6191e1e595736f8--harness-developer.netlify.app/release-notes/delegate)
[PL-49109]: …
> [PL-49109] DEL 82800 Release Notes

- release-notes/infrastucture-as-code-management.md
* Back filling release for IACM into March 2024
* JIRA: [IAC-1830](https://harness.atlassian.net/browse/IAC-1830)
[IAC-1830]: https://harness.atlassian.net/browse/IAC-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: [IAC-1830]: IACM release notes (versions 0.175.0, 0.176.0 & 0.178.0)

- docs/chaos-engineering/architecture-and-security/architecture/components.md
- docs/chaos-engineering/architecture-and-security/architecture/control-plane.md
- docs/chaos-engineering/architecture-and-security/architecture/execution-plane.md
Add re-directs to fix broken links
> add redirects

- docs/hdh/hdh-docusaurus-sandbox.md
> Updated Sandbox with SetFocus Feature

- release-notes/delegate.md
- release-notes/platform.md
* Please describe your changes: Sync PL-47920 in PL and delegate RN
[PL RN](https://662a6ad16b4658c55828d8e3--harness-developer.netlify.app/release-notes/platform#new-features-and-enhancements)
[Delegate RN](https://662a6ad16b4658c55828d8e3--harness-developer.netlify.app/release-notes/delegate#harness-version-1335-harness-delegate-version-240482707-) …
> Sync PL-47920 in PL and delegate RN

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
* Please describe your changes: Add example command - configure vanity URL SMP
* Jira/GitHub Issue numbers (if any): PL-49252
* Preview links/images (Internal contributors only): https://662818cd48d20b07be4d1a4d--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga#optional-configure-a-vanity-url-based-on-your-load-balancer
PRs must …
> [PL-49252] Add example command - configure vanity URL

- docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md
Update documentation with new theme based custom-cicd endpoint
> fix: [SEI-6375]: Update documentation with new theme based custom-cicd endpoint

- docs/self-managed-enterprise-edition/performance-reports.md
* Please describe your changes: Add SMP perf reports, update topic content
* Jira/GitHub Issue numbers (if any): PL-46424
* Preview links/images (Internal contributors only): [Performance test reports](https://66219c43251134395b8ac741--harness-developer.netlify.app/docs/self-managed-enterprise-edition/performance-reports)
> [PL-46424] Add SMP perf reports, update topic content

- docs/platform/pipelines/looping-strategies/additional-matrix-examples.md
> fix matrix example

- docs/continuous-delivery/x-platform-cd-features/executions/step-failure-strategy-settings.md
> feat:[PIPE-18485]: Add new failure strategy Proceed with default values

- docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
- docs/platform/connectors/code-repositories/connect-to-code-repo.md
- docs/platform/connectors/code-repositories/git-hub-app-support.md
- docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
* GH connector - Recommend GH App for authentication
* Local runner build infrastructure - MSI option for Windows platform runner
* Jira/GitHub Issue numbers (if any): CI-11959
* GH connector settings - Authentication - GH App recommended: https://662a95aca2195724f73fd3c8--harness-developer.netlify.app/docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference#authentication
* Local runner install as process or service: https://662a95aca2195724f73fd3c8--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-bu …
> Recommend GH app for GH connector; MSI support for Local Runner Build Infra

- docs/self-managed-enterprise-edition/performance-reports.md
> move content to the intro

- docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
> Update app.harness registry to EOL

- release-notes/infrastucture-as-code-management.md
* Backfilling IACM release notes to for February 2024
* Jira: [IAC-1847](https://harness.atlassian.net/browse/IAC-1847)
[IAC-1847]: https://harness.atlassian.net/browse/IAC-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: [IAC-1847]: IAC 0.152.0 Release Notes

- release-notes/feature-flags.md
* Please describe your changes: \ golang sdk release notes added. 
* Jira/GitHub Issue numbers (if any): \   FFM--11297
> golang sdk 0.1.21 rns added

- .github/CODEOWNERS
* Updating CONTRIBUTORS IACM user @richardblack-Harness 
* Jira: [IAC-1848](https://harness.atlassian.net/browse/IAC-1848)
[IAC-1848]: https://harness.atlassian.net/browse/IAC-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: [IAC-1848] Add richardblack-Harness as IACM contributor

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
* Please describe your changes: Update SMP install with ingress controller info
* Jira/GitHub Issue numbers (if any): PL-46995
* Preview links/images (Internal contributors only): [Add a load balancer](https://662aac0ec66abc318d703fa8--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga#add-a-load-balancer) …
> [PL-46995] Update SMP install with ingress controller info

- docs/service-reliability-management/monitored-service/health-source/azurelogs.md
* Please describe your changes: \Instructions for Azure health source
> Added steps on how to find values for Azure health source

- kb/continuous-delivery/continuous-delivery-faqs.md
> FAQ on how stats are calculated.

- docs/platform/delegates/delegate-concepts/delegate-overview.md
- docs/platform/delegates/delegate-reference/common-delegate-profile-scripts.md
- docs/platform/delegates/delegate-reference/delegate-environment-variables.md
- docs/platform/delegates/delegate-reference/docker-delegate-environment-variables.md
- docs/platform/delegates/install-delegates/build-custom-delegate-images-with-third-party-tools.md
- docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
- docs/platform/delegates/install-delegates/docker-delegate-to-ecs-fargate.md
- docs/platform/delegates/install-delegates/enable-root-user-privileges-to-add-custom-binaries.md
- docs/platform/delegates/install-delegates/gke-workload-identity.md
- docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md
- docs/platform/delegates/install-delegates/overview.md
- docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile.md
- docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md
- docs/platform/delegates/secure-delegates/delegate-mtls-support.md
- docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
- docs/platform/delegates/secure-delegates/secure-delegates-with-tokens.md
- docs/platform/delegates/secure-delegates/trust-store-override-for-delegates.md
* Please describe your changes: fix typos, formatting, etc delegate docs
> fix typos, formatting, etc delegate docs

- docs/platform/triggers/triggering-pipelines.md
* Please describe your changes: \ Added troubleshooting info based on customer error. 
> Added troubleshooting for OAuth with git.

- .github/CODEOWNERS
> add: [BT-7848]: Update CODEOWNERS

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
- docs/continuous-delivery/x-platform-cd-features/environments/create-environments.md
Clean up the following FFs from HDH:
CDS_FIX_RETRY_FAILED_PIPELINE_WITH_USE_SERVICES_FROM_STAGE
CDC_SERVICE_DASHBOARD_REVAMP_NG
CDS_HTTP_STEP_NG_CERTIFICATE
CDS_SUPPORT_DIFFERENT_INFRA_DURING_ENV_PROPAGATION
> FF cleanup

- docs/continuous-delivery/manage-deployments/rollback-deployments.md
> fix:[CDS-89531]: Update rollback deployment doc with a limitation

- release-notes/continuous-delivery.md
> fixed a format issue

- docs/continuous-delivery/cd-integrations.md
- docs/platform/connectors/cloud-providers/add-aws-connector.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
- kb/continuous-delivery/continuous-delivery-faqs.md
* Please describe your changes: Add Harness OIDC provider endpoint and OIDC audience settings
* Jira/GitHub Issue numbers (if any): PL-49125
* [AWS](https://662afbd11170693bf81f2e67--harness-developer.netlify.app/docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference)
* [GCP](https://662afbd11170693bf81f2e67--harness-developer.netlify.app/docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference) …
> [PL-49125] Add Harness OIDC provider endpoint and OIDC audience settings

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
> fix:[CDS-95390]: Add info regarding export KUBECONFIG

- docs/internal-developer-portal/catalog/custom-catalog-properties.md
* Please describe your changes: Updated the metadata ingestion API docs with mandatory fields
> [IDP-2714]: Updated the metadata ingestion API docs with mandatory fields

- docs/chaos-engineering/get-started/powered-by-litmus.md
> CHAOS-5287 Update hce versus litmus

- docs/chaos-engineering/get-started/tutorials/prerequisites.md
> CHAOS-5241 Update prerequisites.md

- docs/infra-as-code-management/get-started/overview.md
* Update IaCM overview description highlighting that we currently support Terraform and OpenTofu, also made common issue points bold.
* [JIRA](https://harness.atlassian.net/browse/IAC-1870)
> docs: [IAC-1870]: Update overview doc description

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-patch-step.md
https://harness.atlassian.net/browse/CDS-92138
Added a new topic in the CD documentation for Kubernetes Patch step
> CDS-92138 K8s Patch Step

- kb/platform/harness-platform-faqs.md
> delegate scope info

- docs/continuous-integration/secure-ci/configure-oidc-gcp-wif-ci-hosted.md
- docs/continuous-integration/secure-ci/secure-connect.md
- docs/platform/connectors/cloud-providers/add-aws-connector.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
- kb/continuous-delivery/continuous-delivery-faqs.md
* Please describe your changes: Delegate version required for OIDC added to 3 connector topics. Misc other updates discovered when looking at other mentions of OIDC.
* Jira/GitHub Issue numbers (if any): PL-50559
> oidc delegate version and misc changes

- docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
* Please describe your changes: \_Cleaned up YAML that was not spaced correctly and added information about where the YAML is to be inserted
* Preview links/images (Internal contributors only): [Install delegates with custom certificates](https://66312e24d6b8e0009df4cfb9--harness-developer.netlify.app/docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs) …
> cleaned up YAML spacing and related items

- docs/faqs/cloud-cost-management-faqs.md
> [DOC-3983]

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-patch-step.md
* Please describe your changes: Update delegate verno info
> Update delegate verno info

- .github/CODEOWNERS
* Please describe your changes: Update CI and CODE codeowners
* Jira/GitHub Issue numbers (if any): n/a
* Preview links/images (Internal contributors only): n/a
> update CI and CODE codeowners

- kb/continuous-delivery/continuous-delivery-faqs.md
- kb/platform/harness-platform-faqs.md
amit q1 faq contribution
All faq contribution for q1 fy25
amit q1 faq contribution
> amit q1 faq contribution

- docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/add-bg-with-configurable-amount-of-tanzu.md
- docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
> Tas doc improvement

- docs/infra-as-code-management/workspaces/pr-automation.md
* Update IACM PR-Automation doc to highlight that we also support OPA
* [JIRA](https://harness.atlassian.net/browse/IAC-1885)
> docs: [IAC-1885]: Update pr-automation doc to highlight OPA support with IACM

- docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md
* Please describe your changes: Removed FF React Native v1 details
* Jira/GitHub Issue numbers (if any): FFM-11423
> Remove FF React Native SDK v1 details

- yarn.lock
postcss-modules-local-by-default  4.0.5
> Updated Yarn Lock for postcss-modules-local-by-default

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: SMP 0.14.7 patch RN
* Jira/GitHub Issue numbers (if any): PL-50695
* Preview links/images (Internal contributors only): preview building
> [PL-50695] SMP 0.14.7 patch RN

- docs/platform/governance/policy-as-code/configure-gitexperience-for-opa.md
* Please describe your changes: \ Gitlab is not supported for OPA
- [] Code owner review.
> Remove unsupport git provider

- package.json
- yarn.lock
> DS 3.3.0 Upgrade

- docs/platform/variables-and-expressions/harness-variables.md
https://harness.slack.com/archives/C04SV4386Q7/p1714737979702659?thread_ts=1714656997.582069&cid=C04SV4386Q7
> added expression for TAS

- src/components/Roadmap/data/cdData.ts
- src/components/Roadmap/data/platformData.ts
* Please describe your changes: \ Updated Next portion of roadmap. 
- [] Code owner review.
> Roadmap q2 update

- docs/security-testing-orchestration/use-sto/shared/sto-aida-notes-partial.md
- [Important notes for AI-enhanced remediations in STO](https://66352c42a93f24332fcbe67f--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/view-and-troubleshoot-vulnerabilities/ai-based-remediations#important-notes-for-ai-enhanced-remediations-in-sto)
> update AI important notes STO-7536

- docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
> Remove sentence fragment

- docs/internal-developer-portal/plugins/available-plugins/github-catalog-discovery.md
* Please describe your changes: Added the docs on scripts for github discovery plugin
> feat: [IDP-2690]: Added the docs on scripts for github discovery plugin

- release-notes/continuous-delivery.md
https://harness.atlassian.net/wiki/spaces/PD/pages/21768012211/NG+Release+SAAS+April+29th+2024+for+1.36.x-+Build
> CD 1.36.x Release Notes

- docs/cloud-cost-management/get-started/ccm-smp/1-smp-ccm-roadmap.md
- docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
- docs/cloud-cost-management/get-started/ccm-smp/gcp-smp.md
- docs/cloud-cost-management/shared/ccm-supported-platforms.md
> Updated docs for SMP feature availability

- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> fixed a note format

- src/css/custom.css
> FIX : [HDH 248] investigate-new-build-warning

- src/components/HomepageUniversity/data/universityData.ts
- src/components/University/data/iltData.ts
> Added STO ILT

- docs/internal-developer-portal/flows/create-a-service.md
* Please describe your changes:  Updated the links in workflows tutorial
> fix: [IDP]: Updated the links in workflows tutorial

- release-notes/platform.md
https://harness.slack.com/archives/C04R4UDE1FT/p1714972253677999 cc @saifeemustafaqharness 
You can find the delegate version that we will deploy (in this case 24.04.82901) when the PL deployment is announced in the #prod-announce Slack channel.
* Please describe your changes: Correct the delegate version in PL RN
PRs must meet …
> Correct the delegate version in PL RN

- docs/platform/get-started/subscriptions-licenses/subscriptions.md
Updated FF Developer definition
> Update subscriptions.md - Updated FF Developer definition

- src/components/HomepageUniversity/data/universityData.ts
- src/components/University/data/sptData.ts
> Added CI SPT

- docs/software-supply-chain-assurance/get-started/key-concepts.md
- docs/software-supply-chain-assurance/get-started/onboarding-guide.md
- docs/software-supply-chain-assurance/get-started/overview.md
- docs/software-supply-chain-assurance/remediation-tracker/create-remediation-tracker.md
- docs/software-supply-chain-assurance/sbom/generate-sbom.md
- docs/software-supply-chain-assurance/slsa/generate-slsa.md
- docs/software-supply-chain-assurance/ssca-policies/create-ssca-policies.md
> Add videos to SSCA docs

- docs/faqs/cloud-cost-management-faqs.md
> [CCM-17043]: added info

- release-notes/cloud-cost-management.md
> Minot updates

- docs/platform/delegates/delegate-reference/common-delegate-profile-scripts.md
- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: Delegate image version status
* Jira/GitHub Issue numbers (if any): PL-49305
* Preview links/images (Internal contributors only): [Delegate image version support status](https://663567122788c4669d1f40be--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status)
> [PL-49305] Delegate image version status

- docs/software-supply-chain-assurance/get-started/onboarding-guide.md
- docs/software-supply-chain-assurance/shared/ssca-supported.md
> clarified 3rd party code repo integration

- release-notes/internal-developer-portal.md
* Please describe your changes: Added the release notes for v0.26.0
> feat: [IDP-2781]: Added the release notes for v0.26.0

- docs/internal-developer-portal/rbac/resources-roles.md
* Please describe your changes: Added the RBAC policies for workflows and hide catalog
> feat: [IDP-2780]: Added the RBAC policies for workflows and hide catalog

- docs/platform/git-experience/manage-environments-infra-definitions.md
- docs/platform/git-experience/manage-services-using-git-experience.md
* Please describe your changes: Improvement of Git Experience doc 
* Jira/GitHub Issue numbers (if any): CDS-95099
> fix: [CDS-95099]: Improvement of GitEx doc

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
* Please describe your changes: document new functionality allowing configuring authenticated base image connector to build-and-push to docker registry 
* Jira/GitHub Issue numbers (if any): CI-7201
> add base image connector to build-and-push to docker registry

- release-notes/feature-flags.md
* Please describe your changes: \_updated release notes for go sdk 0.1.22
* Jira/GitHub Issue numbers (if any): \_FFM-11343
> go sdk release notes added

- docs/platform/connectors/code-repositories/ref-source-repo-provider/git-lab-connector-settings-reference.md
* Please describe your changes: Remove OAuth FF reference
* Preview links/images (Internal contributors only): PL-50691
> [PL-50691] Remove OAuth FF reference

- release-notes/feature-flags.md
* Please describe your changes: \ updated release notes for react client sdk 1.11.0
* Jira/GitHub Issue numbers (if any): \ FFM-11356
> react sdk release notes added.

- docs/internal-developer-portal/api-refernces/public-api.md
* Please describe your changes: Added the API Endpoint to delete the Catalog components
> feat: [IDP-2799]: Added the API Endpoint to delete the Catalog components

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes:  SMP patch RN 0.15.3, 0.16.1
* Jira/GitHub Issue numbers (if any): PL-50905
* Preview links/images (Internal contributors only): https://663ba5f1004dc0125a088bdf--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#may-8-2024-version-0161
> [PL-50905] SMP patch RN 0.15.3, 0.16.1

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: Add 24.04.82901 delegate to image support list
* Preview links/images (Internal contributors only): [Delegate image version support status](https://663b7e0007d03e46c01c125b--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status)
> Add 24.04.82901 delegate to image support list

- docs/chaos-engineering/get-started/onboarding/single-click-onboarding.md
- docs/chaos-engineering/get-started/overview.md
- docs/chaos-engineering/get-started/tutorials/chaos-experiment-from-blank-canvas.md
- docs/chaos-engineering/get-started/tutorials/experiment-using-api.md
- docs/chaos-engineering/get-started/tutorials/first-chaos-engineering.md
- docs/chaos-engineering/get-started/tutorials/prerequisites.md
- docs/chaos-engineering/integrations/chaos-ff.md
> CHAOS-5129 Update chaos exp with API

- docs/chaos-engineering/chaos-faults/gcp/gcp-iam-integration.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/container-kill.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/disk-fill.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-block.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-latency.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-modify-body.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-latency.md
Add KSA_NAME default value
Remove empty spaces
> CHAOS-5374 Add KSA_NAME default value

- docs/faqs/chaos-engineering-faq.md
- docs/faqs/cloud-cost-management-faqs.md
- docs/faqs/continuous-delivery-faqs.md
- docs/internal-developer-portal/flows/create-workflows-without-idp-stage.md
> docs: fix typos

- release-notes/delegate.md
* Please describe your changes: Delegate RN - remove Harness PL SaaS vernos from headings
* Preview links/images (Internal contributors only): [Delegate release notes](https://663cb6cda718f7a7fbbe00d3--harness-developer.netlify.app/release-notes/delegate)
> Delegate RN - remove Harness PL SaaS vernos

- docs/continuous-delivery/cd-onboarding/existing-user/sync-pipelines-with-barriers.md
> fix: [PIPE-18811]: Add barrier step is supported within a single pipeline

- release-notes/feature-flags.md
* Please describe your changes: \ python sdk 1.6.1 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11455
> python sdk 1.6.1 release notes added

- docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
> fix typos - minor cleanup

- docs/internal-developer-portal/catalog/system-model.md
* Please describe your changes: Improved the SEO for system model docs
> fix: [IDP-2812]: Improved the SEO for system model docs

- docs/chaos-engineering/get-started/onboarding/guided-onboarding.md
- docs/chaos-engineering/get-started/onboarding/single-click-onboarding.md
Replace 'click' with 'select'
Remove 'single click' in guided onboarding first and second steo
> Minor changes based on review

- docs/platform/platform-whats-supported.md
> Updated JIRA and ServiceNow supported version

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: SMP 0.14.8 patch RN
* Jira/GitHub Issue numbers (if any): PL-51075
* Preview links/images (Internal contributors only): https://663e310ae261e5008476ab32--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#may-10-2024-patch-version-0148
> [PL-51075] SMP 0.14.8 patch RN

- docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
* Please describe your changes: \ remove old improvement
> Updated old docs

- docs/continuous-delivery/monitor-deployments/dora-metrics-dashboard.md
https://harness.atlassian.net/browse/CDS-95656
> CDS-95656-using variables to capture execution id of reverted pipeline

- docs/internal-developer-portal/flows/create-a-service.md
* Please describe your changes: Added the script to register catalog back in IDP
> feat: [IDP-2818]: Added the script to register catalog back in IDP

- docs/software-supply-chain-assurance/get-started/overview.md
- docs/software-supply-chain-assurance/ssca-supported.md
- src/components/Docs/SoftwareSupplyChainAssurance.tsx
> Remove Limited GA from SSCA docs

- src/components/Roadmap/data/sscaData.ts
> Update: SSCA Roadmap

- docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
- release-notes/security-testing-orchestration.md
- STO release notes > [Version 1.94.4](https://663e71389f93db31d73e237d--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1944)
- Grype scanner reference > [Target](https://663e71389f93db31d73e237d--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference#target) Add repo as supported type
- Supported scanners > [Code repo scanners](https://663e71389f93db31d73e237d--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#code-repo-scanners) Added Grype to open-source list
> relnotes 1.94 draft 1 STO-7564

- docs/security-testing-orchestration/get-started/your-first-sto-pipeline.md
- docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/trigger-sto-scans-to-block-prs-with-vulnerabilities.md
- kb/security-testing-orchestration/security-testing-orchestration-faqs.md
- [Your first STO pipeline](https://66424f54c145411f216b149b--harness-developer.netlify.app/docs/security-testing-orchestration/get-started/your-first-sto-pipeline) Added redirect, clarified sentence based on DV feedback
- [Trigger STO scans to block pull requests](https://66424f54c145411f216b149b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/trigger-sto-scans-to-block-prs-with-vulnerabilities) > [Pipeline input](https://66424f54c145411f216b149b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/trigger-sto-scans-to-block-prs-with-vulnerabilities#pipeline-input) Grammer tweak
> DV feedback STO-7568

- release-notes/delegate.md
* Please describe your changes: Delegate HF RN - 24.05.82902
* Preview links/images (Internal contributors only): https://66423d9611c0610ec665d4f2--harness-developer.netlify.app/release-notes/delegate#version-240582902-
> Delegate HF RN - 24.05.82902

- docs/platform/secrets/secrets-management/custom-secret-manager.md
> added clarification on what the permissions are for.

- docs/platform/triggers/triggering-pipelines.md
> feat: [CDS-89723]: Skip build if it contains keywords like skip ci,ci skip,skip pipeline,pipeline skip,no_ci 

- docs/platform/git-experience/git-experience-overview.md
> fix: [PIPE-18515]: Add info in gitex regarding changes made in id and scope parameter

- release-notes/continuous-delivery.md
> Add release notes for PIPE-18705

- docs/internal-developer-portal/plugins/available-plugins/harness-ci-cd.md
* Please describe your changes: Added the links to fetch annotations for CI/CD plugin
> feat: [IDP-2817]: Added the links to fetch annotations for CI/CD plugin

- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-block.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-latency.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-modify-body.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-modify-header.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-status-code.md
> Chaos 5381 review

- release-notes/continuous-delivery.md
https://harness.atlassian.net/wiki/spaces/PD/pages/21775286273/NG+Release+SAAS+May+6th+2024+for+1.37.x-+Build
> CD 1.37.x Release Notes

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: Remove 0.14.8, add 0.14.10 patch RN
* Jira/GitHub Issue numbers (if any): PL-51141
* Preview links/images (Internal contributors only): https://6642932f8081d5308cda7615--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#may-13-2024-patch-version-01410
> [PL-51141] Remove 0.14.8, add 0.14.10 patch RN

- src/components/LandingPage/TutorialCard.module.scss
> FIX : hover color for cards

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: add 24.05.82902 to delegate image version status
> add 24.05.82902 to delegate image version status

- docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
* Please describe your changes: fixed information on adding layout component
> fix: [IDP]: fixed information on adding layout component

- docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
> [fix]: [CDS-96722]: Update drift detection documentation

- docs/continuous-delivery/shared/cd-integrations-supported.md
- docs/platform/delegates/delegate-reference/delegate-required-sdks.md
- docs/platform/delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
- docs/platform/platform-whats-supported.md
https://harness.atlassian.net/browse/CDS-88116
> CDS-88116-kubctl version update

- docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
* Please describe your changes: Change the harness chart name for new installs in SMP.
> Change chart name in SMP install document

- docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
* Please describe your changes: Update K8s cluster connector reference
* Jira/GitHub Issue numbers (if any): PL-43388
* Preview links/images (Internal contributors only): https://66391339d79e9e0f2e51f28b--harness-developer.netlify.app/docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference#service-account
> [PL-43388] Update K8s cluster connector reference

- docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3.md
> adding s3fs to s3 artifacts doc

- src/components/Roadmap/data/stoData.ts
- [ x] Successful preview build.
Local Preview screenshot:
> Updated the STO FY25 Q2 and the released feature list based on Q1 work

- kb/platform/harness-platform-faqs.md
* Please describe your changes: Cleanup up some typos, minor revisions
> pl kb faq cleanup

- docs/software-engineering-insights/get-started/enable-the-sei-module.md
> feat: [SEI-6878]: NEW NAV INFO ADDED

- docs/platform/governance/audit-trail/audit-streaming.md
https://harness.atlassian.net/browse/PL-51185
"Delegate version 82500 is required" note.
https://developer.harness.io/docs/platform/governance/audit-trail/audit-streaming/#configure-the-streaming-connector
> [PL-51185] del v82500 required for Splunk Audit Trail using a HEC_Token

- docs/platform/get-started/key-concepts.md
* Please describe your changes: Add redirect for key concepts
* Jira/GitHub Issue numbers (if any): PL-51248
> [PL-51248] Add redirect for key concepts

- release-notes/delegate.md
* Please describe your changes: Delegate 24.05.82903 HF RN
> fix: [CDS-96627]: Release not for GAR Trigger with OIDC auth - Delegate HF RN 24.05.82903

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: Add 24.05.82903 HF delegate
> add 24.05.82903 HF delegate

- kb/platform/pipeline-faq.md
> minor pl pipeline faq cleanup

- docs/platform/delegates/secure-delegates/delegate-mtls-support.md
- [ x ] Successful preview build.
> Updated for clarity and for YAML spacing

- release-notes/feature-flags.md
* Please describe your changes: \ Adding Golang SDK release notes 0.1.23 
* Jira/GitHub Issue numbers (if any): \ FFM-11482
> golang sdk 0.1.23 rns added

- release-notes/feature-flags.md
* Please describe your changes: \ adding info boxes about retracted versions due to a critical bug. 
* Jira/GitHub Issue numbers (if any): \ FFM-11481
> note about retracted versions added

- release-notes/feature-flags.md
* Please describe your changes: \ ruby 1.3.0 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11506
> ruby 1.3.0 release notes added

- src/components/Roadmap/data/codeData.ts
* Please describe your changes: \ Updating the Code Repository Roadmap for Q2 CY24
> updating code repository roadmap for Q2

- docs/platform/pipelines/failure-handling/define-a-failure-strategy-for-pipelines.md
> fix: [PIPE-18771]: Fix Pipeline rollback documentation

- docs/platform/pipelines/input-sets.md
…uble qoutes to parse it correctly
> fix: [PIPE-19047]: Add information for enclosing input set between double quotes to parse it correctly.

- docs/infra-as-code-management/pipelines/_category_.json
* Update the IaCM Pipelines category url slug from incremented `pipelines-1` to `iacm-pipelines`.
* [JIRA](https://harness.atlassian.net/browse/IAC-1955)
> docs: [IAC-1955]: Update IaCM Pipeline Category slug

- docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
- kb/security-testing-orchestration/security-testing-orchestration-faqs.md
- release-notes/security-testing-orchestration.md
- [Version 1.95.0](https://66469c7a1ee1d02fe800daa5--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1950)
- Prisma Cloud scanner reference > [Settings](https://66469c7a1ee1d02fe800daa5--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference#settings)
- [Prisma Cloud scans](https://66469c7a1ee1d02fe800daa5--harness-developer.netlify.app/kb/security-testing-orchestration/security-testing-orchestration-faqs#prisma-cloud-scans) - removed note about it being supported on k8s build infras only
> STO 1.95 release notes STO-7581

- release-notes/delegate.md
* Please describe your changes: Delegate 24.05.82205 HF RN
* Jira/GitHub Issue numbers (if any): PL-51359
> [PL-51359] Delegate 24.05.82205 HF RN

- docs/platform/triggers/trigger-deployments-using-custom-triggers.md
* Please describe your changes: Add note about the Feature Flag CDS_AUTH_CHECK_IN_WEBHOOK_DETAILS_ENDPOINTS for enforcing authorization in webhook execution details endpoints.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PIPE-19306
> feat: [PIPE-19306]: Add note about the Feature Flag `CDS_AUTH_CHECK_IN_WEBHOOK_DETAILS_ENDPOINTS`

- src/components/HomepageUniversity/data/universityData.ts
- src/components/University/data/sptData.ts
> Staging SPT addition for STO 

- src/components/Roadmap/data/ciData.ts
> Update CI roadmap dates

- src/components/Roadmap/data/ffData.ts
Updated entire roadmap
* Please describe your changes: Updated roadmap for Q2 and beyond
* Jira/GitHub Issue numbers (if any): NA
* Preview links/images (Internal contributors only): NA
> Update roadmap for FF

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: add hf delegate 24.05.82205 to support status list
> add hf delegate 24.05.82205

- docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
* Please describe your changes: add a link to delegate image support status topic
> add a link to delegate image support status topic

- docs/platform/variables-and-expressions/add-a-variable.md
> Add limitation regarding using underscore in value of a variable of type string

- src/components/Roadmap/data/ccmData.ts
> added new roadmap

- docs/continuous-delivery/get-started/upgrading/upgrade-nextgen-cd.md
Adding the info note:
:::info note
After migrating from FirstGen to NextGen, please clean up the user accounts in FirstGen.
:::
This has been requested by @meenakshi-harness on ticket: https://harness.atlassian.net/browse/PL-50895
Changes will be reflected on the following page:
https://developer.harness.io/docs/continuous-delivery/get-started/upgrading/upgrade-nextgen-cd/#upgrading-to-nextgen-cd …
> [PL-50895] Note for cleaning up the user accounts in FirstGen

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
- release-notes/delegate.md
* Please describe your changes: Delegate hotfix RN 24.05.82904
https://664cc19cea6b9a008ce99453--harness-developer.netlify.app/release-notes/delegate#version-240582904-
https://664cc19cea6b9a008ce99453--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status#supported-versions …
> feat: [CDS-97030]: update release notes for delegate hotfix 82904

- src/components/Roadmap/data/stoData.ts
> Updated the STO roadmap with the released column at the start

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
> ARN role clarification

- docs/chaos-engineering/troubleshooting/known-issues.md
- docs/chaos-engineering/troubleshooting/troubleshooting.md
> CHAOS-5505 Cleanup

- docs/platform/variables-and-expressions/harness-variables.md
> added cross link to improve search

- docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> Doc update for CDS-84392

- docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3.md
> change s3fs section title

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: Update delegate eos and eol dates
* Jira/GitHub Issue numbers (if any): [PL-51434] 
* Preview links/images (Internal contributors only): [Supported versions](https://664e2f1cf5da550862a308f5--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status#supported-versions)
[PL-51434]: …
> [PL-51434] Update delegate eos and eol dates

- docs/platform/variables-and-expressions/harness-expressions-reference.md
> Added new expression to expressions reference "getParentStepGroup"

- src/components/Roadmap/data/idpData.ts
* Please describe your changes: Added the Q2 roadmap for IDP
> feat:[IDP-2949]: Added the Q2 roadmap for IDP

- docs/internal-developer-portal/flows/service-onboarding-pipelines.md
* Please describe your changes: Added the steps to fetch output in IDP flows using custom action
> feat: [IDP-2950]: Added the steps to fetch output in IDP flows using custom action

- release-notes/security-testing-orchestration.md
STO release notes > [Version 1.96.2](https://664e92c0d9b5f373f831929d--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1962)
> 1.96 relnotes STO-7617

- docs/infra-as-code-management/get-started/onboarding-guide.md
* Tabbed section regarding adding Cloud Provider and Code Repo connectors included in the IaCM onboarding doc
* Tabs include two interactive walkthroughs and a written step by step guide.
* [JIRA](https://harness.atlassian.net/browse/IAC-1999)
> docs: [IAC-1999]: Add connectors steps

- release-notes/internal-developer-portal.md
* Please describe your changes: Added the release notes for v0.27.0
> feat: [IDP-2955]: Added the release notes for v0.27.0

- docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-functions.md
> fixed link

- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-block.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-latency.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-modify-body.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-modify-header.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-api-status-code.md
- docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-api-block/advanced-filters.yaml
- docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-api-latency/advanced-filters.yaml
- docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-body/advanced-filters.yaml
- docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-headers/advanced-filters.yaml
- docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-api-status-code/advanced-filters.yaml
> docs:[CHAOS-5378][CHAOS-5381]: Enhace the pod-api chaos faults for advance filtering and latency unit support

- docs/platform/delegates/secure-delegates/secure-delegates-with-tokens.md
* Please describe your changes: Add delegate token details
* Jira/GitHub Issue numbers (if any): PL-51455
* Preview links/images (Internal contributors only): [Secure delegates with tokens](https://664f8e49e1c4d94fd2ee9a4e--harness-developer.netlify.app/docs/platform/delegates/secure-delegates/secure-delegates-with-tokens)
> [PL-51455] Add delegate token details

- docs/internal-developer-portal/plugins/available-plugins/adr.md
* Please describe your changes: Added the docs on ADR Plugin
> feat: [IDP-2798]: Added the docs on ADR Plugin

- docs/internal-developer-portal/catalog/layout-deepdive.md
* Please describe your changes: add more information on configuring the sidenav
> fix: add more information on configuring the sidenav

- docs/internal-developer-portal/flows/idp-stage.md
* Please describe your changes: added the information on checking the harness idp images used in pipeline
> feat: [IDP-2976]: added the information on checking the harness idp images 

- docs/chaos-engineering/api-reference/_category_.json
- docs/chaos-engineering/api-reference/hce-cli.md
> chore: [CHAOS-5586]: Update docs for hce cli enhancements to include custom org

- docs/internal-developer-portal/get-started/setup-git-integration.md
- docs/internal-developer-portal/whats-supported.md
> fix: Removed the limitation of eu cluster for hcr integration in IDP

- kb/continuous-integration/continuous-integration-faqs.md
- kb/platform/harness-platform-faqs.md
* Please describe your changes: Add restart delegate step to CI_INDIRECT_LOG_UPLOAD faq, add faq to PL
* Jira/GitHub Issue numbers (if any): PL-51484
https://6650a6ee99936d0382639a52--harness-developer.netlify.app/kb/continuous-integration/continuous-integration-faqs#step-logs-disappear
https://6650a6ee99936d0382639a52--harness-developer.netlify.app/kb/platform/harness-platform-faqs#why-did-step-logs-disappear
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEO …
> [PL-51484] Add restart delegate step to CI_INDIRECT_LOG_UPLOAD faq, add faq to PL
