harness/developer-hub

docs/continuous-delivery/manage-deployments/deployment-freeze.md

* Please describe your changes: \ Updated freeze window docs for new UI.

Updated settings instructions for new UI

---

docusaurus.config.js
sidebars-university.js
src/components/University/LandingPage.tsx
src/components/University/UniversityCD.tsx
src/components/University/UniversityCI.tsx
src/components/University/UniversityChaos.tsx
src/components/University/UniversityCloudCostManagement.tsx
src/components/University/UniversityFeatureFlags.tsx
src/components/University/UniversitySTO.tsx
university/faqs.md
university/instructions.md

* vILT Cal Links
* Updated FAQs to include ILTs.
* Linking to ILTs in footer of HDH.

Added links to vILT Calendar.

---

kb/continuous-delivery/articles/create-cascading-fields-jira.md

feat:[CDS-96727]: review comments for jira kb for custom fields

---

release-notes/software-engineering-insights.md

feat: [SEI-6964]: RELEASE NOTES VERSION 202405.2

---

release-notes/platform.md

[PL-51473](https://harness.atlassian.net/browse/PL-51473)
[PL-51473]: https://harness.atlassian.net/browse/PL-51473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-51473] PL 1.39.x Release Notes

---

docs/infra-as-code-management/get-started/onboarding-guide.md

* Update IaCM onboarding steps with interactive guides and updates flow
* [JIRA](https://harness.atlassian.net/browse/IAC-2005)

docs: [IAC-2005]: Update IaCM onboarding

---

docs/platform/authentication/authentication-overview.md
docs/platform/authentication/multiple-identity-providers.md
docs/platform/authentication/single-sign-on-saml.md
docs/platform/authentication/single-sign-on-sso-with-ldap.md
docs/platform/authentication/single-sign-on-sso-with-oauth.md
docs/platform/authentication/switch-account.md
docs/platform/authentication/two-factor-authentication.md

* Please describe your changes: clean up headings, remove whitespace, fix typos

Pl authentication cleanup

---

docs/continuous-delivery/gitops/gitops-faqs.md

Added FAQ for GitopS RBAC permission

---

docs/chaos-engineering/chaos-faults/linux/linux-network-corruption.md
docs/chaos-engineering/chaos-faults/linux/linux-network-duplication.md
docs/chaos-engineering/chaos-faults/linux/linux-network-latency.md
docs/chaos-engineering/chaos-faults/linux/linux-network-loss.md
docs/chaos-engineering/chaos-faults/linux/linux-network-rate-limit.md

Chaos 5621 review

---

release-notes/continuous-delivery.md

Pipe 14601

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP RN minor formatting fix

SMP RN minor formatting fix

---

src/components/University/Card.tsx
src/components/University/CertCard.module.scss
src/components/University/LandingPage.tsx
src/components/University/UniversityCD.tsx
src/components/University/UniversityCI.tsx
src/components/University/UniversityChaos.tsx
src/components/University/UniversityCloudCostManagement.tsx
src/components/University/UniversityFeatureFlags.tsx
src/components/University/UniversitySTO.tsx

Updated SPT and ILT Prices

---

docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-tutorial.md
docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
docs/software-engineering-insights/sei-integrations/automated-integrations/sei-github-integration.md
docs/software-engineering-insights/sei-integrations/automated-integrations/sei-jira-integration.md

* Please describe your changes: \ Broken links

Fixed broken links, removed tinyurls

---

release-notes/platform.md

* Please describe your changes: comment out 1.39.4 RN - rolled back

comment out 1.39.4 RN - rolled back

---

release-notes/continuous-delivery.md

* Please describe your changes: \ Rollback release notes for rollbacked release

rollback 1.39.4 release

---

release-notes/continuous-delivery.md

Republish 1.39.x RN

---

release-notes/platform.md

* Please describe your changes: uncomment 1.39.4 PL RN https://harness.slack.com/archives/C04R4UDE1FT/p1717053352486039?thread_ts=1716802931.400029&cid=C04R4UDE1FT

uncomment 1.39.4 RN - redeployed

---

release-notes/feature-flags.md

* Please describe your changes: \.net sdk release notes added 1.6.9
* Jira/GitHub Issue numbers (if any): \ FFM-11543

.net sdk release notes added 1.6.9

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md
release-notes/delegate.md

* Please describe your changes: Delegate HF RN 24.05.82711
* Jira/GitHub Issue numbers (if any): PL-51555
* Preview links/images (Internal contributors only): https://console.cloud.google.com/storage/browser/smp-airgap-bundles/harness-0.16.2
https://6658c2456690d55416cfb9c0--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status#supported-versions

[PL-51555] Delegate HF RN 24.05.82711

---

kb/continuous-delivery/articles/harness-approval-api.md

Fixed a typo for the API payload.

Fixed a typo in API call payload

---

src/components/University/LandingPage.tsx
src/components/University/UniversityCD.tsx
src/components/University/UniversityCI.tsx
src/components/University/UniversityChaos.tsx
src/components/University/UniversityCloudCostManagement.tsx
src/components/University/UniversityFeatureFlags.tsx
src/components/University/UniversitySTO.tsx
src/components/University/data/sptData.ts

Changed SPT verbiage

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.16.2 patch RN
* Jira/GitHub Issue numbers (if any): PL-51530
* Preview links/images (Internal contributors only): https://6657743b77ed451c2f28f087--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#may-29-2024-version-0162

[PL-51530] SMP 0.16.2 patch RN

---

src/components/University/CertCard.module.scss
src/components/University/CertCard.tsx

HDH 260 create-paid-free-tags-for-cert-card-types

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP RN - Update date in frontmatter for RSS feed

SMP RN - Update date in frontmatter for RSS feed

---

release-notes/feature-flags.md

* Please describe your changes: \ java sdk release notes 1.6.0 added
* Jira/GitHub Issue numbers (if any): \ FFM-11544

java sdk release notes 1.6.0 added

---

src/components/DocVideo/index.tsx

Moved YT Videos to No-Cookie

---

docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md

- Burp scanner reference > Authentication > [Domain](https://6659fc183975c9664dea3da7--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference#domain)

fix Authentication/Domain STO-7624

---

package.json
yarn.lock

Upgrade to DS 3.4.0

---

kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: update bg step limits with more accurate info
* Jira/GitHub Issue numbers (if any): CI-12812

update bg step limits with more accurate info

---

docs/self-managed-enterprise-edition/get-started/onboarding-guide.md
docs/self-managed-enterprise-edition/self-managed-helm-based-install/harness-helm-chart.md
docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
docs/self-managed-enterprise-edition/self-managed-helm-based-install/manage-feature-flags.md
docs/self-managed-enterprise-edition/shared/dev-env-infra.md
docs/self-managed-enterprise-edition/shared/prod-env-infra.md

* Please describe your changes: Remove CET from SMP 0.17.0
* Jira/GitHub Issue numbers (if any): PL-50688

[PL-50688] Remove CET from SMP 0.17.0

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/integrations/integrations-faqs.md
docs/continuous-delivery/x-platform-cd-features/cd-steps/cd-steps-faqs.md
kb/continuous-delivery/faqs.md

FAQS:[CDS-97308]: Addition of CD Faqs

---

docs/chaos-engineering/chaos-faults/kubernetes/fault-wise-permission.md

CHAOS-5650 update fault permissions

---

docusaurus.config.js
src/css/custom.css

Pride Month 2024

---

release-notes/self-managed-enterprise-edition.md

SMP RN - update date in frontmatter for RSS feed, update patch version headings

---

docs/chaos-engineering/onboarding/guided-onboarding.md
docs/chaos-engineering/onboarding/hce-onboarding.md
docs/chaos-engineering/onboarding/single-click-onboarding.md

Prominence of two types of onboarding
Definition for the onboarding types

CHAOS-5676 Add content

---

release-notes/security-testing-orchestration.md

- STO release notes > [Version 1.96.2](https://664fb650c6f0707be71a0bd4--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1962)

STO 1.96 relnotes update

---

docs/platform/secrets/add-use-text-secrets.md

* Please describe your changes: Add note to Add and reference text secrets
* Jira/GitHub Issue numbers (if any): [PL-51597-1]

[PL-51597] Add note to Add and reference text secrets

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Update SMP 0.17.0 release notes - add missing SMP PL tickets
* Jira/GitHub Issue numbers (if any): PL-51618
https://harness.slack.com/archives/C0501BCG1EF/p1717188370903799

Update SMP 0.17.0 release notes - add missing smp pl tickets

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md

Update certificate mount example

---

docs/platform/variables-and-expressions/harness-variables.md

* Please describe your changes: \ Added a new example of a for a simple string concatenation
* Jira/GitHub Issue numbers (if any): \ address customer Zendesk https://harnesssupport.zendesk.com/agent/tickets/64522

(Add) Simple Example for String Concatenation

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/native-helm-quickstart.md

https://harness.atlassian.net/browse/CDS-97014

CDS-97014-notes about FF

---

release-notes/delegate.md

* Please describe your changes: Delegate 24.05.83003 HF RN - CCM NodeInfo labels issue fix

NodeInfo labels issue fix

---

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md

https://harness.atlassian.net/browse/CDS-97219 - Removed tab structure to be able to link appropriate sections in Tooltips in the UI.

CDS-97219-removed tabs

---

release-notes/chaos-engineering.md

CHAOS-5623 Release notes 1.38.1

---

docs/software-engineering-insights/sei-ingestion-satellite/run-the-satellite-container.md

Combined YAML, fixed YAML spacing, made Kubernetes default over Docker

---

release-notes/chaos-engineering.md
release-notes/self-managed-enterprise-edition.md

Update chaos-engineering release notes

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md
release-notes/self-managed-enterprise-edition.md

fix type field in custom cicd integration request

---

docs/platform/references/allowlist-harness-domains-and-ips.md

* Please describe your changes: \ adding ip addresses for feature flags
* Jira/GitHub Issue numbers (if any): \ FFM-11545

adding ip addresses for feature flags

---

docs/platform/delegates/delegate-reference/delegate-environment-variables.md

fix typo - correct delegate capitalization

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md

add 24.06.83003 hf

---

docs/cloud-cost-management/get-started/ccm-smp/1-smp-ccm-roadmap.md

Dashboards smp

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Doc - Add PL-50528 to SMP 0.17.0 RN
* Jira/GitHub Issue numbers (if any): PL-50528

[PL-50528] Doc - Add PL-50528 to SMP 0.17.0 RN

---

docs/platform/get-started/tutorials/add-secrets-manager.md

* Please describe your changes: While browsing through the docs this stood out to me as a typo. Fixed the typo.

Add missing whitespace

---

docs/internal-developer-portal/catalog/custom-catalog-properties.md

* Please describe your changes: Added info on need of escape character in filter

fix: [IDP-3002]: Added info on need of escape character in filter

---

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/gcp-recommendations.md

Added new recommendations for GCP governance

---

docs/continuous-delivery/verify/cv-results/interpret-metric-results.md

CDS-97392-note about threshold metrics

---

kb/continuous-integration/continuous-integration-faqs.md

KB > CI FAQs > [When using the --no-push option in a Harness build step, where is the locally built image stored ?](https://665e1cf524f451466dadfefd--harness-developer.netlify.app/kb/continuous-integration/continuous-integration-faqs#when-using-the---no-push-option-in-a-harness-build-step-where-is-the-locally-built-image-stored-)

add FAQs from PR-6687

---

docs/platform/get-started/harness-ui-overview.md

Remove nav 2.0 ff

---

docs/infra-as-code-management/get-started/onboarding-guide.md

* Add OIDC snippet to onboarding doc for easier connector configuration
* [JIRA](https://harness.atlassian.net/browse/IAC-2028)

docs: [IAC-2028]: Add OIDC snippet to onboarding doc

---

kb/platform/harness-platform-faqs.md
kb/platform/new-navigation-faqs.md

* Please describe your changes: Update new nav FAQ content
* Jira/GitHub Issue numbers (if any): PL-51682

[PL-51682] Update new nav FAQ content

---

docs/self-managed-enterprise-edition/performance-reports.md

* Please describe your changes: Add May SMP performance report - https://github.com/harness/harness-performance-tool/blob/main/reports/05-June'24.md
* Jira/GitHub Issue numbers (if any): PL-51722
* Preview links/images (Internal contributors only): https://6661d8449522ed1817c95a31--harness-developer.netlify.app/docs/self-managed-enterprise-edition/performance-reports#2024-reports

[PL-51722] Add May SMP performance report

---

docs/self-managed-enterprise-edition/performance-reports.md

SMP performance test reports - minor cleanup

---

release-notes/chaos-engineering.md

Add video tutorials about k8s upgrade

Add video tutorials about k8s upgrade

---

docs/chaos-engineering/onboarding/guided-onboarding.md
docs/chaos-engineering/onboarding/hce-onboarding.md

CHAOS-5711 Update content

---

university/faqs.md

Updated Exam FAQ

---

docs/infra-as-code-management/workspaces/project-setup/opa-workspace.md

* Rearrange OPA usage for IaC governance doc for more clarity. 
* [JIRA](https://harness.atlassian.net/browse/IAC-2044)

docs: [IAC-2044]: Rearrange IACM OPA usage doc

---

docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md
docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md

* Add new custom images doc explaining how to create and use a custom image with your Terraform plugin steps.
* [JIRA](https://harness.atlassian.net/browse/IAC-2029)

docs: [IAC-2029]: Add custom images doc

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md
release-notes/delegate.md

* Please describe your changes: Adding hotfix for Delegate Hotfix 83004
* Jira/GitHub Issue numbers (if any): [PL-51747](https://harness.atlassian.net/browse/PL-51747)
[PL-51747]: https://harness.atlassian.net/browse/PL-51747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-51747] Delegate Hotfix 83004

---

src/components/Roadmap/data/cdData.ts
src/components/Roadmap/data/platformData.ts

Roadmap for CD + a few for Platform.

---

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/fossa-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md

update target-detection heading STO-7691

---

docs/software-engineering-insights/sei-integrations/semi-automated-integrations/sei-custom-cicd-integrations.md

fix: [SEI-6738]: Add 'web_url' field in CICD Custom endpoint

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md

* Please describe your changes: Fixed Spelling Mistake for gradle

fix Spell Mistake in ti-for-java-kotlin-scala.md

---

docs/continuous-integration/migration-guides/migrating-from-circleci.md

* Please describe your changes: adding examples of how to use orbs in steps

adding examples of how to use orbs in steps

---

src/components/Roadmap/data/platformData.ts

* Please describe your changes: update pl roadmap-minor copy edits - fix typos, etc

update pl roadmap-minor copy edits

---

docs/platform/git-experience/git-experience-overview.md
docs/platform/git-experience/gitexp-bidir-sync-setup.md

fix: [PIPE-18576]: Improvement of Git Experience docs

---

kb/cloud-cost-management/articles/onboarding/k8s.md

Need to document the ability to block a delegate from taking shell tasks when installing a delegate for pure CCM usage.

add BLOCK_SHELL_TASK to CCM delegate guide

---

.github/CODEOWNERS

Adding codeowners to RA section. Chris and I can begin reviewing new solutions from the team.

Update CODEOWNERS to include RA

---

kb/cloud-cost-management/articles/onboarding/k8s.md

Add link to helm chart for enabling autostopping. This will make onboarding more simple for teams.

add autostopping helm chart

---

docs/platform/references/entity-identifier-reference.md

Added two reserved identifiers

---

docs/cloud-cost-management/CCMRoadmap.tsx
docs/cloud-cost-management/styles.module.scss

Add Legends in CCM's Roadmap

---

kb/reference-architectures/ansible.md

Add link to a template example of implimenting the guide.

add link to template example

---

docs/feature-flags/ff-creating-flag/manage-stale-flags.md

* Please describe your changes: \ incorporated additional steps to use javascript for flag cleanup. 
* Jira/GitHub Issue numbers (if any): \_FFM-10269

adding javascript flag cleanup steps

---

docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism.md

Admonition for concurrent nodes.

---

docs/platform/delegates/delegate-concepts/delegate-image-types.md

topic cleanup

---

docs/platform/connectors/artifact-repositories/nexus-connector-settings-reference.md

update link to fix 404

---

docs/platform/delegates/install-delegates/docker-delegate-to-ecs-fargate.md

update link - fix 404

---

docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md

OIDC warnings for AWS

---

kb/platform/harness-platform-faqs.md

* Please describe your changes: Add a new delegate FAQ for custom image API
* Jira/GitHub Issue numbers (if any): PL-51833

[PL-51833] Add new delegate FAQ for custom image API

---

docs/platform/git-experience/cg-vs-ng-git-experience.md

feat: [PIPE-19588]: cg git sync vs ng git ex page

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-restart.md
docs/platform/pipelines/failure-handling/define-a-failure-strategy-on-stages-and-steps.md

fix:[PIPE-19466]: Improve doc for mark as failure

---

docs/platform/variables-and-expressions/harness-expressions-reference.md

fix:[PIPE-19769]: Add info regardig fetching GAR version via expression

---

docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md

* Please describe your changes: Updated the missing endpoint under proxy

fix: [IDP]: Updated the missing endpoint under proxy

---

kb/cloud-cost-management/articles/onboarding/k8s.md

Autostopping no longer requires a FG api key

remove mention of FG api key

---

docs/continuous-integration/development-guides/browser/_category_.json
docs/continuous-integration/development-guides/browser/browserstack.md

* Please describe your changes: adding Browser Testing section with BrowserStack doc

adding Browser Testing section with BrowserStack doc

---

release-notes/continuous-delivery.md

removed internal ticket id

---

release-notes/platform.md

update delegate verno

---

release-notes/feature-flags.md

* Please describe your changes: \ android sdk 2.2.1 rns added
* Jira/GitHub Issue numbers (if any): \ FFM-11658

android sdk 2.2.1 rns added

---

kb/feature-flags/harness-feature-flag-faqs.md

* Please describe your changes: \ adding ff/database error question to ff knowledge base
* Jira/GitHub Issue numbers (if any): \ FFM-11497

adding ff/database error question to ff knowledge base

---

docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md

* Please describe your changes: Issues with serverless tutorial. Following it doesn't get you started and quick. Got rid of things causing errors, next sprint the plan is to redo the doc.

Updates to quickstart guide

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md

PL-51863 - add secret info

---

src/css/custom.css

HDH-267-dark-mode-round-edges-chatbot-search-box

---

release-notes/feature-flags.md

* Please describe your changes: \ flutter sdk release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11667

flutter sdk release notes added

---

docs/platform/git-experience/gitexp-bidir-sync-setup.md

remove ff for bidirectional sync in docs

---

src/components/KnowledgeBase/data/knowledgeBaseData.ts

Added the most recent CD KBs in the landing page

Added latest KBs in the landing page

---

kb/continuous-delivery/articles/input-set-gitsync.md

correct spelling in git sync kb

---

docs/chaos-engineering/chaos-faults/kubernetes/node/node-network-latency.md
docs/chaos-engineering/chaos-faults/kubernetes/node/node-network-loss.md

chore: [CHAOS-5774]: Add the multiple nodes support in node-network faults

---

docs/infra-as-code-management/get-started/onboarding-guide.md

* Update Tango walkthrough guides to follow new UI updates
* [JIRA](https://harness.atlassian.net/browse/IAC-2082)

docs: [IAC-2082]: Update Tango steps to follow UI updates

---

.gitignore
netlify.toml
netlify/functions/auth.mts
netlify/functions/chatbot_proxy.mts
package.json
yarn.lock

Add netlify funcitons

---

docusaurus.config.js

Case update

---

release-notes/feature-flags.md

* Please describe your changes: \ node.js release note 1.8.1 added
* Jira/GitHub Issue numbers (if any): \ FFM-11674

node.js release note 1.8.1 added

---

docs/platform/references/allowlist-harness-domains-and-ips.md

* Please describe your changes: update pl allowlist - remove GitOps
* Jira/GitHub Issue numbers (if any): PL-51882
* Preview links/images (Internal contributors only): [Allowlist Harness domains and IPs](https://666cf949048ee05890e87ea0--harness-developer.netlify.app/docs/platform/references/allowlist-harness-domains-and-ips)

PL-51882 update pl allowlist

---

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
release-notes/security-testing-orchestration.md

- STO release notes [Version 1.98.7](https://666c9c27633cce18b51694ee--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1987)
- Anchore Enterprise scanner reference > [Anchore Enterprise requirements](https://666c9c27633cce18b51694ee--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference#anchore-enterprise-requirements)

1.98 relnotes update STO-7719

---

docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
docs/cloud-cost-management/get-started/ccm-smp/azure-smp.md
docs/cloud-cost-management/get-started/ccm-smp/gcp-smp.md

* Jira/GitHub Issue numbers (if any): 18035

[CCM-18035]: Added troubleshooting for when the secrets expire for a CCM SMP customer

---

netlify/functions/auth.mts

temporary change in cors origin for QA test

---

docs/internal-developer-portal/tutorials/how-to-use-catalog-ingestion-api.md

* Please describe your changes: Added the Run step for jira project creation

feat: [IDP-3044]: Added the Run step for jira project creation

---

netlify/functions/auth.mts

FIX:name cookie

---

docs/software-engineering-insights/early-access/integrations/sei-integration-servicenow.md

feat: [SEI-7113]: ServiceNow Oauth config

---

docs/software-engineering-insights/early-access/metrics-reports/issue-backlog-trend-report.md
docs/software-engineering-insights/early-access/metrics-reports/sei-lead-time-beta.md

feat: [SEI-6903]: Lead time median calculation

---

release-notes/feature-flags.md

* Please describe your changes: \ .net sdk release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11682

.net sdk release notes added

---

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md

added overrides v2 notes

---

kb/continuous-delivery/faqs.md

CDS-96165-faq

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/integrations/integrations-faqs.md

FAQs: [CDS-97807]: FAQs addition for AIDA

---

docs/cloud-cost-management/get-started/overview.md

Removed FF info since now new overview screen is enabled for everyone

---

docs/continuous-delivery/gitops/gitops-faqs.md

We added this ability. Fits best as a FAQ

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md

CI-13037
* Please describe your changes: missing quotes in pipeline
* Jira/GitHub Issue numbers (if any): CI-13037

Update harness-ci.md CI-13037

---

netlify.toml
netlify/functions/auth.mts
netlify/functions/chatbot_proxy.mts

netlify cors fix

---

docs/software-engineering-insights/early-access/metrics-reports/sei-business-alignment-report.md

Add beta tag to BA usecases topic

---

netlify.toml
netlify/functions/auth.mts
netlify/functions/chatbot_proxy.mts

Netlify function

---

docs/platform/triggers/triggers-reference.md

https://harness.atlassian.net/browse/PIPE-19792

added payload size limit

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes:  SMP 0.17.1 patch RN
* Jira/GitHub Issue numbers (if any): PL-51751
* Preview links/images (Internal contributors only): https://6663206831a1e63b35aa48d3--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#june-7-2024-patch-version-0171

[PL-51751] SMP 0.17.1 patch RN

---

src/components/University/UniversityIDP.tsx
src/components/University/UniversitySEI.tsx
yarn.lock

Added SEI and IDP Study Guides and Yarn Maint

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

AWS custom parameters

---

docs/software-engineering-insights/sei-ingestion-satellite/run-the-satellite-container.md
docs/software-engineering-insights/sei-ingestion-satellite/satellite-overview.md
docs/software-engineering-insights/sei-integrations/sei-integrations-overview.md

fix: [SEI-7224]: IP whitelisting docs added

---

release-notes/self-managed-enterprise-edition.md

update release date

---

netlify/functions/chatbot_proxy.mts

Fix : token rotation

---

docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/host.yaml
docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/load-image.yaml
docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/spawn-rate.yaml
docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/users.yaml

chore: [CHAOS-5838]: Fix the locust loadgen charts for invalid args

---

docs/service-reliability-management/monitored-service/monitored-service-template-quickstart.md

Fixed step format

---

src/components/Chatbot/Chatbot.tsx
src/components/Chatbot/styles.module.scss
src/css/custom.css

Hdh 268 aida  on hdh UI   improvements

---

release-notes/platform.md

* Please describe your changes: PL 1.42.x Release Notes PR
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-51920

[PL-51920] PL 1.42.x Release Notes

---

release-notes/delegate.md

fix: [CDS-98000]: add new delegate release version

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md

* Please describe your changes: 24.06.83204 - delegate hf
* Preview links/images (Internal contributors only): https://667483923bf94caeac4ac9fd--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status#supported-versions

24.06.83204 - delegate hf

---

release-notes/platform.md

* Please describe your changes: PL-48009 and PL-47825 are present in SMP but not in PL RN, hence adding them to PL
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-51622

[PL-51622] tickets present in SMP but not in PL

---

docs/internal-developer-portal/get-started/enable-docs.md
kb/internal-developer-portal/harness-internal-developer-portal-faqs.md

* Please describe your changes: Added the example of mkdocs.yaml

fix: [IDP-3114]: Added the example of mkdocs.yaml

---

release-notes/chaos-engineering.md

CHAOS-5887 Release notes 1.39.11

---

release-notes/chaos-engineering.md

CHAOS-5887 Update chaos-engineering.md

---

release-notes/continuous-integration.md

- CI release notes > [Version 1.30](https://66608a524f2a363d5df9bc42--harness-developer.netlify.app/release-notes/continuous-integration#version-130)

v1 draft CI 1.30 relnotes

---

src/components/Chatbot/Chatbot.tsx

Patched AIDA Logo Location

---

docs/security-testing-orchestration/custom-scanning/custom-ingest-reference.md
docs/security-testing-orchestration/custom-scanning/custom-scan-reference.md
docs/security-testing-orchestration/exemptions/exemption-workflows.md
docs/security-testing-orchestration/get-started/key-concepts/ingest-scan-results-into-an-sto-pipeline.md
docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/build-scan-push-workflows/build-scan-push-sto-ci.md
docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/build-scan-push-workflows/build-scan-push-sto-only.md
docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/run-scans-using-github-actions.md

Update sto redirects sto 7609

---

docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss.md
docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop.md

List the IAM permissions used by various GCP faults

CHAOS-5851 Add IAM permissions used

---

client_module/chatbot.js
src/components/Chatbot/Chatbot.tsx
src/components/Chatbot/helpers.ts
src/components/Chatbot/styles.module.scss

Hdh 272 add aida to right hand on each page fix

---

src/components/University/styles.module.scss

HDH-269-hdh-university-idp-sei-background-image-size

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
kb/continuous-delivery/faqs.md

FAQs: [CDS-98339]: FAQs Addition for 21st June

---

.github/CODEOWNERS

* Please describe your changes: Update PL CODEOWNERS - remove Harish

update PL CODEOWNERS

---

release-notes/self-managed-enterprise-edition.md

Update SMP 0.17.1 RN

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md

* Please describe your changes: add nexus to connector docs

add nexus to connector docs

---

release-notes/delegate.md

add PIPE-19585

---

docs/chaos-engineering/chaos-faults/kubernetes/node/node-drain.md

chore: [CHAOS-5868]: Updated docs for node drain fault

---

archive/redirects/client-redirects-aug-16-2023.js
archive/redirects/client-redirects-may-10-2023.js
docs/security-testing-orchestration/jira-integrations.md
docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
release-notes/security-testing-orchestration.md

- STO release notes > [Version 1.99.2](https://6679fa4233e46c5191f1fd40--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-1992)
- STO release notes > Version 1.96 > [Breaking change](https://6679fa4233e46c5191f1fd40--harness-developer.netlify.app/release-notes/security-testing-orchestration#breaking-change)

1.99.2 relnotes STO-7735 v2

---

docs/continuous-delivery/cd-integrations.md

Converted html table to md table to fix format

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md

Minor change to include Base ASG option to docs.

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-restart.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-step.md

Help differentiate rollout deployment and restart steps

---

release-notes/continuous-delivery.md

Fixed bug id

---

docs/continuous-delivery/monitor-deployments/pipeline-execution-dashboard.md

removed notes reg pipeline execution

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/1-introduction.md
docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/_category_.json

Minor change

---

docs/platform/get-started/subscriptions-licenses/cloud-marketplaces/aws.md
docs/platform/get-started/subscriptions-licenses/subscriptions.md

* Please describe your changes: Update PL Subscriptions content
* Jira/GitHub Issue numbers (if any): PL-52031
* Preview links/images (Internal contributors only): [View and manage subscriptions](https://6679eef3dacb454914c93118--harness-developer.netlify.app/docs/platform/get-started/subscriptions-licenses/subscriptions)

[PL-52031] Update PL Subscriptions content

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md
docs/continuous-integration/use-ci/run-tests/tests-v2.md
docs/continuous-integration/use-ci/viewing-builds.md
docs/faqs/self-managed-ee-faq.md
docs/self-managed-enterprise-edition/install/install-in-an-air-gapped-environment.md

* Please describe your changes: Removed references for CET in regards to CI - the Run Tests step no longer supports CET even with both modules enabled.

Remove CET from CI

---

docs/software-engineering-insights/early-access/integrations/sei-integration-servicenow.md

quick fix servicenow doc

---

docs/platform/git-experience/gitexp-bidir-sync-setup.md

feat:[PIPE-20098]: Mention in docs that .harness folder is tracked by default for all the webhooks

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

Update SQ Scan Mode description based on GA feedback STO-5799

---

docusaurus.config.js
package.json
src/components/Chatbot/Chatbot.tsx
src/components/Telemetry/TememetryConstants.ts
src/components/Telemetry/index.tsx
src/pages/index.tsx
src/theme/MDXComponents.js
yarn.lock

Hdh 273 add telemetry data to aida on hdh

---

release-notes/platform.md

* Please describe your changes: Platform 1.43.6 release notes
* Jira/GitHub Issue numbers (if any): [PL-52028](https://harness.atlassian.net/browse/PL-52028)
* Preview links/images (Internal contributors only): [Platform 1.43.6 release notes](https://667d69fff61a71007b48d59f--harness-developer.netlify.app/release-notes/platform#version-1436)
[PL-52028]: …

[PL-52028] Platform 1.43.6 release notes

---

release-notes/feature-flags.md

* Please describe your changes: \ python sdk release notes 1.6.2 added
* Jira/GitHub Issue numbers (if any): \ FFM-11717

python sdk release notes 1.6.2 added

---

release-notes/feature-flags.md

* Please describe your changes: \ node.js release notes 1.8.2 added
* Jira/GitHub Issue numbers (if any): \ FFM-11736

node.js release notes 1.8.2 added

---

release-notes/platform.md

update date for RSS feed, release verno

---

release-notes/feature-flags.md

* Please describe your changes: \ golang sdk 0.1.24 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11731

golang sdk 0.1.24 release notes added

---

release-notes/continuous-delivery.md

CDS-98279-CD 1.43.x Release Notes

---

release-notes/security-testing-orchestration.md

Preview link
- STO release notes > [Version 1.100.2](https://667eed11dd2cea21bf8604c3--harness-developer.netlify.app/release-notes/security-testing-orchestration/#version-11002)

1.100 release notes STO-7784

---

docs/continuous-delivery/cd-infrastructure/terraform-infra/provision-infra-dynamically-with-terraform.md
docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md

Added language for terra https connector support

---

docs/platform/shared/subscription-manage.md

[PL-52149] Update credit verbiage

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.14.6 HF RN
* Jira/GitHub Issue numbers (if any): PL-52150
* Preview links/images (Internal contributors only): https://667fef0f7bad5922cdf899c8--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#june-29-2024-patch-version-01411

[PL-52150] SMP 0.14.11 Patch RN

---

release-notes/self-managed-enterprise-edition.md

Published release notes on June 29 without air gap bundle link. PR to uncomment air gap bundle info, and the link to the bundle, and update the date in the frontmatter for the RSS feed.

uncomment air gap bundle - SMP 0.14.11 RN

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk 1.3.1 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11740

ruby sdk 1.3.1 release notes added

---

docusaurus.config.js
src/css/custom.css

Updated logo and tooltip

---

docs/infra-as-code-management/policies/_category_.json
docs/infra-as-code-management/policies/terraform-plan-cost-policy.md

* Add new IaCM-specific policies section with Terraform Plan Cost example
* [JIRA](https://harness.atlassian.net/browse/IAC-2104)

docs: [IAC-2104]: Add IaCM built-in policies 

---

docs/platform/triggers/trigger-on-a-new-artifact.md

Update trigger-on-a-new-artifact.md - Regex condition update

Update trigger-on-a-new-artifact.md - Regex condition update

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md
release-notes/delegate.md

* Please describe your changes: Delegate HF RN 24.07.82905
* Jira/GitHub Issue numbers (if any): PL-52037, PL-55198
- [Supported versions](https://66832ff7a2ea16b6a4b51a7b--harness-developer.netlify.app/docs/platform/delegates/delegate-reference/delegate-image-version-status#supported-versions)
- [24.07.82905 HF RN](https://66832aec0e7b30994fe62584--harness-developer.netlify.app/release-notes/delegate#version-240782905-) …

[PL-55198] Delegate HF RN 24.07.82905

---

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md

chore: Add New Resources for Governance's Cost Correlation

---

kb/cloud-cost-management/articles/onboarding/gcp.md

Fixing typo 

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/1-ccm-recommendations/azure-vm.md

[CCM-18436] added minor changes

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md

feat: [CI-13177]: Update upload-artifacts-to-jfrog.md

---

release-notes/feature-flags.md

* Please describe your changes: \ java sdk 1.6.1 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11742

java sdk 1.6.1 release notes added

---

docs/internal-developer-portal/whats-supported.md

Bitbucket Server is supported in IDP as well

---

docs/software-engineering-insights/early-access/sei-early-access-overview.md
docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-azure-devops.md
docs/software-engineering-insights/sei-supported-platforms.md
release-notes/software-engineering-insights.md

feat: [SEI-7353]: Early access docs migration

---

docs/software-engineering-insights/get-started/enable-the-sei-module.md

feat: [SEI-7343]: SEI ENABLE THE MODULE TOPIC UPDATED

---

release-notes/security-testing-orchestration.md

Update 1.98 relnotes

---

docs/internal-developer-portal/flows/idp-stage.md
docs/internal-developer-portal/flows/self-service-onboarding-pipeline-tutorial.md
release-notes/internal-developer-portal.md

fix: [IDP]: Removed all instances of IDP stage FF

---

docs/platform/authentication/single-sign-on-sso-with-ldap.md

remove firstgen reference

---

docs/infra-as-code-management/remote-backends/state-migration.md

* Document IaCM state migration to generate new workspace and import infrastructure state into each new workspace.
* [JIRA](https://harness.atlassian.net/browse/IAC-2151)

docs: [IAC-2151]: IaCM State migration tooling document

---

docs/platform/triggers/trigger-deployments-using-custom-triggers.md

trigger v2/v3 webhook clarifications

---

docs/software-engineering-insights/get-started/sei-onboarding-guide.md
docs/software-engineering-insights/sei-integrations/sei-integrations-overview.md

Reverting back to older version 

---

src/css/custom.css
src/pages/legal/accessibility.module.scss

HDH-278-legal-page-dark-mode

---

docs/internal-developer-portal/get-started/setup-git-integration.md
docs/internal-developer-portal/whats-supported.md

fix: [IDP]: Added detailed explanation on only HTTP Support

---

docs/platform/git-experience/autocreation-of-entities.md

feat: [PIPE-20191]: Add new file convention for environment

---

docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-csharp.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
docs/continuous-integration/use-ci/run-tests/ti-overview.md
kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: Added item to KB about 'Unable to get changed files list' in TI
* Jira/GitHub Issue numbers (if any): CI-13153

Added item to KB about 'Unable to get changed files list' in TI [CI-13153]

---

docs/infra-as-code-management/pipelines/iacm-plugins/approval-step.md
docs/infra-as-code-management/whats-supported.md

* Add Wiz scan support notice to IaCM docs
* [JIRA](https://harness.atlassian.net/browse/IAC-2136)

docs: [IAC-2136]: Add Wiz scan support to IaCM docs

---

docs/internal-developer-portal/plugins/available-plugins/harness-ci-cd.md
docs/internal-developer-portal/plugins/available-plugins/harness-iacm.md

feat: [IDP-3196]: Added the docs for Harness IACM plugin

---

docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md

The docs for updating the execution config for IaC custom images was lacking the option to set it for Tofu based pipelines.
Tested in my own account.

Update plugin-images.md to include IACMOpentofuTag

---

kb/continuous-delivery/faqs.md

FAQ updates in CD

---

docs/security-testing-orchestration/get-started/key-concepts/ingest-scan-results-into-an-sto-pipeline.md
docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/coverity-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/fortify-on-demand-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/fortify-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/fossa-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/nexus-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/qualys-web-app-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/qwiet-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/reapsaw-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.BACKUP.txt
docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.txt
docs/security-testing-orchestration/sto-techref-category/wiz/artifact-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/iac-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/repo-scans-with-wiz.md

update pill links v2

---

docs/platform/templates/create-a-secret-manager-template.md

* Please describe your changes: \____  Limitation found with Secrets Manager Template that doesn't allow the reference to a secret stored in non-Harness Built In Secrets Manager
* Jira/GitHub Issue numbers (if any): \_______ https://harness.atlassian.net/browse/PL-55254

(Update) Added new limitation

---

docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-deployment-faqs.md
kb/continuous-delivery/faqs.md

FAQs: [CDS-98834]: Adding faqs for July 5th

---

.github/CODEOWNERS

* Please describe your changes: Add Jim Sheldon to Drone FAQ KB

Add Jim Sheldon to Drone FAQ KB

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md

* Please describe your changes: This PR fixes the artifact variable listed in the ECS docs to be the correct variable.
* Jira/GitHub Issue numbers (if any): None

Fix artifact image variable used in the ECS task definition sample

---

docs/platform/authentication/single-sign-on-saml.md

* Please describe your changes: Add displayname tip
* Jira/GitHub Issue numbers (if any): PL-55246
* Preview links/images (Internal contributors only): https://668d814bdfc644c312b8d81d--harness-developer.netlify.app/docs/platform/authentication/single-sign-on-saml

[PL-55246] Add displayname tip

---

docs/platform/templates/create-a-secret-manager-template.md

* Please describe your changes: \____ Provided additional context and link to original announcement

(Update) Additional Info for Restriction

---

.github/CODEOWNERS
docs/security-testing-orchestration/custom-scanning/ingesting-issues-from-other-scanners.md
docs/security-testing-orchestration/dashboards/view-scan-results.md
docs/security-testing-orchestration/get-started/key-concepts/sto-workflows-overview.md

Add redirects sto

---

docs/self-managed-enterprise-edition/performance-reports.md

* Please describe your changes: July performance test report
* Jira/GitHub Issue numbers (if any): PL-55300
* Preview links/images (Internal contributors only): https://668ea1a5ef88591ee187f444--harness-developer.netlify.app/docs/self-managed-enterprise-edition/performance-reports

[PL-55300] July performance test report

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md
release-notes/delegate.md

feat: [CDS-97512]: add new delegate release version

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md

add 24.07.83404 delegate

---

docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md

Adding https protocol to two spots I missed

---

docs/code-repository/config-repos/import-repo.md

* Please describe your changes: This PR adds Azure DevOps PAT requirements to [this page](https://developer.harness.io/docs/code-repository/config-repos/import-repo/#import-repositories).
* Preview: https://668d7a96129405b9f5297a35--harness-developer.netlify.app/docs/code-repository/config-repos/import-repo

Add Azure DevOps PAT requirements.

---

release-notes/delegate.md

copy edits

---

kb/cloud-cost-management/articles/best-practices/aws-connectors-and-roles.md

update aws tf code and add cloudformation stackset option

---

release-notes/platform.md

* Please describe your changes: PL 1.45.x Release Notes
* Jira/GitHub Issue numbers (if any): [PL-55258]
*  Preview: https://668ecd540d8d252d4ae3436d--harness-developer.netlify.app/release-notes/platform#version-1455
[PL-55258]: https://harness.atlassian.net/browse/PL-55258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-55258] PL 1.45.x Release Notes

---

release-notes/delegate.md

* Please describe your changes: Delegate 24.07.83404 RN
* Jira/GitHub Issue numbers (if any): PL-55369
* Preview links/images (Internal contributors only): https://668ece23101b8f31316a3759--harness-developer.netlify.app/release-notes/delegate#version-240783404-

[PL-55369] Delegate 24.07.83404 RN

---

docs/chaos-engineering/chaos-faults/linux/experiments.ts
docs/chaos-engineering/chaos-faults/linux/linux.md
docs/chaos-engineering/chaos-faults/linux/permissions.md

Linux left nav bar and center screen mismatch fixed
Tags added

CHAOS-6114 Linux tags added

---

release-notes/chaos-engineering.md

CHAOS-6072 Release notes 1.40.0

---

_server-redirects
docs/feature-flags/troubleshoot-ff/harness-policy-engine.md
docs/feature-flags/use-ff/ff-creating-flag/manage-featureflags-in-git-repos.md
docs/feature-flags/use-ff/ff-sdks/sdk-overview/cdn-support.md
docs/feature-flags/use-ff/relay-proxy/relay_proxy_v2.md

Patched FF Links

---

kb/platform/harness-platform-faqs.md

* Please describe your changes: Update RBAC section - inline vs git pipeline
* Jira/GitHub Issue numbers (if any): PL-52121
* Preview links/images (Internal contributors only): https://668d8c15fdccced1c96c2633--harness-developer.netlify.app/kb/platform/harness-platform-faqs#why-are-rbac-checks-different-for-pipelines-stored-inline-vs-git

[PL-52121] Update RBAC FAQ section - inline vs git pipeline

---

kb/platform/harness-platform-faqs.md

* Please describe your changes: Add a Subscriptions section to KB FAQ
* Jira/GitHub Issue numbers (if any): PL-52124

[PL-52124] Add a Subscriptions section to KB FAQ

---

docs/platform/role-based-access-control/add-users.md

* Jira/GitHub Issue numbers (if any): [PL-52109](https://harness.atlassian.net/browse/PL-52109)
[PL-52109]: https://harness.atlassian.net/browse/PL-52109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-52109][DOC] User preference landing page

---

docs/chaos-engineering/features/image-registry.md

CHAOS-6097 Update image registry

---

docs/internal-developer-portal/whats-supported.md

fix: [IDP]: Added info on cd license support for custom stage

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md

Added Tango for Commitment Orchestrator

---

docs/security-testing-orchestration/exemptions/exemption-workflows.md
docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
release-notes/early-access.md
release-notes/security-testing-orchestration.md

- [Version 1.102.2](https://6691311a40536d22eb9a03a4--harness-developer.netlify.app/release-notes/security-testing-orchestration#version-11022)
- [STO early access features](https://6691311a40536d22eb9a03a4--harness-developer.netlify.app/release-notes/early-access#sto-early-access-features)
- [STO features promoted to GA](https://6691311a40536d22eb9a03a4--harness-developer.netlify.app/release-notes/early-access#sto-features-promoted-to-ga)

Add: STO Release Notes for Week of 2024-07-07

---

docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md

Fix dead link in Checkmarx step config doc

---

docs/platform/platform-whats-supported.md

copy edits, add links

---

docs/security-testing-orchestration/exemptions/exemption-workflows.md
release-notes/early-access.md
release-notes/security-testing-orchestration.md

Update release notes for STO-7675

---

docs/internal-developer-portal/catalog/catalog-scripts.md

feat: [IDP]: Added docs on catalog scripts

---

docs/cloud-cost-management/roadmapData.ts

ccm-supported-platforms.md

---

release-notes/continuous-delivery.md

move repolisting from fixed issues to new features and enhancements

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Add supported swimlanes for AWS OIDC

---

docs/platform/references/tags-reference.md

fix: [PIPE-20256]: Add updates to tag overview page

---

src/components/University/LandingPage.tsx
src/components/University/UniversityCD.tsx
src/components/University/UniversityCI.tsx
src/components/University/UniversityChaos.tsx
src/components/University/UniversityCloudCostManagement.tsx
src/components/University/UniversityFeatureFlags.tsx
src/components/University/UniversityIDP.tsx
src/components/University/UniversitySEI.tsx
src/components/University/UniversitySTO.tsx
src/components/University/styles.module.scss

HDH-284-harness-u-on-hdh-minor-improvements

---

release-notes/feature-flags.md

* Please describe your changes: \ python sdk 1.6.3 release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11762

python sdk 1.6.3 release notes added

---

docs/chaos-engineering/features/chaos-infrastructure/harness-infra/_category_.json
docs/chaos-engineering/features/chaos-infrastructure/harness-infra/harness-infra.md
docs/chaos-engineering/onboarding/guided-onboarding.md
docs/chaos-engineering/onboarding/hce-onboarding.md
docs/chaos-engineering/onboarding/single-click-onboarding.md

Change 'delegate-driven' to 'dedicated' chaos infrastructure

CHAOS-6123 Change 'delegate-driven' to 'dedicated'

---

src/components/Roadmap/data/stoData.ts

Update the STO roadmap for the q3'25

---

docs/platform/secrets/secrets-management/add-a-cyberark-conjur-custom-secret-manager.md

* Please describe your changes: Updated formating and error handling in Conjur Secret Manager script
* Jira/GitHub Issue numbers (if any): none
* Preview links/images (Internal contributors only): none

Improved Conjur secret manager template to have better error handling

---

docs/continuous-integration/get-started/ci-subscription-mgmt.md

* Please describe your changes: Update Team to Startup

Update Team to Startup

---

release-notes/feature-flags.md

* Please describe your changes: \android sdk 2.2.2 release notes added
* Jira/GitHub Issue numbers (if any): \FFM-11766

android sdk 2.2.2 release notes added

---

release-notes/delegate.md

* Please describe your changes: 24.07.82906 Delegate HF RN
* Preview links/images (Internal contributors only): https://6697d1c8657aadd087e205db--harness-developer.netlify.app/release-notes/delegate#version-240782906-

24.07.82906 Delegate HF RN

---

kb/platform/pipeline-faq.md

* Please describe your changes: Update Gitness to Harness Open Source
* Jira/GitHub Issue numbers (if any): PL-52053

[PL-52053] Update Gitness to Harness Open Source

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

Updated gitops version table

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md

added clarifications for single host

---

docs/internal-developer-portal/catalog/how-to-create-idp-yaml.md
docs/internal-developer-portal/catalog/yaml-file.md
docs/internal-developer-portal/flows/service-onboarding-pipelines.md

Added docs on account variable support in idp yaml

feat: [IDP-3253]: Added docs on account variable support in idp yaml

---

docs/internal-developer-portal/scorecards/checks-datasources.md

* Please describe your changes: Added the docs on file exists data point for bitbucket datasource
* Jira/GitHub Issue numbers (if any): IDP-3254

feat: [IDP-3254]: Added the docs on file exists data point for bitbucket datasource

---

docs/internal-developer-portal/plugins/available-plugins/bug-snag.md
docs/internal-developer-portal/plugins/available-plugins/harness-iacm.md

* Please describe your changes: Added the docs for bugsnag plugin

feat: [IDP-3260]: Added the docs for bugsnag plugin

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/sptData.ts

Add SEI SPT

---

client_module/iframeEmbed.js

HDH-287-embed-mode-remove-aida-container

---

src/components/HomepageUniversity/Carousel.module.scss
src/components/HomepageUniversity/Carousel.tsx
src/components/HomepageUniversity/index.tsx

HDH-289-validate-carousel-behavior

---

docs/internal-developer-portal/plugins/available-plugins/grpc.md

feat: [IDP-3271]: Added the docs on gRPC plugin

---

release-notes/feature-flags.md

* Please describe your changes: \android 2.2.3 release notes added
* Jira/GitHub Issue numbers (if any): \ffm-11781

android 2.2.3 release notes added

---

release-notes/delegate.md

* Please describe your changes: Add blocked Stackdriver log notice
* Jira/GitHub Issue numbers (if any): PL-55566
* Preview links/images (Internal contributors only): https://669960e35c71ed531c6ee83b--harness-developer.netlify.app/release-notes/delegate

[PL-55566] Add blocked Stackdriver log notice

---

docs/platform/triggers/trigger-on-a-new-artifact.md

Remove GA FF from triggers topic

---

docs/continuous-integration/get-started/overview.md

Corrected the grammar - Removed unneeded of

Corrected the grammar - Removed unneeded of

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md

Add new delegate versions

---

docs/platform/monitored-service.md
docs/platform/triggers/custom-trigger-passing-data.md
docs/platform/triggers/schedule-pipelines-using-cron-triggers.md
docs/platform/triggers/selective-stage-execution-using-triggers.md
docs/platform/triggers/trigger-on-a-new-artifact.md
docs/platform/triggers/trigger-pipelines-from-a-third-party-ci-system.md
docs/platform/triggers/triggers-reference.md

remove ws triggers section

---

docs/continuous-integration/ci-supported-platforms.md
release-notes/continuous-integration.md

- [Version 1.35](https://668d7d57e34150bdf70ab1f4--harness-developer.netlify.app/release-notes/continuous-integration#version-135)
- [Version 1.34](https://668d7d57e34150bdf70ab1f4--harness-developer.netlify.app/release-notes/continuous-integration#version-134)

CI 1.34 and 1.35 release notes

---

docs/internal-developer-portal/plugins/available-plugins/bug-snag.md

* Please describe your changes: Updated the info on bugsnag token

fix: [IDP]: Updated the info on bugsnag token

---

docs/faqs/harness-delegate-faqs.md
docs/platform/delegates/delegate-concepts/delegate-overview.md
docs/platform/delegates/delegate-concepts/delegate-requirements.md

* Please describe your changes: Update delegate docs on the number of parallel executions
* Jira/GitHub Issue numbers (if any): PL-52014
* https://667b1819d506d3273137e8d9--harness-developer.netlify.app/docs/faqs/harness-delegate-faqs#what-are-the-delegate-system-requirements
* https://667b1819d506d3273137e8d9--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-overview#delegate-sizes
* https://667b1819d506d3273137e8d9--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-requirements
If your PR is open …

[PL-52014] Update delegate docs on number of parallel executions

---

docs/chaos-engineering/chaos-faults/kubernetes/pod/shared/io-faults-caution.md
src/components/HomepageUniversity/Carousel.module.scss
src/components/HomepageUniversity/data/universityData.ts
src/components/University/LandingPage.tsx
src/components/University/UniversityIDP.tsx
src/components/University/data/certificationsData.ts

Added IDP Dev Cert and CE Patch

---

docs/chaos-engineering/chaos-faults/kubernetes/pod/shared/io-faults-caution.md
src/components/HomepageUniversity/Carousel.module.scss
src/components/HomepageUniversity/Carousel.tsx

HDH-292-carousel-with-eight-elements-have-a-gap

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md

Added admonition for k8s delegate

---

docs/platform/delegates/delegate-reference/delegate-image-version-status.md

* Please describe your changes: Remove unsupported delegate images from support table

Remove unsupported delegate images from support table

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md
docs/continuous-delivery/manage-deployments/deployment-faqs.md

CD FAQ updates in ECS and Helm Deployment

CD FAQ updates in ECS and Helm Deployment

---

release-notes/security-testing-orchestration.md

STO Release Notes: Week of 2024-07-14

---

docs/software-engineering-insights/early-access/integrations/sei-integration-servicenow.md

feat: [SEI-7608]: ServiceNow permissions updated

---

src/components/HomepageUniversity/Carousel.tsx
src/components/University/styles.module.scss
yarn.lock

HDH-288-prep-for-next-ds-upgrade

---

package.json
tsconfig.json
yarn.lock

Tweaks to Core JS

---

release-notes/feature-flags.md

* Please describe your changes: \python sdk 1.6.4 release notes added
* Jira/GitHub Issue numbers (if any): \FFM-11771

python sdk 1.6.4 release notes added

---

kb/cloud-cost-management/cloud-cost-management-faqs.md

[CCM-18675]

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md

Ad hoc update for copy config path creation behavior

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md

Added, K8s

---

release-notes/chaos-engineering.md

CHAOS-6181 Release notes 1.41.1

---

docs/infra-as-code-management/get-started/onboarding-guide.md
docs/infra-as-code-management/remote-backends/state-migration.md

* Update state migration instruction to correctly reflect usage.
* [JIRA](https://harness.atlassian.net/browse/IAC-2177)

docs: [IAC-2177]: Update state migration instruction

---

src/components/Roadmap/data/roadmapData.ts
src/components/Roadmap/data/sscaData.ts

[SSCA-2320] Update SSCA Roadmap for Q3

---

release-notes/software-supply-chain-assurance.md

Add SSCA Release Notes for v1.14.3

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-apply-step.md
docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md

Add admonition for k8s deployments with delegate selectors

---

release-notes/platform.md

* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-55543

[PL-55543] PL 1.48.xx Release Notes

---

release-notes/cloud-cost-management.md

Added release notes

---

release-notes/delegate.md

Update delegate.md for security update notice

---

docs/chaos-engineering/get-started/powered-by-litmus.md
src/components/Docs/data/chaosEngineeringData.ts
src/components/Docs/data/chaosEngineeringData_Complex.ts

[update landing page](https://66a143d956955015bb4e010c--harness-developer.netlify.app/docs/chaos-engineering)
Update hce and litmus page

CHAOS-6213 update landing page

---

release-notes/chaos-engineering.md
src/components/Docs/data/chaosEngineeringData.ts
src/components/Docs/data/chaosEngineeringData_Complex.ts

Update date in the release notes

Update date in the release notes

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/3-setting_up_CO.md

added tango for cluster

---

docs/internal-developer-portal/api-refernces/public-api.md

feat: [IDP-3306]: Added the instructions to delete the orphaned entities

---

release-notes/software-engineering-insights.md

feat: [SEI-7733]: Release migrated version 202407.2

---

release-notes/self-managed-enterprise-edition.md

* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-55727

[PL-55727] SMP 0.18.1 Patch Release Notes

---

docs/harness-cloud-operations/tenancy.md

Update tenancy.md for content modification

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/k8s-dry-run.md

fix:[CDS-99376]: add warning regarding literal in the shell script step in kubernetes dry run step doc

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/container-step.md

deprecation for container step

---

docs/software-engineering-insights/sei-metrics-and-reports/dora-metrics/dora-onboarding.md

feat: [SEI-7180]: Github onboarding limit

---

docs/software-engineering-insights/sei-metrics-and-reports/dora-metrics/dora-onboarding.md
docs/software-engineering-insights/sei-profiles/workflow-profile.md

feat: [SEI-7781]: CICD CORRELATION NOTE ADDED

---

release-notes/security-testing-orchestration.md

STO Release Notes for Week of 2024-07-21

---

docs/software-engineering-insights/get-started/sei-subscription-and-licensing.md

feat: [SEI-7782]: SEI Subscriptions and Licenses

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/sptData.ts

Added CCM SPT

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.36 and 1.37 Release Notes

CI 1.36 and 1.37 RN for CI.

---

docs/chaos-engineering/features/chaos-infrastructure/connect-chaos-infrastructures.md
docs/chaos-engineering/features/chaos-infrastructure/harness-infra/harness-infra.md
docs/chaos-engineering/features/chaos-infrastructure/introduction.md

CHAOS-6261 Update content

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md

This PR updates [this page](https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure/#configure-cluster-and-build-infrastructure) based on [this discussion](https://harness.slack.com/archives/C013KJMDV0U/p1720417463172819).
[JIRA](https://harness.atlassian.net/browse/CI-13352)
[Preview Link](https://668e9fa0cfb6d12309c1458a--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure)

Update windows custom image info note.

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md

This PR adds a missing requirement for K8s build infra per https://harness.atlassian.net/browse/CI-13459
Checklist:

Add requirement to open port 20001.

---

docs/platform/delegates/install-delegates/docker-delegate-to-ecs-fargate.md

fixed typos, consistency

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-load-balancer/create-an-application-gateway-for-azure.md

[CCM-16902]: Minor fix autostopping

---

sidebars.js
src/css/custom.css

* Please describe your changes: \____________Adding module logos in sidebar______________________
* Jira/GitHub Issue numbers (if any): \___HDH 294___________________________
* Preview links/images (Internal contributors only): \_____
_____________

HDH-294-investigate-icons-on-sidebar

---

docs/harness-cloud-operations/computing-uptime.md
release-notes/security-testing-orchestration.md

fix: [STO-7190]: Update STO SLIs and fix-up existing release notes

---

docs/continuous-delivery/gitops/use-gitops/harness-git-ops-agent-with-self-signed-certificates.md

Update harness-git-ops-agent-with-self-signed-certificates.md to add steps for mounting certs with Helm

---

docs/code-repository/work-in-repos/keyword-search.md

Adding documentation on recursive keyword code search

---

docusaurus.config.js
sidebars.js

Cleaned up order of nav - left and top for Docs

Cleaned up order of nav - left and top for Docs

---

src/components/Docs/data/iacmData.ts

* Add IaCM onboarding tile to IaCM landing doc under Get Started panel
* [JIRA](https://harness.atlassian.net/browse/IAC-2279)
https://github.com/user-attachments/assets/ece5001e-3f82-4bfe-9b6d-5b895d2cec5a

docs: [IAC-2279]: Add IaCM onboarding tile to get started panel

---

docs/software-engineering-insights.md
src/components/Docs/SoftwareEngineeringInsights.tsx
src/components/Telemetry/TememetryConstants.ts
src/components/Telemetry/index.tsx

feat: [SEI-7828]: Add SEI Telemetry data into Segment [WIP]

---

release-notes/platform.md

* Please describe your changes: https://harness.slack.com/archives/C011SD1S1U3/p1722500714452489
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-55887

[PL-55887] change in version number as requested

---

docs/platform/shared/delegate-legacy-eos.md

Update delegate-legacy-eos.md for delegate upgrade steps

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md

* Please describe your changes: fix error in supported architectures for Cloud

fix error in supported architectures for Cloud

---

.github/CODEOWNERS
sidebars-kb.js
sidebars-university.js

* Sidebar Icons on KB and Univ
* Update to Codeowners

Updated Sidebar Icons and Codeowners

---

docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-functions-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
kb/continuous-delivery/faqs.md

FAQs: [CDS-99282, CDS-99642]: FAQs addition for CD

---

.github/CODEOWNERS

Add Vishal in CODEOWNERS of CD

---

docs/continuous-delivery/manage-deployments/deployment-freeze.md

Added the following note to /continuous-delivery/manage-deployments/deployment-freeze "Account admins are always able to bypass deployment freeze windows"

[CDS-99587] Added note to deployment-freeze

---

release-notes/infrastructure-as-code-management.md

* Backfilled Release Notes for IaCM from late April to June 24
* [JIRA](https://harness.atlassian.net/browse/IAC-2239)

docs: [IAC-2239]: Backfilled IaCM Release Notes

---

docs/first-gen/continuous-delivery/continuous-verification/custom-metrics-and-logs-verification/monitor-applications-24-7-with-custom-metrics.md
docs/first-gen/continuous-delivery/continuous-verification/custom-metrics-and-logs-verification/verify-deployments-with-custom-metrics.md
docs/hdh/hdh-docusaurus-sandbox.md
docusaurus.config.js
package.json
yarn.lock

HDH-297-add-math-packages-to-ds

---

docs/internal-developer-portal/catalog/catalog-scripts.md

fix: [IDP]: Fixed issues with catalog scripts docs

---

docs/hdh/hdh-docusaurus-sandbox.md

Updating Escape Characters

---

src/components/Roadmap/HorizonCard/index.tsx
src/components/Roadmap/data/roadmapData.ts
src/components/Roadmap/index.tsx

Updated to allow background colors in cards

---

docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-gcp.md

[CCM-14135]: Update set-up-cost-visibility-for-gcp.md

---

src/components/Roadmap/data/cdData.ts

* Preview links/images (Internal contributors only): https://github.com/harness/developer-hub/pull/7588 

roadmap rough draft

---

docs/platform/delegates/manage-delegates/upgrade-legacy-delegate.md

Create Upgrade Delegate

---

docs/database-devops/get-started/onboarding-guide.md
docs/database-devops/get-started/overview.md

* Please describe your changes: \ making edits and corrections to the db devops docs
* Jira/GitHub Issue numbers (if any): \ DBOPS-326

making edits and corrections to the db devops docs

---

src/components/Roadmap/data/cdData.ts

hotfix description

---

release-notes/continuous-delivery.md

CD Release notes 1.49.5

---

release-notes/continuous-delivery.md

add pipeline release notes in 1.36.5 release

---

release-notes/continuous-delivery.md

fix:[PIPE-20901]: Fix release notes for 1.39.4

---

docs/feature-flags/_category_.json
docs/feature-flags/get-started/_category_.json
docs/feature-flags/subscribe-ff/_category_.json
src/css/custom.css

Fix for FF Icons

---

kb/software-engineering-insights/articles/how-to-onboard-devs-on-sei.md

SEI KB quick fix

---

docs/platform/delegates/manage-delegates/upgrade-legacy-delegate.md

Update upgrade-legacy-delegate.md to contact support

---

src/components/Roadmap/data/platformData.ts

Update platformData.ts update

---

src/components/Roadmap/data/idpData.ts

IDP: update roadmap Q3

---

docs/internal-developer-portal/plugins/available-plugins/opsgenie.md

[IDP-3334]: fix: Update opsgenie.md

---

docs/chaos-engineering/troubleshooting/known-issues.md

CHAOS-6310 Update known issues

---

docs/internal-developer-portal/plugins/available-plugins/grafana.md

fix: [IDP]: Updated the docs with annotation information on grafana

---

release-notes/continuous-delivery.md

fix 1.48.x version and move 1.49.x in August month

---

docs/internal-developer-portal/flows/custom-actions.md

* Please describe your changes: Added the info on git experince for custom actions

fix: [IDP]: Added the info on git experince for custom actions

---

src/components/Roadmap/data/ceData.ts

Updating the Chaos Roadmap for Q3-2024 and beyond

Updating the Chaos Roadmap for Q3-2024 and beyond

---

src/components/Roadmap/data/srmData.ts

Update the roadmap details starting with Q3 2024

Update SRM roadmap for Q3-2024

---

src/components/Roadmap/data/ciData.ts

roadmap update

---

docs/continuous-integration/development-guides/security/_category_.json
docs/continuous-integration/development-guides/security/git_revert_from_pr.md
docs/continuous-integration/use-ci/codebase-configuration/git-revert-commit.md

* Please describe your changes: Adds a document to show git revert using Run step
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CI-13574

Add git revert in CI docs.

---

sidebars.js

Updated FF API Doc

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/LandingPage.tsx
src/components/University/UniversitySEI.tsx
src/components/University/data/certificationsData.ts

Launching SEI Dev Cert

---

docs/platform/git-experience/oauth-integration.md

fix: [PIPE-20740]: add info that we currently do not support OAuth authentication for Git providers that use vanity URLs

---

docs/code-repository/work-in-repos/keyword-search.md
src/components/Roadmap/data/codeData.ts

Updating 2024 Q3 Code Repo roadmap and adding documentation for regex search

Q3 Code Repo roadmap and documentation for regex search

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/iltData.ts

Added CCM ILT

---

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md

feat: [CDS-99673]: Docs for remote service, env prequisite for remote overrides

---

release-notes/continuous-integration.md

This PR moves a notice to the right place per comment and removes a repeat text.

Move notice to the right place and chores.

---

docs/continuous-delivery/gitops/use-gitops/harness-git-ops-agent-with-self-signed-certificates.md

remove self managed

---

release-notes/delegate.md
release-notes/platform.md

* Please describe your changes: Platform 1.51.x release notes
* Jira/GitHub Issue numbers (if any): [PL-56035](https://harness.atlassian.net/browse/PL-56035)
[PL-56035]: https://harness.atlassian.net/browse/PL-56035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56035] PL 1.51.x Release Notes

---

docs/chaos-engineering/chaos-faults/linux/linux-network-corruption.md
docs/chaos-engineering/chaos-faults/linux/linux-network-duplication.md
docs/chaos-engineering/chaos-faults/linux/linux-network-latency.md
docs/chaos-engineering/chaos-faults/linux/linux-network-loss.md
docs/chaos-engineering/chaos-faults/linux/linux-network-rate-limit.md

* Please describe your changes: Adds whitelist SSH port inputs in LCI network faults

feat: [CHAOS-5621]: Adds whitelist SSH port input

---

src/components/Roadmap/data/sscaData.ts

[SSCA-2320] Update SSCA Roadmap for Q3 - New

---

kb/chaos-engineering/chaos-engineering-faq.md

CHAOS-6351 Add FAQs

---

docs/chaos-engineering/onboarding/guided-onboarding.md
docs/chaos-engineering/onboarding/hce-onboarding.md
docs/chaos-engineering/onboarding/single-click-onboarding.md

Remove feature flag since the feature is enabled by default now.

CHAOS-6309 Remove feature flag

---

docs/platform/connectors/code-repositories/ref-source-repo-provider/git-connector-settings-reference.md

[PIPE-20112] Added warning related to git connector SSH URL

---

release-notes/software-engineering-insights.md

feat: [SEI-7926]: Added release notes for patch releases

---

package.json
src/theme/DocCard/index.tsx
yarn.lock

HDH-303-investigate-ds-3-5-1-build-warnings-errors

---

release-notes/continuous-delivery.md

[CDS-99734] CD release notes 1.51.x

---

src/components/Roadmap/data/seiData.ts

Q3FY25 Update

---

release-notes/feature-flags.md

* Please describe your changes: \javascript sdk release notes updated
* Jira/GitHub Issue numbers (if any): \FFM-11825

javascript sdk release notes updated

---

docs/continuous-integration/use-ci/run-tests/tests-v2.md

For the V2 Test Intelligence it requires Python 3, added an info box, matching the V1 documentation and verified that the FAQ is correct. 

Added info box requiring Python 3

---

sidebars.js

Typo Refrence -> Reference

---

sidebars.js

Patch CD Link

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.17.3 Release Notes
* Jira/GitHub Issue numbers (if any): [PL-56101](https://harness.atlassian.net/browse/PL-56101)
[PL-56101]: https://harness.atlassian.net/browse/PL-56101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SMP 0.17.3 Release Notes

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.18.2 Release Notes
* Jira/GitHub Issue numbers (if any): [PL-56073](https://harness.atlassian.net/browse/PL-56073)
[PL-56073]: https://harness.atlassian.net/browse/PL-56073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SMP 0.18.2 Release Notes

---

release-notes/delegate.md

* Please describe your changes: 833xx, 834xx, 836xx DELEGATE RN
* Jira/GitHub Issue numbers (if any): [PL-56116](https://harness.atlassian.net/browse/PL-56116)
[PL-56116]: https://harness.atlassian.net/browse/PL-56116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

833xx, 834xx, 836xx DELEGATE RN

---

docs/hdh/hdh-docusaurus-sandbox.md
netlify/functions/api_proxy.mts
src/components/HarnessApiData/index.tsx
src/theme/MDXComponents.js

* Preview links/images (Internal contributors only): \_______
___________

HDH-295-remote-api-call-c-url-plugin-for-hdh-dynamic-material

---

docs/feature-flags/use-ff/ff-creating-flag/tag_management.md

* Please describe your changes: \adding instructions for rbac by tagging
* Jira/GitHub Issue numbers (if any): \FFM-11278

adding instructions for rbac by tagging

---

release-notes/feature-flags.md

* Please describe your changes: \ javascript release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11883

javascript release notes added

---

release-notes/continuous-integration.md

* Please describe your changes: Adds CI 1.41 RN
* Preview links/images (Internal contributors only): [Preview](https://66bb642b7cf6ac3d8176e903--harness-developer.netlify.app/)

Add CI 1.41 RN.

---

docs/continuous-delivery/cd-infrastructure/_category_.json
docs/continuous-delivery/cd-integrations.md
docs/continuous-delivery/cd-onboarding/_category_.json
docs/continuous-delivery/deploy-srv-diff-platforms/_category_.json
docs/continuous-delivery/get-started/_category_.json
docs/continuous-delivery/manage-deployments/_category_.json
docs/continuous-delivery/toolchain-policy.md
docs/continuous-delivery/x-platform-cd-features/_category_.json

Upgrade policy made

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md

[CDS-99852] Added warning for Download Artifact process
[CDS-99852]: https://harness.atlassian.net/browse/CDS-99852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

[CDS-99852] Added warning for Download Artifact Command

---

docs/chaos-engineering/using-harness-ce/experiments/create-experiments.md

CHAOS-6331 add create-experiments

---

docs/chaos-engineering/features/experiments/halt-chaos-experiments.md
docs/chaos-engineering/features/resilience-probes/datadog-probe.md
docs/chaos-engineering/features/resilience-probes/http-probe.md
docs/chaos-engineering/features/resilience-probes/k8s-probe.md
docs/chaos-engineering/features/resilience-probes/prom-probe.md
docs/chaos-engineering/features/resilience-probes/slo-probe.md

CHAOS-6156 update halt-experiments

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md

This PR updates the formatting for a link.

Change formatting for link.

---

release-notes/delegate.md

* Please describe your changes: Removed DEL Version 24.07.83503 RN

Removed DEL Version 24.07.83503 RN

---

release-notes/self-managed-enterprise-edition.md

* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-55745

[PL-55745] SMP 0.19.0 Release Notes

---

release-notes/platform.md

* Please describe your changes: PL 1.52.x Release notes
* Jira/GitHub Issue numbers (if any): [PL-56169](https://harness.atlassian.net/browse/PL-56169)
[PL-56169]: https://harness.atlassian.net/browse/PL-56169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PL-56169]: …

[PL-56169]: PL 1.52.x Release notes

---

release-notes/feature-flags.md

* Please describe your changes: Adds relay proxy release notes
* Jira/GitHub Issue numbers (if any): FFM-11897

FFM-11897 proxy 2.0.3 release notes

---

docs/infra-as-code-management/get-started/overview.md

* Update IaCM overview doc to switch perspective from common issues to feature focused
* [JIRA](https://harness.atlassian.net/browse/IAC-2344)

docs: [IAC-2344]: Update iacm overview

---

sidebars.js
src/css/custom.css
static/img/All_Docs_Logo.svg

HDH-301-implement-hdh-docs-nav-2-0

---

release-notes/delegate.md

* Please describe your changes: DEL 24.07.83608 RN
* Jira/GitHub Issue numbers (if any): [PL-56171](https://harness.atlassian.net/browse/PL-56171)
[PL-56171]: https://harness.atlassian.net/browse/PL-56171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56171]: DEL 24.07.83608 RN

---

docs/platform/triggers/trigger-deployments-using-custom-triggers.md

Clarification on

---

release-notes/feature-flags.md

* Please describe your changes: \ added java sdk notes
* Jira/GitHub Issue numbers (if any): \ FFM-11905

added java sdk notes

---

release-notes/feature-flags.md

* Please describe your changes: \_typo correction
* Jira/GitHub Issue numbers (if any): \_FFM-11905

typo correction

---

release-notes/feature-flags.md

Merge main into my branch

---

release-notes/continuous-delivery.md

[CDS-100013] CD Release notes 1.52.4

---

release-notes/continuous-delivery.md

Updated Release Notes 1.52.4

---

docs/software-engineering-insights/sei-diagnostics.md
release-notes/software-engineering-insights.md

chore: [SEI-8006]: SEI Release notes related docs

---

docs/internal-developer-portal/plugins/available-plugins/harness-ci-cd.md
docs/internal-developer-portal/plugins/available-plugins/jira.md

feat: IDP: Emphasised on points which folks miss out while adding the jira plugin

---

docs/software-engineering-insights/sei-integrations/semi-automated-integrations/jenkins-plugin.md

feat: [SEI-7938]: Jenkins Configuration as Code support

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md

feat:[CDS-99605]: Add JSON for pipeline events in webhook notification

---

release-notes/delegate.md

* Please describe your changes: DELEGATE RN Notice Update
* Jira/GitHub Issue numbers (if any): [PL-56272](https://harness.atlassian.net/browse/PL-56272)
[PL-56272]: https://harness.atlassian.net/browse/PL-56272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56272]: DELEGATE RN Notice Update

---

release-notes/delegate.md

* Please describe your changes: DEL 24.07.83609 Hotifx RN
* Jira/GitHub Issue numbers (if any): [PL-56270](https://harness.atlassian.net/browse/PL-56270)
[PL-56270]: https://harness.atlassian.net/browse/PL-56270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56270]: DEL 24.07.83609 Hotifx RN

---

kb/cloud-cost-management/articles/best-practices/aws-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/azure-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/gcp-connectors-and-roles.md

ccm best practices updates from customer feedback

---

.github/CODEOWNERS
kb/armory/General/_category_.json
kb/armory/armory-faqs.md

Patched Armory KB

---

docs/internal-developer-portal/catalog/catalog-scripts.md

fix: [IDP]: Updated the not found error in the catalog script

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP Patch 0.19.1 RN
* Jira/GitHub Issue numbers (if any): [PL-56352](https://harness.atlassian.net/browse/PL-56352)
[PL-56352]: https://harness.atlassian.net/browse/PL-56352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56352]: SMP Patch 0.19.1 RN

---

docs/database-devops/get-started/key-concepts.md

* Please describe your changes: \key concepts doc for db devops
* Jira/GitHub Issue numbers (if any): \ DBOPS-440

key concepts doc for db devops

---

docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md

Added status step to docs

---

docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md

Fix URL for ECR Registry for Harness Internal Images

Fix URL for ECR Registry for Harness Internal Images

---

docs/internal-developer-portal/get-started/setup-git-integration.md

fix: [IDP-123]: Update repository path info

---

docs/internal-developer-portal/get-started/enable-docs.md

fix: [IDP-7]: Update techdocs support on HCR

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md

fix: [CDS-99546]: Update AWS SAM Images for multiple runtime

---

docs/chaos-engineering/chaos-faults/windows/prerequisites.md
docs/chaos-engineering/get-started/ce-on-smp/ce-smp-roadmap.md
docs/chaos-engineering/troubleshooting/troubleshooting.md

CHAOS-6433 Add troubleshooting content

---

docs/continuous-delivery/verify/cv-whats-supported.md

fix: [CDS-93300]: Add limitation of DataDog

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.19.2 patch version RN
* Jira/GitHub Issue numbers (if any): [PL-56356](https://harness.atlassian.net/browse/PL-56356)
[PL-56356]: https://harness.atlassian.net/browse/PL-56356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56356]: SMP 0.19.2 patch version RN

---

src/components/LandingPage/TutorialCard.module.scss
src/components/LandingPage/styles.module.scss
src/components/LearnAboutPlatform/styles.module.scss
src/components/Roadmap/HorizonCard/styles.module.scss
src/css/custom.css

Additional Gitness CSS

---

docs/internal-developer-portal/rbac/resources-roles.md

feat: [IDP-3578]: Enhanced the RBAC docs

---

docusaurus.config.js
sidebars-university.js
university/faqs.md
university/instructions.md

Instructions for Instruqt

---

docs/internal-developer-portal/rbac/resources-roles.md

Tweaks around IDP workflows access control docs

---

release-notes/platform.md

* Please describe your changes: PL 1.53x RN
* Jira/GitHub Issue numbers (if any): [PL-56353]
[PL-56353]: https://harness.atlassian.net/browse/PL-56353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56353]: PL 1.53x RN

---

docs/continuous-delivery/cd-onboarding/new-user/rampup-templates.md

* Please describe your changes: This PR updates the versioning recommendations in the Template on boarding guide.  The updated comment represents the current state of best practices and customer recommendations.
* Jira/GitHub Issue numbers (if any): none

Update template versioning best practices

---

kb/continuous-delivery/articles/api-list-of-execution-ids-execution-details-in-one-call.md

feat: [PIPE-19211]: KB - API to get list of plaExecutionIDs and all execution details

---

release-notes/chaos-engineering.md

CHAOS-6393 Release notes 1.43.3

---

docs/chaos-engineering/architecture-and-security/architecture/control-plane.md

Correct content in interaction b/n execution and control plane

CHAOS-6471 Correct content in interaction b/n execution and control plane

---

docs/hdh/hdh-docusaurus-sandbox.md
netlify/functions/api_proxy.mts
package.json
src/components/HarnessApiData/index.tsx
yarn.lock

Hdh 309 api caller allow for updated parse command e g like jq in the caller

---

docs/internal-developer-portal/tutorials/service-onboarding-pipeline.md

fix: [IDP]: Fixed typo

---

src/components/Roadmap/data/ccmData.ts

new roadmap

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.43 release notes based on https://harness.atlassian.net/wiki/spaces/CI1/pages/21973926030

CI 1.43 RN.

---

docusaurus.config.js
sidebars.js

Added Gitness to top-nav and left-nav

---

_server-redirects

Updated Server re-direct

---

docs/platform/triggers/trigger-deployments-using-custom-triggers.md
docs/platform/triggers/triggers-reference.md

add executions info for custom triggers

---

release-notes/continuous-delivery.md

release notes 1.53.5

---

release-notes/continuous-delivery.md

Reverts harness/developer-hub#7781

Revert "release notes 1.53.5"

---

kb/continuous-delivery/faqs.md
release-notes/continuous-delivery.md

Updated CD release notes

---

sidebars-community.js

Updated Community Icons

---

docusaurus.config.js
src/components/NavbarItems/CoveoSearch.scss
src/css/custom.css

Hdh 314 adjust top nav re active

---

src/components/HarnessApiData/index.tsx

HDH API caller fix

---

docs/continuous-delivery/toolchain-policy.md

Updated Jenkins version to 2.440

---

static/robots.txt

* Please describe your changes: \Clean up robots.txt - merge disallows of the same user-agent
* Jira/GitHub Issue numbers (if any): \N/A
* Preview links/images (Internal contributors only): \N/A

Chore: Clean up robots.txt - merge disallows of the same user-agent

---

docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-attribute-override.md
docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-error.md
docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-latency.md
docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-mistake.md
docs/chaos-engineering/chaos-faults/kubernetes/pod/shared/io-faults-caution.md
docs/chaos-engineering/chaos-faults/load/k6-loadgen.md
docs/chaos-engineering/chaos-faults/load/locust-loadgen.md

chore: [CHAOS-6498]: Update IO Chaos docs to add supported methods and error codes

---

kb/continuous-delivery/faqs.md
kb/platform/harness-platform-faqs.md
kb/platform/pipeline-faq.md

q3 faq by nandeesh

---

docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-winrm-faqs.md

add amit-faq

---

docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md

add brijesh-faq-pr

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-faqs.md
kb/continuous-delivery/faqs.md

kartikeya-faq-pr-q2

---

release-notes/infrastructure-as-code-management.md

* August 2024 release notes entry for iac-server v1.50 and iac-manager 1.32
* [JIRA](https://harness.atlassian.net/browse/IAC-2413)

docs: [IAC-2413: IACM Release Notes entry

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md

[CDS-97217] Updating attach alarm to scaling policy

---

docs/software-engineering-insights/sei-metrics-and-reports/dora-metrics/dora-metrics.md

added bullet points

---

docs/internal-developer-portal/whats-supported.md

fix: [IDP]: Updated the whats supported page to remove a limitation

---

docs/continuous-integration/secure-ci/secure-connect.md

* Please describe your changes: ports range update for secure connect 

ports range update for secure connect 

---

docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/integrations/integrations-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-application-service-deployment-faqs.md

Faqs: [CDS-100007]: Addition of CD Faqs

---

docs/platform/git-experience/autocreation-of-entities.md

* Please describe your changes: \___ Customer was confused and did not understand the application for this feature flag.  Added some clarification about what this feature is
* Jira/GitHub Issue numbers (if any): \_____ https://harnesssupport.zendesk.com/agent/tickets/68464

(Update) AutoCreation of Entities

---

docs/platform/delegates/secure-delegates/delegate-read-only-file-system-config-guide.md

* Please describe your changes: Running Harness Delegate on a Read-Only File System DOC
* Jira/GitHub Issue numbers (if any): [PL-55612](https://harness.atlassian.net/browse/PL-55612)
* Preview links/images (Internal contributors only): https://66cd65aa99b6638c361c6eff--harness-developer.netlify.app/docs/platform/delegates/secure-delegates/delegate-read-only-file-system-config-guide
[PL-55612]: …

[PL-55612]: Running Harness Delegate on a Read-Only File System DOC

---

docs/infra-as-code-management/get-started/key-concepts.md

* Update IaCM Key concepts page for better readability
* [JIRA](https://harness.atlassian.net/browse/IAC-2419)

docs: [IAC-2419]: Update IaCM key concepts

---

release-notes/feature-flags.md

* Please describe your changes: \_python sdk release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-11940

python sdk release notes added

---

release-notes/delegate.md

[CDS-100389]/[CDS-100046]: Delegate HF release notes 

---

_server-redirects

Update _server-redirects for CD AWS category

---

docs/internal-developer-portal/plugins/available-plugins/snyk.md

feat: [IDP-3643]: Added the snyk plugin docs

---

docusaurus.config.js

* Please describe your changes: \ remove "infra-as-code-management" from Sitemap Ignore Patterns
* Jira/GitHub Issue numbers (if any): \ N/A
* Preview links/images (Internal contributors only): \ N/A

Chore: remove "infra-as-code-management" from Sitemap Ignore Patterns

---

release-notes/internal-developer-portal.md

feat: [IDP-3650]: Added the release notes for v0.32.0

---

docs/platform/git-experience/gitexp-bidir-sync-setup.md

* Please describe your changes: Fix typo.

Fix typo in gitexp-bidir-sync-setup.md

---

docs/internal-developer-portal/plugins/available-plugins/harness-chaos.md
docs/internal-developer-portal/plugins/available-plugins/harness-feature-flags.md
docs/internal-developer-portal/plugins/available-plugins/harness-iacm.md

fix: [IDP]: Fixed the layout instructions for plugins

---

docs/infra-as-code-management/whats-supported.md

* Remove feature flags table from IaCM What's Supported doc
* [JIRA](https://harness.atlassian.net/browse/IAC-2426)

doc: [IAC-2426]: Remove support feature flags table

---

docs/feature-flags/use-ff/ff-target-management/targeting-users-with-flags.md

* Please describe your changes: Add note to be clear that for large customers we only support searching targets by exact identifier matches
* Jira/GitHub Issue numbers (if any): FFM-11966

feat: [FFM-11966]: docs update for target searching

---

docs/feature-flags/get-started/webhook-for-ff.md
docs/feature-flags/use-ff/webhook-for-ff.md

* Please describe your changes: \webhook doc for feature flag
* Jira/GitHub Issue numbers (if any): \FFM-11729

webhook doc for feature flag

---

release-notes/chaos-engineering.md

CHAOS-6540 Add release notes 1.44.3

---

docs/code-repository/work-in-repos/labels.md

Added new page for creating and editing labels within Harness Code

adding labels documentation

---

release-notes/delegate.md

RN for delegate proxy url fix

---

release-notes/software-engineering-insights.md

feat: [SEI-8253]: Release notes added

---

docs/platform/delegates/delegate-concepts/delegate-overview.md

* Please describe your changes: Update recommendation on disabling stackdriver
* Jira/GitHub Issue numbers (if any): [PL-55760](https://harness.atlassian.net/browse/PL-55760)
* Preview links/images (Internal contributors only): https://66d19c68655357d9d6ac1785--harness-developer.netlify.app/docs/platform/delegates/delegate-concepts/delegate-overview/
[PL-55760]: …

[PL-55760]: Update recommendation on disabling stackdriver

---

docs/software-engineering-insights/early-access/sei-early-access-overview.md
docs/software-engineering-insights/sei-supported-platforms.md
release-notes/software-engineering-insights.md

Gitlab early access

---

docusaurus.config.js

Update themes to github and vscode dark with additional languages support for prism.
Waiting for preview build to show up and will share screenshots to compare.
cc @ravilach @deba-harness

YAML and JSON code block syntax highlighting

---

docs/database-devops/get-started/onboarding-guide.md

* Please describe your changes: \added warning for feature flag req in db devops
* Jira/GitHub Issue numbers (if any): \DBOPS-496

added warning for feature flag req in db devops

---

docs/software-engineering-insights/sei-integrations/automated-integrations/sei-github-integration.md
docs/software-engineering-insights/sei-integrations/automated-integrations/sei-jira-integration.md

feat: [SEI-8260]: Re-auth docs added

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.20.0 RN
* Jira/GitHub Issue numbers (if any): [PL-56710](https://harness.atlassian.net/browse/PL-56710)
[PL-56710]: https://harness.atlassian.net/browse/PL-56710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56710]: SMP 0.20.0 RN

---

docs/platform/git-experience/autocreation-of-entities.md

feat: [PIPE-21469]: Add overrides in autocreation doc

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: reformat smp release notes page

[PL-56710]: reformat smp release notes page

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md

feat: [CDS-100658]: Add new SAM images for python,ruby,java,go

---

docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md

* Update plan command info to include newly supported options.
* [JIRA](https://harness.atlassian.net/browse/IAC-2437)

docs: [IAC-2437]: Update plan command support info

---

docs/continuous-delivery/get-started/cd-tutorials/aws-lambda.md
docs/continuous-delivery/get-started/cd-tutorials/gcp-cloud-func.md
docs/continuous-delivery/get-started/cd-tutorials/helm-chart.md
docs/continuous-delivery/get-started/cd-tutorials/kustomize.md
docs/continuous-delivery/get-started/cd-tutorials/manifest.md
docs/continuous-delivery/get-started/cd-tutorials/ownapp.md

Deprioritize the CLI in tabs

---

docs/continuous-delivery/cd-infrastructure/provisioning-faqs.md
kb/continuous-delivery/faqs.md

[CDS-99994] Added CD FAQ

---

release-notes/self-managed-enterprise-edition.md

Adding gitops service version in 0.20.0

---

release-notes/feature-flags.md

* Please describe your changes: Adds proxy release notes
* Jira/GitHub Issue numbers (if any): [FFM-11983](https://harness.atlassian.net/browse/FFM-11983)
[FFM-11983]: https://harness.atlassian.net/browse/FFM-11983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FFM-11983 Proxy 2.0.4 release notes

---

src/components/Roadmap/data/fmeData.ts

* Please describe your changes: \___Guardrail Metric Alerts released to 100%______
* Jira/GitHub Issue numbers (if any): \none

Update fmeData.ts to release Guardrail Metric Alerts

---

docs/security-testing-orchestration/sto-techref-category/checkov-iac-scan.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
docs/security-testing-orchestration/sto-techref-category/wiz/artifact-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/repo-scans-with-wiz.md

Document Checkov step

---

release-notes/platform.md

* Please describe your changes: PL 1.55.x releae notes
* Jira/GitHub Issue numbers (if any): [PL-56824](https://harness.atlassian.net/browse/PL-56824)
[PL-56824]: https://harness.atlassian.net/browse/PL-56824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56824]: PL 1.55.x releae notes

---

docs/software-engineering-insights/sei-technical-reference/sei-datasheets/sei-servicenow-datasheet.md

Update SNow datasheet

---

docs/continuous-integration/use-ci/run-tests/viewing-tests.md

* Please describe your changes: CI-13784

added docs for parse results plugin CI-13784

---

release-notes/feature-flags.md

* Please describe your changes: \release notes for react client added
* Jira/GitHub Issue numbers (if any): \FFM-11982

release notes for react client added

---

release-notes/feature-flags.md

* Please describe your changes: \javascript sdk release notes added
* Jira/GitHub Issue numbers (if any): \FFM-11975

javascript sdk release notes added

---

release-notes/feature-flags.md

* Please describe your changes: \react native sdk release notes added
* Jira/GitHub Issue numbers (if any): \FFM-11985

react native sdk release notes added

---

docs/chaos-engineering/features/image-registry.md

CHAOS-6743 Update image-registry.md

---

docs/platform/delegates/troubleshooting/certificate-issues.md

* Please describe your changes: Add instructions to delegate installation troubleshooting page when using vanity URLs
* Jira/GitHub Issue numbers (if any): [CI-13697](https://harness.atlassian.net/browse/CI-13697)
* Preview links/images (Internal contributors only): [here](https://66d7197d1c073f48c2b4f47a--harness-developer.netlify.app)
[CI-13697]: …

Add troubleshooting notes for cert issues with vanity URLs.

---

docs/infra-as-code-management/workspaces/workspace-expressions.md

* Add migration details to update old expressions to adhere to our new workspace expression 
* [JIRA](https://harness.atlassian.net/browse/IAC-2470)

docs: [IAC_2470]: Add workspace expression migration guide

---

docs/internal-developer-portal/plugins/available-plugins/image-jfrog.md
docs/internal-developer-portal/plugins/available-plugins/jfrog.md

Fix indentation in layouts of IDP JFrog plugins

---

docs/platform/settings/default-settings.md

* Please describe your changes: CI-14203

Update default-settings CI-14203

---

release-notes/security-testing-orchestration.md

Publish STO release notes for week of 2024-09-01

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md

fix:[CDS-100527]: Add client key certificate information

---

docs/internal-developer-portal/plugins/available-plugins/sonarqube.md

fix: [IDP]: Removed mention of an internal sq instance

---

release-notes/continuous-delivery.md

[CDS-100759] CD release notes 1.55.x

---

docs/continuous-delivery/x-platform-cd-features/services/harness-file-store-faqs.md

fix: [CDS-100280]: Remove FAQ from the section

---

docs/software-engineering-insights/sei-technical-reference/sei-datasheets/sei-azure-boards-datasheet.md
docs/software-engineering-insights/sei-technical-reference/sei-datasheets/sei-azure-pipelines-datasheet.md
docs/software-engineering-insights/sei-technical-reference/sei-datasheets/sei-azure-repos-datasheet.md

feat: [SEI-8357]: Azure datasheets added

---

docs/internal-developer-portal/flows/service-onboarding-pipelines.md

feat: [IDP]: Added usage`formData` to pre-fill workflows

---

docs/hdh/hdh-docusaurus-sandbox.md

Added canonical_url in Sandbox

---

src/components/NavbarItems/CoveoSearch.js

* Please describe your changes: \ update Coveo template
* Jira/GitHub Issue numbers (if any): \ N/A
* Preview links/images (Internal contributors only): \ N/A

chore: update Coveo template

---

docs/internal-developer-portal/plugins/overview.md

fix: [IDP]: fixed the URL on the overview page

---

release-notes/continuous-integration.md

Update 1.45 release notes

---

docs/continuous-delivery/gitops/use-gitops/add-a-harness-git-ops-repository.md
docs/continuous-delivery/gitops/use-gitops/add-harness-git-ops-repository-credentials-template.md
docs/continuous-delivery/gitops/use-gitops/create-cluster-with-iam.md
docs/continuous-delivery/gitops/use-gitops/harness-git-ops-agent-with-self-signed-certificates.md
docs/continuous-delivery/gitops/use-gitops/manage-permissions.md
docs/continuous-delivery/gitops/use-gitops/sops.md
docs/continuous-delivery/gitops/use-gitops/sync-gitops-applications.md

add rbac sync docs

---

docs/internal-developer-portal/plugins/available-plugins/new-relic.md

feat: [IDP]: Added the docs for New Relic Plugin

---

docs/internal-developer-portal/flows/idp-stage.md

feat: [IDP-3697]: Added the docs on cookiecutter template structure

---

release-notes/platform.md

* Please describe your changes: PL 1.56.x Release Notes
* Jira/GitHub Issue numbers (if any): [PL-56994]
[PL-56994]: https://harness.atlassian.net/browse/PL-56994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-56994]: PL 1.56.x Release Notes

---

release-notes/feature-flags.md

* Please describe your changes: \erlang sdk release notes added
* Jira/GitHub Issue numbers (if any): \FFM-12001

erlang sdk release notes added

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk release notes added
* Jira/GitHub Issue numbers (if any): \ FFM-12002

ruby sdk release notes added

---

docs/continuous-delivery/get-started/key-concepts.md

Add best practice

---

plugins/docsEnhanced-plugin/index.js

HDH-320 Re-adding default canonical meta tag

---

release-notes/self-managed-enterprise-edition.md

Release notes for 0.20.2
* Please describe your changes: SMP 0.20.2 patch RN
* Jira/GitHub Issue numbers (if any): PL-56932

[PL-56932]: Release notes for 0.20.2

---

docs/internal-developer-portal/plugins/available-plugins/new-relic.md

fix:[IDP-3711]: Adding newrelic info to docs

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

agent update

---

docs/code-repository/config-repos/create-repo.md
docs/code-repository/get-started/overview.md
docs/continuous-integration/development-guides/ci-golang.md
docs/continuous-integration/development-guides/ci-java.md
docs/continuous-integration/development-guides/ci-ruby.md
docs/continuous-integration/get-started/key-concepts.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md
docs/continuous-integration/use-ci/codebase-configuration/built-in-cie-codebase-variables-reference.md
docs/continuous-integration/use-ci/manage-dependencies/run-docker-in-docker-in-a-ci-stage.md
docs/continuous-integration/use-ci/run-tests/code-coverage.md
docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
docs/continuous-integration/use-ci/run-tests/viewing-tests.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/public-docker-images.md
docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
docs/continuous-integration/use-ci/viewing-builds.md

* Please describe your changes: Add canonical_url for HDH-320 work.
* Jira/GitHub Issue numbers (if any): [HDH-320](https://harness.atlassian.net/browse/HDH-320)
* Preview links/images (Internal contributors only): _to be added_
[HDH-320]: https://harness.atlassian.net/browse/HDH-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add canonical_url for HDH-320 work.

---

docs/faqs/harness-feature-flag-faqs.md
docs/feature-flags/get-started/onboarding-guide.md
docs/feature-flags/use-ff/ff-creating-flag/create-a-project.md
docs/feature-flags/use-ff/ff-sdks/client-sdks/flutter-sdk-reference.md
docs/feature-flags/use-ff/ff-sdks/sdk-overview/communication-sdks-harness-feature-flags.md
docs/feature-flags/use-ff/ff-sdks/server-sdks/erlang-sdk-reference.md
docs/feature-flags/use-ff/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
docs/feature-flags/use-ff/ff-sdks/server-sdks/python-sdk-reference.md

* Please describe your changes: \adding canonical urls for ff
* Jira/GitHub Issue numbers (if any): \ HDH-320

adding canonical urls for ff

---

release-notes/self-managed-enterprise-edition.md

Added release note, changed formatting

---

release-notes/feature-flags.md

Add Proxy 2.0.5 release notes

---

docusaurus.config.js

Added Partner Resource to Footer

---

docs/platform/delegates/delegate-concepts/delegate-image-types.md

[CDS-100752] Added delegate and scm versions

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md

[CDS-100969] Removed NG_CDS_HELM_SUB_CHARTS reference

---

docs/chaos-engineering/concepts/explore-concepts/infrastructures/infrastructures.md

CHAOS-6697 Scope and fault execution

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md

feat:[CDS-100293]: Add how certificates are bundled in build pod

---

release-notes/internal-developer-portal.md

feat: [IDP-3735]: Added the release notes for v0.33.0

---

docs/software-engineering-insights/sei-metrics-and-reports/dora-metrics/dora-ci-cd-correlation.md

feat:[SEI-8533]: DORA CI/CD Correlation

---

kb/cloud-cost-management/articles/best-practices/aws-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/azure-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/gcp-connectors-and-roles.md

Add aws org data 

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md

* Please describe your changes: This PR adds a note for `CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR` FF.
* Jira/GitHub Issue numbers (if any): CI-14028

Add note for `CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR` FF.

---

kb/continuous-integration/continuous-integration-faqs.md
release-notes/continuous-integration.md

* Please describe your changes: Fixing a few dead links based on DLC

Few dead link fixes.

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md

* Please describe your changes: Added a FAQ for switching from rolling to blue-green deployment.

FAQ to switch from rolling to blue-green deployment

---

docs/chaos-engineering/concepts/chaos101.md
docs/chaos-engineering/concepts/deployment-architecture.md
docs/chaos-engineering/concepts/explore-concepts/app-maps.md
docs/chaos-engineering/concepts/explore-concepts/chaosguard.md
docs/chaos-engineering/concepts/explore-concepts/gameday.md
docs/chaos-engineering/concepts/explore-concepts/infrastructures/delegate/delegate.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/resilience-probes.md
docs/chaos-engineering/concepts/explore-concepts/service-discovery/service-discovery.md
docs/chaos-engineering/getting-started/saas/first-experiment.md
docs/chaos-engineering/getting-started/smp/connect-enterprise-chaoshub.md
docs/chaos-engineering/getting-started/smp/smp.md
docs/chaos-engineering/security/security-templates/security-templates.md
docs/chaos-engineering/security/security.md
docs/chaos-engineering/use-harness-ce/chaoshubs/chaoshubs.md
docs/chaos-engineering/use-harness-ce/dashboards/dashboards.md
docs/chaos-engineering/use-harness-ce/infrastructures/infrastructures.md

CHAOS-6698 Add redirects

---

docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_type.md
docs/security-testing-orchestration/sto-techref-category/snyk/snyk-container-scanning.md

STO: Document image type Local OCI/Docker archive

---

docs/internal-developer-portal/flows/custom-extensions.md

feat: [IDP]: Added the docs on entitypicker and multientitypicker

---

release-notes/internal-developer-portal.md

fix: [IDP]: Updated the missing bug fixes in release notes

---

docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

STO: Document Policy Failure Ingestion

---

release-notes/chaos-engineering.md

CHAOS-6709 Release notes 1.45.5

---

docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-bitbucket.md
docs/software-engineering-insights/sei-metrics-and-reports/planning/sprint-metrics/sei-sprints-metrics-overview.md
docs/software-engineering-insights/sei-metrics-and-reports/planning/sprint-metrics/sei-sprints-metrics-reports.md

fix: [SEI-8562]: Added canonical url for SEI topics

---

kb/cloud-cost-management/articles/onboarding/k8s.md

We removed non in-cluster examples yesterday, need to remove them from here as well

remove non-in-cluster tf references

---

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md

* Please describe your changes: \______.  Customer was confused that ONLY Environment Variables would change location.  Added clarification.
* Jira/GitHub Issue numbers (if any): \___  https://harnesssupport.zendesk.com/agent/tickets/70286

(Update) Clarify overrides

---

docs/chaos-engineering/concepts/explore-concepts/resilience-probes/datadog-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/dynatrace-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/prom-probe.md

CHAOS-6710 Fix broken links

---

release-notes/security-testing-orchestration.md

STO Release notes with bug fixes

---

docs/chaos-engineering/concepts/deployment-architecture.md
docs/chaos-engineering/concepts/explore-concepts/infrastructures/delegate/proxy-support.md

CHAOS-6714 Update proxy docs

---

kb/continuous-delivery/faqs.md

* Please describe your changes: added FAQ to create filestore from harness shell script

added FAQ to create filestore from harness shell script

---

docs/platform/git-experience/git-ratelimit-bestpractice.md

* Please describe your changes: \_________ Advise customers about what to do if they are concerned about GitHub Rate Limits
* Jira/GitHub Issue numbers (if any): \_______  https://harnesssupport.zendesk.com/agent/tickets/68458 \ https://harness.atlassian.net/browse/PIPE-21164

(Create) Git Rate Limit Best Practice

---

docs/chaos-engineering/concepts/explore-concepts/infrastructures/delegate/mtls-support.md

Add reference link

---

docs/infra-as-code-management/remote-backends/state-migration.md

* Update IaCM state migration repo reference from private to public address.
* [JIRA](https://harness.atlassian.net/browse/IAC-2506)

docs: [IAC-2506] Update IaCM state migration repo reference

---

docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-cpu-hog.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-disk-loss.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-dns-chaos.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-host-reboot.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-http-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-http-modify-response.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-http-reset-peer.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-io-stress.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-memory-hog.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-network-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-network-loss.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-network-rate-limit.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-process-kill.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-service-stop.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-vm-poweroff.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-windows-blackhole-chaos.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-windows-cpu-hog.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-windows-disk-stress.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware-windows-memory-hog.md
docs/chaos-engineering/use-harness-ce/chaos-faults/windows/prerequisites.md

chore: [CHAOS-6720]: Add vmware note for baremetal in vmware experiment

---

release-notes/delegate.md

* Please describe your changes: DEL 838 and 839 RN
* Jira/GitHub Issue numbers (if any): [PL-57263](https://harness.atlassian.net/browse/PL-57263)
[PL-57263]: https://harness.atlassian.net/browse/PL-57263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57263]: DEL 838 and 839 RN

---

docs/chaos-engineering/concepts/explore-concepts/resilience-probes/cmd-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/datadog-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/dynatrace-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/http-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/k8s-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/prom-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/resilience-probes.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/shared/common-note.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/slo-probe.md
docs/chaos-engineering/concepts/explore-concepts/resilience-probes/types.md
docs/chaos-engineering/concepts/explore-features.md
docs/chaos-engineering/use-harness-ce/experiments/experiments.md
docs/chaos-engineering/use-harness-ce/probes/cmd-probe-usage.md
docs/chaos-engineering/use-harness-ce/probes/probes.md

Source mode, type and mode fields in resilience probes

CHAOS-6466 Add content for resilience probes

---

docs/infra-as-code-management/remote-backends/init-configuration.md

* Update initialize backend doc with dynamo db example
* [JIRA](https://harness.atlassian.net/browse/IAC-2497)

docs: [IAC-2497]: Update initialize backend doc with dynamo db example

---

src/components/University/data/sptData.ts

STO order typo

---

kb/platform/harness-platform-faqs.md

* Please describe your changes: Added FAQ regarding the impact of delegate upgrade on running pipeline

Added FAQ regarding the impact of delegate upgrade on running pipeline

---

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md

* Please describe your changes: \_______ Add further information and details about Delegate expiration
* Jira/GitHub Issue numbers (if any): \_______ Regards to https://harness.atlassian.net/browse/CDS-100739

(Update) Delegate Expiry

---

src/components/Roadmap/data/ccmData.ts

[CCM-0]: CCM Roadmap changes

---

release-notes/delegate.md

feat: [CDS-101176]: add new delegate release version

---

src/components/Roadmap/data/platformData.ts

remove reoadmpa item

---

release-notes/delegate.md

Updated the release notes for Delegate.md

fix:[CDS-101154]: Sensitive data is not being sanitized for DryRunManifest variable

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
docs/faqs/security-testing-orchestration.md
docs/security-testing-orchestration/custom-scanning/custom-scan-reference.md
docs/security-testing-orchestration/get-started/onboarding-guide.md
docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/built-in/containers.md
docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
docs/security-testing-orchestration/sto-techref-category/shared/_without-dind-supported-scanners.md
docs/security-testing-orchestration/sto-techref-category/shared/custom-scan/_workflow-repo.md
docs/security-testing-orchestration/sto-techref-category/shared/custom-scan/_workflow.md
docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements.md
docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_type.md
docs/security-testing-orchestration/sto-techref-category/snyk/snyk-container-scanning.md
docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/wiz/artifact-scans-with-wiz.md
docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/build-scan-push-workflows/build-scan-push-workflows.md
release-notes/early-access.md
release-notes/security-testing-orchestration.md

STO: Document DinD and Without-DinD flows

---

docs/chaos-engineering/getting-started/saas/chaos-experiment-from-blank-canvas.md
docs/chaos-engineering/integrations/experiment-as-gitlab-pipeline.md
docs/chaos-engineering/integrations/experiment-as-jenkins-pipeline.md
docs/chaos-engineering/integrations/hce-with-google.md
docs/chaos-engineering/integrations/pipeline-exec.md
docs/chaos-engineering/integrations/use-chaos-with-srm.md

Integrate HCE with Google Cloud Build

CHAOS-6640 Integrate HCE with Google Cloud Build

---

docs/software-engineering-insights/get-started/migrate-propelo-to-harness/migration-faqs.md

feat: [SEI-8600]: Migration FAQs

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.47 RN

Add CI 1.47 RN.

---

docs/infra-as-code-management/remote-backends/state-migration.md

* Update IaCM state migration instructions to include fork link as well as git clone option. 
* [JIRA](https://harness.atlassian.net/browse/IAC-2520)

docs: [IAC-2520]: Update state migration doc 

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/run-step.md

* Please describe your changes: \_______ Information is out of date, and needs to be updated to include Run As user information.  Added additional information regarding Limits and Step Groups as a part of another ticket, 
* Jira/GitHub Issue numbers (if any): \____ https://harnesssupport.zendesk.com/agent/tickets/70490 , https://harness.atlassian.net/browse/CI-14289
PRs …

(Update) Run Step-As user

---

docs/database-devops/use-dbdevops/_category_.json
docs/database-devops/use-dbdevops/rollback-for-database-schemas.md

* Please describe your changes: \_added automated rollback for database schemas
* Jira/GitHub Issue numbers (if any): \_DBOPS-427

added automated rollback for database schemas

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md
kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: Adds FAQ and a link to docs on why **Build and Push** steps don't support V2 API URLs
* Jira/GitHub Issue numbers (if any): CI-14287

Add FAQ and link to docs - CI-14287.

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md

[CDS-100058] Added ASG rollback feature

---

src/components/Roadmap/data/ccmData.ts

new changes for test - updated tags on the roadmap

---

docs/continuous-integration/use-ci/run-tests/tests-v2.md

* Please describe your changes: added clarification to tests splitting in new Test step 
* Jira/GitHub Issue numbers (if any):CI-14385

updated tests splitting in Test step CI-14385

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-http-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-http-modify-body.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-http-modify-header.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-http-reset-peer.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-http-status-code.md

Add note regarding HTTP, HTTPs, and gRPC support for pod HTTP faults

CHAOS-6506 Add note

---

docs/software-engineering-insights/early-access/profiles/sei-trellis-factors.md
docs/software-engineering-insights/get-started/migrate-propelo-to-harness/migrate-propelo-to-harness-sei.md

Jenkins plugin set up

---

docs/internal-developer-portal/flows/create-a-new-service-using-idp-stage.md
docs/internal-developer-portal/flows/create-a-service.md
docs/internal-developer-portal/flows/create-new-service-along-with-pipeline.md
docs/internal-developer-portal/flows/custom-actions.md
docs/internal-developer-portal/flows/provision-infrastructure-using-idp.md
docs/internal-developer-portal/flows/self-service-onboarding-pipeline-tutorial.md
docs/internal-developer-portal/flows/service-onboarding-pipelines.md
docs/internal-developer-portal/get-started/workflow-quickstart.md

fix: [IDP-3797]: added the warning on token 

---

kb/internal-developer-portal/articles/secrets-issue.md
release-notes/internal-developer-portal.md

feat: [IDP]: Updated instructions and release notes with the instructions regarding ui:widget: password issue

---

docs/platform/git-experience/git-experience-overview.md

feat:[PIPE-21754]: Add limitations of repolisting and branch listing API in doc

---

kb/continuous-delivery/articles/migrating-helm-deployment-from-cd-to-gitops.md

[CDS-98940] KB - Migrate a Helm Deployment

---

docs/continuous-delivery/gitops/troubleshooting.md

[CDS-96554] Added CrashLoopBackoff troubleshooting

---

release-notes/database-devops.md
src/components/ReleaseNotes/data/releaseNotesData.ts

* Please describe your changes: \database devops page added
* Jira/GitHub Issue numbers (if any): \DBOPS-607-A

database devops page added

---

docs/chaos-engineering/concepts/chaos101.md
docs/chaos-engineering/concepts/explore-features.md
docs/chaos-engineering/getting-started/getting-started.md

[Add litmuschaos and hce feature comparison](https://66f43dc094949a0a41c9e879--harness-developer.netlify.app/docs/chaos-engineering/getting-started/#hce-and-litmuschaos)

CHAOS-6771 Add litmuschaos and hce feature comparison

---

release-notes/platform.md

* Please describe your changes: PL 1.57.x release notes
* Jira/GitHub Issue numbers (if any): [PL-57348](https://harness.atlassian.net/browse/PL-57348)
[PL-57348]: https://harness.atlassian.net/browse/PL-57348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57348]: PL 1.57.x release notes

---

docs/chaos-engineering/getting-started/getting-started.md
docs/chaos-engineering/use-harness-ce/chaos-faults/load/experiments.ts
docs/chaos-engineering/use-harness-ce/chaos-faults/load/load.md

Update HCE vs LitmusChaos fault list

Update list of faults

---

release-notes/delegate.md

fix:[CDS-101408]: updating logs

---

release-notes/continuous-delivery.md

Added CD release notes 1.57.x

---

docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/override-tanzu-manifest-and-config-files.md
docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md

Updated CF CLI environment variables

---

docs/cloud-cost-management/ccm-onboarding/onboarding-path.md

[CCM-18821]

---

.github/CODEOWNERS

Add @codewdhruv as SEI KB owner

---

release-notes/internal-developer-portal.md

feat: [IDP-3835]: Added the release notes for v0.34.0

---

release-notes/continuous-integration.md

* Please describe your changes: This PR adds CI 1.48 release notes.

Add CI 1.48 RN.

---

src/components/NavbarItems/CoveoSearch.js

optimize-the-invocation-of-the-coveo-api-function

---

docs/open-source/gitspaces/whats-supported.md
docs/open-source/installation/data.md
docs/open-source/installation/dns.md
docs/open-source/installation/postgres.md
docs/open-source/installation/quick_start.md
docs/open-source/installation/settings.md
docs/open-source/installation/ssl.md
docs/open-source/overview.md

This PR updates some `Gitness` references with `Harness Open Source`.
https://github.com/harness/developer-hub/pull/8173 is open to add /docs/open-source CODEOWNERS. Till that PR is merged, the code contributions to /docs/open-source will go to overall docs owners.

Update to swap Gitness with Harness Open Source.

---

docs/infra-as-code-management/workspaces/workspace-expressions.md

The examples in the docs do not match the real values possible and will lead to errors if copied/pasted.
Add code syntax to suggest copy/pasting.

correct <+workspace.type> options

---

docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md

* Update custom image example for us with Harness Cloud and Docker, and Kubernetes
* [JIRA](https://harness.atlassian.net/browse/IAC-2567)

docs: [IAC-2567]: Update custom images example

---

kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: \_______ Add KB note for error regarding Kaniko Ignore Path
* Jira/GitHub Issue numbers (if any): \______. https://harness.atlassian.net/browse/CI-14540

(Update) Kaniko IgnorePath

---

.github/CODEOWNERS

* Please describe your changes: Add CODEOWNERS for /docs/open-source/

Add CODEOWNERS for /docs/open-source/

---

docs/continuous-delivery/get-started/key-concepts.md

add secret best practice

---

src/components/NavbarItems/CoveoSearch.js

Chore : optimize-the-invocation-of-the-coveo-api-function

---

release-notes/delegate.md

fix:[CDS-101499]: remove tags for ASG
