harness/developer-hub

release-notes/cloud-cost-management.md

Release notes v 1.31.4

---

docs/internal-developer-portal/catalog/catalog-scripts.md

fix: [IDP]: Updated the python cli commands for catalog scripts into working format

---

docs/infra-as-code-management/get-started/onboarding-guide.md
docs/infra-as-code-management/whats-supported.md
src/components/NavbarItems/CoveoSearch.js

* Add OpenTofu migration links to What's supported and Onboarding guide
* [JIRA](https://harness.atlassian.net/browse/IAC-2572)

docs: [IAC-2572]: Add OpenTofu migration link

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Update OIDC sample policy for project scoping

---

docs/platform/git-experience/oauth-integration.md

feat:[PIPE-21014]: Doc for generating an OAuth Access Token with VanityURLs as the Host

---

docs/open-source/installation/quick_start.md

* Please describe your changes: Fix weird heading spacing issue.

Fix weird heading spacing issue.

---

kb/cloud-cost-management/articles/best-practices/aws-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/azure-connectors-and-roles.md
kb/cloud-cost-management/articles/best-practices/gcp-connectors-and-roles.md

updates based on trying the code w/ IaCM

---

release-notes/feature-flags.md

* Please describe your changes: Proxy release notes
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FFM-12095

FFM-12095 - Proxy 2.0.6 release notes

---

.github/CODEOWNERS
docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md

* Add OpenTofu firewall exception requirements to custom images doc
* [JIRA](https://harness.atlassian.net/browse/IAC-2575)
https://github.com/user-attachments/assets/bbc87709-a123-420d-8059-c5819c09d1a3

docs: [IAC-2575]: Add opentofu restricted network envs

---

docs/software-engineering-insights/sei-integrations/automated-integrations/sei-integration-sonarqube.md
docs/software-engineering-insights/sei-supported-platforms.md
release-notes/software-engineering-insights.md

feat: [SEI-8724]: SEI Release update for version 202409.2

---

docs/platform/governance/policy-as-code/harness-governance-quickstart.md

fix: [PIPE-22212]: update Policy As Code quickstart to clarify Free Tier limitations

---

docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/aws-security-hub-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/checkov-iac-scan.md
docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
docs/security-testing-orchestration/sto-techref-category/shared/_additional-config.md
docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements-no-dind.md
docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements.md
docs/security-testing-orchestration/sto-techref-category/shared/step_palette/image/_type.md
docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md

Update DinD content in STO docs

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-block.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-body.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-header.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-status-code.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-block/https-enabled.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-latency/https-enabled.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-body/https-enabled.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-modify-headers/https-enabled.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-status-code/https-enabled.yaml

chore: [CHAOS-6837]: Add Both Self Signed and trusted CA certificates support to API chaos

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.49 RN

Add CI 1.49 RN.

---

release-notes/security-testing-orchestration.md

STO: Add Release Notes for week 2024-09-29

---

docs/internal-developer-portal/get-started/setup-git-integration.md

fix: [IDP]: Added the warning to convert private github keys into required format for GitHub App based GitHub connector

---

src/components/Roadmap/data/iacmData.ts

* Move IaCM roadmap item - SMP (on-prem), from Q3 to Q4
* [JIRA](https://harness.atlassian.net/browse/IAC-2574)

IAC-2574 Move SMP (on-prem) to Q4 in roadmap

---

release-notes/continuous-delivery.md

[CDS-101547] CD release notes 1.59

---

docs/internal-developer-portal/roadmap/harness-vs-backstage.md

feat: [IDP]: Added the information on backstage customisation comparison with Harness IDP

---

.github/CODEOWNERS
src/components/University/UniversityIACM.tsx

Added IACM Dev Cert Scaffolding and CODEOWNERS to UNIV to Ravi

---

release-notes/delegate.md
release-notes/platform.md

* Please describe your changes:  PL 1.59.x Release Notes
* Jira/GitHub Issue numbers (if any): [PL-57579](https://harness.atlassian.net/browse/PL-57579)
[PL-57579]: https://harness.atlassian.net/browse/PL-57579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57579]: PL 1.59.x Release Notes

---

docs/internal-developer-portal/governance/policy-as-a-code.md
docs/internal-developer-portal/scorecards/opa-implementation.md

fix: [IDP]: Removed the mention of FF

---

docs/continuous-delivery/manage-deployments/rollback-deployments.md

[CDS-100758] Removed internal API references

---

docs/chaos-engineering/use-harness-ce/infrastructures/enable-disable.md

Specify the min Delegate version number required to run chaos experiments.
[
](url)

CHAOS-6863 Specify Delegate version number

---

docs/continuous-delivery/manage-deployments/deployment-logs-and-limitations.md

feat:[PIPE-22124]: Add info about adding logs more than 5000 lines

---

docs/continuous-integration/secure-ci/secure-connect.md

* Please describe your changes: This PR adds a note for secure connect client.
* Jira/GitHub Issue numbers (if any): CI-14250

Add a note on secure connect client.

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
release-notes/continuous-integration.md

* Please describe your changes: Add min. required delegate version.
* Jira/GitHub Issue numbers (if any): CI-14381

Add minimum required delegate version.

---

release-notes/delegate.md

 add release notes

---

docs/internal-developer-portal/plugins/available-plugins/azure-devops.md

fix:[IDP-3863]: Updating azure docs

---

docs/software-engineering-insights/sei-technical-reference/sei-datasheets/sei-bitbucket-datasheet.md

feat: [SEI-8933]: Bitbucket datasheet

---

src/components/NavbarItems/CoveoSearch.js

HDH-327-coveo-search-results-tags-are-missing-after-pr-8179

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md

fix dead link

---

docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
release-notes/self-managed-enterprise-edition.md

* Please describe your changes:  SMP 0.21.0 Release Notes
* Jira/GitHub Issue numbers (if any): [PL-57426](https://harness.atlassian.net/browse/PL-57426)
[PL-57426]: https://harness.atlassian.net/browse/PL-57426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57426]: SMP 0.21.0 Release Notes

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

[CDS-101059] Added HPA support in GitOps

---

docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md

[CDS-100196] Anonymous support to public Docker registries

---

kb/cloud-cost-management/articles/onboarding/k8s.md

Change location of helm chart as i migrated it to a central repo

update autostopping helm chart location

---

release-notes/platform.md

* Please describe your changes: PL 1.60.x RN
* Jira/GitHub Issue numbers (if any): [PL-57762](https://harness.atlassian.net/browse/PL-57762)
[PL-57762]: https://harness.atlassian.net/browse/PL-57762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57762]: PL 1.60.x RN

---

kb/continuous-delivery/articles/using-terraform-to-install-gitops-agent.md

Added kb - Using Terraform to install Gitops agent

---

docs/platform/git-experience/git-experience-overview.md
docs/platform/git-experience/oauth-integration.md

fix:[PIPE-22410]:Added details on GitLab repository search limitations

---

release-notes/continuous-integration.md

* Please describe your changes: CI release notes 1.50

Add CI 1.50 RN

---

docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-aws.md

[CCM-19245} : added note on Permission boundary 

---

docs/cloud-cost-management/3-use-ccm-cost-reporting/4-detect-cloud-cost-anomalies-with-ccm.md

[CCM-19467]

---

.github/CODEOWNERS
kb/reference-architectures/iacm/iacm-best-practices.md

* Add OpenTofu and Terraform authentication approaches depending on use case.
* [JIRA](https://harness.atlassian.net/browse/IAC-2491)

docs: [IAC-2491]: Add TF Auth approaches

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md

fix:[CDS-101683]: Added note on Delegate network connectivity requirement for Azure Web App deployments

---

src/components/Roadmap/data/roadmapData.ts

* Update IaCM Roadmap GA status from `Limited GA` to `GA`. 
* [JIRA](https://harness.atlassian.net/browse/IAC-2626)

docs: [IAC-2626]: Update limited GA status to GA

---

docs/internal-developer-portal/catalog/catalog-ingestion/catalog-ingestion-api.md
docs/internal-developer-portal/catalog/entity-ref.md

feat: [IDP]: Added the docs on Entity Refernce

---

docs/security-testing-orchestration/sto-techref-category/snyk/snyk-code-scanning.md
docs/security-testing-orchestration/sto-techref-category/snyk/snyk-container-scanning.md
docs/security-testing-orchestration/sto-techref-category/snyk/snyk-iac-scanning.md
release-notes/security-testing-orchestration.md

Remove FF notes in Synk docs and update RN

---

docs/platform/account-license-limits.md

* Please describe your changes: doc for account license limits
* Jira/GitHub Issue numbers (if any): [PL-57766](https://harness.atlassian.net/browse/PL-57766)
[PL-57766]: https://harness.atlassian.net/browse/PL-57766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-57766]: doc for account license limits

---

release-notes/self-managed-enterprise-edition.md

Added looker image tag in release notes.

Added looker image tag in release notes

---

release-notes/chaos-engineering.md

Changed an entry from "New features" to "Fixed issues".

Changed an entry

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/3-setting_up_CO.md

added docs for terraform support

---

docs/security-testing-orchestration/sto-techref-category/shared/_wiz-policy-failure-results.md
docs/security-testing-orchestration/sto-techref-category/wiz/artifact-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/iac-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/repo-scans-with-wiz.md

STO: Document Wiz Policy Failures

---

.github/CODEOWNERS

* Please describe your changes: \ add more module owners
* Jira/GitHub Issue numbers (if any): \ N/A
* Preview links/images (Internal contributors only): \ N/A

chore: add more module owners

---

docs/internal-developer-portal/catalog/catalog-ingestion/catalog-ingestion-api.md

feat: [IDP]: Added the info on mode append

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md

* Please describe your changes:  Updated Azure Web App documentation to provide detailed explanation of the 'clean' option
* Jira/GitHub Issue numbers (if any): CDS-101940

fix: [CDS-101940]: Updated Azure Web App documentation to provide detailed explanation of the 'clean' option for all deployment strategy

---

docs/continuous-delivery/gitops/gitops-faqs.md

Update ArgoCD Supported version

---

release-notes/continuous-delivery.md

Added hotfix release notes 1.59

---

docs/platform/approvals/adding-harness-approval-stages.md

[CDS-100697] Update Support for allowed values

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Adding notes for SMP installations based on ArgoCD for an issue faced with looker during upgrades
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-56236

fix: [PL-56236]: adding notes for argocd based installation for looker encryptionKey issue

---

docs/hdh/hdh-docusaurus-sandbox.md

Added Banner Docs

---

src/components/ReleaseNotes/data/releaseNotesData.ts

fix: [CDE]: Updated the title of the release notes for CDE

---

release-notes/feature-flags.md

* Please describe your changes: \ java sdk release notes added
* Jira/GitHub Issue numbers (if any): \FFM-12087

java sdk release notes added

---

docs/software-engineering-insights/propelo-end-of-life.md

feat:[SEI-9004]: End of Life - Propelo announcement

---

docs/internal-developer-portal/scorecards/track-migrations.md
docs/internal-developer-portal/tutorials/how-to-track-migrations.md
docs/open-source/support.md
docusaurus.config.js
src/components/Community/Aspects.tsx

Patch broken slack join links.

---

docs/internal-developer-portal/scorecards/track-migrations.md
docs/internal-developer-portal/tutorials/how-to-track-migrations.md
docs/open-source/support.md
docusaurus.config.js
src/components/Community/Aspects.tsx

This PR updates the community slack join link with a generic one so that the underlying invite link can be updated without needing to modify multiple files in the future.

Update slack join link with a generic one.

---

release-notes/security-testing-orchestration.md

STO: Add release notes for 2024-10-13

---

docs/software-supply-chain-assurance/manage-risk-and-compliance/standards-and-rule-definitions.md
release-notes/software-supply-chain-assurance.md

SCS: Document rule 2.3.9 for Harness pipelines and update release notes

---

src/components/NavbarItems/CoveoSearch.scss

coveo-search-cde-icon-fix

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/iltData.ts
src/components/University/data/sptData.ts

Launch of IDP SPT and IaCM ILT

---

docs/chaos-engineering/getting-started/smp/smp.md

Specify link to installing SMP in air-gapped environment

CHAOS-6893 Link to air-gapped env

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

[CDS-100348] Added JET identity token for AWS

---

docs/internal-developer-portal/catalog/catalog-ingestion/catalog-ingestion-api.md

feat: [IDP]: Added the info on how to add annotations

---

docs/internal-developer-portal/catalog/catalog-ingestion/catalog-ingestion-api.md

fix: [IDP]: Fixed the headings

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/iltData.ts

GA of IDP ILT

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md

* Please describe your changes: **Added clarification that stage start contain unresolved expressions for services, infrastructure, and environments**
* Jira/GitHub Issue numbers (if any): **PIPE-22632**
Please review second point:-

feat: [PIPE-22632]: Added clarification that stage start  contain unresolved expressions for services, infrastructure, and environments

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/artifacts-tab.md

* Please describe your changes: Add instructions for setting display name to URLSs
* Jira/GitHub Issue numbers (if any): CI-14996

Add instructions for setting display name to URLSs

---

kb/platform/harness-platform-faqs.md

Platform faq
* Please describe your changes: Added platform faq

Platform faq

---

_server-redirects

Add redirect for IDP Workflows page move

---

.github/CODEOWNERS

* Please describe your changes: \ update code owners for CDE Docs

chore: update code owners for CDE docs

---

docs/platform/get-started/tutorials/onboard-terraform-provider.md

* Please describe your changes: \________ covers issue found where Harness resources were deleted before the state file was updated.
* Jira/GitHub Issue numbers (if any): \______ https://harnesssupport.zendesk.com/agent/tickets/69748

(update) Terraform error Statefile

---

docs/continuous-delivery/cd-infrastructure/cloudformation-infra/provision-with-the-cloud-formation-create-stack-step.md

feat:[CDS-101255]: clarify CloudFormation Create Stack step behavior for existing stacks

---

docs/continuous-delivery/manage-deployments/deployment-faqs.md

Brijesh Deployment FAQ

---

docs/continuous-delivery/cd-infrastructure/provisioning-faqs.md

Brijesh CD Infra Doc

---

docs/continuous-delivery/gitops/get-started/harness-cd-git-ops-quickstart.md

[CDS-100606] Update Gitops delete application

---

docs/infra-as-code-management/workspaces/cost-estimation.md
docs/infra-as-code-management/workspaces/delete-workspace.md
docs/infra-as-code-management/workspaces/workspace-expressions.md
docs/infra-as-code-management/workspaces/workspace-tempates.md

* IaCM workspace templates guide
* [JIRA](https://harness.atlassian.net/browse/IAC-2473)
https://github.com/user-attachments/assets/750429aa-9698-4a46-a719-6b9577dd74d5

docs: [IAC-2473] IaCM workspace templates

---

release-notes/delegate.md
release-notes/platform.md

* Please describe your changes: delegate release note fix
* Jira/GitHub Issue numbers (if any): [PL-57762](https://harness.atlassian.net/browse/PL-57762)
[PL-57762]: https://harness.atlassian.net/browse/PL-57762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PL-57762]: delegate release note fix

---

README.md

Updated Readme with additional modules

---

docs/internal-developer-portal/plugins/available-plugins/harness-iacm.md

Add guidance for URL

---

release-notes/delegate.md
release-notes/platform.md

* Please describe your changes: PL 1.62.x Release Notes
* Jira/GitHub Issue numbers (if any): [PL-58104](https://harness.atlassian.net/browse/PL-58104)
[PL-58104]: https://harness.atlassian.net/browse/PL-58104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-58104]: PL 1.62.x Release Notes

---

release-notes/continuous-delivery.md

[CDS-102820] CD release notes 1.62.x

---

release-notes/continuous-delivery.md

Cds 102820

---

release-notes/continuous-integration.md

CI RN 1.51

---

docs/open-source/gitspaces/manage-gitspaces/create-gitspaces.md
docs/open-source/gitspaces/whats-supported.md

* Please describe your changes: Removing Gitness references

Remove Gitness references from Gitspaces docs

---

.github/CODEOWNERS

Added codeowners for Pipeline

---

docs/chaos-engineering/use-harness-ce/application-map.md

Add redirect link after restructuring application map section

Add redirect link

---

docs/infra-as-code-management/workspaces/cli-integration.md

* Document IaCM workspace CLI Integration screen
* [JIRA](https://harness.atlassian.net/browse/IAC-2642)

docs: [IAC-2642]: Document IaCM workspace CLI Integration screen

---

docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md

* Move network connectivity requirement block to top of Custom images doc
* [JIRA](https://harness.atlassian.net/browse/IAC-2591)
https://github.com/user-attachments/assets/bb697215-92c1-4901-9e77-757a4e83be58

docs: [IAC-2591]: Move network connectivity requirements

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: SMP 0.22.0 RN
* Jira/GitHub Issue numbers (if any): [PL-58076](https://harness.atlassian.net/browse/PL-58076)
[PL-58076]: https://harness.atlassian.net/browse/PL-58076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-58076]: SMP 0.22.0 RN

---

release-notes/software-engineering-insights.md

feat:[SEI-9288]: Release update version 202410.2

---

docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md

Document policy failures ingestion for Veracode and Anchore

---

docs/chaos-engineering/concepts/explore-features.md
docs/chaos-engineering/use-harness-ce/application-map.md
docs/chaos-engineering/use-harness-ce/image-registry.md
docs/chaos-engineering/use-harness-ce/infrastructures/infrastructures.md
docs/chaos-engineering/use-harness-ce/license-consumption.md
kb/chaos-engineering/chaos-engineering-faq.md
src/components/Docs/data/chaosEngineeringData.ts
src/components/Docs/data/chaosEngineeringData_Complex.ts

CHAOS-6910 License docs

---

docs/continuous-delivery/get-started/services-and-environments-overview.md

[CDS-100967] Multi-select dropdown for Infrastructure hosts

---

docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md

Add FAQ for configuring artifactPath and artifactName in artifact fetch to prevent common misconfigurations

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

[CDS-100456] Added GitOps Auto Updater Job

---

docs/platform/connectors/code-repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
docs/platform/connectors/code-repositories/ref-source-repo-provider/git-connector-settings-reference.md
docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
docs/platform/connectors/code-repositories/ref-source-repo-provider/git-lab-connector-settings-reference.md

Git connector ssh key file

---

docs/platform/triggers/triggers-reference.md

[CDS-101585] Added GitLab System Hooks config

---

docs/platform/secrets/add-file-secrets.md

* Please describe your changes: \_________ Added single quotes to fix error
syntax error near unexpected token `|'

(Update) FileSecrets Missing Quotes

---

docs/infra-as-code-management/module-registry.md

* Update module registry doc to state that delegate users much have minimum version installed.
* [JIRA](https://harness.atlassian.net/browse/IAC-2700)

docs: [IAC-2700]: Add delegate pre-req for module registry

---

docs/internal-developer-portal/flows/create-new-service-along-with-pipeline.md

fixed pipeline and other docs improvements

---

release-notes/feature-flags.md

* Please describe your changes: Adds the 2.0.7 release notes for the Relay Proxy
* Jira/GitHub Issue numbers (if any):N/A

Proxy 2.0.7 release notes

---

kb/cloud-cost-management/articles/autostopping/proxy.md

Adding new troubleshooting section for the autostopping proxy to help guide customers on how to look into issues they may be having.

kb: ccm: add proxy troubleshooting docs

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/data/iltData.ts

PR for adding CE ILT to HDH 

---

.github/CODEOWNERS

Correct typos in CODEOWNER file

---

docs/platform/pipelines/add-a-stage.md
kb/continuous-delivery/faqs.md

feat: [CDS-102740]: Add note on 4-day runtime limit for delegate-based steps in Harness

---

docs/platform/variables-and-expressions/expressions-java-methods.md

correct Split section

---

src/components/Roadmap/data/idpData.ts

Update IDP Roadmap for Q4 and beyond

---

src/components/Roadmap/data/idpData.ts

Push out k8s discovery in IDP roadmap

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/_category_.json
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-swap.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-delete.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-deploy.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-deploy.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-rollback.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-stage-deployment.md

Native Helm Canary/Blue Green docs

---

docs/infra-as-code-management/pipelines/iacm-plugins/approval-step.md
docs/infra-as-code-management/whats-supported.md

* Add note that Wiz scans require an STO license.
* [JIRA](https://harness.atlassian.net/browse/IAC-2722)

docs: [IAC-2722]: Add STO license requirement to WIZ highlights

---

docs/infra-as-code-management/workspaces/workspace-tempates.md

* Add workspace template video demo in feature document
* [JIRA](https://harness.atlassian.net/browse/IAC-2741)

docs: [IAC-2741]: Add workspace template video

---

release-notes/continuous-delivery.md

[CDS-103222] Gitops release notes for Version 1.19.0

---

kb/armory/General/armory-support-case-management-via-harness.md

Updated module from Armory -> Spinnaker

small update to armory-support-case-management-via-harness.md 

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md

* Please describe your changes: add docs for build intelligence auto-setup
* Jira/GitHub Issue numbers (if any): CI-15142

CI-15142 build intelligence auto setup docs

---

src/components/Roadmap/data/ceData.ts
src/components/Roadmap/data/srmData.ts

- [CE roadmap](https://672b991d652c681f0875530f--harness-developer.netlify.app/roadmap/#ce)
- [SRM roadmap](https://672b991d652c681f0875530f--harness-developer.netlify.app/roadmap/#srm)

Update  CE Roadmap for Q4 FY25

---

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/2-Harness-Concepts.md

increased limit

---

docs/cloud-cost-management/CCM-usecases/AutoStopping/autostopping_spot.md

new usecase

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-deploy.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-swap.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-delete.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-deploy.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-rollback.md

[CDS-57235] Updated Helm Canary and BG deployment

---

docs/internal-developer-portal/api-refernces/overview.md

feat: [IDP]: Added the API Overview Page

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md

* Please describe your changes:add hardware accelerated limitation

add hardware accelerated limitation

---

release-notes/cloud-cost-management.md

new release notes

---

docs/continuous-integration/use-ci/run-tests/flaky-tests.md
docs/continuous-integration/use-ci/run-tests/viewing-tests.md
src/components/Roadmap/data/ciData.ts

* Please describe your changes: added docs for flaky tests plugin, and updated external roadmap 
* Jira/GitHub Issue numbers (if any):[ CI-15071 ]

flaky tests plugin and roadmap update

---

docs/continuous-delivery/get-started/service-licensing-for-cd.md

Licensing v2

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/LandingPage.tsx
src/components/University/UniversityIACM.tsx
src/components/University/data/certificationsData.ts
src/components/University/data/sptData.ts

Launch IaCM Dev Cert

---

docs/continuous-delivery/get-started/service-licensing-for-cd.md

cleaned up and added the changes

---

src/components/HomepageUniversity/data/universityData.ts
src/components/University/UniversityChaos.tsx
src/components/University/UniversityIACM.tsx
src/components/University/data/sptData.ts

Patch iacm dev cert

---

docs/code-repository/pull-requests/merge-pr.md

adding docs for Fast forward merge strategy and Rebase.

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md

* Please describe your changes: \_______ Added additional information for customers and added BuildX scenario.  Completed some clarity requests from JPMC
* Jira/GitHub Issue numbers (if any): \__________  https://harnesssupport.zendesk.com/agent/tickets/73024

(Update) NonRoot Build Push

---

docs/internal-developer-portal/flows/flows-input.md
docs/internal-developer-portal/flows/flows-output.md
docs/internal-developer-portal/flows/service-onboarding-pipelines.md

fix: [IDP]: Fixed few spell-checks and grammatical errors

---

release-notes/delegate.md

fix delegate release notes version

---

.github/CODEOWNERS

new codeowners

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/3-setting_up_CO.md

added new changes

---

docs/platform/git-experience/git-experience-overview.md

Update GitLab search functionality

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.53 release notes

CI 1.53 release notes

---

docs/platform/connectors/code-repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md

* Please describe your changes: update bitbucket connector documentation based on implementation with customer yesterday. The username needs to be `x-token-auth` for the access token method to work with bitbucket cloud.

Update bitbucket cloud connector steps

---

release-notes/continuous-integration.md

* Please describe your changes: clarified a couple of items in CI RN 1.53 

update CI RN 1.53

---

src/components/Roadmap/data/ccmData.ts

added cluster orchestrator roadmap

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: Updated Kubernetes setup with podSpecOverlay option
* Jira/GitHub Issue numbers (if any): CI-14248

Updated Kubernetes setup with podSpecOverlay option

---

release-notes/self-managed-enterprise-edition.md

smp 0.22.1 rn

---

release-notes/platform.md

* Please describe your changes: PL 1.63.x Release Notes
* Jira/GitHub Issue numbers (if any): [PL-58236](https://harness.atlassian.net/browse/PL-58236)
[PL-58236]: https://harness.atlassian.net/browse/PL-58236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-58236]: PL 1.64.x Release Notes

---

release-notes/continuous-delivery.md

[CDS-103056] CD release notes 1.64

---

docs/platform/triggers/triggers-reference.md

[PIPE-22879]: Document behavior of eventPayload resolution in stage variables

---

src/components/Roadmap/data/cdData.ts

[Preview](https://672eda9f608750b1b7085e7b--harness-developer.netlify.app/roadmap/#cd)

[CDS-103235] Updated CD roadmap

---

docs/infra-as-code-management/pipelines/operations/pr-automation.md

* Rewriting PR automation doc due to high bounce rate.
* [JIRA](https://harness.atlassian.net/browse/IAC-2761)

docs: [IAC-2761]: IaCM PR automation rewrite

---

src/components/Roadmap/data/codeData.ts

Updating code repo roadmap for Q4

---

docs/continuous-delivery/get-started/service-licensing-for-cd.md

Thisrohangupta patch 3

---

docs/first-gen/firstgen-platform/security/secrets-management/add-an-aws-secrets-manager.md
docs/platform/secrets/secrets-management/add-an-aws-secret-manager.md

…AWS Secret Manager
* Please describe your changes: Update Harness Documentation for the aws-permissions
* Jira/GitHub Issue numbers (if any): [PL-58448](https://harness.atlassian.net/browse/PL-58448)
[PL-58448]: https://harness.atlassian.net/browse/PL-58448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

[PL-58448]: Update Harness Documentation for the aws-permissions

---

release-notes/continuous-delivery.md

[CDS-103056] updated CD release notes 1.64

---

release-notes/delegate.md

ubi base image change for delegate note

---

docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/Azure/azure-recommendations.md

feat:[CCM-18219]: Add new governance azure recommendation - delete-orphaned-azure-appserviceplan

---

release-notes/chaos-engineering.md

CHAOS-6988 Release notes 1.48.0

---

docs/infra-as-code-management/pipelines/operations/default-pipelines.md
docs/infra-as-code-management/pipelines/operations/destroy-workspaces.md
docs/infra-as-code-management/pipelines/operations/iacm-cd-pipeline.md
docs/infra-as-code-management/pipelines/operations/pr-automation.md
docs/infra-as-code-management/pipelines/operations/provision-workspace.md

* Separating Provision and Destroy workspace docs and adding interactive guides to help improve bounce rates.
* [JIRA](https://harness.atlassian.net/browse/IAC-2771)

docs: [IAC-2771]: Split provision and destroy workspace docs

---

docs/internal-developer-portal/tutorials/opa-scorecards.md

fix: [IDP]: Removed the mention of Feature Flag

---

docs/platform/triggers/trigger-on-a-new-artifact.md

fix: [CDS-103087]: Improve S3 trigger docs

---

docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md

[CDS-102895]: Add new serverless with v.1.0.1 changes

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
kb/platform/harness-platform-faqs.md

[CDS-103705]: Update docs to reflect deprecated FF

---

docs/security-testing-orchestration/sto-techref-category/traceable-step-configuration.md

Add Traceable docs URL for runner id

---

docs/infra-as-code-management/iacm_security.md

* Update IaCM security doc to make interactive model static, moving the steps above the diagram, and rewriting some descriptions. Also renaming titles for better engagement and SEO.
* [JIRA](https://harness.atlassian.net/browse/IAC-2786)

docs: [IAC-2786]: Update IaCM security doc

---

docs/software-engineering-insights/sei-ingestion-satellite/satellite-troubleshooting-and-faqs.md

feat: [SEI-9464]: adds satellite troubleshooting guide

---

release-notes/delegate.md
release-notes/platform.md

delegate rn for 24.11.84304

---

.github/CODEOWNERS

Update SCS RN file in CODEOWNERS

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md

* Please describe your changes: \__________  JPMC required additional clarifications in the documentation.
* Jira/GitHub Issue numbers (if any): \___________.  https://harnesssupport.zendesk.com/agent/tickets/73024

(Update) Build and Push

---

release-notes/software-supply-chain-assurance.md

SCS Release notes for v1.19.1

---

docs/platform/account-license-limits.md

update platform resource limits

---

docs/internal-developer-portal/api-refernces/public-api.md

feat: [IDP]: Added a real world example for backstage APIs to filter components based on conditions

---

docs/platform/pipelines/pipeline-settings.md

feat:[PIPE-22721]: Document execution and crud limits

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md

Add warning for deployment

---

release-notes/continuous-integration.md

Update release notes with whitelisting configuration for cloud macos

---

netlify/functions/coveo_api.mts

 add-harness-staging-as-allowed-origin-in-coveo-api

---

docs/internal-developer-portal/flows/service-onboarding-pipelines.md

feat: [IDP]: Added the warning for the template editor

---

docs/chaos-engineering/use-harness-ce/image-registry.md

[Preview](https://673aebe0e563dce5d9d6e05d--harness-developer.netlify.app/docs/chaos-engineering/use-harness-ce/image-registry#images-required)

CHAOS-6853 Image registry

---

release-notes/continuous-integration.md

Change to release notes - m2 machines 

---

docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md

Added DLC troubleshooting info  CI-15259

---

docs/internal-developer-portal/flows/custom-actions.md
docs/internal-developer-portal/flows/flows-input.md
docs/internal-developer-portal/flows/flows-output.md
docs/internal-developer-portal/get-started/workflow-quickstart.md

fix: [IDP]: Removed all the references of Custom Actions

---

docs/continuous-delivery/gitops/gitops-faqs.md

[CDS-101654] Added Gitops Faq

---

release-notes/continuous-delivery.md

Release notes 1.65.x

---

docs/infra-as-code-management/faq.md

* Add IaCM FAQ page
* [JIRA](https://harness.atlassian.net/browse/IAC-2760)

docs: [IAC-2760]: Add IaCM FAQ page

---

docs/continuous-delivery/verify/continuous-verification-faqs.md

[CDS-103086]: Add FAQ on Sumo Logic data collection interval for Continuous Verification

---

docs/platform/pipelines/step-skip-condition-settings.md

[CDS-101542]: Configuring a Step/Template in the Rollback Section with Custom when Condition, add examples in the doc

---

docs/internal-developer-portal/catalog/add-links-docs.md
docs/internal-developer-portal/flows/custom-actions.md

fix: [IDP]: Removed the example of step variables

---

src/components/University/LandingPage.tsx
src/components/University/UniversityChaos.tsx

CE Admin Beta

---

release-notes/security-testing-orchestration.md

STO Release Notes v1.114.3

---

release-notes/continuous-delivery.md

add PIPE-19754 in release notes

---

docs/artifact-registry/get-started/overview.md
docs/artifact-registry/whats-supported.md

Add proper emails

---

docs/internal-developer-portal/plugins/available-plugins/sonarqube.md

fix: [IDP]: Highlighted the user-token related information for SQ plugin

---

docs/platform/templates/template.md

[PIPE-22020]: Add note on audit events change when stable version of template gets updated

---

src/components/Roadmap/data/idpData.ts

Split IDP RBAC scope into Q4 and Q1

---

docs/continuous-delivery/gitops/connect-and-manage/hosted-gitops.md

[CDS-85347] Added Limitations for hosted agents

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md

[CDS-99509] Removed video referencing to old UI.

---

docs/internal-developer-portal/rbac/resources-roles.md

fix: [IDP]: Added reference to platform docs

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3.md

* Please describe your changes: CI-15079

Add additional env variable reference.

---

docs/internal-developer-portal/catalog/catalog-scripts.md

feat: [IDP]: Added a troubleshooting section for Catalog Scripts in IDP

---

docs/database-devops/get-started/onboarding-guide.md

* Please describe your changes: \ capacity planning section added
* Jira/GitHub Issue numbers (if any): \ DBOPS-439

capacity planning section added

---

kb/armory/General/artifact-store-compatibility-workaround.md

* Please describe your changes: Adding an Armory KB article for a compatibility workaround on the Artifact-Store OSS feature
* Jira/GitHub Issue numbers (if any): ASSMT-510

chore(armory): Adding Armory KB article for Artifact-store compatibility

---

docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md

* Please describe your changes: Add automation script, prerequisites, recommendation and troubleshooting
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-58176

feat: [PL-58176]: Update increase-pv-size-statefulsets.md

---

kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: update FAQ - allowed variables in stage parallelism strategy
* Jira/GitHub Issue numbers (if any): CI-15317

CI-15317 update FAQ - allowed variables in stage parallelism strategy

---

docs/faqs/harness-delegate-faqs.md

fix: [PL-58853]: Doc is wrong, it says delegate falls back to polling upon wss drops

---

docs/internal-developer-portal/flows/dynamic-picker.md
docs/internal-developer-portal/flows/flows-input.md

feat: [IDP]: Added Example for dynamic pickers reference 

---

release-notes/platform.md

* Please describe your changes: PL 1.65.x RN

[PL-58627]: PL 1.65.x RN

---

docs/chaos-engineering/getting-started/getting-started.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-status-code.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-dns-spoof.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-error.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/time-chaos.md
docs/chaos-engineering/use-harness-ce/chaoshubs/chaoshubs.md
docs/chaos-engineering/use-harness-ce/gameday.md
docs/chaos-engineering/use-harness-ce/governance/governance-in-execution/govern-run.md
docs/chaos-engineering/use-harness-ce/image-registry.md
docs/chaos-engineering/use-harness-ce/probes/probes.md

Reference YT videos in the docs

CHAOS-7094 Reference YT videos

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/3-setting_up_CO.md

[CCM-20105]: Update 3-setting_up_CO.md

---

docs/internal-developer-portal/plugins/available-plugins/harness-ccm.md

fix: [IDP]: Updated the annotations for CCM plugin

---

docs/security-testing-orchestration/sto-techref-category/qwiet-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/tenable-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/traceable-step-configuration.md
docs/security-testing-orchestration/sto-techref-category/wiz/artifact-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/iac-scans-with-wiz.md
docs/security-testing-orchestration/sto-techref-category/wiz/repo-scans-with-wiz.md

STO: Add Proxy settings to supported scanners

---

release-notes/early-access.md

STO: Remove FF `STO_EXEMPTION_SETTING` from STO early access page.

---

docs/continuous-delivery/cd-integrations.md
docs/platform/approvals/adding-harness-approval-stages.md

[CDS-100424] Updated FF details for Approval API

---

docs/platform/git-experience/git-experience-overview.md
docs/platform/git-experience/gitexp-bidir-sync-setup.md

[PIPE-23714]:  add note about handling commits with 300+ files in GitX bidirectional sync for GitHub

---

docs/internal-developer-portal/scorecards/checks-datasources.md

fix: [IDP]: Updated docs on `harness.io/services` annotation being optional for Policy Evaluation and STO stages based checks

---

release-notes/self-managed-enterprise-edition.md

RN for SMP 0.22.2 HF

---

docs/internal-developer-portal/scorecards/custom-data-sources.md

feat:[IDP]: Added the video tutorial for custom data-source ingestion

---

docs/continuous-delivery/deploy-srv-diff-platforms/integrations/integrations-faqs.md
docs/platform/git-experience/git-experience-overview.md
docs/platform/git-experience/git-settings.md

remove PIE_GIT_BI_DIRECTIONAL_SYNC from doc

---

docs/self-managed-enterprise-edition/back-up-and-restore-helm.md

The original document didn't capture the whole namespace backup/restore process. Also it didn't have troubleshoot steps. This PR aims to fix the gap.
* Please describe your changes: Update backup/restore process
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-58092

fix: [58092]: Update back-up-and-restore-helm.md

---

docs/internal-developer-portal/flows/dynamic-picker.md
docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md

fix: [IDP]: Fixed the endpoint URL

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/3-Cluster-orchestrator/3-setting_up_CO.md

[CCM-20272]: Update 3-setting_up_CO.md

---

release-notes/delegate.md

* Jira/GitHub Issue numbers (if any):(https://harness.atlassian.net/wiki/spaces/LEARNING/pages/22158770497/Prod+Hotfix+Delegate+delegate+version+8430x)

Delegate 24.11.84309 Hotfix RN

---

docs/feature-flags/ff-supported-platforms.md
docs/feature-flags/shared/ff-resource-limits.md

* Please describe your changes: Add information on the limit of resources in Feature Flags
* Jira/GitHub Issue numbers: https://harness.atlassian.net/browse/FFM-12199

feat: [FFM-12199]: FF Resource Limits

---

docs/platform/references/entity-identifier-reference.md
docs/platform/references/harness-entity-reference.md

[PL-58591]: reformat entity id reference

---

docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-cloud-run.md

Update Google Cloud Run

---

docs/software-supply-chain-assurance/slsa/generate-slsa.md

SCS: Fix Variable Expressions for Artifact Digest fields

---

docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-cache-expire.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-cache-limit.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-cache-penetration.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-sentinel-stop.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/shared/redis-auth.md

Adds redis fault address input

chore: [CHAOS-7037]: Adds redis fault address input

---

docs/chaos-engineering/use-harness-ce/infrastructures/enable-disable.md

[Preview](https://6746b6e6330f67b5e9cb975f--harness-developer.netlify.app/docs/chaos-engineering/use-harness-ce/infrastructures/enable-disable#using-ddcr)

CHAOS-7119 Update enable-disable.md

---

release-notes/continuous-delivery.md

release notes 1.67.x

---

docs/internal-developer-portal/flows/dynamic-picker.md

fix: [IDP]: added / in the url examples

---

release-notes/delegate.md
release-notes/platform.md

PL 1.67.x RN and DEL RN

---

kb/cloud-cost-management/articles/onboarding/k8s.md

[CCM-20371]: Update k8s.md

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

* Please describe your changes: Add note about pipeline ID inclusion in JWT sub field with **CDS_ENABLE_PIPELINE_SCOPED_OIDC_SUB**

feat:[PIPE-23044]: Add note about pipeline ID inclusion in JWT sub field with CDS_ENABLE_PIPELINE_SCOPED_OIDC_SUB

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-deployment-faqs.md

Remove FF: CDS_CONTAINER_STEP_GROUP_AWS_S3_DOWNLOAD details from the documentation.

[CDS-103999] Remove FF: CDS_CONTAINER_STEP_GROUP_AWS_S3_DOWNLOAD details

---

docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md

* Please describe your changes: \________. Customer needed to make changes on the SonarQube side to resolve the issue.  Added reference to the documentation
* Jira/GitHub Issue numbers (if any): \______.  https://harnesssupport.zendesk.com/agent/tickets/74169

(Update) SonarQube PDF Report Setting

---

release-notes/delegate.md

Fixing the Delegate RN

---

docs/continuous-delivery/cd-integrations.md
docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md
release-notes/continuous-delivery.md

Added Feature flag details to Azure functions deployment

---

release-notes/delegate.md

* Please describe your changes: We are exposing custom CF CLI variables while executing CF commands 
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CDS-104745

exposing custom CF CLI variables while executing CF commands

---

docs/continuous-delivery/gitops/use-gitops/add-a-harness-git-ops-repository.md

* Please describe your changes: \______ It was not clear to the customer or us if Bitbucket was officially supported.   We have added information into what this means according to this Slack thread
https://harness.slack.com/archives/C013KJMDV0U/p1732005065543869?thread_ts=1731943212.541229&cid=C013KJMDV0U
* Jira/GitHub Issue numbers (if any): \________. https://harnesssupport.zendesk.com/agent/tickets/73330 …

(Update) Added Info about Git Platforms

---

release-notes/delegate.md

fix: [CDS-102807]: add release notes of delegate 84307

---

release-notes/delegate.md

[PIPE-23686]: Added release notes for delegate hotfix version 24.10.84106

---

release-notes/self-managed-enterprise-edition.md

RN for SMP 0.22.3 HF

---

package.json
yarn.lock

HDH-339-scss-deprecation-warning

---

.github/workflows/markdown-file-validation.yaml

HDH-338-add-markdown-file-name-check-github-action

---

release-notes/self-managed-enterprise-edition.md

SMP 0.23.0 RN Dec 4th 2028

---

release-notes/self-managed-enterprise-edition.md

Removed the code module from the SMP RN

---

docs/self-managed-enterprise-edition/advanced-configurations/use-hpa-for-autoscaling.md

In SMP version 0.23.0, we have added support for configuring service's HPA through global overrides and also enhanced the number of fields supported for HPA.
* Please describe your changes: Guide to configure HPA in SMP
* Jira/GitHub Issue numbers (if any): PL-58826

feat: [PL-58826]: Create use-hpa-for-autoscaling.md

---

docs/internal-developer-portal/flows/flows-input.md
docs/internal-developer-portal/flows/workflows-tutorials/create-a-new-service-using-idp-stage.md
docs/internal-developer-portal/flows/workflows-tutorials/create-a-service.md
docs/internal-developer-portal/flows/workflows-tutorials/create-new-service-along-with-pipeline.md
docs/internal-developer-portal/flows/workflows-tutorials/self-service-onboarding-pipeline-tutorial.md

feat: [IDP]: Check for technical correctness of workflow tutorials and remove the repeated information

---

docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md

[CDS-76567] Added troubleshooting documentation linked to resolved bugs.

---

docs/internal-developer-portal/get-started/register-a-new-software-component.md

fix: [IDP]: Added the docs for registering components from harness code repository

---

release-notes/continuous-delivery.md

Update CD release notes

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/drone-email-plugin.md

Change plugin image name

---

release-notes/delegate.md

feat: [CDS-104813]: update delegate release notes

---

release-notes/continuous-integration.md

* Please describe your changes: Release Notes CI 1.56

Release Notes CI 1.56

---

docusaurus.config.js
university/faqs.md

Updated Footer URL for Partners and quick FAQ add. 

Updated Harness Partner URL

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md

updated vm runner doc

---

docusaurus.config.js
sidebars-university.js
src/css/custom.css

Added FME to HarnessU [Split Arcade Link]. Needed to update the header and custom CSS for the FME logo. 

Added FME to Univ

---

docs/service-reliability-management/monitored-service/health-source/google-cloud-operations.md

CHAOS-7140 add note about SRM and delegate task

---

release-notes/continuous-delivery.md

Release notes 1.68.x

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

[CDS-101336] Default In-Cluster for Account-Level GitOps Agent

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-attribute-override.md

CHAOS-7164 Update pod-io-attribute-override.md

---

docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-api-block.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-api-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-api-modify-body.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-api-modify-header.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux-api-status-code.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/shared/api-chaos-fault-permissions.md

* Please describe your changes: Updates linux api chaos fault permissions
* Jira/GitHub Issue numbers (if any): CHAOS-7136

chore: [CHAOS-7136]: Updates linux api chaos fault permissions

---

release-notes/self-managed-enterprise-edition.md

Specify overrides in SMP release notes for chaos engineering

CHAOS-7151 Specify overrides in SMP

---

docs/internal-developer-portal/flows/workflows-tutorials/create-new-service-along-with-pipeline.md
docs/internal-developer-portal/flows/workflows-tutorials/provision-infrastructure-using-idp.md
docs/internal-developer-portal/flows/workflows-tutorials/self-service-onboarding-pipeline-tutorial.md

fix: [IDP]: Updated the conclusion for workflows with correct end goals

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md

* Please describe your changes: \_____. Add CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR information for Base Image to Connector information
* Jira/GitHub Issue numbers (if any): \______. https://harnesssupport.zendesk.com/agent/tickets/69939

(Update): CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR

---

docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md

* Update terraform plugin commands doc
* [JIRA](https://harness.atlassian.net/browse/IAC-2871)

docs: [IAC-2871]: Update Terraform commands

---

release-notes/software-engineering-insights.md

feat: [SEI-9778]: release update version 202412.1

---

docs/internal-developer-portal/overview.md

fix: [IDP]: Added a redirect to an removed link

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/drone-email-plugin.md

Cleanup email plugin docs

---

release-notes/platform.md

Added platform release notes for 1.68x

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollback.md

* Please describe your changes: \_____. Added troubleshooting information to help if a customer doesn't understand why a Canary did not roll back due to resource constraints
* Jira/GitHub Issue numbers (if any): \______. https://harness.atlassian.net/browse/CDS-104551

(Update) Kubernetes Rollback

---

docs/platform/variables-and-expressions/runtime-input-usage.md

Add new download file API in the doc as well restriction based on number of upload step a pipeline can have

---

.github/CODEOWNERS
docs/artifact-registry/get-started/quickstart.md

* Add Tango interactive guide to AH Upstream proxy creation section
* [JIRA](https://harness.atlassian.net/browse/IAC-764)
https://github.com/user-attachments/assets/b16395cd-2134-4cca-b922-6b98632a0a70

docs: [AH-764]: Add Tango guide to create a docker upstream proxy

---

release-notes/self-managed-enterprise-edition.md

RN for SMP 0.23.1 HF

---

kb/armory/General/db-compression-rollback.md

* Please describe your changes: Adding Armory KB article for compression rollback
* Jira/GitHub Issue numbers (if any): ASSMT-684

chore(armory): Adding Armory KB article for compression rollback

---

docs/platform/platform-whats-supported.md

bumped versions

---

docs/platform/git-experience/autocreation-of-entities.md

Add note in doc to limit commits to fewer than 300 files to avoid autocreation failures

---

docs/database-devops/dbdevops_supported_platforms.md
docs/database-devops/use-database-devops/set-up-connectors.md

* Please describe your changes: \_dbdevops supported platforms doc
* Jira/GitHub Issue numbers (if any): \ DBOPS-646

dbdevops supported platforms doc

---

.github/CODEOWNERS

Should I be added to the CI codeowners list?

Update CI Codowner to add sushrut

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md

* Please describe your changes: Resolves [CI-13991](https://harness.atlassian.net/browse/CI-13991)
* Jira/GitHub Issue numbers (if any): [CI-13991](https://harness.atlassian.net/browse/CI-13991)
[CI-13991]: https://harness.atlassian.net/browse/CI-13991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

Conditional Execution Using Crane

---

release-notes/continuous-integration.md

* Please describe your changes: CI release notes for 1.58

release notes for 1.58

---

release-notes/continuous-delivery.md

Updated release version to 1.69.9

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-sonatype-nexus.md

upload sonatype

---

docs/database-devops/use-database-devops/set-up-connectors.md

I had to add `&nbsp;` characters for proper spacing/formatting on the markdown. If anyone knows a better way let me know. 

added FAQ for oracle DB

---

release-notes/security-testing-orchestration.md

STO Release Notes for v1.120.4

---

netlify/functions/coveo_api.mts
src/components/NavbarItems/CoveoSearch.js

HDH-329-unable-to-search-through-documentation-expired-token

---

src/components/Docs/data/internalDeveloperPortal.ts

fix: [IDP]: Updates to the IDP landing page

---

docs/internal-developer-portal/flows/workflows-tutorials/create-a-new-service-using-idp-stage.md
docs/internal-developer-portal/flows/workflows-tutorials/create-new-service-along-with-pipeline.md
docs/internal-developer-portal/flows/workflows-tutorials/provision-infrastructure-using-idp.md
docs/internal-developer-portal/flows/workflows-tutorials/self-service-onboarding-pipeline-tutorial.md
docs/internal-developer-portal/techdocs/add-docs-for-components.md
docs/internal-developer-portal/tutorials/how-to-use-catalog-ingestion-api.md
docs/internal-developer-portal/tutorials/service-onboarding-pipeline.md
docs/internal-developer-portal/tutorials/service-onboarding-with-idp-stage.md
docs/internal-developer-portal/tutorials/using-secret-as-an-input.md

fix: [IDP]: Replaced all instances of templates with workflows

---

release-notes/delegate.md

Update delegate notes for CDS-105184

---

release-notes/continuous-delivery.md

update release version of NG manager to 1.69.7

---

docs/internal-developer-portal/get-started/adoption-playbook.md

feat: [IDP]: Added the info on central vs distributed catalog definition files

---

docs/continuous-integration/use-ci/use-drone-plugins/ci-jira-int-plugin.md

JIRA plugin will now update for multiple issues

---

.github/CODEOWNERS

* Please describe your changes: Add code owners for each module of the docs data files to ensure proper oversight and review.
- [] Code owner review.

chore: add code owners for docs data files

---

docs/chaos-engineering/use-harness-ce/chaos-faults/windows/experiments.ts
docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows-network-corruption.md
docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows.md

[Preview](https://6761a4c6d32a12169c21c696--harness-developer.netlify.app/docs/chaos-engineering/use-harness-ce/chaos-faults/windows/)

Update faults page

---

docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
docs/continuous-integration/use-ci/caching-ci-data/share-ci-data-across-steps-and-stages.md
kb/continuous-integration/continuous-integration-faqs.md

* Please describe your changes: CI-15007
* Jira/GitHub Issue numbers (if any): CI-15007

Add FAQ on cache between OS.

---

docs/artifact-registry/platform-integrations/ci-ar-integrations.md

* Add Tango interactive guide to AR x CI intergration doc
* [JIRA](https://harness.atlassian.net/browse/AH-803)
https://github.com/user-attachments/assets/cf33bbe7-44f8-4cfc-818c-1a3df927c1a9

docs: [AH-803]: Add Tango guide to AH and CI integration

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-block.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-body.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-header.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-status-code.md

chore: [CHAOS-7238]: Support blast radius control via transaction percentage in API Chaos

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-cpu-stress.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-method-exception.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-method-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-modify-return.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-trigger-gc.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/redis-cache-expire.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/redis-cache-limit.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/redis-cache-penetration.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-cpu-stress/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-method-exception/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-method-latency/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-modify-return/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-trigger-gc/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/redis-cache-expire/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/redis-cache-limit/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/redis-cache-penetration/params.yaml

Fix YAML examples

---

.github/CODEOWNERS

* Please describe your changes: remove Dewan from data file global owners

chore: remove Dewan from data file global owners

---

release-notes/self-managed-enterprise-edition.md

Update SMP release notes for chaos

---

docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md

* Please describe your changes: Update supported tool - cache intel 
* Jira/GitHub Issue numbers (if any):  CI-15487 , CI-15134 

Update supported tool - cache intel 

---

docs/platform/delegates/manage-delegates/delegate-metrics.md

update delegate metrics to add new metric

---

.github/CODEOWNERS

Updated codeowners for FAQ and First gen doc

Chore - Update CODEOWNERS

---

docs/continuous-integration/shared/build-and-push-local-tar.md

* Please describe your changes: the yaml example is shared in all the build and push steps, but the specific example is for build and push to Docker registry. This PR adds a note saying that the YAML can be repurposed for other registries.

Add note for other registries for local tar output.

---

docs/chaos-engineering/use-harness-ce/chaos-faults/aws/aws.md
docs/chaos-engineering/use-harness-ce/chaos-faults/aws/windows-ec2-network-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/gcp/gcp.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/kubernetes.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/linux.md
docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/vmware.md

Fixed left and right nav bar of every fault's landing page

Fixed left and right nav bar

---

release-notes/continuous-delivery.md

This includes changes 1.21 and agent 0.82 from @vishal-av 's PR last week. 

PR for Gitops 1.22, Agent 0.83

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md

Add warnings for platform connectivity

---

docs/continuous-delivery/gitops/use-gitops/sync-gitops-applications.md

Docs for Gitops Fail if steps times out 

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Add OIDC warning for AWS

---

docs/software-supply-chain-assurance/shared/generate-consign-keys-prerequisite.md
docs/software-supply-chain-assurance/shared/generate-cosign-key-pair.md

SCS: Fixed the Cosign Hyper Links

---

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md

Update last successful run tag limitations

---

university/faqs.md

Updated EDU FAQ

---

.github/CODEOWNERS

Chore - Update CODEOWNERS for platform component

---

src/components/Roadmap/data/idpData.ts

Moved out a few items from Q1 to Q2+ which may not be included in Q1. Will re-update roadmap in a few weeks after estimation.

Update IDP roadmap

---

docs/continuous-delivery/x-platform-cd-features/executions/execution-history.md

add info that executions are only kept for 6 months

---

docs/continuous-delivery/get-started/cd-tutorials/ownapp.md

[CDS-100018] Updated deploy own app links and formatting

---

docs/continuous-delivery/gitops/use-gitops/add-a-harness-git-ops-repository.md

[CDS-85348] Adding note related anonymous https connection

---

src/components/Roadmap/data/fmeData.ts

* Please describe your changes: \_____Adding thin SDKs to later phase of roadmap
* Jira/GitHub Issue numbers (if any): \__________N/A_________________
* Preview links/images (Internal contributors only): \_N/A_________________

Update fmeData.ts to add thin SDK clients to Later

---

src/components/Roadmap/data/fmeData.ts

Added links for SemVir attribute dictionary and FF alerts.  No release notes page for Access Split from within Harness so we'll leave that one w/o a link.
* Please describe your changes: \______Added links to Released items____________
* Jira/GitHub Issue numbers (if any): \_________N/A_____________________
* Preview links/images (Internal contributors only): \____N/A______________

Update fmeData.ts added links to recent release items

---

.github/CODEOWNERS

Update CODEOWNERS to add Rohan

---

docs/platform/triggers/trigger-pipelines-using-generic-events.md
docs/platform/triggers/trigger-pipelines-using-slack-events.md

Updated EventRelay Triggers title

---

docs/continuous-delivery/x-platform-cd-features/executions/step-failure-strategy-settings.md

Add step template dependency note for deployment stages

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md
docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-cloud-run.md
docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md

Added Azure Functions and Artifact tag sample links

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md
docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md

Update Docs with ECR Image for Azure function, Serverless and SAM Deployment swimlanes

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/comparison-ec2.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/tkgi/permissions.md

CHAOS-6731 EC2 chaos for k8s and linux

---

docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md

Added Faq related to difference between Last Successful Deployment Tag and from Post-Production Rollback

[CDS-105371] Added Faq

---

docs/software-engineering-insights/sei-metrics-and-reports/planning/sprint-metrics/sei-sprints-metrics.md

feat: [SEI-9880]: sprint metrics docs update

---

docs/internal-developer-portal/flows/custom-actions.md
docs/internal-developer-portal/flows/flows-output.md
docs/internal-developer-portal/flows/service-onboarding-pipelines.md

feat: [IDP]: Added the info on where parameters.x is supported. 

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md

* Update platform doc to include specific configuration for docker registry with Artifact Registry.
* [JIRA](https://harness.atlassian.net/browse/AH-860)

docs: [AH-860]: Update platform connector doc to support AR

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md
docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md
docs/continuous-integration/use-ci/run-tests/tests-v2.md
docs/continuous-integration/use-ci/run-tests/ti-overview.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md

* Please describe your changes: GAing intelligence features

GAing intelligence features

---

release-notes/self-managed-enterprise-edition.md

SMP Release Notes Summary 0.24.0

---

docs/platform/delegates/manage-delegates/configure-delegate-proxy-settings.md

Added related information about the Helm connector and the delegate proxy settings

feat: [CDS-105092]: Update configure-delegate-proxy-settings.md

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md

* Please describe your changes: Add deprecation warning.

Add warning note for deprecation timeline.

---

docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md

Add language for multi source apps in pr pipeline docs.

---

src/components/Roadmap/data/fmeData.ts

Made title more concise and correct. These are client-side SDKs only so saying "JavaScript" (which could include node), would be incorrect.
* Please describe your changes: \_____Update title and description for remote eval SDKs__________
* Jira/GitHub Issue numbers (if any): \___________N/A__________________
* Preview links/images (Internal contributors only): \__N/A_______________

Update fmeData.ts revise remote evaluation client-side SDKs

---

docs/cloud-cost-management/4-use-ccm-cost-optimization/autostopping-guides/kubernetes-autostopping-traefik.md

We give examples in this doc, but don't necessarily clarify how the values are crafted.
Added a clarification to say how the middleware header is created.

Update kubernetes-autostopping-traefik.md middleware format

---

docs/internal-developer-portal/techdocs/enable-docs.md

feat: [IDP]: Added the examples for Harness code repository URL for techdocs refernce

---

docs/internal-developer-portal/plugins/available-plugins/jenkins.md
docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md

fix:[IDP]: Fixed typo and updated an example

---

release-notes/chaos-engineering.md

Add rn entry

---

release-notes/continuous-integration.md

* Please describe your changes: CI Release Notes 1.60

CI Release Notes 1.60

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-jira-issues-in-cd-stages.md

* Please describe your changes: \_____. Additional information when creating Jira tickets.  Field requirements and user list issue
* Jira/GitHub Issue numbers (if any): \______.  https://harnesssupport.zendesk.com/agent/tickets/75823

(Update) Create Jira Ticket

---

release-notes/security-testing-orchestration.md

STO: Release Notes for week 05-01-2025

---

docs/chaos-engineering/use-harness-ce/application-map.md
kb/chaos-engineering/chaos-engineering-faq.md

Describes how to list an experiment in an application map

CHAOS-7331 List experiment in app map

---

release-notes/delegate.md
release-notes/platform.md

* Please describe your changes: system release note for platform and delegates.
* Jira/GitHub Issue numbers (if any): PL-59596

[Doc] platform system release note

---

docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-functions.md
docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md

[CDS-105547] Updated GCP OIDC compatibility

---

docs/continuous-delivery/cd-integrations.md
release-notes/continuous-delivery.md

[CDS-105762] Updated Active Feature Flags list

---

src/components/Roadmap/data/sscaData.ts

[SSCA-3165] Update SSCA Roadmap for Q4

---

release-notes/delegate.md

release note update

---

src/components/Roadmap/data/fmeData.ts

RUM sampling is being re-considered... any sampling we do will need to be beyond just RUM events.  On hold for planning and re-prioritization.
* Please describe your changes: \_______Remove RUM Sampling from roadmap________
* Jira/GitHub Issue numbers (if any): \_______________N/A____________
* Preview links/images (Internal contributors only): \___N/A____________

Update fmeData.ts removed RUM sampling from roadmap

---

docs/self-managed-enterprise-edition/performance-reports.md

* Please describe your changes: missing performance report updated
* Jira/GitHub Issue numbers (if any): PL-59579

[Doc] performance report update

---

docs/self-managed-enterprise-edition/install/helm-chart-provenance.md
release-notes/helm-chart-provenance.md
release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Added Helm Provenance in info section
* Jira/GitHub Issue numbers (if any): PL-59448

[Doc] Create single page on signed helm charts

---

docs/continuous-delivery/get-started/services-and-environments-overview.md

[CDS-105744]: Add infrastructure definition scoping limitation in doc

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk release notes updates from november 2024
* Jira/GitHub Issue numbers (if any): \ ffm-12212

ruby sdk release notes updates from november 2024

---

docs/database-devops/use-database-devops/rollback-for-database-schemas.md

* Please describe your changes: \ rollback database schemas steps added
* Jira/GitHub Issue numbers (if any): \ DBOPS-608

rollback database schemas steps added

---

.github/workflows/markdown-and-image-file-validation.yaml

revert static file checker

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk 1.4.1 notes added from november 2024
* Jira/GitHub Issue numbers (if any): \ FFM-12203

ruby sdk 1.4.1 notes added from november 2024

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk 1.4.4 added from nov 2024
* Jira/GitHub Issue numbers (if any): \ FFM-12216

ruby sdk 1.4.4 added from nov 2024

---

release-notes/feature-flags.md

* Please describe your changes: \ ruby sdk 1.4.5 added from nov 2024
* Jira/GitHub Issue numbers (if any): \ FFM-12230

ruby sdk 1.4.5 added from nov 2024

---

docs/continuous-delivery/manage-deployments/rollback-deployments.md

[CDS-104651] Added Post Deployment API docs link

---

docs/artifact-registry/manage-registries/create-registry.md

* Update AR Create Registry section for AWS ECR upstream proxy
* [JIRA](https://harness.atlassian.net/browse/AH-874)

docs: [AH-874]: Add AWS ECR selection tab

---

docs/chaos-engineering/integrations/pipeline-exec.md

CHAOS-7396 update pipeline integration

---

release-notes/chaos-engineering.md

CHAOS-7320 Release notes 1.52.3

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-block.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-body.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-modify-header.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-status-code.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-dns-spoof.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-attribute-override.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-error.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-io-latency.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-network-rate-limit.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/time-chaos.md
docs/chaos-engineering/use-harness-ce/chaoshubs/chaoshubs.md
docs/chaos-engineering/use-harness-ce/gameday.md
docs/chaos-engineering/use-harness-ce/governance/governance-in-execution/govern-run.md
docs/chaos-engineering/use-harness-ce/image-registry.md
docs/chaos-engineering/use-harness-ce/infrastructures/upgrade-infra.md
docs/chaos-engineering/use-harness-ce/probes/probes.md

Add reference links to YouTube videos
Reword existing content associated with YouTube videos

CHAOS-7353 Add reference links

---

release-notes/delegate.md

Delegate 24.12.84708 Hotfix RN

---

release-notes/feature-flags.md

* Please describe your changes: \ android sdk release notes from december 2024
* Jira/GitHub Issue numbers (if any): \ FFM-12247

android sdk release notes from december 2024

---

release-notes/continuous-delivery.md

[CDS-105922] CD release notes 1.72

---

docs/software-supply-chain-assurance/slsa/generate-slsa.md

Add Attestation sample to SLSA docs

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.61 Release Notes.

CI 1.61 release notes.

---

release-notes/platform.md

PL - Release 1.72.x

---

docs/continuous-delivery/cd-integrations.md
docs/platform/triggers/trigger-pipelines-using-generic-events.md
docs/platform/triggers/trigger-pipelines-using-slack-events.md

Updated FF details for EventRelay triggers

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

Updated GitOps Agent version 0.84.2

---

docs/platform/templates/inject-step-stage-templates.md

add flexible template demo video

---

release-notes/chaos-engineering.md

[Release notes 1.53.1](https://678f466034afd7d5ba943fb5--harness-developer.netlify.app/release-notes/chaos-engineering#version-1531)

CHAOS-7452 Release notes 1.53.1

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md

Add note that windows is not supported

---

release-notes/chaos-engineering.md

Update Release notes date

---

release-notes/feature-flags.md

* Please describe your changes: \_ruby sdk 1.4.6 notes added. archived 2024 notes. corrected missing version. 
* Jira/GitHub Issue numbers (if any): \FFM-12284 

ruby sdk 1.4.6 notes added. archived 2024 notes. corrected missing version. 

---

docs/continuous-integration/ci-supported-platforms.md
docs/platform/delegates/secure-delegates/delegate-mtls-support.md

update mtls support doc

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
docs/platform/delegates/secure-delegates/delegate-mtls-support.md

Add minimum versions for mTLS with K8s

---

src/components/Roadmap/data/stoData.ts

ease notes/new features docs: Feature/version released to at least one prod environment.

Pritesh q125 roadmap

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.62 Release Notes

CI 1.62 RN

---

docs/internal-developer-portal/plugins/custom-plugins/add-a-custom-plugin.md
docs/internal-developer-portal/plugins/custom-plugins/overview.md

feat: [IDP]: Added information on non availability of Custom Plugins in EU region

---

src/components/Roadmap/data/iacmData.ts

* Update IaCM roadmap, moving Default pipelines to `Released` and Ansible support to `Later` (Q2).
* [JIRA](https://harness.atlassian.net/browse/IAC-3004)

roadmap: [IAC-3004]: Update IaCM roadmap

---

docs/continuous-delivery/cd-infrastructure/terraform-infra/remove-provisioned-infra-with-terraform-destroy.md
docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md

[CDS-106118] Viewing Destroy Plan Logs Without Export

---

docs/platform/automation/api/api-permissions-reference.md

* Please describe your changes: API Permission for input sets
* Jira/GitHub Issue numbers (if any): PL-59432 & PL-43114

[PL-Doc] API permission updates for Input sets

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Added AWS OIDC connector limitations

---

release-notes/security-testing-orchestration.md

STO Release Notes for v1.124.3

---

.github/CODEOWNERS

* Please describe your changes: Update CI CODEOWNERS

Update CI CODEOWNERS

---

release-notes/delegate.md
release-notes/platform.md

[PL-doc] RN release 1.73.x

---

docs/continuous-delivery/cd-integrations.md

remove ff from docs

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/json-and-xml-functors.md

[CDS-105682] Masking Attributes from JSON Secrets

---

docs/software-engineering-insights/get-started/migrate-propelo-to-harness/migrate-propelo-to-harness-sei.md
docs/software-engineering-insights/sei-integrations/custom-cicd/sei-custom-cicd-integration.md

Migration guide update (adds EU cluster information)

---

release-notes/continuous-delivery.md

update 1.73.5 to 1.73.6

---

docs/continuous-delivery/x-platform-cd-features/failure-strategy-service-env.md

[CDS-105787] Override Failure Strategy at Service/Environment Level

---

_server-redirects
docs/internal-developer-portal/get-started/get-started.md

feat: [IDP]: Added the server redirect for IDP landing page

---

docs/platform/role-based-access-control/tag-based-rbac-for-pipelines.md

Add FF for tag based RABC for pipeline

---

docs/platform/automation/api/api-permissions-reference.md
docs/platform/role-based-access-control/permissions-reference.md

[feat]: [DBOPS-856]: Documenting DBDevOps Schema and Instance related resources and permissions

---

docs/platform/settings/default-settings.md

* Please describe your changes: note for adding any changes made in setting can take upto 1 min to reflect.
* Jira/GitHub Issue numbers (if any): PL-59705

[PL-Doc] Note added ➝ Default setting changes can take upto 1 min

---

docs/internal-developer-portal/get-started/get-started.md

fix: [IDP]: Increased the image width on getting started page

---

docs/continuous-integration/secure-ci/secure-connect.md

A Kubernetes deployment will self heal in the event the pod fails. The Docker example is retained under a secondary tab.
* Please describe your changes: add k8s manifest for secure connect

docs: add k8s manifest for secure connect

---

src/components/NavbarItems/components/Facet.tsx
src/components/NavbarItems/components/ResultList.tsx
src/components/NavbarItems/components/styles.module.scss
src/components/NavbarItems/data.ts
src/css/custom.css

HDH-352 coveo search box improvements

---

docs/internal-developer-portal/adoption/adoption-playbook.md
docusaurus.config.ts
static/robots.txt

fix: [IDP]: Hide Adoption Playbook from sidenav

---

docs/continuous-delivery/cd-integrations.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-patch-step.md
kb/continuous-delivery/faqs.md

feat: [CDS-103581]: remove FF from docs

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-deploy.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-swap.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-delete.md
docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-deploy.md

feat: [CDS-102903]: remove Helm Canary/BG FFs from docs

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md

add fargate limitations

---

docs/continuous-delivery/gitops/connect-and-manage/manage-argo-configs.md

Add parity options to spec sample

---

docs/platform/triggers/trigger-pipelines-using-generic-events.md

add demo video for event relay

---

docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/add-a-governance-policy-step-to-a-pipeline.md
docs/continuous-delivery/x-platform-cd-features/templates/artifact-source-template.md

Added OPA Limitation on Filter evaluation

---

docs/open-source/faq.md

* Please describe your changes: Add FAQ for running Harness Open Source in airgapped env

Add FAQ for airgapped env.

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md

FF cleanup [CDS_HELM_CANARY_STRATEGY, CDS_HELM_BG_STRATEGY]

---

release-notes/self-managed-enterprise-edition.md

[PL-Doc] SMP release notes 0.25.0

---

docs/continuous-delivery/gitops/use-gitops/agent-argocd-performance.md

Scalability and Performance the ArgoCD components

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.63 release notes

CI 1.63 release notes

---

release-notes/self-managed-enterprise-edition.md

[PL-Doc] SMP release notes 0.24.3 and 0.25.1

---

release-notes/delegate.md

release note for delegate hotfix (PIPE-24724)

---

release-notes/code-repository.md

Missing from Aug to Jan but generating that list next week.
* Jira/GitHub Issue numbers (if any): \______https://harness.atlassian.net/browse/CODE-3131________________________

[CODE-3131] - Fix - Updating code repo release notes to backfill from april. 

---

docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/veracode-scanner-reference.md

STO: Link Sample Policy to Aquasec, Prisma, and Veracode

---

docs/security-testing-orchestration/remediations/ai-based-remediations.md

STO: Add video to AI Remediation docs

---

docusaurus.config.ts
src/pages/index.tsx

Hide feedback buttons before refiner fix

---

docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/opa-policies-for-cd-entities.md
release-notes/continuous-delivery.md

Update CDS_OPA_CD_ENTITIES_GOVERNANCE FF

---

release-notes/platform.md

[PL-Doc] Release Notes 1.74.x

---

docs/chaos-engineering/whats-supported.md

[What's supported](https://679cd0cf39e4081257acf814--harness-developer.netlify.app/docs/chaos-engineering/whats-supported)

CHAOS-7321 Update whats supported

---

docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md

[CDS-106346] Updated Terraform variable files config details

---

docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-cloud-run.md

Added Note to Google Cloud Run Job step

---

release-notes/security-testing-orchestration.md

STO: Document STO Release Notes v1.125.0

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md

Update doc to inform about the changes in BG ECS with the FF: CDS_ECS_BG_VALIDATION_WITH_SAME_TARGET_GROUPS

fix:[CDS-105573] Update doc to inform about the changes in BG ECS with the FF: CDS_ECS_BG_VALIDATION_WITH_SAME_TARGET_GROUPS

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md

* Please describe your changes: Update additional docs page for IP whitelisting.

Update additional docs page for IP whitelisting.

---

release-notes/code-repository.md

* Please describe your changes: \___Backfilling Release Notes_______________________________
* Jira/GitHub Issue numbers (if any): \_____[CODE-3131]_________________________
[CODE-3131]: https://harness.atlassian.net/browse/CODE-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CODE-3131] Updating Code Repo Release Notes from Aug to Dec. This is up to date now

---

release-notes/continuous-integration.md
src/components/Roadmap/data/ciData.ts

* Please describe your changes: update external CI roadmap

update external roadmap

---

docs/self-managed-enterprise-edition/monitor-harness-on-prem.md

* Please describe your changes: Move postgresql podAnnotations under postgresql.primary
* Jira/GitHub Issue numbers (if any): PL-59970

fix: [PL-59970]: Move postgresql override under postgresql.primary

---

release-notes/self-managed-enterprise-edition.md

Add Release 0.24.4 notes

---

release-notes/self-managed-enterprise-edition.md

Release note for 0.25.2

---

docs/continuous-delivery/x-platform-cd-features/executions/step-failure-strategy-settings.md

Add support of Rollback Pipeline as post timeout action in case of Manual Intervention

---

docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md

Add Tango for Azure Function

---

docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md

* Please describe your changes: Output Variables on Step Failure
* Jira/GitHub Issue numbers (if any): CI-15190

Output Variables on Step Failure

---

src/components/Roadmap/data/codeData.ts

[CODE-3139] CR Q1 Public Roadmap update

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
release-notes/continuous-integration.md

* Please describe your changes: Change whitelist to allowlist for certain CI docs pages.

Change whitelist to allowlist.

---

docs/continuous-delivery/verify/cv-results/interpret-metric-results.md

(Update) Normalization Average note

---

docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md

Add create gitops agent guide 

---

docs/code-repository/get-started/cr-subscription-mgmt.md

updating CR documenation to include usage limits

[CODE-3144] updating CR documenation to include usage limits

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md

Bumped required versions

---

docs/chaos-engineering/use-harness-ce/infrastructures/centralized-delegate.md
docs/chaos-engineering/use-harness-ce/infrastructures/dedicated-delegate.md

Specify token is base64 decoded.

Update token authentication

---

docs/chaos-engineering/use-harness-ce/image-registry.md
release-notes/chaos-engineering.md

Update image versions required for Image Registry
Specify the same in the release notes

CHAOS-7561 Update image versions required for Image Registry

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/k8s-dry-run.md

Updated Dry Run step output

---

docs/platform/account-license-limits.md

* Jira/GitHub Issue numbers (if any): PL-59162

[PL-Doc] Roles Maximum limit update to 21k

---

docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md

Added new variable functionality to update release repo

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: hotfixes for SMP 0.14.13

[PL-Doc] Hotfix SMP-Release Notes 0.14.13 

---

docs/code-repository/config-repos/rules.md

[CODE-2767] Adding documentaton for Branch Rules at Space level

---

src/components/Roadmap/data/cdData.ts

Updated CD Q1 Roadmap

---

src/components/NavbarItems/Engine.ts
src/components/NavbarItems/components/Facet.tsx
src/components/NavbarItems/index.tsx

coveo-token-expire-handler

---

release-notes/chaos-engineering.md

CHAOS-7539 Release notes

---

docs/internal-developer-portal/catalog/software-catalog.md

[IDP] Broken link redirect added

---

docs/continuous-integration/ci-supported-platforms.md
docs/continuous-integration/troubleshoot-ci/ci-env-var.md

Document feature flag for CI always true

---

_server-redirects

* Please describe your changes: Doc page was missing affecting loss of web traffic
* Jira/GitHub Issue numbers (if any): PL-60386

[PL-Doc] Missing URL Fix 

---

docs/continuous-delivery/get-started/key-concepts.md

Add a key concept that a harness delegate is always used for deployments

---

docs/platform/monitored-service.md

Monitored service limitation

---

docs/chaos-engineering/use-harness-ce/infrastructures/enable-disable.md

creating infra using document harness terrform provider

CHAOS-6940 harness terrform provider

---

docs/platform/approvals/custom-approvals.md

clarify interaction between Pipeline, Stage, and Step timeouts

---

docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/linux/binary-installation.md

[Steps to Install binaries for VMware Linux faults](https://67a4706f3d902b171a2ba25e--harness-developer.netlify.app/docs/chaos-engineering/use-harness-ce/chaos-faults/vmware/linux/binary-installation)
PRs must meet these requirements …

CHAOS-7521 Steps to Install binaries

---

docs/platform/pipelines/step-skip-condition-settings.md

Cds 106540

---

release-notes/continuous-delivery.md

Added Gitops RN for GitOps Agent Version 0.78.0

---

docs/infra-as-code-management/pipelines/operations/iacm-cd-pipeline.md

* Update Provision during deployment doc
- This docs had a consistently high bounce rate so I rewrote it to help boost engagement. 
* [JIRA](https://harness.atlassian.net/browse/IAC-3068)

docs: [IAC-3068]: Update iacm cd provisioning doc

---

docs/infra-as-code-management/workspaces/cli-integration.md
docs/infra-as-code-management/workspaces/cost-estimation.md
docs/infra-as-code-management/workspaces/delete-workspace.md
docs/infra-as-code-management/workspaces/destroy-workspaces.md
docs/infra-as-code-management/workspaces/workspace-expressions.md
docs/infra-as-code-management/workspaces/workspace-tabs.md
docs/infra-as-code-management/workspaces/workspace-tempates.md

* New workspace settings docs to walkthrough all workspace tabs.
* [JIRA](https://harness.atlassian.net/browse/IAC-3031)

docs: [IAC-3031]: Add new workspace tabs doc

---

docs/software-supply-chain-assurance/artifact/sign-artifacts.md
docs/software-supply-chain-assurance/artifact/verify-signed-artifacts.md

SCS: Removed the Feature Flag for Artifact Signing and Verification Steps

---

release-notes/software-supply-chain-assurance.md

SCS: Release Notes 1.25.1

---

docs/continuous-delivery/x-platform-cd-features/failure-strategy-service-env.md

[CDS-106277] Added limitation for Failure Strategy

---

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md

[CDS-105748] Added note to Overrides V2

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md

[CDS-105603] Feature - ASG Steady State Step

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md

* Please describe your changes: Add note about private IP creation for pool.yml
* Jira/GitHub Issue numbers (if any): CI-15685

Add note about private IP creation for pool.yml

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md

[CDS-99008] Updated AWS Load Balancer Configuration description

---

docs/platform/delegates/secure-delegates/delegate-mtls-support.md

Add mTLS option for helm chart
* Please describe your changes: \ We added new helm option mTLS.secretName which can be used to enable mTLS feature on Delegate and Upgrader when using Helm installation otion.
* Jira/GitHub Issue numbers (if any): \ https://harness.atlassian.net/browse/PL-59074
* Preview links/images (Internal contributors only): \

feat: [PL-59074]: Add mTLS option for helm chart

---

docs/self-managed-enterprise-edition/shared/dev-env-infra.md
docs/self-managed-enterprise-edition/shared/prod-env-infra.md
docs/self-managed-enterprise-edition/smp-supported-platforms.md

SCS: Updated the SMP-supported-platform page

---

docs/self-managed-enterprise-edition/smp-supported-platforms.md

Updated the text 'Beta'

---

docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md

DO NOT MERGE - Merge only after Helm chart release - https://github.com/harness/delegate-helm-chart/pull/100
* Please describe your changes: Describe options to setting registry mirror configuration for Upgrader
* Jira/GitHub Issue numbers (if any): PL-58735

feat: [PL-58735]: Update docs about new registryMirror option

---

docs/platform/connectors/code-repositories/git-hub-app-support.md

Only PR read/write is required. 
CI-14823

deleted excessive permission.

---

docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md

Delegate release is out for clarification

---

docs/infra-as-code-management/iacm-features/module-registry/module-registry.md

Update module registry doc to:
- Remove pending release banners
- Remove prerequisites of configured connectors 
- Update required delegate version
* [JIRA](https://harness.atlassian.net/browse/IAC-3085)

docs: [IAC-3085]: Pre GA module registry doc updates

---

release-notes/feature-flags.md

* Please describe your changes: Adds release notes
* Jira/GitHub Issue numbers (if any): FFM-12325

FFM-12325 Add Proxy 2.0.8 release notes

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md

Update supported build infra docs
* Please describe your changes: Update supported build infra docs
* Jira/GitHub Issue numbers (if any): CI-15935

Update supported build infra docs

---

docs/software-supply-chain-assurance/slsa/generate-slsa.md
docs/software-supply-chain-assurance/slsa/overview.md

SCS: Add pipeline security to SLSA docs

---

docs/platform/get-started/subscriptions-licenses/subscriptions.md

CHAOS-6910 Update reference link

---

docs/chaos-engineering/use-harness-ce/license-consumption.md

Change table type

---

docs/platform/variables-and-expressions/runtime-inputs.md

Platform: Details on variables as secrets

---

docs/security-testing-orchestration/set-up-scans/built-in-scanners.md
docs/security-testing-orchestration/set-up-scans/container-scanning.md
docs/security-testing-orchestration/set-up-scans/dynamic-application-security-testing.md
docs/security-testing-orchestration/set-up-scans/infrastructure-as-code-scanning.md
docs/security-testing-orchestration/set-up-scans/shared/next-steps-for-scan-types.md
docs/security-testing-orchestration/set-up-scans/software-composition-analysis.md
docs/security-testing-orchestration/set-up-scans/static-application-security-testing.md
docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
release-notes/security-testing-orchestration.md

STO: Restructure docs for scan types

---

release-notes/continuous-integration.md

* Please describe your changes: Add CI 1.66 RN

Add CI 1.66 RN

---

docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md

[CDS-106870] Update Helm deployments

---

docs/continuous-delivery/cd-integrations.md
release-notes/continuous-delivery.md

[CDS-106822] CD release notes 1.77

---

docs/database-devops/dbdevops_supported_platforms.md
docs/database-devops/use-database-devops/set-up-connectors.md

* Please describe your changes: adding supported db name
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-879

[DBOPS-879]: adding google spanner to supported dbs

---

docs/software-supply-chain-assurance/cicd-security-posture-management-cicdspm.md
docs/software-supply-chain-assurance/repository-security-posture-management-rspm.md

SCS: Added a note for the RSPM and CI/CD SPM scans

---

docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
docs/platform/connectors/code-repositories/connect-to-code-repo.md
docs/self-managed-enterprise-edition/install/manage-feature-flags.md

feat: [CDS-106830]: remove NG docs for the FF OPTIMIZED_GIT_FETCH_FILES

---

docs/continuous-delivery/verify/cv-concepts/cv_templates.md

update the documentation with a note specifying that GitX is not supported for monitored services

---

docs/infra-as-code-management/get-started/get-started.md
docs/infra-as-code-management/get-started/overview.md
docs/infra-as-code-management/workspaces/create-workspace.md

* Update IaCM, Get Start, and Create/Clone workspace docs to include the new workspace wizard guide.
* [JIRA](https://harness.atlassian.net/browse/IAC-2964)

docs: [IAC-2964]: Update docs to include pending new workspace wizard

---

release-notes/self-managed-enterprise-edition.md

[PL-Doc] SMP release notes 0.25.3

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md

Mention PowerShell 7.5.0+ incompatibility with Harness delegate

---

docs/internal-developer-portal/adoption/adoption-playbook.md

fix: [IDP]: Reverted the hidden status of Adoption playbook

---

release-notes/platform.md

* Please describe your changes: Platform Release Note 1.77.x
* Jira/GitHub Issue numbers (if any): [PL-Qry](https://harness.atlassian.net/issues/?filter=15297&jql=%28fixversion%20%3D%20%22ng-manager%2Fv1.77.0%22%20OR%20fixversion%20%3D%20%22next-gen-ui%2Fv1.62.0%22%29%20AND%20project%20in%20%28Platform%29%20AND%20%22Release%20Notes%20Candidate%5BCheckboxes%5D%22%20%3D%20Yes) & PL-60500
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) …

[Pl-Doc] Platform Release Note 1.77.x

---

docs/artifact-registry/get-started/overview.md
docs/artifact-registry/whats-supported.md

* Update What's supported page with latest supported and upcoming registries, and remove references to BETA.
* [JIRA](https://harness.atlassian.net/browse/AH-980)

docs: [AH-980]: Update supported registries

---

release-notes/chaos-engineering.md

CHAOS-7629 Release notes 1.55

---

docs/continuous-delivery/cd-integrations.md
docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-a-kubernetes-sidecar-container.md

Added info related to FF CDS_K8S_CUSTOM_YAML_PARSER

---

kb/reference-architectures/ccm/best-practices/aws-connectors-and-roles.md
kb/reference-architectures/ccm/best-practices/azure-connectors-and-roles.md
kb/reference-architectures/ccm/best-practices/ccm-only-delegate.md
kb/reference-architectures/ccm/best-practices/gcp-connectors-and-roles.md
kb/reference-architectures/ccm/best-practices/k8s-and-ccm-k8s-connectors.md
kb/reference-architectures/ccm/onboarding/autostopping/k8s.md
kb/reference-architectures/ccm/onboarding/k8s.md

ccm best practices and onboarding doc improvements

---

docs/chaos-engineering/getting-started/saas/saas.md

Update heading level

---

docs/harness-cloud-operations/computing-uptime.md
docs/software-engineering-insights/sei-administration/harness-sei-sli.md
docs/software-engineering-insights/setup-sei/configure-integrations/sei-integrations-overview.md

feat: [SEI-10461]: adds harness sei sli

---

docs/faqs/chaos-engineering-faqs.md

HDH 358 broken link fix in main

---

docs/infra-as-code-management/workspaces/workspace-expressions.md

* Update workspace expression doc to improve bounce/engagement rates.
* [JIRA](https://harness.atlassian.net/browse/IAC-3150)

IAC-3150 Update workspace expression doc for improved engagement

---

kb/feature-flags/harness-feature-flag-faqs.md

* Please describe your changes: fix typo

Fix typo in harness-feature-flag-faqs.md

---

docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md

feat: [CDS-105586]: ssh skip instances V2 errata

---

src/components/Docs/IncidentResponse.tsx

Updated module name in title
* Please describe your changes: Updating title of module

Update module name in title

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Updated AWS OIDC Connector Limitations

---

release-notes/continuous-delivery.md

[CDS-106823] CD release notes 1.78

---

release-notes/platform.md

[PL-Doc] Release notes 1.78.x

---

src/components/Roadmap/data/cdData.ts

[CDS-107129] Added doc to Q4 delivered features

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md

Update connector limitations

---

docs/software-supply-chain-assurance/artifact/verify-signed-artifacts.md

SCS: Removed the note from Artifact Verification

---

release-notes/delegate.md

[PL-Doc] Delegate RN 25.02.85301

---

docs/platform/git-experience/git-experience-overview.md

support of git experience for OPA Policy

---

docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md

Update Selective Rerun and Skipping Hosts with Same Artifact

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md

* Please describe your changes: \_____  Updated with information about feature flag and Rootless images
* Jira/GitHub Issue numbers (if any): \__. https://harness.atlassian.net/browse/CI-14868

(Update) Rootless Windows

---

docs/infra-as-code-management/pipelines/plugin-images.md

* Update plugin image descriptions and layout
* [JIRA](https://harness.atlassian.net/browse/IAC-3171)

docs: [IAC-3171]: Update plugin images

---

docs/internal-developer-portal/flows/worflowyaml.md

[IDP] Quick fix - Harness API Key Secret Definition

---

docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md

feat: [CDS-107184]: add docs about supported terragrunt version

---

docs/platform/governance/policy-as-code/harness-governance-overview.md
docs/platform/templates/create-a-remote-pipeline-template.md

feat: [Feature Request] - Policy to disallow inline account templates

---

release-notes/delegate.md

[PL-Doc] Delegate updating to 24.12.84710

---

docs/platform/variables-and-expressions/harness-expressions-reference.md

feat: use isResolved and isUnresolved expressions for reliable variable evaluation

---

docs/software-engineering-insights/setup-sei/configure-integrations/gitlab/sei-gitlab-onprem.md
docs/software-engineering-insights/setup-sei/configure-integrations/gitlab/sei-gitlab-private-cloud.md
docs/software-engineering-insights/setup-sei/configure-integrations/gitlab/sei-integration-gitlab.md

fix: update token permission on gitlab integration document

---

release-notes/continuous-integration.md

added note about new license page

---

docs/continuous-integration/secure-ci/configure-oidc-gcp-wif-ci-hosted.md

Remove incorrect supportability information from doc.

---

release-notes/delegate.md

Update delegate release dodc

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md

Add Kubernetes Faq related to GIT_SSL_NO_VERIFY and SCM_SKIP_SSL flags

---

docs/chaos-engineering/use-harness-ce/use-harness-ce.md

Content audit and add reference links

Content audit

---

docs/continuous-delivery/x-platform-cd-features/overrides-v2.md

Update doc to remove info regarding support of storing overrides in default branch

---

docs/continuous-delivery/cd-infrastructure/aws-cdk.md
docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md
docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md

Update OIDC support

---

docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md

Added DescribeInstanceRefreshes API to ASG Steady State Step

---

docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md

This reverts changes made to help cover for this bug: https://harness.atlassian.net/browse/CDS-104975

Remove dated warnings about OIDC

---

docs/platform/secrets/secrets-management/add-hashicorp-vault.md

[PL-Doc] Added note for bound_issuer & oidc_discovery_url

---

docs/platform/authentication/single-sign-on-saml.md

[PL-Doc] Fixing typo

---

docs/platform/references/allowlist-harness-domains-and-ips.md

Added new NAT IPs for IE Infra. 
For U.S.
104.196.251.84
34.94.191.198
34.106.170.77
For Eu
34.38.153.209
35.189.94.200
34.141.112.174
* Please describe your changes: Added new NAT IPs
* Jira/GitHub Issue numbers (if any): OPS-46554

Added new NAT IPS for IE Evolve

---

docs/platform/secrets/secrets-management/add-hashicorp-vault.md

* Jira/GitHub Issue numbers (if any): PL-60855

[PL-Doc] JWT/Vault : Add note for Delegate version support. 

---

release-notes/self-managed-enterprise-edition.md

* Please describe your changes: Release notes added for SMP version 0.26.0 and 0.25.4
* Jira/GitHub Issue numbers (if any): [Release Tickets](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22330245122/Release+Notes+tickets+for+v0.26.0+release) & [Doc](https://harness.atlassian.net/browse/PL-60700)

[PL-Doc] SMP RNs for 0.26.0 & 0.25.4

---

docs/database-devops/dbdevops_supported_platforms.md
docs/database-devops/get-started/overview.md
sidebars.ts
src/components/Docs/ArtifactRegistry.tsx
src/components/Docs/DatabaseDevOps.tsx

Remove beta from IR, AR, and DBDEVOPS

---

docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md

* Please describe your changes: Native support to handle immutable ECR repo.
* Jira/GitHub Issue numbers (if any): [CI-10350](https://harness.atlassian.net/browse/CI-10350), [CI-16087](https://harness.atlassian.net/browse/CI-16087)
[CI-10350]: https://harness.atlassian.net/browse/CI-10350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

Native support to handle immutable ECR repo.

---

release-notes/infrastructure-as-code-management.md

* Please describe your changes: Existing PRs like https://github.com/harness/developer-hub/pull/9566/ are failing due to this broken link. IaCM CODEOWNERS: pls review.

Fix IaCM release notes broken link.

---

docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
docs/infra-as-code-management/workspaces/worksace-statuses.md
docs/infra-as-code-management/workspaces/workspace-tabs.md
docs/infra-as-code-management/workspaces/workspace-tempates.md
src/components/Roadmap/data/iacmData.ts

* Update IaCM Roadmap tiles so they link to docs
* [JIRA](https://harness.atlassian.net/browse/IAC-3243)
https://github.com/user-attachments/assets/3d378391-2adb-44e3-9924-5d124541be1f

docs: [IAC-3243]: Make roadmap tiles clickable

---

src/components/Roadmap/data/seiData.ts

fixes typo in sei roadmap

---

kb/continuous-integration/continuous-integration-faqs.md

limit change description - FAQ

---

docs/software-engineering-insights/ai-productivity-insights/dashboards/ai-overview-dashboard.md

fix: [SEI-10693]: adds the current peb formula

---

release-notes/self-managed-enterprise-edition.md

docs: [CDS-107535]: Release Notes - SMP HF 1.26.2

---

docs/platform/service-discovery/service-discovery.md

CHAOS-7739 Specify how service discovery works

---

release-notes/platform.md

* Please describe your changes: Updated PL release notes "Important feature change notice" section to add a Warning banner for upcoming changes on default registry change for Harness images.

PL Release notes:Add upcoming default registry change warning

---

release-notes/chaos-engineering.md

CHAOS-7722 Release notes

---

docs/database-devops/use-database-devops/database-devops-images.md
docs/database-devops/use-database-devops/governance/using-opa-with-database-devops.md

[DBOPS-894]: Update the DBOPS base images documentation

---

src/components/HomepageFeatures/data/featureListData.tsx
src/components/LearnAboutPlatform/data/moduleListData.tsx

Change "run chaos experiments" to "resilience testing"

CHAOS-7767 Change "run chaos experiments"

---

docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-cache-expire.md

Review for CHAOS-7293

---

.github/CODEOWNERS

* Please describe your changes:  update FME Release Notes Codeowners

Chore: update FME Release notes codeowners

---

src/components/Roadmap/data/idpData.ts

IDP Roadmap Update

---

docs/continuous-delivery/monitor-deployments/pipeline-execution-dashboard.md

feat:[PIPE-25667]: Documentation for total queued count in executions explore

---

release-notes/continuous-integration.md

CI RN 1.68 FF addition

---

src/components/Roadmap/data/platformData.ts

HDH PL Roadmap:Update PL items

---

docs/self-managed-enterprise-edition/install/install-using-helm.md

* Please describe your changes: \_____  Update correction for SMP Vanity URL creation
* Jira/GitHub Issue numbers (if any): \______  Zendesk Ticket: https://harnesssupport.zendesk.com/agent/tickets/79712
Slack Conversation: https://harness.slack.com/archives/CSL96M7UG/p1741192438364579
* 

(Update) Vanity URL

---

docs/internal-developer-portal/flows/dynamic-picker.md
docs/internal-developer-portal/flows/worflowyaml.md

[IDP] Add docs on feature flag not supported in Playground Editor

---

docs/platform/triggers/trigger-deployments-using-custom-triggers.md

* Please describe your changes: \_____. Clarify the documentation around what the default setting is
* Jira/GitHub Issue numbers (if any): \_______ https://harness.atlassian.net/browse/PIPE-24469?atlOrigin=eyJpIjoiODE2NGIzOGY1NDAwNGMxZjhhMzcwMGJhZDVlMjE0YzEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

(Update) Clarify documentation

---

docs/self-managed-enterprise-edition/advanced-configurations/configure-custom-dashboards.md
docs/self-managed-enterprise-edition/advanced-configurations/configure-custom-smp-dashboards.md

* Jira/GitHub Issue numbers (if any): [PL-46628](https://harness.atlassian.net/browse/PL-46628) 
[PL-46628]: https://harness.atlassian.net/browse/PL-46628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PL-Doc] Custom-dashboard page in SMP 

---

docs/faqs/chaos-engineering-faqs.md
kb/chaos-engineering/chaos-engineering-faq.md

Update reference links in KB and FAQs section

Update reference links

---

docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/event-listener-step.md

[CDS-105554] Feature: Event Listener

---

docs/continuous-delivery/gitops/troubleshooting.md

Redis NOAuth docs added to troubleshooting

---

release-notes/self-managed-enterprise-edition.md

GitOps and CCM HF - SMP HF 0.26.3

---

docs/chaos-engineering/getting-started/smp/connect-enterprise-chaoshub.md
docs/chaos-engineering/getting-started/smp/connect-infrastructure.md
docs/chaos-engineering/getting-started/smp/enable-ff.md
docs/chaos-engineering/getting-started/smp/prerequisites.md

CHAOS-7824 Prerequisite

---

docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/byoc-injector.md

chore: [CHAOS-7828]: Remove the chaos_duration field from byoc fault

---

release-notes/continuous-integration.md

* Please describe your changes: CI 1.70 RN
@nofarblue a few things to modify on this PR:
- Need the FF name for https://harness.atlassian.net/browse/CI-15756
- Need to update the generic text under "Change" column for image updates. I couldn't find any details on https://harness.atlassian.net/wiki/spaces/CI1/pages/22352234325/CI+Feature+Sign+off+3rd-March+2025 …

CI 1.70 Release Notes

---

docs/platform/authentication/single-sign-on-saml.md

[PL-Doc] SAML update permission

---

docs/platform/variables-and-expressions/harness-expressions-reference.md

Add expressions to fetch original execution details when rollback occurs

---

docs/platform/pipelines/failure-handling/timeout-settings.md

Update documentation to clarify the behavior of EXPIRE_ALL status wrt to failure strategy

---

src/components/Roadmap/data/stoData.ts

update sto roadmap for Q1 FY'26

---

docs/platform/triggers/triggers-overview.md

Remove CD_TRIGGER_V2 FF from docs

---

kb/continuous-integration/articles/parallel-step-for-logging.md

Added background task monitoring step

---

.github/CODEOWNERS

SCS: Add Lavakush to the SCS Codeowners

---

src/components/Roadmap/data/sscaData.ts

SCS: Add Tags to the SCS Roadmap

---

docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr-vs-dedicated.md
docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/ddcr.md
docs/chaos-engineering/use-harness-ce/infrastructures/types/legacy-infra.md

Move the comparison of ddcr versus dedicated to "types" section

Move to "types" section

---

docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/redis-cache-expire.md
docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/redis-cache-expire/params.yaml
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/redis-cache-expire.md
docs/chaos-engineering/use-harness-ce/chaos-faults/linux/static/manifests/redis-cache-expire/keys.yaml

* Please describe your changes: adds changes for redis cache expire multiple keys
* Jira/GitHub Issue numbers (if any): CHAOS-7293

feat: [CHAOS-7293]: adds changes for redis cache expire multiple keys

---

docs/platform/variables-and-expressions/runtime-input-usage.md

* Jira/GitHub Issue numbers (if any): [Doc Ticket](https://harness.atlassian.net/browse/PL-61163)

[PL-Doc] Fix false statement

---

docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr-vs-dedicated.md

Update ddcr vs dedicated infra with info on CRDs and faults that can be executed.

Update ddcr vs dedicated

---

release-notes/continuous-integration.md

Update to 1.70 RN.

---

docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-releases-and-versioning.md

Add warning for release names to be unique.

---

docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr-vs-dedicated.md

Fix keyword

---

release-notes/platform.md

adding GAR path in PL RN

---

docs/chaos-engineering/getting-started/onboarding/onboarding.md
docs/chaos-engineering/use-harness-ce/experiments/create-experiments.md

CHAOS-7868 Update onboarding

---

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
docs/platform/triggers/triggers-overview.md

[CDS-107857] Google Container Registry deprecation note

---

docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
docs/platform/triggers/triggers-overview.md

update GCR deprecation dates

---

docs/software-supply-chain-assurance/shared/ssca-supported.md

SCS: Add table for SCS Steps Support Across Stages

---

kb/reference-architectures/ccm/onboarding/k8s.md

the terraform here is broken due to the resource name having a capital letter.
also need to clean up the example code to be how you would really use it, not copy/paste from the linked docs (which dont follow best practice).

fix: k8s onboarding tf

---

docs/chaos-engineering/concepts/how-stuff-works/io-stress-latency-flow.md

How stuff works- IO stress update

---

docs/security-testing-orchestration/set-up-scans/secret-detection.md
docs/security-testing-orchestration/set-up-scans/shared/next-steps-for-scan-types.md

STO: Add secret detection to set up scans section

---

docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/centralized-delegate.md
docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/dedicated-delegate.md
docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/installation.md
docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/mtls-support.md

CHAOS-7872 Update DDCR

---

docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md

* Please describe your changes: This adds extra information to the AWS VM Build Infrastructure documentation page for CI
* Jira/GitHub Issue numbers (if any): None

Update CI AWS Build Infrastructure Documentation

---

docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md

* Please describe your changes: CI-16383 update and remove long GA note.
* Jira/GitHub Issue numbers (if any): CI-16383

CI-16383 update and remove long GA note.

---

release-notes/self-managed-enterprise-edition.md

[PL-Doc] SMP hotfix 0.26.4 - RN

---

release-notes/continuous-integration.md

Update RN with docker rate limit change

---

release-notes/platform.md

pl - docker limit notice update

---

docs/platform/git-experience/autocreation-of-entities.md

Remove autocreation FF from doc

---

docs/software-supply-chain-assurance/sbom/generate-sbom.md

SCS:Add Info for the SBOM File Path

---

docs/platform/authentication/single-sign-on-saml.md

[PL-Doc] SSO with saml
