harness/developer-hub

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> [CDS-107039] Tag support for Lambda and ECS deployment

- docs/platform/governance/policy-as-code/harness-governance-overview.md
- docs/platform/governance/policy-as-code/policy-as-code-faqs.md
> Update documentation to include OPA library version 0.62.0

- docs/continuous-delivery/cd-integrations.md
- release-notes/continuous-delivery.md
> Cds 107425

- docs/continuous-integration/get-started/onboarding-guide.md
> Ci get started revamp

- docs/faqs/chaos-engineering-faqs.md
- kb/chaos-engineering/chaos-engineering-faq.md
> Update FAQ and KB links

- src/components/Roadmap/HorizonCard/index.tsx
> FIX : HDH-362-roadmap-card-dark-mode-issue

- docs/platform/governance/audit-trail/audit-streaming.md
* Jira/GitHub Issue numbers (if any): [Doc](https://harness.atlassian.net/browse/PL-61288)
> [PL-Doc] Update account scope for Audit streaming

- docs/platform/triggers/triggers-reference.md
> [CDS-106754] Feature: Gitlab trigger for tag creation

- docs/platform/pipelines/dynamic-execution-pipeline.md
> Add example for dynamic execution of pipeline

- docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md
* Update module registry usage doc to include local authentication and correct example folder structure in submodule usage.
* [JIRA](https://harness.atlassian.net/browse/IAC-3329)
> docs: [IAC-3329]: Update module registry local auth

- docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-gcs-step-settings.md
The content that was added here was heavily constructed from @Ompragash 's gist: https://gist.github.com/Ompragash/78592f5830c0503d581b044f141f4946
Thus, this PR requires an approval from him before merging. 
> Add OIDC support to download for GCS

- docs/software-supply-chain-assurance/artifact/sign-artifacts.md
- docs/software-supply-chain-assurance/artifact/verify-signed-artifacts.md
- docs/software-supply-chain-assurance/sbom-policies/enforce-sbom-policies.md
- docs/software-supply-chain-assurance/sbom/generate-sbom.md
- docs/software-supply-chain-assurance/shared/artifact-source.md
- docs/software-supply-chain-assurance/slsa/generate-slsa.md
- docs/software-supply-chain-assurance/slsa/verify-slsa.md
> SCS: Add note for the GCR Deprecation for all the steps

- docs/platform/triggers/triggers-reference.md
- release-notes/continuous-delivery.md
> [CDS-108113] Revert Gitlab Tag based trigger docs and RN

- docs/chaos-engineering/use-harness-ce/experiments/fault-template.md
> [CHAOS-7927] Specify feature flag

- docs/platform/triggers/triggers-reference.md
> [CDS-106741] Feature: Github trigger Support for tag

- release-notes/self-managed-enterprise-edition.md
> [PL-Doc]Add SMP RN 0.26.7

- kb/reference-architectures/ccm/onboarding/k8s.md
> correct harness_platform_connector_kubernetes_cloud_cost

- release-notes/platform.md
> [PL-Doc] Sys release 1.80.x

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: ng-manager version was wrong. it has been fixed.
> [PL-Doc] Fix ng manager version

- docs/continuous-delivery/cd-infrastructure/cloudformation-infra/cloud-formation-provisioning-with-harness.md
- docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
- docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-provisioning-with-harness.md
- docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot-deployment.md
- docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md
- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> Update AWS OIDC connector limitations

- release-notes/self-managed-enterprise-edition.md
> [PL-Doc]Add missing Custom Banner release in SMP 0.26.0

- docs/continuous-delivery/cd-integrations.md
- release-notes/continuous-delivery.md
> [CDS-108176] CD release notes 1.81

- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> CI-16565 Notes

- docs/infra-as-code-management/remote-backends/state-migration.md
* Update state migration doc to make it more usable and straightforward, highlight the 3 phases and copyable command snippets.
* [JIRA](https://harness.atlassian.net/browse/IAC-3370)
> docs: [IAC-3370]: Update State Migration doc

- docs/continuous-integration/shared/build-and-push-runtime-flags.md
> add ignore path flag needs stage variable.

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> Remove non existent ff

- release-notes/delegate.md
> Update delegate.md for Delegate HF 85302

- release-notes/delegate.md
> Update delegate.md for Delegate HF 85305

- docs/faqs/chaos-engineering-faqs.md
- kb/chaos-engineering/chaos-engineering-faq.md
> Update HCE to Harness CE

- docs/continuous-delivery/gitops/gitops-faqs.md
> CDS-107602: Add FAQ for ArgoCD ApplicationSet failure with Harness Code Repo

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
> CDS-100549: Document that pipeline and stage variables are being added to env variables for command step

- docs/continuous-delivery/gitops/use-gitops/add-a-harness-git-ops-repository.md
> CDS-108122: Add note on Helm OCI limitation in application creation in Gitops

- docs/platform/pipelines/pipeline-settings.md
> PIPE-23059: Add timeout precedence hierarchy for pipeline timeout settings

- docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-api-block.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-api-block/advanced-fault-tunables.yaml
> feat: [CHAOS-7968]: enhance the pod-api-block fault to add data_direction support

- release-notes/delegate.md
Merged the delegate 25.02.85303 and 25.02.85304 into 25.02.85305 version
> Merged the delegate 25.02.85303 and 25.02.85304 into 25.02.85305 version

- docs/platform/git-experience/git-settings.md
> [CDS-106722] Feature: Git experience for CD Entities

- release-notes/platform.md
> [PL-Doc] System RN 1.81.x

- docs/continuous-delivery/gitops/get-started/harness-cd-git-ops-quickstart.md
> CDS-107828: Update doc that we don't support using harness expressions in gitops manifest

- src/components/Roadmap/data/aidaData.ts
> updated Harness AI roadmap

- .github/CODEOWNERS
> Add codeowners for PST timezone pipeline

- docs/platform/variables-and-expressions/harness-expressions-reference.md
> PIPE-26127: Document new expression support for notification event type

- release-notes/delegate.md
> [PL-Doc]  Delegate RN - 25.03.85403

- docs/platform/variables-and-expressions/expressions-java-methods.md
> [CDS-108232] Added warning related to .replace() expression resolution

- docs/database-devops/use-database-devops/database-devops-images.md
> Update harness images tags

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-delete.md
Adding Command Flags at the Service for Helm delete step
> [CDS-108313] Adding Command Flags configs at the Service

- docs/platform/variables-and-expressions/expressions-java-methods.md
* Please describe your changes: \______ Explain how to resolve for variables that may not be available at the time of resolution.
* Jira/GitHub Issue numbers (if any): \_______ https://harness.atlassian.net/browse/CDS-108232
> (Update) Info Method Order Resolution

- docs/platform/pipelines/failure-handling/define-a-failure-strategy-for-pipelines.md
> update rollback docs.

- release-notes/self-managed-enterprise-edition.md
> [PL-Doc] SMP Release Notes hf-0.26.10

- docs/self-managed-enterprise-edition/install/install-in-an-air-gapped-environment.md
* Please describe your changes: Add airgap global config for SMP installation
* Jira/GitHub Issue numbers (if any): PL-61359
> fix: [PL-61359]: Add airgap config in install-in-an-air-gapped-environment.md

- docs/self-managed-enterprise-edition/advanced-configurations/configure-custom-dashboards.md
* Please describe your changes: Update configuration for looker and fix indentation
* Jira/GitHub Issue numbers (if any): PL-61359
> fix: [PL-61359]: Update configuration for looker in configure-custom-dashboards.md

- docs/security-testing-orchestration/view-security-test-results/export-scan-results.md
> STO: Add Run step to the pipeline

- release-notes/cloud-cost-management.md
> Release notes ccm

- docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> Added support for other secret managers.

- docs/continuous-integration/get-started/onboarding-guide.md
> Update paths to be absolute not relative. Fix dead links

- src/components/University/data/ci-certification-developer-review-guide.md
> Updated CI Dev Dead Link

- release-notes/delegate.md
* Please describe your changes: This is Biweekly Delegate Release Notes. 
* Jira/GitHub Issue numbers (if any): [RN list](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22405971969/NG+Release+SAAS+March+24th+2025+for+1.82.xx-+Build#NG-Delegate-dependent-changes-(List-created-using-Jira-fixed-version)) & [Sign off](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22402924630/Build+Release+Sign+off+March+24th+-+build+1.82.xx+-+2025) …
> [PL-Doc] Delegate RN 25.03.85503

- release-notes/platform.md
> [PL-Doc] Platform Release Notes 1.82.xx

- docs/platform/pipelines/run-specific-stage-in-pipeline.md
> You can select Re-run Stage even if Pipeline is Successful

- release-notes/delegate.md
> [PL-Doc] delegate version update 25.03.85504

- release-notes/delegate.md
* Please describe your changes: This PR adds missing release notes that were available in the public repo but were not previously published, as there were no delegate tickets for those versions.
* Jira/GitHub Issue numbers (if any): [JIRA Ticket](https://harness.atlassian.net/browse/PL-61515)
> [PL-Doc] Add delegate RN for 24.12.84709,25.01.85000,25.02.85201

- docs/platform/governance/policy-as-code/harness-governance-overview.md
- docs/platform/governance/policy-as-code/policy-as-code-faqs.md
> Add documentation for Service entity support in On Run and On Save events. Mention feature flag CDS_ENABLE_SERVICE_ON_RUN_OPA_EVAL.

- release-notes/continuous-delivery.md
> Release notes 1.82.3

- release-notes/delegate.md
* Please describe your changes:Updated RN.
* Jira/GitHub Issue numbers (if any): [JIRA TICKET](https://harness.atlassian.net/browse/CDS-108081) & [Slack thread](https://harness.slack.com/archives/C08KED7FX38/p1743090242709529)
> [PL-Doc] delegate RN 85504

- release-notes/platform.md
* Please describe your changes: RN added for feature notification via delegate in 1.81.x
* Jira/GitHub Issue numbers (if any): [JIRA Ticket](https://harness.atlassian.net/browse/PL-61277)
> [PL-Doc] Notification via Delegate RN

- docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
> [CDS-102223] Doc update: Terraform Artifactory support

- .github/CODEOWNERS
* Please describe your changes: Adding myself as codeowner of CODE related docs
> CODEOWNERS | Add `johannesHarness` as owner of CODE Docs

- docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md
> Add local files as build dependencies

- release-notes/continuous-integration.md
* Please describe your changes: CI Release Notes 1.72
> CI Release Notes 1.72

- docs/platform/triggers/trigger-pipeline-on-tag-event.md
> added payload conditions for push tag triggers

- docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
* Please describe your changes: Changes per CI-16202
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CI-16202
> Changes per CI-16202

- docs/platform/get-started/tutorials/install-delegate.md
We don't have any prerequisite on kubernetes version for delegate hence removing it from the doc
> remove kubernetes version from install delegate page

- release-notes/chaos-engineering.md
> CHAOS-7898 Release notes 1.57.2

- docs/chaos-engineering/getting-started/saas/saas.md
> CHAOS-8013 Fix typo

- docs/continuous-delivery/cd-integrations.md
- release-notes/continuous-delivery.md
> Update release notes and active FF table

- docs/database-devops/concepts-and-features/understanding-changelog-directories/changelog-directories-structure.md
> [DBOPS - 436]: one change in one changeset

- docs/infra-as-code-management/workspaces/workspace-tabs.md
* Remove execution history from workspace settings doc as it has been replaced with Activity History.
* [JIRA](https://harness.atlassian.net/browse/IAC-3416)
> docs: [IAC-3416]: Remove execution history from workspace settings

- docs/self-managed-enterprise-edition/troubleshooting/timescaledb.md
* Please describe your changes: Create troubleshoot document for SMP timescaledb
* Jira/GitHub Issue numbers (if any): PL-61388
> fix: [PL-61388]: Create troubleshoot document for SMP timescaledb

- docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
- release-notes/continuous-delivery.md
> GitOps Release Notes 1.28

- docs/software-supply-chain-assurance/sbom/generate-sbom.md
> SCS: Add Info for support of all Registry types in SBOM step

- docs/chaos-engineering/security/security-templates/security-templates.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/kube-resilience/kube-resilience.md
Add redirects to fix broken links
[Slack Conversation](https://harness.slack.com/archives/C8LE2H4BE/p1743623521212849?thread_ts=1743622436.426739&cid=C8LE2H4BE)
> [CHAOS-8025] Add redirects

- release-notes/continuous-integration.md
* Please describe your changes: Add missing FF for CI-15398
* Jira/GitHub Issue numbers (if any): CI 1.73 release notes update
> Add missing FF for CI-15398

- release-notes/software-supply-chain-assurance.md
> SCS: Release Notes - 1.29.0

- docs/continuous-delivery/cd-infrastructure/provisioning-faqs.md
- docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
- docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-faqs.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/use-a-local-helm-chart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-releases-and-versioning.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
- docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-winrm-faqs.md
- docs/continuous-delivery/manage-deployments/deployment-faqs.md
- docs/continuous-delivery/shared/cd-integrations-supported.md
- docs/continuous-delivery/verify/continuous-verification-faqs.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
- docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md
- docs/continuous-delivery/x-platform-cd-features/services/harness-file-store-faqs.md
- docs/continuous-delivery/x-platform-cd-features/templates/static/create-a-remote-step-template.md
> Remove firstgen cd

- docs/internal-developer-portal/rbac/resources-roles.md
> [IDP] Add info on deprecated IDP platform engineer role

- docs/database-devops/dbdevops-supported-platforms.md
* Please describe your changes: \ Add description for CDS_EXECUTION_LIST_CARD_VIEW Feature flag
> Update dbdevops-supported-platforms.md with FF details

- docs/platform/triggers/triggers-reference.md
> [CDS-106754] Feature: Gitlab Trigger for tag events

- docs/platform/triggers/triggers-reference.md
> [CDS-106754] Gitlab Tag support update

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-apply-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-patch-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-restart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-step.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/k8s-command-flags.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/delete-kubernetes-resources.md
> [CDS-108376] K8s Command flags

- docs/infra-as-code-management/iacm-features/module-registry/module-registry-testing.md
- docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
* Add new module registry testing doc
* [JIRA](https://harness.atlassian.net/browse/IAC-3374)
> docs: [IAC-3374]: Add updated module registry testing doc

- docs/infra-as-code-management/remote-backends/state-migration.md
- docs/infra-as-code-management/workspaces/create-workspace.md
* Update tfvar file usage to inform users that tfvar files don't support jexl.
* [JIRA](https://harness.atlassian.net/browse/IAC-2903)
> docs: [IAC-2903]: Add tfvar jexl support info panels

- docs/continuous-integration/shared/build-and-push-runtime-flags.md
> Add docs for environment variable for CI

- docs/continuous-integration/shared/build-and-push-runtime-flags.md
* Please describe your changes: Changes requested per CI-16952
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CI-16952
> Revised explanation for envDockerSecrets.

- docs/software-supply-chain-assurance/get-started/overview.md
> SCS: Fix Broken links

- docs/infra-as-code-management/workspaces/workspace-tabs.md
* Add descriptions for IaCM workspace configuration advanced options:
-  Submodules and sparse checkout
* [JIRA](https://harness.atlassian.net/browse/IAC-3480)
> docs: [IAC-3480]: Add workspace configuration advanced option descriptions

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
- docs/platform/tags/apply-filters-using-tags.md
> fix:[CDS-108375]: add note about issues with newlines in input variables for Command and Shell Script steps

- docs/continuous-integration/shared/enhanced-output-variables.md
- docs/continuous-integration/shared/output-var.md
* Please describe your changes: [Details](https://harness.slack.com/archives/C03KSJDM3NK/p1744215047143149)
> Remove front matter from partials.

- docs/chaos-engineering/use-harness-ce/chaos-faults/aws/security-configurations/aws-switch-profile.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/aws/security-configurations/introduction.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/sql-failover.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/gcp/security-configurations/gcp-iam-integration.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/permissions/fault-wise-permission.md
- docs/faqs/chaos-engineering-faqs.md
- kb/chaos-engineering/chaos-engineering-faq.md
Move GCP IAM integration into "security configurations" directory
Rename "AWS switch profile" to "AWS secret-based authentication"
> Move IAM integration into "security configurations" directory

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
- release-notes/continuous-delivery.md
> Update AWS lambda limitation

- docs/internal-developer-portal/2-0-overview-and-upgrade-path.md
> Add tentative date for IDP 2.0

- release-notes/delegate.md
* Please describe your changes: No tickets, regular system checks and stability implemented
* Jira/GitHub Issue numbers (if any): [JIRA](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22441001091/NG+Release+SAAS+April+7th+2025+for+1.84.xx-+Build#NG-Delegate-dependent-changes-(List-created-using-Jira-fixed-version))
> [PL-Doc] Delegate 25.04.85601

- docs/platform/tags/apply-filters-using-tags.md
> fix:[CDS-108375]:clarify tag filter logic with OR for tags-only and AND for Name+Tags

- docs/continuous-delivery/gitops/pr-pipelines/pr-pipeline-application-set.md
> fix:[CDS-109005]: Add more info about generators in ApplicationSet

- docs/platform/templates/reconcile-pipeline-templates.md
> feat:[PIPE-26139]: Document best practices for Bulk reconciliation

- release-notes/platform.md
* Please describe your changes: Release notes for system release version 1.84.x added
* Jira/GitHub Issue numbers (if any): [JIRA](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22441001091/NG+Release+SAAS+April+7th+2025+for+1.84.xx-+Build) 
> [PL-Doc] RN for PL 1.84.x

- src/components/University/UniversityCR.tsx
> One line change - Nit

- release-notes/feature-management-experimentation.md
* Please describe your changes: **Add 'Append impression properties' to FME release notes**
> FME release note - Append impression properties

- docs/code-repository/work-in-repos/semantic-search.md
* Please describe your changes: Add info on how to enable semantic search.
> Add info on how to enable semantic search.

- kb/cloud-cost-management/cloud-cost-management-faqs.md
> [CCM-18044]

- docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
- release-notes/continuous-delivery.md
> Gitops release notes 1.29, 0.90

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2.0.md
* Preview links/images (Internal contributors only): https://67f82d3bc6d286822d0814e4--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0
> install delegate 2.0 docs

- docs/platform/delegates/manage-delegates/hide-logs-using-regex.md
> [CDS-108564]: Update hide-logs-using-regex.md

- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
- docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
- docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
- docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
* Please describe your changes: Details: https://harness.atlassian.net/browse/CI-16272?focusedCommentId=1137335
* Jira/GitHub Issue numbers (if any): CI-16272
> Update to previous changes for CI-16272

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-without-push.md
* Please describe your changes: Changes per CI-16586. Need to update the pipeline YAML to include Trivy scan.
* Jira/GitHub Issue numbers (if any): CI-16586
> Changes per CI-16586

- .github/CODEOWNERS
> Update CD code owner

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-faqs.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
- docs/continuous-delivery/verify/continuous-verification-faqs.md
- docs/continuous-delivery/x-platform-cd-features/cd-steps/cd-steps-faqs.md
- docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md
> [CDS-106825] Added CD faqs

- docs/platform/get-started/harness-ui-overview.md
> add visibile modules flag to another spot

- kb/platform/harness-platform-faqs.md
* Please describe your changes: \______ Update to include error and troubleshooting for SSH Secrets
* Jira/GitHub Issue numbers (if any): \____ https://harnesssupport.zendesk.com/agent/tickets/81915
> (Updates) SSH Secrets

- release-notes/software-supply-chain-assurance.md
> SCS: Add about JFrog Updation in Release Notes

- release-notes/delegate.md
> fix: [CDS-109201]: add delegate release notes for 85604

- docs/infra-as-code-management/workspaces/workspace-tempates.md
* Add pending release banner and admonition to highlight that Workspace Templates are coming soon!
* [JIRA](https://harness.atlassian.net/browse/IAC-3544)
> docs: [IAC-3544]: Add pending release banners to workspace templates

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.75 RN
> CI 1.75 RN.

- docs/continuous-delivery/get-started/service-licensing-for-cd.md
- docs/platform/pipelines/add-a-stage.md
> Add license clarifications

- docs/code-repository/config-repos/archive-repo.md
- docs/code-repository/config-repos/import-repo.md
- docs/code-repository/config-repos/webhooks.md
- docs/code-repository/pull-requests/review-pr.md
> Multiple doc updates for CR docs

- .github/CODEOWNERS
> Update Codeowners for CD and Pipeline

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
> Update AWA Lambda Limitation

- docs/platform/settings/default-settings.md
* Please describe your changes: This PR removes limitations on auth methods per https://harness.atlassian.net/browse/CI-17141
* Jira/GitHub Issue numbers (if any): CI-17141
> Remove limitations on auth methods.

- docs/cloud-cost-management/3-use-ccm-cost-reporting/2-ccm-cost-categories/2-cost-categories-usage.md
> [CCM-16146]

- docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orch-docs/aws-ec/co-for-ec.md
> [CCM-21497]: FAQ for commitment orchestrator

- docs/infra-as-code-management/get-started/get-started.md
- docs/infra-as-code-management/iacm-features/module-registry/module-registry-testing.md
* Make minor tweaks to Module Registy Testing docs and adjustment tango guides to remove view count and improve zoom level.
* [JIRA](https://harness.atlassian.net/browse/IAC-3543)
> docs: [IAC-3543]: Minor doc fixes plus Tango guide adjustments

- release-notes/infrastructure-as-code-management.md
* Add new release notes for IaC Server v1.26.1
* [JIRA](https://harness.atlassian.net/browse/IAC-3354)
> Release Notes: Add server 1.26.1 release notes

- docs/self-managed-enterprise-edition/install/install-using-helm.md
> [PL-Doc] Helm Fix URL

- src/components/Roadmap/data/roadmapData.ts
* Please describe your changes: update GA status - SMP in code repo roadmap page
> code repo roadmap page  - update GA status - SMP

- release-notes/security-testing-orchestration.md
> STO: Add Release Notes v1.136.1

- docs/security-testing-orchestration/sto-techref-category/shared/custom-scan/container.md
- docs/security-testing-orchestration/sto-techref-category/shared/step-palette/image/domain.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/configure-pipeline-to-use-sto-images-from-private-registry.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/create-custom-scan-images.md
- docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/sto-images.md
> STO: Update GCR to GAR

- release-notes/self-managed-enterprise-edition.md
* Please describe your changes: HF for SMP version 0.27.1 - 'Account Edition' Column Removed from Account List View
> [PL-Doc] RN for SMP hf 0.27.1

- docs/security-testing-orchestration/whats-supported/sto-deployments.md
> STO: Add Custom Dashboard Limitations for SMP

- docs/cloud-cost-management/ccm-onboarding/onboarding-path.md
- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
- docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-gcp.md
Removing links to first gen docs in prepartion for their removal. This PR is for CCM module
> remove first gen links for CCM

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
> Add warning for OIDC limitation

- docs/continuous-integration/troubleshoot-ci/debug-mode.md
> add mac os support

- docs/feature-flags/use-ff/ff-creating-flag/using-ff-ccm.md
> remove first gen links for FF

- docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
- release-notes/continuous-delivery.md
> Gitops 1.30 release notes PR

- docs/continuous-integration/use-ci/run-tests/ti-overview.md
* Please describe your changes: For TI, this PR adds trigger event conditions for PRs.
* Jira/GitHub Issue numbers (if any): CI-17200
> Add trigger event conditions for PRs.

- docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/byoc-injector.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/static/manifests/byoc-injector/advance-tunables.yaml
- docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/static/manifests/byoc-injector/mounted-chaos-script.yaml
- docs/chaos-engineering/use-harness-ce/chaos-faults/byoc/static/manifests/byoc-injector/self-contained-lib-image.yaml
> chore: [CHAOS-8114]: Rename the byoc helper image env

- release-notes/platform.md
* Please describe your changes: Added release notes for platform version 1.85.x
* Jira/GitHub Issue numbers (if any):  [JIRA Ticket](https://harness.atlassian.net/browse/PL-62071)
> [PL-Doc] Release notes 1.85.x

- docs/continuous-integration/use-ci/run-tests/tests-v2.md
- docs/continuous-integration/use-ci/run-tests/ti-overview.md
* Please describe your changes: Add ™ to Test Intelligence in the CI docs according to Legal's request
> Add ™ to Test Intelligence in the CI docs according to Legal's request

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
> Include important infra configs

- release-notes/continuous-delivery.md
- release-notes/platform.md
- release-notes/self-managed-enterprise-edition.md
> Remove FG links from release notes

- docs/faqs/cloud-cost-management-faqs.md
- docs/internal-developer-portal/plugins/overview.md
> Remove FG from faqs and IDP

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/native-helm-quickstart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
> [CDS-107200] Feat: Enforcing Namespace Consistency got K8s and Helm

- university/faqs.md
Adding detailed policy for our certification exams and testing.
> Add integrity policies

- docusaurus.config.ts
- sidebars-university.ts
- university/instructions.md
- university/policies-and-faqs.md
FAQ Page is now "Policies and FAQs"
> Updated to Policies and FAQs

- release-notes/delegate.md
This reverts commit 569b34dab1ef2168a7ef504b7b10d7a1b6f352c6.
> Revert "fix: [CDS-109201]: add delegate release notes for 85604"

- .github/workflows/label-checker.yaml
* Jira/GitHub Issue numbers (if any): \______HDH 368________________________
> HDH-368-check-label-on-pr-to-disallow-merging

- docs/software-supply-chain-assurance/shared/ssca-supported.md
> SCS: Add Build Infrastructure

- release-notes/chaos-engineering.md
Adding Release notes for Chaos 1.59.0
> chore: Adding Release notes for Chaos 1.59.0

- docs/software-supply-chain-assurance/artifact/sign-artifacts.md
- docs/software-supply-chain-assurance/artifact/verify-signed-artifacts.md
- docs/software-supply-chain-assurance/shared/artifact-source.md
- docs/software-supply-chain-assurance/slsa/generate-slsa.md
- docs/software-supply-chain-assurance/slsa/verify-slsa.md
> SCS: Add image-digest to the steps

- release-notes/software-engineering-insights.md
> SEI Release Update

- docs/continuous-integration/use-ci/run-tests/tests-v2.md
- docs/continuous-integration/use-ci/run-tests/ti-overview.md
* Please describe your changes: This PR updates TI docs with specific trigger steps. Details on [this thread](https://harness.slack.com/archives/C06FHJH7ZEJ/p1744221526940459).
* Jira/GitHub Issue numbers (if any): CI-17200
> Update TI docs for specific trigger steps.

- docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md
* Please describe your changes: Add links to the FAQ/question from tooltip.
* Jira/GitHub Issue numbers (if any): CI-17233
> Changes per CI-17233

- docs/software-supply-chain-assurance/artifact-view.md
> SCS: Add note for vulnerabilities

- docs/infra-as-code-management/remote-backends/init-configuration.md
* Reinstate remote backend initialization doc
* [JIRA](https://harness.atlassian.net/browse/IAC-3581)
Requested by @dwarren-dev 
> docs: [IAC-3581]: Reinstate remote backend init configuration

- docs/continuous-delivery/cd-integrations.md
- release-notes/continuous-delivery.md
> [CDS-109184] CD release notes 1.86

- release-notes/delegate.md
* Please describe your changes: Release Notes for Delegate. 
* Jira/GitHub Issue numbers (if any): [JIRA Signoff](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22463579083/NG+Release+SAAS+April+21st+2025+for+1.86.xx-+Build#NG-Delegate-dependent-changes-(List-created-using-Jira-fixed-version))
> [PL-Doc] Delegate release notes 25.04.85701

- .github/CODEOWNERS
> Add Rohit as IaCM Codeowner

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/service-hooks.md
- docs/continuous-delivery/shared/service-hooks.md
> Make service hook its own file, add it to K8s docs and helm docs

- docs/infra-as-code-management/reports-insights/dashboards.md
* Add doc for new IaCM looker dashboards
* [JIRA](https://harness.atlassian.net/browse/IAC-3524)
> docs: [IAC-3524]: Add IaCM Looker Dashboard doc

- _server-redirects
- src/components/University/data/ci-certification-admin-review-guide.md
- src/components/University/data/ci-certification-architect-review-guide.md
- src/components/University/data/ci-certification-developer-review-guide.md
https://developer.harness.io/docs/category/troubleshoot-harness-ci
> Fixed broken cert link - troubleshoot CI

- release-notes/platform.md
* Please describe your changes: Platform release notes 1.86.x
* Jira/GitHub Issue numbers (if any): [JIRA tickets](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22463579083/NG+Release+SAAS+April+21st+2025+for+1.86.xx-+Build)
> [PL-Doc] System Release notes 1.86.x

- docs/platform/get-started/subscriptions-licenses/subscriptions.md
* Please describe your changes: remove start up reference from 360 subscription
* Jira/GitHub Issue numbers (if any): [JIRA ticket](https://harness.atlassian.net/browse/PL-62181) 
> [PL-Doc] Update & Remove Startup Reference

- docs/platform/notifications/centralised-notification.md
> Added note for SMTP when Connectivity mode=Delegate and channel type=Email

- docs/infra-as-code-management/workspaces/create-workspace.md
- release-notes/infrastructure-as-code-management.md
* Add new release notes entry matching IDP example layout for IAC-Server v1.138.0
* [JIRA](https://harness.atlassian.net/browse/IAC-3453)
> release notes: [IAC-3453]: Add v1.138 release notes

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.76 RN
> CI Release Notes 1.76

- release-notes/early-access.md
> STO: Early Access - Remove Checkmarx One, Add Global Exemptions

- src/components/NavbarItems/components/Facet.tsx
- src/components/NavbarItems/components/SearchBox.tsx
- src/components/NavbarItems/components/SearhResultBox.tsx
> PL-61589-documentation-search-persist-module-filter

- docs/chaos-engineering/integrations/experiment-as-github-action.md
> feat:[CHAOS-8160]: Adding github action integration doc for chaos

- docs/self-managed-enterprise-edition/troubleshooting/database-crash.md
> [PL-Doc] Add new page - database crashes

- src/components/University/LandingPage.tsx
> Changed verbiage for paid and free plans

- docs/platform/delegates/manage-delegates/enable-auto-upgrade-for-running-docker-delegates.md
> Doc for Helper script to enable upgrader for existing docker delegates

- src/components/Roadmap/data/cdData.ts
> Remove projects move across orgs tile

- docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
> Add FF info for Docker Delegate Upgrader

- docs/internal-developer-portal/2-0-overview-and-upgrade-path.md
> Tweaks to breaking changes docs in IDP 2.0 API 

- release-notes/software-engineering-insights.md
> release update - version 202504.2

- .github/CODEOWNERS
* Please describe your changes: **Remove GitHub IDs that were causing errors in the CODEOWNERS file**
> Fix CODEOWNERS errors

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
> Closed beta only

- release-notes/continuous-integration.md
> update RN - reverse multi-line update

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
> selection to access

- release-notes/delegate.md
> release note for delegate version 85702

- docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-command-step.md
> [CDS-106640] Feature:  Disable Script Logging in Tanzu Command step

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/native-helm-quickstart.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-deploy.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-bg-swap.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-delete.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-canary-deploy.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-delete.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-deploy.md
- docs/continuous-delivery/deploy-srv-diff-platforms/helm/step-reference/helm-rollback.md
> [CDS-108781] Feature: Command Flags at Step Level

- docs/platform/git-experience/gitexp-bidir-sync-setup.md
> [PIPE-26279] Feat: Default creation of Webhook for Bi directional sync

- src/components/Roadmap/data/ciData.ts
> Change AI devops roadmap

- docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
Changed Duplicate to Parallel for Github actions step docs.
> Changed Duplicate to Parallel

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
- docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md
- docs/platform/settings/default-settings.md
- release-notes/continuous-integration.md
* Please describe your changes: updated release noted and default settings for build and cache intelligence features
* Jira/GitHub Issue numbers (if any): [CI-16463]
[CI-16463]: https://harness.atlassian.net/browse/CI-16463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CI RN 1.77 and related changes

- docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
> Documenting changes to 35d stage timeout for K8s

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
> [CDS-108571] add details about ff: CDS_SERVICE_DASHBOARD_SIMPLIFICATION

- release-notes/continuous-delivery.md
> Update cd release version to 1.87.3

- release-notes/delegate.md
> feat: [CDS-109659]: update delegate release doc

- release-notes/self-managed-enterprise-edition.md
* Jira/GitHub Issue numbers (if any): [JIRA ticket](https://harness.atlassian.net/browse/PL-62393) & [Sign off](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22464004108/SMP+Release+Sign-off+-+April+2025+-+build+0.28.0) and [RN tickets](https://harness.atlassian.net/wiki/spaces/QUAL/pages/22467903489/Release+Notes+tickets+for+v0.28.0+release)  …
> [PL-Doc]SMP RN 0.28.x

- docs/platform/governance/policy-as-code/harness-governance-overview.md
- docs/platform/governance/policy-as-code/policy-package.md
> Rego Import docs draft

- src/components/University/LandingPage.tsx
- src/components/University/UniversityCD.tsx
- src/components/University/UniversityCI.tsx
- src/components/University/UniversityCR.tsx
- src/components/University/UniversityChaos.tsx
- src/components/University/UniversityCloudCostManagement.tsx
- src/components/University/UniversityFeatureFlags.tsx
- src/components/University/UniversityIACM.tsx
- src/components/University/UniversityIDP.tsx
- src/components/University/UniversitySCS.tsx
- src/components/University/UniversitySEI.tsx
- src/components/University/UniversitySTO.tsx
- src/components/University/data/certificationsData.ts
- src/components/University/data/iltData.ts
- src/components/University/data/sptData.ts
> Updated plan tier verbiage

- docs/platform/harness-aida/ai-devops.md
> AI DevOps Agent Feedback

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
- release-notes/continuous-delivery.md
> [CDS-109817] Update FF related to Lambda and ECS Tag management feature.

- docs/platform/secrets/add-use-text-secrets.md
> [CDS-109161] Add info: Secrets are not masked in step summary

- docs/infra-as-code-management/pipelines/operations/pr-automation.md
- docs/infra-as-code-management/workspaces/delete-workspace.md
- docs/infra-as-code-management/workspaces/destroy-workspaces.md
* Update delete action warning to clarify that deleting a workspace removes your state file but doesn't destroy associated resources.
* [JIRA](https://harness.atlassian.net/browse/IAC-3628)
> docs: [IAC-3628]: Update delete action warning

- release-notes/self-managed-enterprise-edition.md
> [PL-Doc]SMP RN 0.28.x to add iacm bundles

- src/components/Roadmap/data/iacmData.ts
> [IaCM]: Roadmap update for IaCM

- docs/platform/git-experience/configure-git-experience-for-harness-entities.md
> [CDS-109748] Update Git Experience file path convention

- docs/platform/harness-aida/ai-devops.md
> Add data privacy terms

- docs/software-supply-chain-assurance/sbom-policies/enforce-sbom-policies-with-github-actions.md
- docs/software-supply-chain-assurance/sbom/generate-sbom-with-github-actions.md
- docs/software-supply-chain-assurance/sbom/ingest-sbom-with-github-actions.md
- docs/software-supply-chain-assurance/slsa/generate-slsa-with-github-actions.md
- docs/software-supply-chain-assurance/slsa/verify-slsa-with-github-actions.md
> SCS: Update workflow yaml files

- docs/infra-as-code-management/pipelines/operations/drift-detection.md
- docs/infra-as-code-management/pipelines/terraform-plugins.md
* Update Drift Detection doc and Drift detection section in Tofu/Terraform plugin commands doc
* [JIRA](https://harness.atlassian.net/browse/IAC-3502)
> docs: [IAC-3502]: Elaborate on drift detection doc

- docs/continuous-delivery/cd-integrations.md
- release-notes/continuous-delivery.md
> [CDS-109849] CD release notes 1.88

- release-notes/infrastructure-as-code-management.md
* Add new release notes for IAC-Version 1.143.0 
* [JIRA](https://harness.atlassian.net/browse/IAC-3538)
This only has one entry for Module Registry Access
> docs: [IAC-3538]: Add release note IAC-Server version 1.143

- release-notes/platform.md
* Please describe your changes: This is platform system release v0.88.x
> [PL-Doc] Platform release 1.88.x

- docs/cloud-cost-management/get-started/ccm-smp/1-smp-ccm-roadmap.md
- docs/cloud-cost-management/shared/ccm-supported-platforms.md
> changed roadmap

- docs/security-testing-orchestration/exemptions/manage-exemptions.md
> STO: Remove FF for "Users Can Approve Their Own Exemptions" Default Setting

- docs/continuous-integration/use-ci/run-tests/speed-up-ci-test-pipelines-using-parallelism.md
> Added missing slash in the path to split-tests binary

- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
* Please describe your changes: \____ Changed to how Google specifies the OIDC Aud URL as per: https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers
Incorrect values are being referenced, causing customer confusion
* Jira/GitHub Issue numbers (if any): \_________ https://harness.atlassian.net/browse/PL-62627
> (Update) OIDC Audience

- src/components/Roadmap/data/fmeData.ts
The quarter went well... lots to update!
* Please describe your changes: \_____Updates in all columns___________
* Jira/GitHub Issue numbers (if any): \_______________N/A_________
* Preview links/images (Internal contributors only): \_____N/A_____________
> Update fmeData.ts Now, Next, Later, Released entries

- docs/infra-as-code-management/workspaces/workspace-tabs.md
* Update Workspace Resource tab details to include Data Sources
* [JIRA](https://harness.atlassian.net/browse/IAC-3595)
* [PREVIEW](https://681ccb7676d12633190a89db--harness-developer.netlify.app/docs/infra-as-code-management/workspaces/workspace-tabs#resources)
> docs: [IAC-3595]: Update workspace settings resources tab details

- docs/continuous-delivery/gitops/use-gitops/gitops-agent-metrics.md
> Agent metric minimum version requirement

- src/components/Roadmap/data/dbdData.ts
- src/components/Roadmap/data/dbdevopsData.ts
- src/components/Roadmap/data/roadmapData.ts
- src/components/Roadmap/index.tsx
* Getting DB DevOps Roadmap visile on Harness developer hub
> add db devops option to roadmap

- src/components/Roadmap/data/platformData.ts
> Update PL roadmap items as per Q2 FY26

- release-notes/continuous-integration.md
> Ci release notes 5 may

- kb/reference-architectures/ccm/best-practices/aws/aws-permissions.md
Resync permissions from current EC2 and RDS featureset
> update comm orch aws permissions

- docs/platform/variables-and-expressions/harness-expressions-reference.md
- docs/platform/variables-and-expressions/harness-variables.md
- kb/continuous-delivery/articles/ternary-operator.md
* Please describe your changes: \_____. provide more connective links to the isResolved/isUnresolved addition, since people have difficulty finding the article.
* Jira/GitHub Issue numbers (if any): \_____.  Multiple Zendesk tickets
> (Update) Is Resolved

- kb/continuous-delivery/articles/servicenow-api-permission.md
* Please describe your changes: \________ Fix issue regarding Access policies
* Jira/GitHub Issue numbers (if any): \______ Sales internal issue
> (Update) SNOW Access Policies

- release-notes/infrastructure-as-code-management.md
* Update to module registry project scope feature improvement.
* [JIRA](https://harness.atlassian.net/browse/IAC-3570)
> rn: [IAC-3570]: IAC Server Release Notes v1.145.0

- docs/software-supply-chain-assurance/artifact/sign-artifacts.md
- docs/software-supply-chain-assurance/artifact/verify-signed-artifacts.md
- docs/software-supply-chain-assurance/sbom-policies/enforce-sbom-policies.md
- docs/software-supply-chain-assurance/sbom/generate-sbom.md
- docs/software-supply-chain-assurance/slsa/generate-slsa.md
- docs/software-supply-chain-assurance/slsa/verify-slsa.md
- release-notes/software-supply-chain-assurance.md
> SCS: Add release notes

- src/components/Roadmap/data/stoData.ts
> update sto roadmap q2 fy 26

- docs/software-engineering-insights/analytics-and-reporting/efficiency/dora-metrics/dora-ci-cd-correlation.md
> sei ci-cd correlation doc update

- docs/continuous-integration/secure-ci/authenticate-gcp-key-in-run-step.md
* Please describe your changes: Directing people to a 3rd party site to enter a secret that may be logged is likely less good. This PR removes the third party site and uses a local tool to encode secret. It also updates a flag `-d` to `--decode` for both Linux and macOS platform compatibility.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CI-17489 …
> Changes per CI-17489

- release-notes/platform.md
> [PL-Doc] Update platform release notes 1.89x

- docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> [CDS-107869] Feature: Terraform OPA evaluation support

- docs/platform/variables-and-expressions/harness-expressions-reference.md
> [CDS-109629] Feature: Connector Type Variable

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
> [CDS-110084]  Info about canary rollback

- docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
- docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
- docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md
* Add important notice to specify the need for git tags to register a module.
* [JIRA](https://harness.atlassian.net/browse/IAC-3726)
> docs: [IAC-3726]: Update Module Registry to specify git tag requirement

- release-notes/delegate.md
* Jira/GitHub Issue numbers (if any): [JIRA](https://harness.atlassian.net/browse/PL-61945)
> [PL-Doc] Delegate RN 25.05.85804

- client-modules/searchBar.js
- src/css/custom.css
> Search button getting appended to the DOM  continuously

- release-notes/feature-flags.md
* Please describe your changes: Adds release notes for FF Relay Proxy
* Jira/GitHub Issue numbers (if any): FFM-12444
> FFM-12444 - Add release notes for FF Relay Proxy

- docs/artifact-registry/whats-supported.md
* Update the What's Supported page to reflect the frontend
* [JIRA](https://harness.atlassian.net/browse/AH-1307)
> docs: [AH-1307]: Update HAR Whats Supported packages

- release-notes/continuous-integration.md
@nofarblue please review the image update descriptions. I feel the following text can be improved
> Change the delimiter from double colon to pipe in the script failure message.
> Harness CI 1.79 Release Notes

- netlify/functions/coveo_api.mts
- src/components/NavbarItems/Engine.ts
- src/components/NavbarItems/components/Facet.tsx
- src/components/NavbarItems/components/ResultList.tsx
- src/components/NavbarItems/components/SearchBox.tsx
- src/components/NavbarItems/components/SearhResultBox.tsx
- src/components/NavbarItems/index.tsx
- src/theme/DocCategoryGeneratedIndexPage/index.tsx
> Coveo token refresh update

- docs/continuous-delivery/verify/configure-cv/health-sources/custom-health-metrics.md
> update custom health metric

- docs/platform/harness-aida/harness-mcp-server.md
Question to the reviewer:
- Is **Authentication** section in the right place on this page?
- VS Code MCP Guide link was missing so I added it
- If we don't need the theory around MCP and related topics, we can trim those.
* Please describe your changes: Add Harness MCP Server docs.
* Jira/GitHub Issue numbers (if any): CDS-110323
> Add Harness MCP Server docs.

- docs/platform/harness-aida/harness-mcp-server.md
> MCP changes

- src/components/Roadmap/data/aidaData.ts
> Roadmap AiDevOps

- src/components/Roadmap/data/ciData.ts
- src/components/Roadmap/data/codeData.ts
* Please describe your changes: CI and Code Q2 roadmap update
> CI and Code Q2 roadmap update

- docs/continuous-delivery/cd-integrations.md
- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
> [CDS-109552] Feature: Refresh EKS token during deployment

- kb/reference-architectures/ccm/onboarding/k8s.md
Add network access for delegate logging
> add logging.googleapis.com to delegate requirements

- docs/platform/harness-aida/harness-mcp-server.md
> AR Tools added to docs

- docs/platform/harness-aida/harness-mcp-server.md
* Please describe your changes: Remove 'Coming Soon' text from MCP server docs.
> Remove 'Coming Soon' text.

- yarn.lock
> browserlist-db-update

- docs/platform/templates/create-pipeline-template.md
- docs/platform/templates/use-a-template.md
> Pipe 26902

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
> [CDS-108850] Feature: Helm Test Support

- docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
* Please describe your changes: Update the doc with AIDA to AI
* Jira/GitHub Issue numbers (if any): [JIRA](https://harness.atlassian.net/browse/PL-62966)
> Dashboard changes AIDA to AI

- release-notes/continuous-delivery.md
> Update Azure CLI feature as breaking change

- docs/platform/harness-aida/ai-devops.md
* Please describe your changes: Typo, grammar, and style fixes.
* Jira/GitHub Issue numbers (if any): none
> Typo, grammar, and style fixes.

- .github/CODEOWNERS
- docs/incident-response/runbooks/integrations/zoom.md
* Please describe your changes: Updated instructions for deauth of Zoom in their marketplace to deauth the Harness connector
> IR - Zoom App Approval for Deauth

- .github/CODEOWNERS
> Add Vasundhara as IR Codeowner

- docs/platform/harness-aida/aida-overview.md
- docs/platform/harness-aida/code-agent.md
> Added FAQs for AI capabilities

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
> [CDS-110494] Update ASG deployment intro

- docs/chaos-engineering/use-harness-ce/chaos-faults/common-tunables-for-all-faults.md
- docs/chaos-engineering/use-harness-ce/chaos-faults/static/manifest/common/status-check-timeout.yaml
> chore: [CHAOS-8187]: adds status check timeouts common tunable

- docs/chaos-engineering/use-harness-ce/probes/apm-probe/appdymanics-probe.md
* Please describe your changes: add a note to app dyanmics probe docs
> fix: add note of app probe docs

- src/components/Roadmap/data/fmeData.ts
Flag Prerequisites moving from Now to Next
* Please describe your changes: \________Moving Flag Prereq to Next_________________
* Jira/GitHub Issue numbers (if any): \______n/a________________________
* Preview links/images (Internal contributors only): \______n/a____________
> Update fmeData.ts moving flag prerequisites to Next

- docs/continuous-delivery/verify/configure-cv/health-sources/dynatrace.md
- docs/continuous-delivery/verify/shared/risk-profile.md
> Canary Analysis with Dynatrace + Metric Filters

- docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
> [CDS-109365] Feature: TAS: Native Autoscaler Binding

- docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
* Please describe your changes: Changes per CI-17216 & CI-17562
* Jira/GitHub Issue numbers (if any): CI-17216 & CI-17562
> Dewan ci17216

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-without-push.md
> CI-17161 Docs changes for build push split use cases

- docs/platform/harness-aida/ai-devops.md
> Cds 109875

- release-notes/delegate.md
> fix:[CI-17618]: Add hotfix for gitlab branch slash

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.80 Release Notes
> CI 1.80 RN.

- release-notes/platform.md
> [PL-Doc]System Release Note 1.90x

- release-notes/security-testing-orchestration.md
> STO: Release Notes for v1.140.1

- src/components/Roadmap/data/sscaData.ts
> SCS: Update Q2 SCS Roadmap

- release-notes/delegate.md
> [PL-Doc]Delegate Release Version 25.05.85903

- docs/continuous-delivery/x-platform-cd-features/executions/execution-history.md
> [PIPE-27480] Expression to fetch execution mode

- release-notes/continuous-delivery.md
> [CDS-110715] Update release notes with docs links

- docs/platform/role-based-access-control/permissions-reference.md
> [PL-Doc] Fix the note

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md
> fix: [CDS-110660]: add helm faq for purging initial failed deploymeny

- docs/continuous-delivery/shared/jira-approval-steps.md
- docs/continuous-delivery/shared/servicenow-approval-steps.md
> [CDS-109601] ServiceNow and Jira Manual Refresh During Execution

- docs/ai-test-automation/integrations/harness-cd.md
- release-notes/ai-test-automation.md
* Please describe your changes: Added a Release note and minor changes in a file \__________________________________
> Ait update harness cd integration

- docs/platform/approvals/custom-approvals.md
> [CDS-109601] Manual Refresh During Execution for custom approval step

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
> [CDS-109488] Escaping the Pipe `(|)` Symbol in Shell script

- docs/platform/delegates/install-delegates/docker-delegate-to-ecs-fargate.md
> Added disclaimer for Harness community GitHub module

- .github/CODEOWNERS
> STO: Add Codeowner to STO Docs

- docs/platform/harness-aida/code-agent.md
* Please describe your changes: Add https://youtu.be/G8IlWLCpkVM to https://developer.harness.io/docs/platform/harness-aida/code-agent
> Add Harness AI Code agent video.

- docs/chaos-engineering/use-harness-ce/probes/apm-probe/appdymanics-probe.md
- docs/chaos-engineering/use-harness-ce/probes/apm-probe/prometheus-probe.md
- docs/chaos-engineering/use-harness-ce/probes/apm-probe/splunk-probe.md
* Please describe your changes: Add interactive guides to apm probe docs
> enhance: add interactive guide to apm probes

- docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/metasploit-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nessus-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/openvas-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/qualys-web-app-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/tenable-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
> STO: Document Burp URL Scope Details

- release-notes/self-managed-enterprise-edition.md
> [CDS-110800] SMP hotfix version 0.28.1

- release-notes/code-repository.md
* Please describe your changes: CODE 1.41 and 1.42 Release Notes
> CODE REPO 1.41 and 1.42 Release Notes

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
> build intelligence - added beta info for maven

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/event-listener-step.md
> Cds 110647

- docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/checkmarx/checkmarx-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/checkmarx/checkmarxone-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
- docs/security-testing-orchestration/sto-techref-category/shared/use-scanner-provided-severity.md
- docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
- release-notes/security-testing-orchestration.md
> STO: Support Scanner Original Severity - CxOne, Prisma, Anchore

- docs/ai-test-automation/test-authoring/creating-tests/create-tests-doc.md
- docs/ai-test-automation/test-authoring/creating-tests/user-actions.md
- docs/ai-test-automation/test-environments/testing-firewall-protected-apps.md
- docs/ai-test-automation/test-execution/data-driven-tests.md
* Please describe your changes: Removed the hint admonition to avoid build warnings\__________________________________
> Removed hint admonition and replaced them with info

- docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
> containerized step group plus mtls yay

- docs/platform/connectors/code-repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
> update bitbucket settings

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
> add the command warning for winrm earlier

- docs/platform/dashboards/dashboard-best-practices.md
Link - https://6837669e1d007600a7f215dc--harness-developer.netlify.app/docs/platform/dashboards/dashboard-best-practices/
> feat: [PL-63142]: Docs for time zone treatment in dashboards:

- docs/continuous-delivery/cd-integrations.md
- docs/platform/variables-and-expressions/runtime-input-usage.md
> Add CDS_INCLUDE_EMPTY_VALUE flag

- docs/security-testing-orchestration/exemptions/exemption-workflows.md
> STO: Add FF for Occurrence Level Exemptions

- src/components/Roadmap/data/platformData.ts
> Reword granular RBAC items

- docs/continuous-delivery/verify/cv-results/interpret-log-results.md
- docs/continuous-delivery/verify/cv-results/log-feedback.md
- docs/continuous-delivery/verify/verify-deployments-with-the-verify-step.md
> PR for CV medium risk issues

- kb/reference-architectures/ccm/best-practices/aws/aws-permissions.md
New permissions for alb were added
Also, rephrase the entire autostopping sections.
> Update aws-permissions.md to add missing alb

- release-notes/continuous-delivery.md
> Add CVE fixes to release notes

- docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
> Add note that known issue was fixed.

- docs/chaos-engineering/use-harness-ce/infrastructures/types/ddcr/resource-requirement.md
> feat: [CHAOS-8770]: Adding chaos v2 resource requirement doc

- docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
> feat: [CDS-110809]: update tf encrypted outputs queried by jq

- .github/CODEOWNERS
* Please describe your changes: Update CODEOWNERS to add nofarblue to CODE
> Update CODEOWNERS to add nofarblue to CODE

- docs/continuous-delivery/gitops/use-gitops/manage-permissions.md
> Gitops permissions

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/android-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/android-suite.md
* Please describe your changes: Reflects the same changes made by Gaston in https://github.com/splitio/documentation/pull/1087 and https://github.com/splitio/documentation/pull/1089, and these changes are live in Zendesk (https://help.split.io/hc/en-us/articles/22916666123277-Android-Suite#configure-cache-behavior and https://help.split.io/hc/en-us/articles/360020343291-Android-SDK#configure-cache-behavior) and in Split.io repository (https://github.com/splitio/documentation/pull/1087 and https://github.com/splitio/documentation/pull/1089).
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-149 …
> FMEPRD-149 Syncing Changes in Android SDK and Android Suite Documentation

- docs/continuous-integration/get-started/ci-subscription-mgmt.md
* Jira/GitHub Issue numbers (if any): CI-17580
> adding free plan note re resource classes

- docs/platform/account-license-limits.md
> [PL-Doc]Platform Limit Notes

- docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
> Updated GitOps CRD FAQ

- release-notes/continuous-integration.md
* Please describe your changes: Add CI Release Notes 1.82
> CI RN 1.82

- src/components/HomepageFeatures/styles.module.scss
- src/components/LearnAboutPlatform/styles.module.scss
> Added additional hoovers for Homepage SCSS's

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/android-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/ios-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/android-suite.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/ios-suite.md
* Please describe your changes: Reflects all the changes made in Zendesk and https://github.com/splitio/documentation/pull/1085.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-149
> FMEPRD-149 Update Android and iOS SDK Documentation

- docs/infra-as-code-management/workspaces/workspace-tempates.md
* Remove workspace template pending release banners and tidy up Tango iframe embed
* [JIRA](https://harness.atlassian.net/browse/IAC-3886)
> IAC-3886 Remove workspace template pending banners

- docs/self-managed-enterprise-edition/advanced-configurations/configure-custom-dashboards.md
> Update tld to custom-domain

- docs/platform/role-based-access-control/permissions-reference.md
> Add gitops rbac permissions for applicationsets

- src/components/HomepageUniversity/CertCard.module.scss
- src/components/University/UniversityCR.tsx
> Typo in CR Univ

- release-notes/continuous-integration.md
* Please describe your changes: Add missing ticket to CI 1.80 RN.
* Jira/GitHub Issue numbers (if any): CI-11987
> Add missing ticket to CI 1.80 RN.

- docs/internal-developer-portal/catalog/catalog-yaml.md
- docs/internal-developer-portal/idp-2o-overview/2-0-overview-and-upgrade-path.md
> IDP Git Experience and YAML Minor Change

- kb/reference-architectures/iacm/iacm-module-governance.md
Adding a guide to help users craft OPA policies for tf module usage
> refarch: add module governance article

- src/components/HomepageUniversity/data/universityData.ts
- src/components/University/data/iltData.ts
> Soft launch of CR ILT

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
* Please describe your changes: Updated and formated the delegate image version releases on the Developer Hub. The last updated delegate image version was from July 07, 2024. Added all the missing delegate image versions since then. 
- [JIRA](https://harness.atlassian.net/browse/PL-63357)
- [Slack](https://harness.slack.com/archives/C8LE2H4BE/p1748603601401579)
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.gith …
> Add missing delegate image versions

- docs/platform/role-based-access-control/user-impersonation.md
* Please describe your changes: Added a note: When impersonation starts, an email is sent to the user being impersonated. This was previously missing.
- [JIRA](https://harness.atlassian.net/browse/PL-63347)
- [Slack](https://harness.slack.com/archives/C089WGZAJNS/p1748870771116899)
> User-impersonation note

- docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orch-docs/aws-ec/getting-started.md
> added changes

- docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> Ccm 23067 update custodian versions in our docs

- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/java-sdk.md
> Update Java SDK Doc Page

- kb/reference-architectures/iacm/iacm-aws-connectors.md
Cant see the value in the screenshot, and otherwise should be included in text anyway.
> fix: iacm eks irsa annotation

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
* Please describe your changes: Add Maven Config for BI
> Add Maven config for BI.

- docs/infra-as-code-management/remote-backends/use-backends.md
* Add new document with remote backend examples
* [JIRA](https://harness.atlassian.net/browse/IAC-3527)
* [PREVIEW](https://6835e0d584f12b6a129a1be3--harness-developer.netlify.app/docs/infra-as-code-management/remote-backends/use-backends)
> docs: [IAC-3527]: Add use backends doc

- docs/platform/role-based-access-control/permissions-reference.md
> STO: Update Exemptions Permission Tag via Platform API

- docs/chaos-engineering/concepts/static/openshift/litmus-scc.yaml
- docs/chaos-engineering/security/security-templates/kyverno-policies.md
- docs/chaos-engineering/security/security-templates/manifest/kyverno-policies/allow-host-namespaces-for-litmus-experiments-which-uses-runtime-api.yaml
- docs/chaos-engineering/security/security-templates/manifest/openshift-scc-policies/litmus-scc.yaml
- docs/chaos-engineering/security/security-templates/manifest/psp/psp-litmus.yaml
- docs/chaos-engineering/security/security-templates/openshift-scc.md
- docs/chaos-engineering/security/security-templates/psp.md
- docs/chaos-engineering/use-harness-ce/infrastructures/types/legacy-infra/static/openshift/litmus-scc.yaml
> fix: [CHAOS-8890]: Updating allowHostNetwork to true

- .github/CODEOWNERS
* Please describe your changes: Consolidating two sections in the CODEOWNERS file for FME documentation and release note and updating it for June 2025.
> Update CODEOWNERS for FME documentation

- release-notes/software-supply-chain-assurance.md
> SCS: Update Release Notes - May

- release-notes/continuous-integration.md
* Please describe your changes: This PR is for CI release notes 1.83. Feature sign off page doesn't have image updates as of the time of raising this PR.
> CI 1.83 RN.

- docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
* Please describe your changes: Add better explanation for plugin output variables.
* Jira/GitHub Issue numbers (if any): CI-17730
> Add better explanation for plugin output variables.

- docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
> [CDS-108616] Added when condition for Custom-mac concurrency

- docs/cloud-cost-management/4-use-ccm-cost-optimization/cluster-orchestrator/setting-up-co.md
> [CCM-23232]: Fixed redirect for broken link

- docs/cloud-cost-management/product-behaviour.md
> Product Behavior on License Upgrades

- docs/cloud-cost-management/product-behaviour.md
> minr tweaks

- docs/artifact-registry/content/python-quickstart.md
- docs/artifact-registry/supported-formats.md
* Add Python quickstart guide including how to create the registry, add and configure your upstream proxy, and Publish/install your python packages.
* [JIRA](https://harness.atlassian.net/browse/AH-1428)
> docs: [AH-1428]: Add python quickstart

- docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/gcp/gcp-recommendations.md
> recommendations name change for gcp

- docs/self-managed-enterprise-edition/get-started/onboarding-guide.md
- docs/self-managed-enterprise-edition/smp-basic-configuration.md
All comments as been fix which was suggested by @avaakash in this PR -> https://github.com/harness/developer-hub/pull/10307 
> [PL-Doc] SMP Basic configuration

- release-notes/delegate.md
> Delegate RN - 25.06.86000

- docs/feature-management-experimentation/60-experimentation/overview.md
- docs/feature-management-experimentation/60-experimentation/setup/index.md
- docs/feature-management-experimentation/70-management-and-administration/tags.md
- release-notes/feature-management-experimentation.md
* Please describe your changes: Fix links in Experimentation Overview page + add information about tags being supported for experiments. Also updates the release notes for FME for this feature release.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-187
> FMEPRD-187 Add Release Note and Documentation for Experiment Tags

- docs/feature-management-experimentation/50-release-monitoring/alerts/alert-policies/monitoring-window.md
- docs/feature-management-experimentation/60-experimentation/key-concepts/sample-size-calculator.md
- docs/feature-management-experimentation/shared/alert-policies/index.md
* Please describe your changes: Resize embedded calculators so that users can see the Submit button and the results without scrolling. Flagged by Wei on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-191
https://6850b30f1d2e335da29c997d--harness-developer.netlify.app/docs/feature-management-experimentation/release-monitoring/alerts/alert-policies/#calculator-for-means
https://6850b30f1d2e335da29c997d--harness-developer.netlify.app/docs/feature-management-experimentation/release-monitoring/alerts/alert-policies/monitoring-window/#calculator-for-means …
> FMEPRD-191 Update Embedded Calculators Sizing

- docs/code-repository/config-repos/create-repo.md
* Please describe your changes: Add the required FF for public repos.
* Jira/GitHub Issue numbers (if any): CODE-3245
> Add the required FF for public repos.

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg/asg-tutorial.md
> [CDS-111579] ASG Multi-Service Deployment Rollback

- docs/platform/triggers/schedule-pipelines-using-cron-triggers.md
> [CDS-27427] Feature: Timezone support for Cron Triggers

- docs/software-engineering-insights/setup-sei/configure-integrations/jenkins/jenkins-plugin.md
- docs/software-engineering-insights/setup-sei/configure-integrations/jenkins/sei-jenkins-use-cases.md
> fix: jenkins sei document update

- release-notes/software-supply-chain-assurance.md
> SCS: Update June Release Notes

- docs/continuous-integration/secure-ci/configure-oidc-gcp-wif-ci-hosted.md
- docs/continuous-integration/shared/issueruri.md
- docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
* Please describe your changes: \__________ Add more documentation about issuer URI with Vanity URLS and different prod environments
* Jira/GitHub Issue numbers (if any): \_______ https://harness.atlassian.net/browse/CI-17933
> (Update): Issuer URI

- src/components/Roadmap/data/dbdevopsData.ts
updated db devops public roadmap
> update db devops public roadmap

- docs/open-source/registries/artifacts.md
* Please describe your changes: This PR is raised since https://github.com/harness/developer-hub/pull/10456 is having its approval's getting dismissed automatically.
> Add documentation for S3 support in Harness Open Source artifact registry

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.84 release notes
> CI 1.84 release notes.

- release-notes/delegate.md
> fix:[CCM-22905]: release notes for the delegate hotfix with watchers.

- docs/security-testing-orchestration/view-security-test-results/issues.md
- release-notes/early-access.md
> STO: Update FF Note for All Issue Documentation.

- release-notes/platform.md
> [PL-Doc] Platform system release 1.94.x

- docs/platform/role-based-access-control/user-impersonation.md
> Added demo video in the User impersonation doc

- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/python-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/ruby-sdk.md
* Please describe your changes: We have two SDK version updates, https://github.com/splitio/documentation/pull/1098 and https://github.com/splitio/documentation/pull/1099, which we've updated in the appropriate Zendesk articles, and now we are updating the respective doc pages in HDH. Conversation with Bilal on Slack.
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS …
> Sync Version Bumps in Zendesk

- docs/platform/connectors/manage-access-control-for-connectors.md
- release-notes/platform.md
> Add FF details for managing RBAC for Connectors through tags

- docs/troubleshooting/troubleshooting-nextgen.md
* Please describe your changes: \______ Exceeding Size Limit for YAML, update information on how to combat it with loops
> (Update) YAML Size Limit

- docs/infra-as-code-management/workspaces/worksace-statuses.md
* Add Update_Needed workspace status description
* [JIRA](https://harness.atlassian.net/browse/IAC-3990)
> docs: [IAC-3990]: Add Apply Needed status description

- src/components/University/data/cr-certification-developer-exam-details.md
- src/components/University/data/cr-certification-developer-review-guide.md
- src/components/University/data/scs-certification-developer-exam-details.md
- src/components/University/data/scs-certification-developer-review-guide.md
* Please describe your changes: Added developer level exam details and review study guide pages for SCS and CR
* Jira/GitHub Issue numbers (if any): None
> SCS and CR additions for certifications

- src/components/University/UniversityCR.tsx
- src/components/University/UniversitySCS.tsx
> Wiring for CR and SCS Dev Cert Data

- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
* Please describe your changes: This PR picks up the proposed changes from https://github.com/harness/developer-hub/pull/7100 which didn't get merged.
* Jira/GitHub Issue numbers (if any): CI-12929
> Changes per CI-12928

- docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
* Please describe your changes: Make delegate requirement more prominent.
* Jira/GitHub Issue numbers (if any): CI-17235
> Make delegate requirement more prominent.

- src/components/Docs/data/platformData.ts
> Add new pipelines category

- src/components/Roadmap/data/cdData.ts
> Move released argo rollout feature to release column

- docs/platform/secrets/secrets-management/add-hashicorp-vault.md
* Please describe your changes: Adding a note on how to make the vault role trust a specific org or entire account when using enhanced subject
* Jira/GitHub Issue numbers (if any): none
> Add note on how to do account level and org level

- docs/software-supply-chain-assurance/get-started/overview.md
> SCS: Fix broken link

- docs/platform/variables-and-expressions/harness-expressions-reference.md
> [PIPE-28010] Feature: Date and time expressions

- docusaurus.config.ts
> SCS Dropdown Name

- docs/continuous-delivery/gitops/get-started/harness-git-ops-basics.md
> Fix dead link for comparison

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
Update Runner version to 0.0.3
> fix: [DOCSTAI-1323]: update runner version

- docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
> STO: Document SonarQube Issue Categorization Details

- docs/security-testing-orchestration/view-security-test-results/view-scan-results.md
- docs/software-supply-chain-assurance/repository-security-posture-management-rspm.md
> SCS: Fix Broken URL Referring to STO

- release-notes/delegate.md
* Please describe your changes: Resolved an issue when the log line exceeds the maximum length, it will split into multiple lines, causing the sanitization not to detect when content is present in different lines.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CDS-111820
> RN - Sanitizing logs based on regex should apply to all portions of the log

- src/components/Docs/ServiceReliabilityManagement.tsx
* Please describe your changes: \_Link Incident response to SRM deprecation notice_
> Link IR to SRM deprecation notice

- docs/platform/platform-whats-supported.md
* Please describe your changes: Adds a bullet point link to the What's Supported doc page in the FME module documentation. Just noticed this while reading through the Harness Platform documentation.
> Add Link to What's Supported in FME

- release-notes/delegate.md
> fix: [CDS-111788]: Add release notes for delegate hotfix

- docs/continuous-delivery/verify/shared/risk-profile.md
> edits to risk profile for clarity and example usage.

- src/css/custom.css
> HDH-375-revert-hdh-from-pride

- release-notes/chaos-engineering.md
> chaos release notes v1.62

- docs/security-testing-orchestration/exemptions/exemption-workflows.md
> STO: Remove FF - Occurrence Level Exemptions

- docs/infra-as-code-management/pipelines/plugin-images.md
* Please describe your changes: The user in the example Dockerfile for a rootless image in IaCM is using "app", but the correct user is "harness".  This PR fixes it to set the correct user.
> Fix user in Rootless image for IaCM

- .github/CODEOWNERS
This pull request updates the ownership assignments in the `.github/CODEOWNERS` file, primarily for the Database DevOps documentation and knowledge base. The changes reflect new team members and updated responsibilities.
* Updated owners for `/docs/database-devops/`, `/release-notes/database-devops.md`, and `/src/components/Docs/data/databaseDevOpsData.ts` to include `@sonichigo` and `@rohitk-h` while removing `@anshul-harness` and `@ankittiwari-harness`.
* Added `/src/components/Roadmap/data/dbdevopsData.ts` to the ownership list with `@stephenatwell`, `@archit-harness`, `@sonichigo`, `@rohitk-h`, `@ivikramsahu`, and `@wei-harness` as owners.
* Updated …
> Update DB DevOps CODEOWNERS

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/spot-traffic-shifting.md
> Added sample yaml

- release-notes/chaos-engineering.md
> ce 1.61.11 release notes

- release-notes/platform.md
> [PL-Doc] Platform Release notes 1.95.x

- release-notes/delegate.md
- release-notes/platform.md
> [PL-Doc] Delegate RN - 25.06.86202

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg/asg-tutorial.md
- docs/platform/pipelines/failure-handling/fast-fail.md
> [CDS-111383] Feature: Fail Fast and Parallel Rollback Behavior for ASG

- docs/cloud-cost-management/3-use-ccm-cost-reporting/anomaly-detection/getting-started-with-ccm-anomaly-detection.md
> Anomaly detection update

- release-notes/self-managed-enterprise-edition.md
> fix: PL-63828: SMP 0.29.1 patch release

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.85 release notes
> CI 1.85 release notes.

- release-notes/cloud-cost-management.md
> fix ccm rss pub date

- docs/internal-developer-portal/get-started/setup-git-integration.md
- docs/platform/connectors/code-repositories/git-hub-app-support.md
> IDP: Added app id warning for GitHub based git integration

- docs/cloud-cost-management/3-use-ccm-cost-reporting/anomaly-detection/getting-started-with-ccm-anomaly-detection.md
> Event driven anomaly

- kb/reference-architectures/ccm/onboarding/autostopping/aws.md
- kb/reference-architectures/ccm/onboarding/autostopping/azure.md
- kb/reference-architectures/ccm/onboarding/autostopping/gcp.md
- kb/reference-architectures/ccm/onboarding/autostopping/k8s.md
- kb/reference-architectures/ccm/onboarding/k8s.md
> fix broken url and add autostopping examples repo

- src/components/Roadmap/data/fmeData.ts
These two features (Rule based segments and client cache expiration) have been released.
* Please describe your changes: \______Moved two features to released column
* Jira/GitHub Issue numbers (if any): \___________N/A__________________
* Preview links/images (Internal contributors only): \_______N/A___________
> Update fmeData.ts to release RBS and Client Cache Expiration

- kb/continuous-integration/continuous-integration-faqs.md
* Please describe your changes: Change per CI-17750
* Jira/GitHub Issue numbers (if any): CI-17750
> Change per CI-17750

- kb/continuous-integration/continuous-integration-faqs.md
* Please describe your changes: @rustd suggested the change.
> Update FAQ on HashiCorp Vault for Harness CI.

- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
* Please describe your changes: \_____ Caching logic for files is unclear.  Made some additional changes so the logic is more clear to the customer
* Jira/GitHub Issue numbers (if any): \____ https://harness.atlassian.net/browse/CI-18015
> (Update) Advise about Caching Logic

- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
> [CDS-112083] Updated Sam and Serverless images and links

- kb/reference-architectures/platform/aws-oidc-role-connector.md
Walk user through creating an OIDC role for Harness using TF
> feat: add doc to guide users for oidc with tf

- docs/continuous-delivery/get-started/cd-tutorials/manifest.md
> remove flux

- release-notes/platform.md
> [PL-Doc] Platform Release Notes 1.96.x

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
> [CDS-110285] Update K8s BG limitations

- docs/software-engineering-insights/sei-new-experience/efficiency.md
- docs/software-engineering-insights/sei-new-experience/enable-sei-new-experience.md
- docs/software-engineering-insights/sei-new-experience/productivity.md
- docs/software-engineering-insights/sei-new-experience/sei-overview.md
- docs/software-engineering-insights/sei-new-experience/setup/developers.md
- docs/software-engineering-insights/sei-new-experience/setup/granular-insights.md
- docs/software-engineering-insights/sei-new-experience/setup/index.md
- docs/software-engineering-insights/sei-new-experience/setup/insights.md
- docs/software-engineering-insights/sei-new-experience/setup/integrations.md
- docs/software-engineering-insights/sei-new-experience/setup/organizations.md
- docs/software-engineering-insights/sei-new-experience/setup/profiles.md
- docs/software-engineering-insights/sei-new-experience/setup/teams.md
* Please describe your changes: Adds a section in the SEI 2.0 Beta doc set for Setup instructions and walking users through the in-app setup workflow.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-211
> FMEPRD-211 Add SEI 2.0 Setup Documentation

- docs/software-supply-chain-assurance/shared/cosign-attestation-options.md
- docs/software-supply-chain-assurance/shared/generate-cosign-artifact.md
> SCS: Add  Vault Jwt Auth type

- docs/software-engineering-insights/troubleshoot-sei/sei-security-data-retention-faqs.md
* Please describe your changes: Clarifies data retention policies for SEI 1.0 and 2.0. Flagged by PB on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-208
> FMEPRD-208 Update SEI Security and Data Retention FAQ

- docs/feature-management-experimentation/10-getting-started/docs/split-and-harness.md
Swapping out the todo comment for a section that refers admins to the Before and After Guide: Administering a Migrated Split Account on Harness.
* Please describe your changes: \_____Added section pointing to admin guide________
* Jira/GitHub Issue numbers (if any): \________n/a______________________
> Update split-and-harness.md to add in section about admin guide

- release-notes/delegate.md
* Please describe your changes: Fix for IDP git integration and catalog flow not working with Github Enterprise GithubApp Authentication mode
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/IDP-5945
> feat: [IDP-5945]: Fix for IDP git integration and catalog flow not working with Github Enterprise GithubApp Authentication mode

- kb/continuous-integration/articles/use-git-credentials-from-codebase-connector-in-ci-pipelines-run-step.md
> private repos only

- docs/continuous-integration/secure-ci/secure-connect.md
* Please describe your changes: Updates based on CI-18281
* Jira/GitHub Issue numbers (if any): CI-18281
> Updates based on CI-18281

- release-notes/feature-management-experimentation.md
* Please describe your changes: Updates links from the Split HC to the FME documentation in HDH for most (not all) pages that have been migrated. Another update to come soon once we migrate the remaining documentation that has been flagged to be carried over.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-179 …
> FMEPRD-179 Replace (Most) Split HC Links in FME Release Notes

- docs/internal-developer-portal/plugins/available-plugins/argo-cd.md
Changes
- Added a section explaining the issue with ArgoCD's HTTP access.
- Included the necessary Kubernetes commands to configure ArgoCD to accept HTTP connections.
> [IDP-6030]: Update ArgoCD IDP plugin doc for HTTP usage

- docs/platform/pipelines/pipeline-settings.md
> [PIPE-28419] Stage/Step-Level Concurrency Limits

- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
* Please describe your changes: Link examples for supported runtime environments.
* Jira/GitHub Issue numbers (if any): CI-17651
> Link examples for supported runtime environments.

- docs/platform/account-license-limits.md
> [PL-Doc] Update Account resource limit

- docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
> Add artifact sources for Serverless

- release-notes/delegate.md
> Delegate rn 25.07.86300

- docs/database-devops/concepts-and-features/key-concepts.md
* Please describe your changes: This pull request updates the `docs/database-devops/concepts-and-features/key-concepts.md` file to enhance clarity and visual representation of database concepts. The most important changes include the addition of a Mermaid diagram to illustrate database relationships and the formatting of SQL code blocks for better readability.
* Added a Mermaid diagram to visually represent key database concepts, including the relationships between database schema, instances, connectors, and infrastructure. The diagram uses a custom theme for improved aesthetics.
* Updated SQL examples to use the `sql` syntax highlighting for better readability and consistency across the …
> feat: mermaid diagram for the key concepts

- docs/platform/delegates/manage-delegates/configure-delegate-proxy-settings.md
> [PL-Doc] Delegate Upgrader with Proxy Settings

- release-notes/self-managed-enterprise-edition.md
> [PL-Doc] SMP Release Notes

- docs/platform/templates/inject-step-stage-templates.md
> Add limitations block

- docs/chaos-engineering/key-concepts.md
> setup redirect

- docs/security-testing-orchestration/set-up-scans/container-scanning.md
- docs/security-testing-orchestration/set-up-scans/dynamic-application-security-testing.md
- docs/security-testing-orchestration/set-up-scans/infrastructure-as-code-scanning.md
- docs/security-testing-orchestration/set-up-scans/secret-detection.md
- docs/security-testing-orchestration/set-up-scans/shared/container-scanners.md
- docs/security-testing-orchestration/set-up-scans/shared/dast-scanners.md
- docs/security-testing-orchestration/set-up-scans/shared/iac-scanners.md
- docs/security-testing-orchestration/set-up-scans/shared/sast-scanners.md
- docs/security-testing-orchestration/set-up-scans/shared/sca-scanners.md
- docs/security-testing-orchestration/set-up-scans/shared/secret-scanners.md
- docs/security-testing-orchestration/set-up-scans/software-composition-analysis.md
- docs/security-testing-orchestration/set-up-scans/static-application-security-testing.md
- docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
> STO: Document Trivy SBOM Scan Configuration

- docs/platform/pipelines/input-sets.md
> [PIPE-28605]: adding FF details in documentation

- docs/software-engineering-insights/harness-sei/analytics-and-reporting/productivity.md
* Please describe your changes: Adds information for each widget on the Productivity tab for SEI Insights 2.0. Proposed by Yash in a Google Doc.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-227
> FMEPRD-227 Update Developer Productivity Insights Documentation

- docs/service-reliability-management/get-started/overview.md
- docs/service-reliability-management/monitored-service/health-source/static/verify-deployments-with-the-verify-step.md
- docs/service-reliability-management/shared/supported.md
* Please describe your changes: Updated broken links
> links updated for SRM - Customer Reported

- release-notes/cloud-cost-management.md
> added minor improvements

- .gitleaksignore
* Please describe your changes: Submitting this change so we can merge in https://github.com/harness/developer-hub/pull/10990/ successfully (CI check dependency). Flagged by Dewan on Slack.
> Update .gitleaksignore file

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
> [CDS-110572] Accessing AWS OIDC Tokens from Connectors in Shell Scripts

- .github/CODEOWNERS
> SCS: Update CodeOwner File

- release-notes/cloud-cost-management.md
> updated timestamp

- docs/code-repository/config-repos/rules.md
* Please describe your changes: Adds tag rules for CODE
* Jira/GitHub Issue numbers (if any): CODE-3791
> Add tag rules.

- docs/internal-developer-portal/catalog/catalog-yaml.md
- docs/internal-developer-portal/idp-2o-overview/2-0-overview-and-upgrade-path.md
- docs/internal-developer-portal/techdocs/add-api-docs.md
> [IDP]  Absolute Path URL is supported as of now

- docs/chaos-engineering/resources/hce-vs-litmus.md
- docs/chaos-engineering/resources/troubleshooting.md
- sidebars.ts
> add hce vs litmus docs

- docs/software-engineering-insights/shared/insights/business-alignment.mdx
- university/policies-and-faqs.md
> EDU Terms and patch

- docs/infra-as-code-management/get-started/get-started.md
- docs/infra-as-code-management/workspaces/create-workspace.md
* Update workspace creation docs
* [JIRA](https://harness.atlassian.net/browse/IAC-3994)
> docs: [IAC-3994]: Update create workspace docs

- docs/cloud-cost-management/content/get-started/aws-quickstart.md
- docs/cloud-cost-management/content/get-started/gcp-quickstart.md
- docs/cloud-cost-management/content/get-started/kubernetes-quickstart.md
- docs/cloud-cost-management/get-started/get-started.md
* Add right-side toc to DynamicMarkdownSelector component to replace former inline toc
> docs: CCM update Get Started right TOC

- docs/continuous-delivery/monitor-deployments/dora-metrics-dashboard.md
- docs/continuous-delivery/monitor-deployments/using-cd-custom-dashboards.md
> Fix reverted deployments documentation

- docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md
* Please describe your changes: add PLUGIN_PATH_STYLE note for S3 path-style support in self-hosted DLC. Reviewer to suggest if the note can be added to any other CI Docs pages.
* Jira/GitHub Issue numbers (if any): CI-18356
> Add PLUGIN_PATH_STYLE note for S3 path-style support in self-hosted DLC

- docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
- docs/continuous-integration/use-ci/run-tests/tests-v2.md
* Please describe your changes: Update troubleshooting sections for BI,TI,CI.
> Update troubleshooting sections for BI,TI,CI.

- docs/cloud-cost-management/3-use-ccm-cost-reporting/1-ccm-perspectives/creating-a-perspective.md
- docs/cloud-cost-management/3-use-ccm-cost-reporting/anomaly-detection/getting-started-with-ccm-anomaly-detection.md
> Added redirects for broken links

- docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
* Please describe your changes: Add up to date list of CI images including BuildX
* Jira/GitHub Issue numbers (if any): CI-18298
> Add up to date list of CI images including BuildX

- docs/platform/variables-and-expressions/runtime-inputs.md
JIRA - https://harness.atlassian.net/browse/PL-56671 
> [PL-Doc] `warning` on using secret expression as input at runtime

- docs/chaos-engineering/faults/chaos-faults/kubernetes/node/probe-validations.md
- docs/chaos-engineering/resources/api-reference/hce-cli.md
- docs/chaos-engineering/resources/api-reference/hce-onboarding-api.md
- sidebars.ts
> CHAOS: fix broken links

- docs/self-managed-enterprise-edition/advanced-configurations/external-db/minio/use-self-managed-minio-object-storage.md
> [PL-Doc] Update Minio policy 

- docs/internal-developer-portal/plugins/available-plugins/azure-devops.md
- docs/internal-developer-portal/plugins/available-plugins/jira.md
azure with reprequisite
and
jira with correct config YAML
> [IDP] - fixed plugin docs for Jira and Azure devops

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
> [CDS-112800] EKS update

- docs/internal-developer-portal/flows/flows-input.md
> [IDP] - Fixed an example pipeline for 'upload a file using Workflows' to parse base64 file

- docs/continuous-delivery/cd-infrastructure/terraform-infra/remove-provisioned-infra-with-terraform-destroy.md
- docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
- docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
> [CDS-111420] Feat: Terraform remote workspace with prefix

- docs/chaos-engineering/guides/chaos-experiments/index.md
- release-notes/chaos-engineering.md
> CHAOS: 1.63 release notes

- release-notes/cloud-cost-management.md
> fixing trigger

- release-notes/continuous-integration.md
* Please describe your changes: CI 1.89 Release Notes
> CI 1.89 RN

- kb/reference-architectures/hsf/htl/_category_.json
- kb/reference-architectures/hsf/htl/configuring-stage-infra.md
- kb/reference-architectures/hsf/htl/developer-env-setup.md
- kb/reference-architectures/hsf/htl/local-testing-using-make.md
- kb/reference-architectures/hsf/htl/naming-convention-standards.md
- kb/reference-architectures/hsf/htl/new-terraform-templates.md
- kb/reference-architectures/hsf/htl/resource-hierarchy.md
- kb/reference-architectures/hsf/htl/setup-custom-htl.md
- kb/reference-architectures/hsf/htl/upgrading-installation.md
Adding in docs from HTL to HDH
> adding in htl docs

- docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/shell-script-step.md
> Update Accessing Tokens from Connectors in Shell Scripts

- release-notes/continuous-delivery.md
> Update CD RN 1.99

- docs/platform/role-based-access-control/access-policy-analyzer.md
> [PL-Doc] Hide Access Policy Analyzer

- src/components/Docs/data/softwareEngineeringInsightsData.ts
- src/components/HomepageFeatures/data/featureListData.tsx
* Please describe your changes: Flagged by PB on Slack.
> Update Navigation Menu in HDH from SEI 1.0 Docs to 2.0 Docs

- docs/internal-developer-portal/get-started/setup-git-integration.md
> [IDP] - Provided correct URL for setting up Git Providers

- docs/internal-developer-portal/idp-2o-overview/2-0-overview-and-upgrade-path.md
- docs/internal-developer-portal/techdocs/add-api-docs.md
- release-notes/internal-developer-portal.md
> [IDP] - HOTFIX release 30/July - Relative link supported

- docs/self-managed-enterprise-edition/smp-supported-platforms.md
This pull request adds a new documentation link to the list of supported features in the Self-Managed Enterprise Edition documentation.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1383
> feat: add database devops to smp docs

- docs/continuous-delivery/gitops/agents/install-a-harness-git-ops-agent.md
- release-notes/continuous-delivery.md
> GitOps Release Notes

- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/java-sdk.md
* Please describe your changes: Syncing changes from https://github.com/splitio/documentation/pull/1103/ in Zendesk and HDH. Flagged by Bilal on Slack.
> Bump Java SDK Version

- docs/internal-developer-portal/flows/dynamic-picker.md
- docs/internal-developer-portal/flows/worflowyaml.md
- release-notes/internal-developer-portal.md
> [IDP] docs: Remove feature flag mentions for Dynamic Picker Features

- docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
* Please describe your changes: Add Node20 suport via FF `CI_GHA_USE_NEKTOS_V2` for GitHub Action step. 
* Jira/GitHub Issue numbers (if any): CI-18572
> Node20 suport via FF.

- docs/feature-management-experimentation/20-sdks-and-infrastructure/sdk-overview/sdk-validation-checklist.md
* Please describe your changes: made a change to add another piece of validation based upon customer feedback
> updated based upon feedback from customer

- docs/continuous-integration/use-ci/set-up-build-infrastructure/install-delegate-2-0.md
> Update docs for delegate 2.0 graceful cleanup feature

- docs/software-engineering-insights/propelo-sei/analytics-and-reporting/efficiency/agile-metrics/sei-sprints-metrics-reports.md
- docs/software-engineering-insights/shared/integrations/jira-use-cases.md
* Please describe your changes: \__________ Explain subtasks in Jira Trend Reports
* Jira/GitHub Issue numbers (if any): \_______ https://harness.atlassian.net/browse/SEI-13189
> (Update) Jira Trend report

- docs/security-testing-orchestration/exemptions/exemption-workflows.md
- docs/security-testing-orchestration/exemptions/manage-exemptions.md
> STO: Add Videos for Issue Exemptions Feature.

- docs/software-engineering-insights/harness-sei/setup-sei/manage-developers.md
- docs/software-engineering-insights/harness-sei/setup-sei/setup-org-tree.md
- docs/software-engineering-insights/harness-sei/setup-sei/setup-teams.md
* Please describe your changes: Reorders the child pages in the Setup SEI 2.0 section. Raised by Santosh on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-254
> FMEPRD-254 Reorder SEI 2.0 Setup Documentation

- docs/platform/delegates/secure-delegates/secure-delegates-with-tokens.md
> [PL-Doc] Update Delegate Delete Token & Revamp Doc

- release-notes/platform.md
> [PL-Doc] Platform release notes 1.100.x

- src/components/Roadmap/data/seiData.ts
* Please describe your changes: Updates the SEI Product Roadmap, flagged by PB on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/SEI-13532
> SEI-13532 Roadmap Update for Q3'FY26

- docs/feature-management-experimentation/api/wrappers/python-admin-api.md
* Please describe your changes: Adds relevant sections from the [Python library README](https://github.com/splitio/python-api?tab=readme-ov-file#using-in-harness-mode) into the documentation, the `Harness Mode` and `Rule-based Segments` sections. Flagged by Josh K on Slack.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-192
PRs must …
> FMEPRD-192 Update Python PyPi library for Split REST Admin API Documentation

- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/python-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/ruby-sdk.md
* Please describe your changes: Updating SDK versions mentioned in the respective code snippets based on Bilal's updates in https://github.com/splitio/documentation/pull/1110 and https://github.com/splitio/documentation/pull/1111.
> Update FME Python and Ruby SDK Versions

- docs/feature-flags/use-ff/relay-proxy/relay-proxy.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/android-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/android-suite.md
* Please describe your changes: Updating SDK versions mentioned in the respective code snippets based on Gaston's updates in https://github.com/splitio/documentation/pull/1104 and https://github.com/splitio/documentation/pull/1108. 
> Update Android and Android Suite Versions

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/ios-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/ios-suite.md
* Please describe your changes: Updating SDK versions mentioned in the respective code snippets based on Gaston's updates in https://github.com/splitio/documentation/pull/1109.
> Update iOS and iOS Suite Versions

- docs/platform/git-experience/gitexp-bidir-sync-setup.md
> Workaround for On save

- docs/database-devops/use-database-devops/set-up-connectors.md
This pull request adds improved documentation for setting up MongoDB connectors in Harness DB DevOps. The most important changes include the addition of MongoDB Atlas connection string details and a new section outlining prerequisites and requirements for MongoDB connections.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1464
If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODE …
> feat: update mongodb jdbc url

- docs/ai-sre/runbooks/integrations/zoom.md
* Jira/GitHub Issue numbers (if any): [IR-1791](https://harness.atlassian.net/browse/IR-1791)
[IR-1791]: https://harness.atlassian.net/browse/IR-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IR-1791: Add details for zoom scope permissions for zoom meeting end actions

- docs/platform/shared/expression-tostring.md
- docs/platform/variables-and-expressions/harness-expressions-reference.md
- docs/platform/variables-and-expressions/variables-and-expressions-faqs.md
* Please describe your changes: \_____ Cover some addtional examples for using to String
* Jira/GitHub Issue numbers (if any): \_____  https://harness.atlassian.net/browse/PIPE-29065
> (Update) Using toString

- docs/database-devops/concepts/changelog-directories-structure.md
- docs/database-devops/concepts/deployment-architecture.md
- docs/database-devops/concepts/glossary/changelog.md
- docs/database-devops/concepts/organizing-sql-files.md
- docs/database-devops/features/access-applied-changesets.md
- docs/database-devops/features/automatic-and-custom-rollback.md
- docs/database-devops/features/runtime-secrets.md
- docs/database-devops/features/ssl.md
- docs/database-devops/features/subs-properties-in-changelogs.md
- docs/database-devops/get-started/build-a-changelog.md
- docs/database-devops/get-started/using-custom-script.md
This pull request updates several documentation files for Harness Database DevOps to add explicit `slug` fields, which define the URL paths for each doc page. This change improves the organization and navigation of the documentation by ensuring consistent and predictable URLs for key concepts and features.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1475 …
> fix: broken google urls

- docs/platform/git-experience/oauth-integration.md
- release-notes/continuous-delivery.md
> Remove CDS Providers

- src/components/Roadmap/data/cdData.ts
> Update CD Q3 roadmap

- docs/software-supply-chain-assurance/get-started/key-concepts.md
> SCS: Update Key Concepts page

- docs/cloud-cost-management/3-use-ccm-cost-reporting/6-use-ccm-dashboards/ccm-explore.md
> fields of dashboards

- docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/1-auto-stopping-rules.md
- docs/cloud-cost-management/4-use-ccm-cost-optimization/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/autostopping-for-aws/load-balancer.md
> added new changes for autostopping

- src/components/Roadmap/data/sscaData.ts
> SCS: Update SCS Q3 Roadmap

- docs/continuous-delivery/gitops/repositories/add-a-harness-git-ops-repository.md
> [CDS-112578] HCR Support for GitOps cluster

- docs/continuous-delivery/cd-infrastructure/aws-cdk.md
- docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
- docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md
- docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-cloud-run.md
- docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
> [CDS-112598] Added Europe GAR links for plugin images

- docs/infra-as-code-management/manage-projects/iacm-smp.md
- docs/infra-as-code-management/whats-supported.md
* Update IaCM SMP support docs
* [JIRA](https://harness.atlassian.net/browse/IAC-4291)
> docs: [IAC-4291]: Update iacm smp support docs

- docs/continuous-integration/secure-ci/secure-connect.md
* Please describe your changes: Add Vault to Secure Connect
* Jira/GitHub Issue numbers (if any): [CI-17600](https://harness.atlassian.net/browse/CI-17600)
[CI-17600]: https://harness.atlassian.net/browse/CI-17600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Vault to Secure Connect

- docs/artifact-registry/platform-integrations/cd-ar-integrations.md
* Update CD/AR integrations doc to walkthrough full integration steps highlighting supported steps like AWS Lambda in use alongside Generic Artifacts.
* [JIRA](https://harness.atlassian.net/browse/AH-1578)
> docs: [AH-1578]: Add Generic Artifact / CD integration.

- docs/feature-management-experimentation/20-sdks-and-infrastructure/optional-infra/split-evaluator.md
* Please describe your changes: Chat with Josh on Slack.
> Split Evaluator Link Fix

- docs/feature-management-experimentation/40-feature-management/best-practices/why-setting-the-order-of-treatments-matters.md
- docs/feature-management-experimentation/40-feature-management/create-a-rollout-plan.md
- docs/feature-management-experimentation/40-feature-management/set-the-default-treatment.md
* Please describe your changes: Flagged by Heather on Slack.
> Replace `Multivariate` with `Multivariant` in Feature Management Documentation

- docs/feature-management-experimentation/10-getting-started/overview/create-an-experiment.md
- docs/feature-management-experimentation/10-getting-started/overview/index.md
- docs/feature-management-experimentation/40-feature-management/index.md
- docs/feature-management-experimentation/40-feature-management/setup/create-a-feature-flag.md
- docs/feature-management-experimentation/60-experimentation/setup/experiment-scope.md
* Please describe your changes: Add testing-related blog posts to relevant Feature Management documentation. Discussion with Dominique on Slack. 
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-222
* Preview links/images (Internal contributors only): https://689e2805ba134617029ffa20--harness-developer.netlify.app//docs/feature-management-experimentation/getting-started/overview/ …
> FMEPRD-222 Add Harness Blog Posts to Feature Management Documentation

- docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
* Please describe your changes: Fix  incorrect entry point reference.
* Jira/GitHub Issue numbers (if any): CI-18542
> Fix  incorrect entry point reference.

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/ios-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/ios-suite.md
* Please describe your changes: Updates iOS SDK and Suite pages versions based on changes in Gaston's PR https://github.com/splitio/documentation/pull/1112/. 
> Update iOS SDK and Suite Versions

- release-notes/cloud-cost-management.md
> added new release notes

- docs/platform/get-started/subscriptions-licenses/subscriptions.md
* Please describe your changes: Incorporates changes in https://github.com/harness/developer-hub/pull/10941 and adds several links to Subscriptions and Licenses pages in additional product modules.
> Add Subscriptions and Licenses Doc Links

- docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-cd-quickstart.md
- docs/platform/connectors/cloud-providers/add-a-microsoft-azure-connector.md
> Azure connector docs OIDC

- src/components/Roadmap/data/iacmData.ts
* Update IaCM Roadmap to reflect the remainder of 2025 features and beyond.
* [JIRA](https://harness.atlassian.net/browse/IAC-4340)
* [PREVIEW](https://689eff0447539dc1ce1a5966--harness-developer.netlify.app/roadmap/#iacm)
> roadmap: [IAC-4340]: IaCM Roadmap update

- docs/internal-developer-portal/plugins/available-plugins/sonarqube.md
* Please describe your changes: \________ Added more info about the secret encryption as there was ambiguity
* Jira/GitHub Issue numbers (if any): \____ https://harness.atlassian.net/browse/IDP-6044
> (Update) SonarQube IDP

- release-notes/security-testing-orchestration.md
> STO: Release Notes for v1.153.3

- docs/continuous-integration/secure-ci/aws-oidc-token-plugin.md
- docs/continuous-integration/secure-ci/gcp-oidc-token-plugin.md
* Please describe your changes: Add usage guide for AWS OIDC token plugin similar to https://developer.harness.io/docs/continuous-integration/secure-ci/gcp-oidc-token-plugin/ 
@Ompragash to review the newly created doc for correctness.
* Jira/GitHub Issue numbers (if any): CI-18316
> Add usage guide for AWS OIDC token plugin

- release-notes/software-supply-chain-assurance.md
> SCS: Release Notes for 1.39.0 

- docs/code-repository/get-started/cr-subscription-mgmt.md
* Please describe your changes: Update phrasing to highlight Code Repository access is not tied to CI licenses
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/CODE-4359
> Update phrasing to highlight Code Repository access is not tied to CI licenses

- docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-cd-quickstart.md
> Kubeconfig version requirement

- src/components/Roadmap/data/iacmData.ts
* Update IaCM roadmap to only reflect recent release items (limited to 6)
* [JIRA](https://harness.atlassian.net/browse/IAC-4371)
> roadmap: [IAC-4371] Update IaCM roadmap

- docs/internal-developer-portal/catalog/catalog-yaml.md
for this ticket - https://harness.atlassian.net/browse/IDP-6050
> [IDP] Update : info on RBAC=! Owner in YAML

- docs/software-supply-chain-assurance/artifact-security/sign-verify/sign-artifacts.md
- docs/software-supply-chain-assurance/artifact-security/sign-verify/verify-signed-artifacts.md
- docs/software-supply-chain-assurance/artifact-security/slsa/generate-slsa.md
- docs/software-supply-chain-assurance/artifact-security/slsa/verify-slsa.md
- docs/software-supply-chain-assurance/shared/artifact-source.md
> SCS: Add note for Supported Auth types

- docs/continuous-integration/use-ci/run-tests/tests-v2.md
* Please describe your changes: Add note regarding HTTPS/TLS config.
* Jira/GitHub Issue numbers (if any): CI-15234
> Add note regarding HTTPS/TLS config.

- release-notes/delegate.md
> Update delegate.md for Delegate HF 85807

- release-notes/database-devops.md
* Please describe your changes:
* Added release notes for version 1.49.x (July 2025), detailing new features such as the ingress-exposed Schema List API, enhanced rollback metadata, and support for optional Primary DB Instance ID, along with a summary of supported integrations and minimum supported versions.
* Added release notes for version 1.48.x (July 2025), outlining enhancements like enriched deployed state APIs, UI improvements, expanded database and integration support, and visibility for metadata fields.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1463
We aim to merge PRs …
> feat: add release for july 2025 db-devops

- src/components/Chatbot/styles.module.scss
- src/components/Community/styles.module.scss
- src/components/Docs/styles.module.scss
- src/components/HomepageUniversity/CertCard.module.scss
- src/components/NavbarItems/components/styles.module.scss
- src/components/Roadmap/index.module.scss
- src/components/TutorialCard/TutorialCard.module.scss
- src/components/University/styles.module.scss
- src/css/custom.css
- src/pages/index.module.scss
> HDH-393-make-hdh-font-font-sizes-consistent

- docs/feature-management-experimentation/api/index.md
* Please describe your changes: Adds a link to the API docs. Requested by Ryan on Slack.
> Admin API Doc Update

- docs/software-supply-chain-assurance/artifact-security/sign-verify/sign-artifacts.md
- docs/software-supply-chain-assurance/artifact-security/sign-verify/verify-signed-artifacts.md
> SCS: Add a note for the Artifact Signing step

- release-notes/delegate.md
> Update delegate.md for Delegate release 86500

- docs/platform/connectors/ticketing-systems/connect-to-service-now.md
* Please describe your changes: \___Remove reference to API ability.
Harness does not support this for SNOW
* Jira/GitHub Issue numbers (if any): \______ https://harness.atlassian.net/browse/CDS-113382
> (Update) SNOW API key Removal

- src/components/Roadmap/data/ciData.ts
- src/components/Roadmap/data/codeData.ts
* Please describe your changes: CI roadmap update Q3FY26
> CI roadmap update Q3FY26

- docs/internal-developer-portal/idp-2o-overview/2-0-overview-and-upgrade-path.md
- src/components/Roadmap/data/idpData.ts
> docs: update IDP roadmap

- docs/platform/authentication/single-sign-on-saml.md
- docs/platform/role-based-access-control/provision-users-and-groups-using-azure-ad-scim.md
- docs/platform/role-based-access-control/provision-users-and-groups-with-one-login-scim.md
- docs/platform/role-based-access-control/provision-users-with-okta-scim.md
- docs/platform/shared/scimurl.md
* Please describe your changes: \______ Add corrections to SCIM urls to cover the correct Prod 2 url and new environments
This caused a lot of unnecessary confusion
* Jira/GitHub Issue numbers (if any): \_____ https://harnesssupport.zendesk.com/agent/tickets/90314
> (Update) Proper SCIM URLS

- .github/CODEOWNERS
> [CDE] Add CODEOWNERS for CDE docs, release notes and roadmap files

- docs/feature-management-experimentation/shared/events/index.mdx
* Please describe your changes: \added milliseconds since epoch
> update to specify milliseconds

- docs/feature-management-experimentation/40-feature-management/monitoring-analysis/impressions.md
- docs/feature-management-experimentation/40-feature-management/monitoring-analysis/live-tail.md
- docs/feature-management-experimentation/40-feature-management/setup/control-treatment.md
- docs/feature-management-experimentation/40-feature-management/setup/create-a-feature-flag.md
- docs/feature-management-experimentation/40-feature-management/setup/dynamic-configurations.md
- docs/feature-management-experimentation/40-feature-management/targeting/limiting-exposure.md
- docs/feature-management-experimentation/40-feature-management/targeting/segments.md
- docs/feature-management-experimentation/40-feature-management/targeting/target-segments.md
- docs/feature-management-experimentation/40-feature-management/targeting/target-with-custom-attributes.md
- docs/feature-management-experimentation/40-feature-management/targeting/target-with-dependencies.md
* Please describe your changes: Flagged by Wei on Slack.
> Cleanup Feature Management Doc Page Aliases

- src/components/Roadmap/data/iacmData.ts
* Update roadmap headers to reflect correct quarters
* [JIRA](https://harness.atlassian.net/browse/IAC-4395)
> roadmap: [IAC-4395]: Update roadmap quarters

- release-notes/delegate.md
> Delegate upgrader 1.8.0

- .github/CODEOWNERS
* Adding myself to fill Dewan's space as config approver
> Update Codeowner config approver

- release-notes/continuous-delivery.md
Notice for the announcement of the upcoming feature: .selectManyFrom() functor
* Please describe your changes: Added pre-release announcement for an upcoming feature enhancement: .selectManyFrom() functor ( addition to multi selection & single selection during runtime input ) 
* Jira/GitHub Issue numbers (if any): [PIPE-28993](https://harness.atlassian.net/browse/PIPE-28993) , [PIPE-29436](https://harness.atlassian.net/browse/PIPE-29436)
* Preview links/images (Internal contributors only): NA …
> Pre-release announcement/Notice for PIPE-28993

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
- release-notes/delegate.md
> [PL-Doc] Delegate RN 25.08.86600

- docs/platform/shared/scimurl.md
* Please describe your changes: \_____URL was incorrect fixed
> (Update) FixURL

- README.md
- static/img/icon-fme-s.svg
* Please describe your changes: update FME logo in README.md
> chore: update FME logo in README.md

- sidebars.ts
* Please describe your changes: Rename the section `Features` to `Use FME` to be consistent. Flagged by Richard on Slack.
> Small FME Documentation Navigation Menu Update

- docs/continuous-integration/secure-ci/secure-connect.md
- release-notes/continuous-integration.md
* Please describe your changes: Adding few missed tickets to 1.92 RN
> 1.93 RN + Addition to 1.92 RN

- sidebars.ts
> CHAOS: Update section names

- docs/artifact-registry/whats-supported.md
* Update what's supported BETA items
* [JIRA](https://harness.atlassian.net/browse/AH-1777)
> docs: [AH-1777]: Update AR what's supported

- release-notes/code-repository.md
* Please describe your changes: Code 1.54.x release notes
> Code 1.54.x release notes

- .github/CODEOWNERS
* Please describe your changes: Add Mauro's engineering team to the list of reviewers for the SDK and customer-deployed component pages in the FME documentation. Not sure if this grants them write access to the repository, or if that requires a SECENG ticket. Chat with Mauro on Slack.
PRs must meet …
> Update FME SDK CODEOWNERS

- docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> Comma separated list support for Canary Deployment

- release-notes/delegate.md
> delegate release notes for PL-65095

- docs/feature-management-experimentation/split-to-harness/administering-migrated-account.md
This PR contains no content changes--only minor corrections as listed below.
Fix the following typo, punctuation, grammar, etc. :
* Remove comma at line 59
* Consistently use format "role binding: [Role] role over [Resource group]"
* Remove parentheses, for cleaner style
* Replace "below" with "above" at line 368 (since the image is above the text)
* Grammar at line 458: "account that your legacy Split objects were merged into" >> "account, into which your legacy Split objects were merged"
* Typo at line 948: "an page" >> "a page"
* Arrange Troubleshooting sub-sections alphabetically
* Other improvements for clarity and style …
> FME RBAC Guide: Minor punctuation, grammar, typo corrections

- docs/database-devops/concepts/mongodb-command.md
This pull request adds a new documentation page providing a comprehensive reference for using Liquibase with MongoDB. The guide covers essential operations such as managing collections, indexes, documents, and executing custom commands, along with practical examples and best practices.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1378 …
> feat: document mongo commands for dbdevops

- docs/security-testing-orchestration/view-security-test-results/issues.md
> STO: Remove Issue Page FF and Add Video

- docs/continuous-integration/use-ci/build-and-upload-artifacts/artifacts-tab.md
* Please describe your changes: Add artifact-metadata-publisher environment variables and k8s flow details to CI artifacts tab docs
* Jira/GitHub Issue numbers (if any): CI-18523
> Add artifact-metadata-publisher environment variables and k8s flow details to CI artifacts tab docs

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-agents/index.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/index.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/index.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/optional-infra/index.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/index.md
- src/components/Docs/data/fmeSDKSData.js
* Please describe your changes: Replacing Markdown tables (✊🏼) with a more interactive tile experience that directs users to the respective child page in the doc folder. Implementing content reuse here resolves situations like these where manually documented Markdown tables are outdated over time. Flagged by Ryan on Slack.
**Before**
**After**
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-269 …
> FMEPRD-269 Update SDKs and Customer-Deployed Components Landing Pages

- release-notes/delegate.md
> Add Delegate token terraform updates

- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
* Please describe your changes: Enable Path Style Support for Cache Intelligence S3 via Stage Variable. This is a work-around and NOT native support.
* Jira/GitHub Issue numbers (if any): CI-17982
> Enable Path Style Support for Cache Intelligence S3 via Stage Variable per CI-17982

- docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
* Please describe your changes: Update per CI-18239 - step5 only. Step12,13 clarification to follow.
* Jira/GitHub Issue numbers (if any): CI-18239
> Update per CI-18239 - step5 only

- release-notes/delegate.md
> [PL-Doc] Minor Doc update

- release-notes/delegate.md
> [PL-Doc] Delegate HF

- docs/platform/references/harness-cloud-vm-images.md
* Please describe your changes: Current links point to 2204 images. This PR swaps the links to point to the correct Linux Ubuntu 2404 images.
* Jira/GitHub Issue numbers (if any): PL-64988
> Point to the correct Linux Ubuntu 2404 image.

- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-sdks/ios-sdk.md
- docs/feature-management-experimentation/20-sdks-and-infrastructure/client-side-suites/ios-suite.md
* Please describe your changes: Updated to latest iOS client & suite version.
> FME iOS-Client 3.3.3 & iOS-Suite 2.2.3

- docs/platform/delegates/delegate-reference/delegate-image-version-status.md
> [PL-Doc] Update Delegate Release page

- release-notes/platform.md
> [PL-Doc] Platform Release notes 1.104.x

- docs/chaos-engineering/faults/chaos-faults/aws/security-configurations/aws-iam-integration.md
- docs/chaos-engineering/faults/chaos-faults/aws/security-configurations/content/aws-iam-integration/assume-role-method.md
- docs/chaos-engineering/faults/chaos-faults/aws/security-configurations/content/aws-iam-integration/oidc-method.md
- docs/chaos-engineering/guides/probes/apm-probes/index.md
> add assume role docs

- docs/continuous-delivery/gitops/clusters/create-cluster-with-azure-wif.md
- docs/continuous-delivery/gitops/clusters/create-cluster-with-iam.md
> [CDS-113003] Creating a GitOps Cluster with Azure WIF

- docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
- docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
* Please describe your changes: Add S3 bucket encryption policy guidance for Save/Restore Cache from S3
* Jira/GitHub Issue numbers (if any): CI-18916
> Add S3 bucket encryption policy guidance for Save/Restore Cache from S3

- docs/feature-management-experimentation/split-to-harness/sso-for-admins.md
A customer interpreted the existing directions to imply they did all the work in just their IdP and then they should notify us to complete the work on the Harness side.  
Making a simple wording change to make it clear that they must log into both Harness and their IdP to complete the directions below.
Also removing all mentions of "opens in a new tab" since that was a feature of the ZD docs that I don't know how to do in HDH yet.
We aim to merge PRs within one week or less, but …
> Dtk dave karow clarify sso done in harness and idp, remove opens in new tab

- src/components/DocsButton/index.tsx
- src/css/custom.css
> improve-typography-in-admonations

- docs/platform/role-based-access-control/heirarchichal-support-for-service-accounts.md
> [PL-Doc] Add note for Organization viewer in SA

- docs/cloud-cost-management/3-use-ccm-cost-reporting/2-ccm-cost-categories/cost-categories.md
> added minor edit

- docs/security-testing-orchestration/notifications/exemption-notifications.md
> STO: Add Video and Remove FF in Exemption Notification Docs.

- docs/database-devops/get-started/build-a-changelog.md
- docs/database-devops/get-started/gitops/environment-based-development.md
- docs/database-devops/get-started/gitops/trunk-based-development.md
- docs/database-devops/get-started/mongodb-changelog-generation.md
- docs/database-devops/get-started/onboarding-guide.md
- docs/database-devops/get-started/using-custom-script.md
This pull request enhances the documentation for Harness Database DevOps by adding interactive tabbed sections that provide both visual and YAML overviews of key workflows. These improvements help users better understand and implement environment-based, trunk-based, and MongoDB changelog generation strategies by offering clear, side-by-side code and UI examples. These changes make the documentation more interactive and user-friendly, especially for teams new to Harness or database DevOps workflows.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/DBOPS-1547
We …
> feat: add yaml codes with the pipeline overview

- docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/customize-podspec.md
* Please describe your changes: PodSpec Overlay supports spec.containers overrides
* Jira/GitHub Issue numbers (if any): CI-18847
> Update PodSpec Overlay page to include spec.containers overrides

- docs/continuous-integration/use-ci/build-and-upload-artifacts/drone-email-plugin.md
* Please describe your changes: Add required setting from drone email plugin.
* Jira/GitHub Issue numbers (if any): CI-17932
> Add required setting from drone email plugin.

- docs/feature-management-experimentation/70-management-and-administration/admin-best-practices/free-edition.md
* Please describe your changes: Clarify user access to environments once they've downgraded plans. Raised by Dave M on Slack.
> Update What happens when I downgrade to the Free Edition?

- docs/self-managed-enterprise-edition/advanced-configurations/configure-readonlyfilesystem.md
> [PL-Doc]Configure `readonlyrootfilesystem` for harness services (SMP)

- docs/internal-developer-portal/catalog/manage-catalog.md
- docs/internal-developer-portal/environment-management/overview.md
- docs/internal-developer-portal/flows/harness-pipeline.md
- docs/internal-developer-portal/git-experience/gitx-journey.md
- release-notes/internal-developer-portal.md
> [IDP]: Add Bitbucket access token authentication mode support docs

- release-notes/ai-test-automation.md
- release-notes/self-managed-enterprise-edition.md
> [PL-Doc] SMP HF 0.32.1

- docs/continuous-integration/shared/preserve-metadata.md
- docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
- docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
- docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
* Please describe your changes: This PR documents `preserveMetadata` flag for Save/Restore Cache
- Added shared include file (preserve-metadata.md) explaining how to use preserveMetadata
- Linked new section in S3 Save/Restore Cache docs
- Updated troubleshooting to mention Gradle cache growth ("snowballing")
* Jira/GitHub Issue numbers (if any): CI-18093
PRs must meet …
> Document preserveMetadata flag for Save/Restore Cache

- docs/feature-management-experimentation/split-to-harness/administering-migrated-account.md
* Add a troubleshooting section: Issue creating FME objects when the user lacks **User** and **User Groups** View permissions.
* Use list format 1.a. for secondary steps.
Jira ticket number: FMEPRD-283
> [FMEPRD-289] FME RBAC guide: Add create objects permissions info

- docs/faqs/harness-feature-flag-faqs.md
- docs/software-engineering-insights/troubleshoot-sei/sei-propels-and-tables-faqs.md
- docs/software-engineering-insights/troubleshoot-sei/sei-security-data-retention-faqs.md
- docs/software-engineering-insights/troubleshoot-sei/sei-widgets-faqs.md
- docs/software-engineering-insights/troubleshoot-sei/troubleshoot-integration-failures.md
* Please describe your changes: Incorporates FAQ content from https://github.com/harness/developer-hub/pull/10161 and https://github.com/harness/developer-hub/pull/11081/ into SEI and FF Classic doc sets. Adds banners for Troubleshooting SEI doc pages to specify the behavior described in these FAQs relates the SEI 1.0 experience only, not 2.0. 
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FMEPRD-290
* Preview links/images (Internal contributors only):  /docs/software-engineering-insights/troubleshoot-sei/sei-widgets-faqs and /docs/faqs/harness-feature-flag-faqs
If your PR is open longer …
> FMEPRD-290 Update SEI and FF Classic FAQs

- docs/platform/harness-aida/harness-gemini-extension.md
Added an introduction section and detailed steps for creating, installing, configuring, and validating a Gemini CLI extension for Harness MCP.
> Enhance documentation for Harness MCP Gemini CLI extension

- docs/platform/harness-aida/harness-gemini-extension.md
Removed duplicate entry for Gemini CLI installation and adjusted formatting for optional environment variables and configuration details.
> Refactor Gemini CLI installation and environment variables

- docs/platform/role-based-access-control/provision-use-jit.md
> [PL-Doc] Remove FF `PL_ENABLE_JIT_USER_PROVISION` since the feature is GA

- release-notes/static/ff-ga-feed.json
> Add CD FFs that are planned to be GA'd in Q3

- release-notes/feature-flags.md
* Please describe your changes: Adds a release note entry for the latest JavaScript SDK release in August.
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/FFM-12602
> FFM-12602 Add August 2025 JavaScript SDK Release Note

- docs/security-testing-orchestration/set-up-scans/shared/ai-scanners.md
- docs/security-testing-orchestration/sto-techref-category/github-advanced-security.md
- docs/security-testing-orchestration/sto-techref-category/modelscan.md
- docs/security-testing-orchestration/sto-techref-category/shared/step-palette/ingest/file.md
- docs/security-testing-orchestration/sto-techref-category/shared/step-palette/target/auto-detect/note.md
- docs/security-testing-orchestration/sto-techref-category/shared/sto-supported-ingestion-formats.md
- docs/security-testing-orchestration/sto-techref-category/shared/sto-supported-scanners.md
- docs/security-testing-orchestration/whats-supported/scanners.md
> STO: Document ModelScan Step

- docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-deployment-faqs.md
Added Helm FAQ:
Is switching between Kubernetes Deployment and Helm Deployment supported?
> [CDS-113975] Added Helm Faq

- kb/reference-architectures/ccm/best-practices/aws/aws-permissions.md
> update aws permissions for visibility

- docs/feature-management-experimentation/10-getting-started/statistical-approach.md
* Please describe your changes: Small typo on sample ratio mismatch: acronym is `SRM`, not `SMR`. Flagged by Ryan on Slack.
> Update Split's approach to statistics

- release-notes/continuous-delivery.md
* Please describe your changes: Added release notes for release 1.109.2
> release notes 1.109.2

- release-notes/static/ff-ga-feed.json
> Add central notifications flag to GA list

- docs/chaos-engineering/content/experiments/old-chaos-studio.md
- docs/chaos-engineering/guides/chaos-experiments/alert-integration.md
- docs/platform/notifications/centralised-notification.md
- docs/platform/notifications/static/manage-notifications.md
> [PL-Doc] Remove `PL_CENTRAL_NOTIFICATIONS` flag

- release-notes/chaos-engineering.md
> CHAOS: 1.66 release notes

- docs/feature-management-experimentation/20-sdks-and-infrastructure/server-side-sdks/java-sdk.md
> Updated FME Java SDK version

- docs/platform/harness-aida/effective-prompting-ai.md
- docs/platform/harness-aida/harness-ai-chat-guide.md
- docs/platform/harness-aida/harness-create-with-ai.md
Clarify the capabilities of Harness AI and update unsupported features section.
> Enhance documentation for Harness AI features

- docs/software-engineering-insights/harness-sei/get-started/enable-sei.md
- docs/software-engineering-insights/harness-sei/get-started/sei-key-concepts.md
- docs/software-engineering-insights/harness-sei/get-started/sei-onboarding-guide.md
* Please describe your changes: Updates wording around beta notices and coming soon features that have been released in SEI 2.0. Also updates some doc links in the Onboarding Guide.
> Update SEI 2.0 Onboarding Documentation

- docs/chaos-engineering/guides/license-consumption.md
> CHAOS: update license consumption docs

- docs/feature-management-experimentation/40-feature-management/setup/fallback-treatment.md
> Banner Nit on Fallback Treatments

- release-notes/cloud-cost-management.md
Added documentation for a hotfix (October 2025) that introduces new columns to the recommendations CSV export, including fields such as Recommendation Link, Recommendation Date, Account and Resource details, Cloud Provider, Region, Cost Category, Tags, Potential Monthly Spend, Potential Savings, Savings Percentage, Recommendation Type, Recommended Action, Recommendation State, Resource Count, and Custom Recommendation.
> [CCM]: Added hotfix release notes

- docs/software-engineering-insights/harness-sei/setup-sei/manage-developers.md
> Add developer records - Checklist for PS & SEs

- docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> [CDS-114025] ServiceNow template docs update

- docs/platform/git-experience/autocreation-of-entities.md
* Please describe your changes: The path for the service and infrastructure Project Level override was incorrect. I have fixed the documentation and updated it to the correct path. 
* Jira/GitHub Issue numbers (if any): [CDS-111506](https://harness.atlassian.net/browse/CDS-111506)
[CDS-111506]: …
> fixed bug CDS-111506
